- lib/specRunner.js
- src/scheduler/micro-task-queue.js
- src/util/get-bound-next.js
- tests/scheduler/next-frame-scheduler-spec.js
Fixes an import, getBoundNext, and adds a smoke tests making sure that the scheduler works.
> fix NextFrameScheduler to run scheduled work asynchronously

- package.json
> remove requirejs as a dependency

- src/OperatorObservable.ts
- src/RxNext.ts
- src/observable/fromEvent.ts
- src/observable/fromEventPattern.ts
Just porting them over to TypeScript
> Adding fromEvent and fromEventPattern 

- src/OperatorObservable.ts
- src/RxNext.ts
- src/observable/empty.ts
- src/observable/range.ts
- src/observable/throw.ts
> Adding static methods to Observable

- spec/observable-spec.js
- src/Scheduler.ts
- src/SchedulerActions.ts
- src/observable/value.ts
There still seems to be something wrong with the recursive scheduler... as in, it doesn't recurse. Fix TBD.
> Fixing the Observable.return test.

- src/CompositeSubscription.ts
> chore(CompositeSubscription.ts): remove unused import

- dist/amd/RxNext.js
- dist/amd/operator/reduce.js
- dist/cjs/RxNext.js
- dist/cjs/operator/reduce.js
- dist/es6/Observable.d.ts
- dist/es6/RxNext.js
- dist/es6/operator/map.js
- dist/es6/operator/reduce.d.ts
- dist/es6/operator/reduce.js
- dist/global/RxNext.js
- spec/operator/reduce-spec.js
- src/Observable.ts
- src/RxNext.ts
- src/operator/map.ts
- src/operator/reduce.ts
> add reduce

- .travis.yml
- README.md
- package.json
Closes #91 
Note: someone with admin privileges on this repo will need to enable the job in Travis: https://travis-ci.org/profile/ReactiveX
> chore(ci): set up Travis configuration

- spec/operator/partition-spec.js
- src/Observable.ts
- src/RxNext.ts
- src/operator/partition.ts
Implements .partition operator because I have impulse control problems. Does not include dist/ changes per #94
> implement partition operator

- index.js
- spec/root-module-spec.js
> feat(index): add index module which requires commonjs build

- spec/operators/merge-spec.js
- src/observables/ArrayObservable.ts
- src/observables/IteratorObservable.ts
- src/observables/RangeObservable.ts
- src/observables/TimerObservable.ts
- src/operators/merge.ts
And fixes off-by-one in iteration Observables.
> Adds merge with scheduling tests.

- package.json
- spec/helpers/test-helper.js
- spec/operators/zip-spec.js
Adds jasmine 'toDeepEqual' custom matcher.
> Adds combineLatest and zip tests with immediate scheduling.

- spec/operators/switch-latest-spec.js
- src/Observable.ts
- src/Rx.ts
- src/Subscriber.ts
- src/operators/combineLatest.ts
- src/operators/merge.ts
- src/operators/switchAll.ts
- src/operators/switchLatest.ts
- src/operators/switchLatestTo.ts
- src/operators/zip.ts
> Adds switchAll, switchLatest, and switchLatestTo operators.

- README.md
- package.json
- perf/flatMap-scalar/index.html
- perf/flatMap-scalar/perf.js
- perf/flatMap/index.html
- spec/root-module-spec.js
- src/Rx.global.js
> Renames RxNext to Rx.

- spec/operators/takeUntil-spec.js
- src/Observable.ts
- src/Rx.ts
- src/operators/takeUntil.ts
Add takeUntil operator and tests.
> feat (takeUntil): add takeUntil operator

- spec/observables/fromEventPattern-spec.js
- src/Observable.ts
- src/Rx.ts
- src/Scheduler.ts
- src/observables/FromEventPatternObservable.ts
> feat(observable): add fromEventPattern creator function

- spec/observables/fromEvent-spec.js
- src/Observable.ts
- src/Rx.ts
- src/observables/FromEventObservable.ts
Addresses #95 
cc/ @mattpodwysocki @trxcllnt
> feat(observable) add fromEvent creation method

- spec/operators/defaultIfEmpty-spec.js
- src/Observable.ts
- src/Rx.ts
- src/operators/defaultIfEmpty.ts
Adds the defaultIfEmpty operator per #128
> feat(operator): add defaultIfEmpty

- src/Observable.ts
- src/Rx.ts
Fixes Issue #174 which removes the ensure alias for finally
> Removing ensure alias for finally

- spec/operators/skipUntil-spec.js
- src/Observable.ts
- src/Rx.ts
- src/operators/skipUntil.ts
> feat(operator): add skipUntil

- spec/operators/throttle-spec.js
- spec/scheduler-spec.js
- src/Observable.ts
- src/Rx.ts
- src/operators/throttle.ts
> feat(operator): add throttle

- spec/operators/debounce-spec.js
- src/Observable.ts
- src/Rx.ts
- src/operators/debounce.ts
> feat(operator): add debounce

- perf/micro/current-thread-scheduler/operators/skip.js
- perf/micro/immediate-scheduler/operators/skip.js
- perf/micro/index.js
Adding additional micro test coverage for skip operator listed in issue https://github.com/ReactiveX/RxJS/issues/100 by following existing one.
> Add micro-benchmark performance test for skip operator.

- perf/micro/current-thread-scheduler/operators/repeat.js
- perf/micro/immediate-scheduler/operators/repeat.js
minor alignment for micro-perf test cases followed by change https://github.com/ReactiveX/RxJS/pull/234
> chore(test): update micro-benchmark performance test for repeat operator

- README.md
- package.json
Getting ready for a pre-alpha release to get the ball rolling with partner projects.
> 0.0.0-prealpha.1

- perf/macro/zip/index.html
- perf/macro/zip/perf.js
- perf/macro/zip/zip.spec.js
Attempt to create macro test to close https://github.com/ReactiveX/RxJS/issues/259
> chore(test): add macro performance tests for zip

- spec/helpers/test-helper.js
- spec/operators/combineLatest-spec.js
- spec/schedulers/TestScheduler-spec.js
- src/schedulers/TestScheduler.ts
- adds virtual time tests from RxJS2/3 with marbley goodness
- updates TestScheduler and test-helpers a bit for better testing.
> chore(test): add combineLatest virtual time tests from RxJS 2/3

- package.json
- perf/micro/index.js
- automatically pick up new files without maintaining a huge array
- add ability to filter down to specific tests: `node perf/micro testfilter` where "testfilter" is any string
to be found inside the path of the test
@kwonoj ... this is for you.
> chore(perf): improve micro perf ergonomics

- CONTRIBUTION.md
- README.md
- doc/operator-creation.md
> docs(operators): document how to add operators to Observable

- spec/operators/takeUntil-spec.js
Continuing effort to cover #309
> chore(test): use test marbles for takeUntil operator spec

- spec/observables/interval-spec.js
- spec/operators/bufferToggle-spec.js
Shaves a couple more seconds off of the test suite.
> Moving interval and bufferToggle tests over to marbles

- spec/helpers/test-helper.js
- spec/observables/combineLatest-spec.js
- spec/operators/combineAll-spec.js
- spec/operators/combineLatest-spec.js
- spec/operators/expand-spec.js
- spec/operators/merge-map-spec.js
- spec/operators/switch-spec.js
- spec/operators/switchMap-spec.js
- spec/operators/withLatestFrom-spec.js
- spec/operators/zipAll-spec.js
- src/InnerSubscriber.ts
- src/OuterSubscriber.ts
- src/observables/PromiseObservable.ts
- src/operators/combineLatest-static.ts
- src/operators/combineLatest-support.ts
- src/operators/combineLatest.ts
- src/operators/expand-support.ts
- src/operators/mergeAll-support.ts
- src/operators/mergeMap-support.ts
- src/operators/mergeMapTo-support.ts
- src/operators/switch.ts
- src/operators/switchMap.ts
- src/operators/withLatestFrom.ts
- src/operators/zip-support.ts
- src/util/subscribeToResult.ts
This is a work in progress ATM.
> Have inner subscriptions allow Promise, Array, Iterable, Observable, and observable

- perf/micro/current-thread-scheduler/operators/timeinterval.js
- perf/micro/immediate-scheduler/operators/timeinterval.js
- spec/operators/timeInterval-spec.js
- src/Rx.KitchenSink.ts
- src/Rx.ts
- src/operators/extended/timeInterval.ts
* adding timeInterval operator, as well as migrating RxJS4 testcases
> feat(operator): add timeInterval operator

- spec/operators/defaultIfEmpty-spec.js
*apply marble test cases for `defaultIfEmpty` operator.
Coverage wise, existing test cases are already same as RxJS4 test cases.
> test(defaultIfEmpty): add marble tests for defaultifEmpty operator

- spec/operators/do-spec.js
- src/operators/do.ts
- also shored up tests around do a little more
closes #476
> feat(do): do will now handle an observer as an argument

- perf/micro/index.js
- formatted the output as a table in console
- added the ability to use a --csv flag to output raw data as csv
> chore(micro perf): better formatting, csv output option

- src/operators/bufferCount.ts
- src/operators/bufferTime.ts
- src/operators/bufferToggle.ts
- src/operators/bufferWhen.ts
- src/operators/catch.ts
- src/operators/combineAll.ts
- src/operators/combineLatest-static.ts
- src/operators/combineLatest.ts
- src/operators/concat-static.ts
- src/operators/concat.ts
- src/operators/concatAll.ts
- src/operators/concatMap.ts
- src/operators/concatMapTo.ts
- src/operators/count.ts
Just starting at the top and working my way through, this PR is just adding basic documentation to operators as listed in the commits.
> Add basic docs for bufferCount through count

- lib/copy_dts.js
- package.json
- src/Observable.ts
- src/observables/ScalarObservable.ts
This fixes two things:
1. Core operators will now show properly on Observables in TypeScript projects
2. Type files are now included in the cjs output
Both of these are to address #528
> Fixes for typings issues

- spec/operators/scan-spec.js
- src/operators/scan.ts
For some crazy reason we had ZERO tests around scan... even with the high level of code coverage we have... 
Question everything. LOL.
This contains tests and fixes for scan.
> Scan fixes

- package.json
- eslint for perf, spec will autofix minor issue
- bump up typescript to 1.8b
> chore(package.json): eslint autofixes minor issue

- spec/util/MapPolyfill-spec.js
- src/util/Map.ts
- src/util/MapPolyfill.ts
- moves polyfill to it's own module
- tests polyfill
doesn't currently test the act of polyfilling.
> Add tests for Map polyfill under util

- spec/util/Immediate-spec.js
Minor correction to variable assignment in test case.
> refactor(Immediate): fix minor syntax in test cases

- wallaby.js
update wallaby configuration remove babel dependency
> chore(test): update wallaby configuration

- spec/util/Immediate-spec.js
- src/util/Immediate.ts
> fix(Immediate): nextTick scheduler should no longer throw in Chrome

- perf/micro/current-thread-scheduler/operators/switchFirst.js
- perf/micro/current-thread-scheduler/operators/switchMapFirst.js
- perf/micro/immediate-scheduler/operators/switchFirst.js
- perf/micro/immediate-scheduler/operators/switchMapFirst.js
- spec/operators/switchFirst-spec.js
- spec/operators/switchMapFirst-spec.js
- src/Rx.KitchenSink.ts
- src/operators/switchFirst.ts
- src/operators/switchMapFirst.ts
(Relates to #645)
Adds `switchFirst` and `switchMapFirst` operators (names still in discussion in #645) with tests and micro perfs.
Tell me if anything is missing from your guidelines !
> feat(operator): add switchFirst and switchMapFirst

- spec/operators/sample-spec.js
Fill small missing coverage for `sample` operator.
> test(sample): expand test coverage for sample

- spec/operators/publish-spec.js
Small update to `publish` test cases.
cc @staltz - would you able to confirm if this is right changes?
> test(publish): update test case for publish operator

- src/CoreOperators.ts
- src/Observable.ts
This PR update type definition for `multiCast` to reflect actual implementation.
> refactor(multiCast): update type definition for multiCast

- src/CoreOperators.ts
- src/Observable.ts
- src/operator/count.ts
relates to #878 
Continue effort to remove `thisArg`.
> feat(count): remove thisArg

- src/CoreOperators.ts
- src/Observable.ts
- src/operator/distinctUntilChanged.ts
> feat(distinctUntilChanged): remove thisArg

- spec/helpers/tests2png/painter.js
This PR updates `painter.js` lint friendly.
/cc @staltz for couple of comments.
> style(test): update test helper lint-friendly

- spec/observables/fromEventPattern-spec.js
- spec/observables/of-spec.js
- spec/observables/range-spec.js
- spec/subjects/replay-subject-spec.js
- Updates remaining cases to complete observables when test finishes.
> fix(test): make explicit unsubscription for observable

- spec/observables/dom/ajax-spec.js
- src/Rx.DOM.ts
- src/add/observable/dom/ajax.ts
- src/observable/dom/ajax.ts
This is the first stage of this.  But there's a lot of work done. See the notes in the commits.
> Refactor of ajax code

- spec/observables/dom/ajax-spec.js
- src/observable/dom/ajax.ts
- src/util/assign.ts
> Ajax Fixes

- spec/Observable-spec.js
- spec/observables/forkJoin-spec.js
- spec/observables/from-promise-spec.js
- spec/operators/concatAll-spec.js
- spec/operators/debounce-spec.js
- spec/operators/mergeAll-spec.js
- spec/operators/throttle-spec.js
relates to #998 
This PR updates references to promise in test case where it uses, ensure browser doesn't support promise can reference it.
> chore(test): update dependency references in tests

- spec/util/Immediate-spec.js
- src/util/Immediate.ts
> fix(Immediate): update setImmediate compatibility on IE

- src/add/observable/of.ts
Adresses #1113
This is actually untested. I'm not sure if this is supposed to have a test but are happy to get any pointers :)
> chore(Observable.of): expose as standalone function

- package.json
Stupidity of confusing to use uppercase in path, not caught while building in local machine...
> chore(package.json): fix build failures on non-windows platform

- package.json
- spec/Observable-spec.js
- spec/observables/dom/ajax-spec.js
- spec/observables/dom/webSocket-spec.js
Cosmetic updates to lint friendly spec. For some reason eslint glob doesn't grab all files, change it to specifying directory.
> style(test): update specs lint, hint friendly

- .eslintrc
- package.json
- spec/helpers/tests2png/painter.js
This PR updates dependencies,
- add peer dependency of karma-browserify
- update eslint to latest 
and update eslint configs with code accordingly.
> Update package dependencies

- src/operator/delayWhen.ts
This PR correctly applies outerSubscriber into delayWhen operator.
> refactor(delayWhen): use subscribeToResult with outerSubscriber

- src/operator/combineLatest.ts
> chore(typings): added scheduler to static combineLatest method

- src/observable/dom/AjaxObservable.ts
closes #1382
/cc @staltz for visibility.
> fix(AjaxObservable): update type definition for AjaxObservable

- spec/observables/dom/ajax-spec.ts
- spec/operators/distinctUntilChanged-spec.ts
- spec/operators/do-spec.ts
- spec/operators/startWith-spec.ts
- src/Rx.DOM.ts
This PR updates types in test cases. Some of type definitions were incomplete at the moment (before typing update from @david-driscoll was checked in), test cases were force casted into any to avoid migration. Most of them are now corrected, PR amends test case as well.
> chore(test): update type definitions

- package.json
Tiny PR, please merge this baby :baby: :baby_bottle:
> chore(package.json): update markdown-doctest to 0.3.1

- spec/Observable-spec.ts
provide delay to setInterval() in test specs to ensure call executes repeatedly,
setInterval's dealy is required parameter.
closes #1451
> test(forEach): update browser compatibility

- package.json
Small chore to update contact address (no, I'm still at my work), may not use corp address to ensure this is not corp-related contribution. I'll check this in myself soon, /cc @blesh for visibility.
> chore(package.json): update contact address

- CONTRIBUTING.md
- MIGRATION.md
Description: Fixed broken path and spelling error inside CONTRIBUTING.md
> docs(CONTRIBUTING): fix spelling and link to submit an issue

- spec/support/tests2png.opts
- spec/support/webpack.mocha.config.js
- spec/tsconfig.json
This PR updates configurations to work with scripts for documentation purpose.
@blesh , sorry for causing regression. I believe now issue is resolve by checking locally, leave this bit if you'd like to check once again before check this in.
> chore(test): update test script for documentation

- doc/scheduler.md
- spec/observables/from-spec.ts
- spec/observables/fromEvent-spec.ts
- spec/observables/fromEventPattern-spec.ts
- src/observable/BoundCallbackObservable.ts
- src/observable/BoundNodeCallbackObservable.ts
- src/observable/FromEventObservable.ts
- src/observable/FromEventPatternObservable.ts
- src/observable/FromObservable.ts
- src/observable/PromiseObservable.ts
Write comprehensive JSDoc for bindCallback, bindNodeCallback, fromPromise, fromEvent, fromEventPattern, from.
> Write JSDoc for bind* and from*

- spec/operators/sampleTime-spec.ts
- src/operator/audit.ts
- src/operator/auditTime.ts
- src/operator/debounce.ts
- src/operator/debounceTime.ts
- src/operator/sample.ts
- src/operator/sampleTime.ts
- src/operator/throttle.ts
- src/operator/throttleTime.ts
debounce, debounceTime, sample, sampleTime, throttle, throttleTime, audit, auditTime.
> write comprehensive JSDoc on all rate-limiting operators

- spec/operators/delayWhen-spec.ts
- src/operator/delayWhen.ts
Also tweak harmless indentation in delayWhen specs.
> docs(operators): write comprehensive JSDoc for delayWhen()

- doc/index.md
- doc/introduction.md
Fix links in tutorial pages. Add link from index to Tutorial.
#1571
> docs(site): fix broken links, add link to Tutorial

- package.json
> chore(commitizen): fix adapter path

- src/operator/reduce.ts
- src/operator/scan.ts
> docs(operators): write comprehensive JSDoc for reduce

- src/testing/HotObservable.ts
This pull request just follow up #1701
> fix(typings): make HotObservavle._subscribe protected

- spec/operators/publishReplay-spec.ts
- src/observable/ConnectableObservable.ts
Fixes an issue that caused ConnectableObservable to assign itself a connection that should be disposed when working with synchronous Observables. This issue caused a race condition in synchronous refCounted Observables if the subscribers dispose before the published source completes, causing the ConnectableObservable not to re-subscribe to the original source when it should have.
#1718
> fix(ConnectableObservable): fix ConnectableObservable connection handling issue

- tsconfig.json
I open this pull request to make our codebase more solidly.
> chore(typings): enable 'noImplicitReturns' compiler option

- src/SubjectSubscription.ts
This clarify arguments' types of `SubjectSubscription`.
> refactor(SubjectSubscription): remove 'any' type from SubjectSubscription

- package.json
- spec/Subject-spec.ts
- spec/support/webpack.mocha.config.js
This PR adds small update to test cases to be compatible with browsers.
> test(Subject): update test object assertion

- spec/helpers/testScheduler-ui.ts
- spec/util/UnsubscriptionError-spec.ts
- src/util/ArgumentOutOfRangeError.ts
- src/util/EmptyError.ts
- src/util/ObjectUnsubscribedError.ts
- src/util/UnsubscriptionError.ts
This is a continuation of #1773 ... just added a commit to fix the other browser issue (I hope)... @kwonoj can you verify?
cc/ @trxcllnt
> Better error messages

- doc/introduction.md
Correct backticks on template literals
> Fix code example on section Purity

- .lgtm
Now anyone in the MAINTAINERS file can say LGTM or :shipit:
> chore(LGTM): allow :shipit: squirrel for PR approvals

- spec/operators/groupBy-spec.ts
> test(groupBy): fix misbehaving groupBy test

- doc/introduction.md
The rate limited example in plain JS is wrong.
I've updated it to work, see https://jsbin.com/dowoto/1/edit?js,console,output
> docs(introduction) Fix one click per second example

- spec/helpers/tests2png/diagram-test-runner.js
- spec/observables/IteratorObservable-spec.ts
- spec/operators/pluck-spec.ts
- src/Notification.ts
- src/Subscription.ts
- src/observable/IteratorObservable.ts
- src/operator/pluck.ts
- src/testing/TestScheduler.ts
- src/util/assign.ts
- tools/custom-esdoc-plugin.js
This PR align error message format to not to use capital characters.
> style(error): format error message to not capitalize

- spec/schedulers/QueueScheduler-spec.ts
This PR refactors test case of `QueueScheduler` to use fake timers instead of real datetime. There is intermittent test asserition failure by test case designed to check real execution time to verify asynchronous behavior, which can be vary per environment (i.e, virtual machines) leads into test failure. Instead, use fake timers and verify values synchronously.
In further, distinct test coverage for `Action<T>` might needed (`QueueAction`, `AsyncAction`...)
> test(QueueScheduler): use fake timers for async schedule

- README.md
adding some formatting so we can demo pull requests for beginners #yolobrolo 
to make @jayphelps happy
> docs(README.md): add spaces to import

- esdoc.json
Update `esdoc.json`, `Rx.umd.js` is now just `Rx.js` 
#1871
> docs(esdoc.json): related to #1871, Rx.umd.js is now just Rx.js

- doc/decision-tree-widget/tree.yml
Also rename `inspectTime` to `auditTime`
> Rename inspect to audit in Docs decision tree

- src/util/root.ts
Appears this is left over from a refactor--even has a lint disable to prove it 😆
> chore(root): remove unused module/exports checking code

- src/add/operator/catch.ts
- src/add/operator/do.ts
- src/add/operator/finally.ts
- src/add/operator/switch.ts
> fix(operators): export reserved name operators on prototype

- doc/tutorial/applications.md
I think it might be typo about tutorial.
> Docs: Fix typo in the tutorial

- spec/operators/expand-spec.ts
This PR adds test coverage to `expand` operator, cases where scheduler is specified.
> test(expand): add test coverage to expand

- spec/Subject-spec.ts
- src/Rx.ts
> fix(AnonymousSubject): is now exposed on Rx namespace

- src/observable/ConnectableObservable.ts
typo
looking to be the 100th contributor
> style(RefCountSubscriber): typo

- src/observable/FromEventObservable.ts
trying to be the 101st contributor ;)
> style(FromEventObservable): @param typo

- src/observable/GenerateObservable.ts
> style(GenerateOptions): typo Inital => Initial

- .travis.yml
> chore(build): Adding Node.js v6 on Travis

- .travis.yml
This PR updates travis configuration, having new env variable `FULL_VALIDATE` to run full test suite only targeted jobs. `FULL` means including below tasks
- lint
- circular dependency check
- coverage report
which doesn't need to be triggered multiple time on each build jobs. Instead, normal jobs only execute essential build (build, test) to get faster build turnaround time. PR still requires all jobs to be passed, so longest run will update github hooks.
> Enhance travis configuration with build matrix

- spec/helpers/testScheduler-ui.ts
- spec/support/debug.opts
- spec/support/default.opts
- spec/support/mocha-setup-node.js
- spec/support/tests2png.opts
- spec/support/webpack.mocha.config.js
- wallaby.js
⚠️ Targeting master ⚠️
This PR simplifies some of mocha runner configurations for further test pipeline refactoring.
Does not have breaking changes, targeting master.
#2225
> Simplify mocha runner configuration

- src/operator/zip.ts
> docs(operator): Zip documentation

- src/operator/max.ts
- src/operator/min.ts
Add min and max operators samples in documentation
> docs(operators): add min and max samples

- README.md
> chore(readme): Simplifes CDN usage directions

- src/operator/mergeScan.ts
- src/operator/toPromise.ts
Add docs for `mergeScan` and `toPromise`
> docs(operators): mergeScan and toPromise

- src/operator/catch.ts
Examples for the 'catch' operator
> docs(operators): examples for catch operator

- doc/introduction.md
Small grammar fix in intro docs.
> docs(intro): fix small grammar issue

- src/operator/concat.ts
Add more details about what parameters operator accepts, how it will behave with empty and never Observables, how it will deal with errors from input Observables and note that it can accept the same Observable many times.
> docs(concat): add more details about static version of operator

- src/operator/zip.ts
Fixes a typo in the description of the zip operator
> docs(zip): Fixed typo in the zip operator docstring

- doc/observable.md
The first two are self-explanatory.
The third was a bit stilted and used a "but" where there was no contrast.
> docs(overview): grammar fixes

- spec/operators/delayWhen-spec.ts
- src/operator/delayWhen.ts
> Revert "feat(delayWhen): add index to the selector function"

- CONTRIBUTING.md
Fixes the indentantion of the headlines in order to generate a correct TOC. Other minor fixes.
> docs(CONTRIBUTING): fix headline levels, minor fixes, regenerate TOC

- src/operator/map.ts
> doc(map) remove extra every

- src/operator/do.ts
Description: Add detail about `do` operator regarding error handling.
Related issue: Related to [#2425](https://github.com/ReactiveX/rxjs/issues/2425).
> docs(do): add more details about the operator

- .npmignore
> npmignore typings folder

- src/operator/observeOn.ts
Create documentation for the operator, describing what it can be used for, what parameters accepts and returns. Add example of typical usage and compare the operator with delay operator.
> docs(observeOn): create the documentation

- spec/operators/find-spec.ts
- src/operator/find.ts
see https://github.com/ReactiveX/rxjs/pull/2463 and https://github.com/ReactiveX/rxjs/pull/2665
> [NEXT] fix(find): force unsubscribe when it completes or errors

- dangerfile.js
> chore(danger): fix badge url

- src/Observable.ts
Fix a typo ("remote" --> "remove").
> docs(Observable): fix typo

- doc/operator-creation.md
docs(typo): Fix subscriptoin spelling
change subscriptoin to subscription
> docs(typo): Fix subscriptoin spelling

- package.json
> chore(package): bump up danger dependencies

- .travis.yml
- package.json
> chore(package): bump up devdependencies

- src/observable/combineLatest.ts
- src/operator/combineAll.ts
- src/operator/combineLatest.ts
- src/operator/distinct.ts
- src/operator/publishLast.ts
- src/operator/publishReplay.ts
- src/operators/combineAll.ts
- src/operators/combineLatest.ts
- src/operators/distinct.ts
- src/operators/index.ts
- src/operators/publishLast.ts
- src/operators/publishReplay.ts
> More lettables

- src/operator/repeat.ts
- src/operator/repeatWhen.ts
- src/operator/retry.ts
- src/operator/retryWhen.ts
- src/operator/sample.ts
- src/operator/sequenceEqual.ts
- src/operator/shareReplay.ts
- src/operator/single.ts
- src/operators/index.ts
- src/operators/repeat.ts
- src/operators/repeatWhen.ts
- src/operators/retry.ts
- src/operators/retryWhen.ts
- src/operators/sample.ts
- src/operators/sampleTime.ts
- src/operators/sequenceEqual.ts
- src/operators/share.ts
- src/operators/shareReplay.ts
- src/operators/single.ts
Adding lettable operators for:
```
single
shareReplay
share
sequenceEqual
sampleTime
sample
retryWhen
retry
repeatWhen
repeat
```
> Lettable operators2

- spec/observables/forkJoin-spec.ts
- src/observable/ForkJoinObservable.ts
* Add detailed description of forkJoin operator.
* Summarize what it accepts and returns.
* Provide links to similar operators.
* Provide examples of different ways it can be used.
> docs(forkJoin): add documentation for the operator

- src/operator/toArray.ts
Add documentation for operator including marble diagram, reference to buffer and code example.
https://github.com/ReactiveX/rxjs/issues/2656
> docs(toArray): create documentation for operator

- doc/writing-marble-tests.md
> [docs] Grammar fix

- README.md
This PR updates README.md to clarify the installation and usage of the library for different systems CJS/ES6/AMD/TypeScript.
- closes #2269
> docs(readme): Improve clarity of library installation and usage

- appveyor.yml
I'm keep forgetting this to check in into master. sigh.
> chore(appveyor): pin down to npm4

- package.json
Fixes #3005
PR to fix `stable` branch: https://github.com/ReactiveX/rxjs/pull/3026
> build: fix pointer to Rx.d.ts file

- src/operator/finally.ts
* Describe what parameters 'finally' accepts.
* Emphasize when function passed to the operator is called. 
* Compare the operator with 'subscribe'. 
* Add examples for calling function passed to 'finally' on complete and on unsubscribe.
> docs(finally): add documentation for the operator

- src/observable/IfObservable.ts
* Describe what if operator accepts and returns.
* Emphasize when condition function will be called. 
* Describe two basic use cases for that operator and show examples with that use cases.
* Compare to defer operator.
> docs(if): create documentation for the operator

- LICENSE.txt
Updated year range to 2018 in `LICENSE` file. Quick PR 😬 
> Updated year range to 2018

- src/scheduler/animationFrame.ts
Just fix a broken example in /src/scheduler/animationFrame.ts and now it works 👍
> Fix broken example in /src/scheduler/animationFrame.ts.

- spec/schedulers/AnimationFrameScheduler-spec.ts
This test is not related to delay but the effect of unsubscribe on the resulting Subscription.
> fix(animationFrame.spec): spec description fix

- package.json
> chore(dependencies): pin dependency-cruiser to 2.10.1

- doc/operators.md
> chore(doc): alphabetical order

- src/BUILD.bazel
- tsconfig.json
cherry-picked from stable branch
> chore(bazel): allow downstream projects to omit //:node_modules

- spec/index-spec.ts
- src/index.ts
> refactor(fromPromise): expose fromPromise through rxjs export

- package.json
- src/ajax/package.json
- src/operators/package.json
- src/testing/package.json
- src/websocket/package.json
> build: make all entry points side-effect free

- doc/installation.md
- doc/introduction.md
- doc/subject.md
- doc/tutorial/applications.md
- doc/tutorial/basics.md
- src/internal/operators/takeLast.ts
> docs(operators): use pipe for operators

- src/internal/types.ts
also remove unused import in types.ts
> fix: remove duplicate Subscribable<T> interface declaration

- node-tests/run.sh
- node-tests/test.js
- package-lock.json
- src/Subscriber.ts
related to #3476 
closes #3475
> fix(node): multno more silent failure for many copies of rxjs

- doc/tutorial/applications.md
> remove . before map operator inside pipe

- spec/operators/first-spec.ts
- src/internal/operators/first.ts
- updates tests
- bases first on take and other operators
- fixes unfound issue where default value could not be falsy
> refactor(first): smaller first

- src/internal/observable/zip.ts
> chore(zip): add deprecation warnings for resultSelector

- spec/observables/bindNodeCallback-spec.ts
- src/internal/observable/bindNodeCallback.ts
- src/internal/util/isScheduler.ts
- readd resultSelector
- update tests
- improve typings
> Bind node callback refactor

- package-lock.json
- spec/operators/skipUntil-spec.ts
- src/internal/operators/skipUntil.ts
Fixes skipUntil behavior to be correct.
- No longer waits for notifier to complete before completing
- No longer retains subscription to notifier after it notifies
> fix skipUntil

- CHANGELOG.md
> Fix typo in features section of the changes associated w/ 6.0.0-rc.0 version of RxJS

- src/ajax/BUILD.bazel
- src/testing/BUILD.bazel
- src/websocket/BUILD.bazel
This is a follow up PR for 26cb6e8ca73caf26b42b7614f9ff134b7edffc38
> build: fix remaining BUILD.bazel files

- migrations/collection.json
> fix(migrations): change the version the migration applies to

- src/websocket/index.ts
Export missing types
**Related issue (if exists):** #3457
> export WebSocketSubject, WebSocketSubjectConfig from rxjs/websocket

- spec/operators/toPromise-spec.ts
show that an empty Observable results in a promise resolved with a
value of undefined
> test: empty Observable.toPromise

- MIGRATION.md
This PR fixes charactors that cannot be displayed and removes unnecessary html tag.
> Fix quote and unnecessary tag in MIGRATION.md

- spec/operators/debounce-spec.ts
update debounce spec to use updated import sites and pipeable operators
> refactor(debounce-spec): update debounce operator tests to use pipeable operators

- spec/operators/concatAll-spec.ts
update concatAll spec to use updated import sites and pipeable operators
> refactor(concatAll-spec): update concatAll operator tests to use pipeable operators

- spec/operators/combineLatest-spec.ts
update combineLatest spec to use updated import sites and pipeable operators
> refactor(combineLatest-spec): update combineLatest operator tests to use pipeable operators

- spec/operators/debounceTime-spec.ts
update debounceTime spec to use updated import sites and pipeable operators
> refactor(debounceTime-spec): update debounceTime operator tests to use pipeable operators

- spec/operators/combineAll-spec.ts
update combineAll spec to use updated import sites and pipeable operators
> refactor(combineAll-spec): update combineAll operator tests to use pipeable operators

- spec/operators/catch-spec.ts
update catch spec to use updated import sites and pipeable operators
> refactor(catch-spec): update catchError operator tests to use pipeable operators

- spec/operators/delayWhen-spec.ts
update delayWhen spec to use updated import sites and pipeable operators
> refactor(delayWhen-spec): update delayWhen operator tests to use pipeable operators

- src/internal/observable/dom/WebSocketSubject.ts
Couldn't find any docs for bundled WebSocketSubject (anyone have a link to quick intro?), so went on to read the source and comments and stumbled upon this.
> docs(WebSocketSubject): fix mixed up comments

- src/internal/operators/audit.ts
- src/internal/operators/auditTime.ts
- src/internal/operators/buffer.ts
- src/internal/operators/bufferCount.ts
- src/internal/operators/bufferTime.ts
- src/internal/operators/bufferToggle.ts
- src/internal/operators/bufferWhen.ts
- src/internal/operators/catchError.ts
- src/internal/operators/concatAll.ts
- src/internal/operators/concatMap.ts
- src/internal/operators/concatMapTo.ts
- src/internal/operators/count.ts
- src/internal/operators/debounce.ts
- src/internal/operators/debounceTime.ts
- src/internal/operators/defaultIfEmpty.ts
- src/internal/operators/delay.ts
- src/internal/operators/delayWhen.ts
- src/internal/operators/dematerialize.ts
- src/internal/operators/distinct.ts
- src/internal/operators/distinctUntilChanged.ts
- src/internal/operators/distinctUntilKeyChanged.ts
Update operators' (audit* through distinct*) jsdoc examples to use pipe()
> update jsdoc examples (audit* through distinct*)

- .travis.yml
This PR expands our test matrix setup as previously discussed - in addition to current test setups, it builds against `typescript@latest` and `typescript@next` always to detect forward-breaking changes early. Those builds are specified as `allow_failures`, so does not block as long as default job passes.
example: 
> ci(travis): expand matrix to test multiple tsc

- src/internal/observable/bindNodeCallback.ts
- src/internal/observable/combineLatest.ts
- src/internal/observable/concat.ts
- src/internal/observable/defer.ts
- src/internal/observable/empty.ts
- src/internal/observable/forkJoin.ts
- src/internal/observable/fromEvent.ts
- src/internal/observable/fromEventPattern.ts
- src/internal/observable/generate.ts
- src/internal/observable/iif.ts
- src/internal/observable/interval.ts
- src/internal/observable/merge.ts
- src/internal/observable/never.ts
- src/internal/observable/onErrorResumeNext.ts
- src/internal/observable/pairs.ts
- src/internal/observable/range.ts
- src/internal/observable/throwError.ts
- src/internal/observable/timer.ts
- src/internal/observable/zip.ts
**Description:** jsdoc examples update in creation factories + converting result selectors to `map` + some linting
> docs: update jsdoc examples (factory functions)

- docs_app/tools/transforms/templates/api/lib/githubLinks.html
closes #3800 
It was really just a minor bug due to the different project structure than the angular team.
> fix(docs): fix broken github links

- docs_app/content/guide/v6/migration.md
> migration.md: Typo

- src/internal/operators/ignoreElements.ts
Add jsdoc examples for `ignoreElements` operator
> docs(jsdoc): add examples for ignoreElements

- src/internal/observable/race.ts
Add two jsdoc examples for `race()` factory method.
> docs(jsdoc): add examples for race()

- CONTRIBUTING.md
This pr adds some minor informations about the new documentation to the contribution.md.
> docs(contribution): describe new documentation

- doc/scheduler.md
> chore( schedule.md): Added Info about Animation Frame scheduler

- docs_app/src/app/layout/top-menu/top-menu.component.ts
> docs(beta): remove beta warning from header

- spec/observables/IteratorObservable-spec.ts
- spec/observables/ScalarObservable-spec.ts
- spec/observables/SubscribeOnObservable-spec.ts
- spec/observables/combineLatest-spec.ts
- spec/observables/concat-spec.ts
- spec/observables/defer-spec.ts
- spec/observables/dom/ajax-spec.ts
- spec/observables/from-promise-spec.ts
- spec/observables/interval-spec.ts
- spec/observables/merge-spec.ts
- spec/observables/of-spec.ts
- spec/observables/race-spec.ts
- spec/observables/range-spec.ts
- spec/observables/timer-spec.ts
- spec/observables/using-spec.ts
- spec/observables/zip-spec.ts
update all tests in spec/observables/ to use pipeable operators and updated import sites
> chore(test): udpate all tests in spec/observables

- README.md
Resolves typo in README for #3875 
> chore(README): fix typo

- doc/decision-tree-widget/tree.yml
**Description:** updates to the operator decision tree widget's content
**Related issue (if exists):** #3900
> doc(decision-tree): update operator/function names

- src/internal/scheduler/AsyncAction.ts
I correct indent size in AsyncAction.ts
Please review my change, thank you!
No issue exists.
> style(AsyncAction): correct indent size

- docs_app/src/environments/environment.archive.ts
- docs_app/src/environments/environment.next.ts
- docs_app/src/environments/environment.stable.ts
> docs: switch to unique ga account

- src/observable/FromEventPatternObservable.ts
* Compare to fromEvent. 
* Describe what addHandler and removeHandler functions are called with and when they are called. 
* Describe how APIs that return cancellation token on handler registration can be handled and show example of that.
* Add note that only first parameter from event handler will appear in the output Observable. 
* Describe how project function can be used to get access to other parameters and show an example of that.
> docs(fromEventPattern): add more details about the operator

- src/observable/GenerateObservable.ts
* Describe what is generate, its input and output, by comparing it to regular for loop.
* Describe two modes it can be used in and give examples for each of these modes.
* Emphasize which arguments are optional in each mode.
> docs(generate): write documentation for the operator

- spec/observables/pairs-spec.ts
- src/observable/PairsObservable.ts
When I am not trying to rewrite fundamentals of rxjs, I still write docs. ;)
* Describe what pairs accepts and returns. 
* Note what kind of object properties will be emitted.
* Add note about optional scheduler parameter.
* Modify `asDiagram` test for better marble in docs.
> docs(pairs): document the operator

- package-lock.json
This PR updated the lock file using these commands (with npm v6.2.0):
```
npm uninstall --save-dev dtslint
npm install --save-dev --save-exact dtslint
```
> chore(package): update lock file

- doc/marble-testing.md
Add import statement for `TestScheduler` and make the first example more complete.
> docs(testing): Improve marble testing example

- src/internal/scheduler/AsyncAction.ts
Solves the issue with Travis failing for TS@3.1.0
> fix(TS@next): remove unnecessary return statement

- docs_app/content/marketing/team.html
It seems like I deleted the teams page with my latest changes. So here's the revert for this
> docs(teams): revert deleting teams page

- spec-dtslint/operators/takeUntil-spec.ts
This PR adds dtslint tests for `takeUntil`.
> test(dtslint): add takeUntil

- spec-dtslint/operators/take-spec.ts
This PR adds dtslint tests for `take`.
> test(dtslint): add take

- spec-dtslint/operators/retry-spec.ts
This PR adds dtslint tests for `retry`.
> test(dtslint): add retry

- docs_app/src/app/app.component.html
- docs_app/src/styles/2-modules/_search-results.scss
Uncomment the search box for quicker document lookup.
> docs(UI): Reintroduce Docs Search Capability

- spec-dtslint/operators/skip-spec.ts
This PR adds dtslint tests for `skip`.
> test(dtslint): add skip

- spec-dtslint/operators/delay-spec.ts
**Description:** add dtsLint test on delay operator
> test(dtslint): add dtslint test on delay operator (#4093)

- spec/migration/update-6_0_0/index-spec.ts
Small update to test cases which doesn't need to be async.
> test(migration): do not schedule in async test

- spec-dtslint/operators/tap-spec.ts
**Description:** Add dtslint test for tap operators
> test(dtslint): add tap operators dtslint test (#4093)

- spec-dtslint/operators/every-spec.ts
**Description:** Add dtslint test for Every operator
> test(dtslint): add dtslint test for every operator (#4093)

- spec-dtslint/operators/timeoutWith-spec.ts
This PR adds dtslint tests for `timeoutWith`.
> test(dtslint): add timeoutWith

- spec-dtslint/operators/materialize-spec.ts
This PR adds dtslint tests for `materialize`.
> test(dtslint): add materialize

- spec-dtslint/operators/single-spec.ts
This PR adds dtslint tests for `single`.
> test(dtslint): add single

- spec-dtslint/operators/finalize-spec.ts
This PR adds dtslint tests for `finalize`.
> test(dtslint): add finalize

- spec-dtslint/operators/elementAt-spec.ts
This PR adds dtslint tests for `elementAt`.
> test(dtslint): add elementAt

- spec-dtslint/operators/dematerialize-spec.ts
This PR adds dtslint tests for `dematerialize`.
> test(dtslint): add dematerialize

- docs_app/content/guide/overview.md
Closes #4173 
This PR fixes operators reference, internal links, given in overview page.
**Related issue (if exists):** N/A
> docs(overview): fix operators internal links

- spec-dtslint/operators/publish-spec.ts
**Description:** Add dtslint test for Publish operator
> test(dtslint): add dtslint test for publish operator (#4093)

- src/internal/observable/zip.ts
**Description:** Fix error in example
**Related issue (if exists):** #4192
> docs(zip): fix error in zip example

- src/internal/observable/dom/ajax.ts
> docs: remove invalid parenthesis in ajax sample code

- spec-dtslint/operators/publishBehavior-spec.ts
**Description:** Add dtslint test for publishBehaviour operator 
> test(dtslint): add dtslint test for publishBehavior operator (#4093)

- spec-dtslint/operators/repeat-spec.ts
This PR adds dtslint tests for `repeat`.
> test(dtslint): add repeat

- spec-dtslint/operators/publishLast-spec.ts
**Description:** Add dtslint test for publishLast operator
> test(dtslint): add dtslint test for publishLast operator (#4093)

- spec-dtslint/operators/publishReplay-spec.ts
**Description:** Add dtslint test for publishReplay operator
> test(dtslint): add dtslint test for publishReplay operator (#4093)

- docs_app/content/marketing/contributors.json
just add me to the core teams page of the docs
> docs(team): add jan-niklas to core team

- spec-dtslint/operators/refCount-spec.ts
**Description:** Add dtslint test for reduce operator
> test(dtslint): add dtslint test for refCount operator (#4093)

- spec-dtslint/operators/reduce-spec.ts
**Description:** Add dtslint for reduce operators
> test(dtslint): add dtslint test for reduce operator (#4093)

- spec-dtslint/operators/map-spec.ts
Description:
This PR adds dtslint tests for `map`.
> test(dtslint): add map

- spec-dtslint/operators/mapTo-spec.ts
Description:
This PR adds dtslint tests for `mapTo`.
> test(dtslint): add mapTo

- src/internal/Subject.ts
> docs(index): error in the doc

- src/internal/operators/publish.ts
https://github.com/ReactiveX/rxjs/issues/4052
> docs($browser): It adds a tiny example of how to use publish operator.

- spec-dtslint/operators/pluck-spec.ts
**Description:** Add dtslint test for Pluck operator
> test(dtslint): add dtslint test for pluck operator(#4093)

- spec-dtslint/operators/sample-spec.ts
**Description:** Add dtslint test for Sample operator
> test(dtslint): add dtslint test for sample operator (#4093)

- spec-dtslint/operators/expand-spec.ts
- spec-dtslint/tslint.json
Description:
This PR adds dtslint tests for `expand`.
> test(dtslint): add expand

- spec-dtslint/operators/sampleTime-spec.ts
**Description:** Add dtslint test for sampleTime operator
> test(dtslint): add dtslint test for sampleTime operator (#4093)

- spec-dtslint/operators/toArray-spec.ts
**Description:** add dtslint tests for toArray operator
> test(dtslint): add dtslint tests for toArray operator (#4093)

- spec-dtslint/operators/sequenceEqual-spec.ts
**Description:** add dtslint test for sequenceEqual operator
> test(dtslint): add dtslint test for sequenceequal operator (#4093)

- docs_app/content/guide/installation.md
Just to make the docs more consistent
> docs(installation): fix punctuation

- spec-dtslint/operators/multicast-spec.ts
- spec-dtslint/tslint.json
Description:
This PR adds dtslint tests for `multicast`.
> test(dtslint): add multicast

- spec-dtslint/operators/window-spec.ts
**Description:** add dtslint tests for window operator
> test(dtslint): add dtslint tests for window operator (#4093)

- spec-dtslint/operators/share-spec.ts
Description:
This PR adds dtslint tests for `share`.
> test(dtslint): add share

- .github/ISSUE_TEMPLATE/documentation.md
Fix typo in the documentation issue template.
> chore(issue-template): fix typo in Issue template

- spec-dtslint/operators/windowCount-spec.ts
**Description:** add dtslint tests for the windowCount operator
> test(dtslint): add dtslint tests for windowCount operator (#4093)

- README.md
Update examples and usage explanation to be more inline with the current version of the library.
The two sentences related to how to import Observables/operators are taken (and slightly modified) from the [doc about pipable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md#usage).
Closes #4370
> docs(README): update examples and usage explanation

- spec-dtslint/operators/shareReplay-spec.ts
Description:
This PR adds dtslint tests for `shareReplay`.
> test(dtslint): add shareReplay

- spec-dtslint/operators/combineLatest-spec.ts
**Description:** Add dtslint test for combineLatest operator
> test(dtslint): add dtslint test for combineLatest operator (#4093)

- compat/operator/distinctUntilChanged.ts
Fixed distinctUntilChanged doc typo
> Fixed distinctUntilChanged doc typo

- src/internal/observable/race.ts
The race function was wrongly documented and made the docs page look weird. Should be fixed after this pr
> docs(observable): fix wrongly formatted race docs

- .travis.yml
- docs_app/scripts/deploy-to-firebase.sh
the firebase token was removed because I put it in the travis settings. Might make changes to it easier.
Additionally I have added the tests2png script to generate the marble diagrams for the docs.
Not completly sure if docs deployment now works automatically maybe we have to take another round :D
> docs(ci): try autodeployment

- README.md
Update the link to API documentation since the current one simply redirects to the new one.
> docs(README): Update link to API documentation

- spec-dtslint/operators/windowToggle-spec.ts
Description:
This PR adds dtslint tests for `windowToggle`.
> test(dtslint): add windowToggle

- src/internal/create/interval.ts
Don't export `intervalWork`; it's an implementation detail.
> chore(interval): don't export work function

- src/internal/Subscription.ts
This removes unnecessary checks on the `teardown` parameter upfront, and
instead moves these checks into the appropriate branches guarded by the
type check. This way we get the same behavior, but with fewer checks and
smaller code size.
Also optimize adding the child `subscription` to `this._subscriptions`
for the common case that there were no previous subscriptions.
> perf(internal): optimize Subscription#add() for the common case

- spec-dtslint/observables/from-spec.ts
**Description:** Add dtslint test for from observable static function 
> test(dtslint): add dtslint test for from static function (#4093)

- spec-dtslint/observables/forkJoin-spec.ts
**Description:** Add dtslint test for forkJoin observable static method creation
> test(dtslint): add dtslint test for forkjoin obsrevable (#4093)

- src/index.ts
Exports `NotificationKind`.
**Related issue (if exists):** #4513
> fix(index): export NotificationKind

- src/internal/observable/bindCallback.ts
Fixed bug `Error: someFunction is not defined`
Site [stackblitz](https://stackblitz.com/run?devtoolsheight=50)
> Fixed bug - Error: someFunction is not defined

- src/internal/observable/combineLatest.ts
Fixed the import in the example
> Fixed import in the combineLatest example

- src/internal/operators/auditTime.ts
> docs(auditTime): fix docs typo

- src/internal/observable/from.ts
Update examples so they work standalone.
Closes #4542
> docs(from): update examples

- src/internal/operators/isEmpty.ts
Added documentation for `isEmpty` operator
> docs(operators): Added docs/examples for isEmpty

- src/internal/observable/concat.ts
> docs(concat): tidy example

- src/internal/observable/ConnectableObservable.ts
there is no need for the assignment
> chore(ConnectableObservable): remove unused code

- src/internal/observable/forkJoin.ts
> docs(forkJoin): fix example

- tslint.json
Disables the `no-unused-variable` TSLint rule in the `experimental` branch. That rule has caused so many problems for me in the past.
**Related issue (if exists):** https://github.com/cartant/rxjs-tslint-rules/issues/4
> chore(tslint): disable no-unused-variable

- src/internal/observable/dom/ajax.ts
👋 loving how great job you people doing here! Thanks for giving us the opportunity to use this library.
I have the feeling that since `ajax` is one of the useful operators we have in Rxjs for making requests it would be nice if the documentation have more examples. Therefore I opened this PR that will add few examples on Stackblitz.
I tried to follow best your style but since its my first PR here I would be happy to hear your feedback. I am positive that I am gonna work on that in order to have this documented well for future referenced.
https://github.com/ReactiveX/rxjs/issues/4652
> docs(ajax): Adding more examples and cases of how ajax operator can be used.

- src/internal/operators/exhaustMap.ts
> docs(exhaustMap): fix example

- src/WORKSPACE
Under bazel, we don't build rxjs from source anymore.
> refactor: remove WORKSPACE

- src/internal/util/hostReportError.ts
@types/node requires to pass milliseconds to setTimeout
> Added ms in setTimeout call

- src/internal/operators/refCount.ts
add short description
add description
add link to image
add example
Closes #4715
> docs: add refcount documentation

- src/internal/operators/timeInterval.ts
**Description:** Updated description of timeInterval operator
**Related issue (if exists):** #4661
> docs(timeinterval): update description for timeInterval

- src/internal/operators/repeatWhen.ts
Added Example and see also links
#4676
> docs(repeatWhen): Added example and see also

- src/internal/operators/retry.ts
**Description:** Updated documentation for retry operator
**Related issue (if exists):** #4627
> docs(retry): add example for retry operator

- .circleci/config.yml
> ci: add circleci

- .circleci/config.yml
Adds Circle config to 6.x branch
> ci: add circleci (#4770)

- src/internal/scheduled/scheduled.ts
fixes a bad import that causes build issues in some systems.
> fix(scheduled): import from relative paths

- src/internal/operators/toArray.ts
**Description:** Added description and example for `toArray`
**Related issue (if exists):** #4613
> docs(toArray): added description and example for toArray

- src/internal/operators/debounce.ts
This PR implements the suggested changed from #4842 
Additionally, I adopted the wording from "value" to "notification" in the documentation section.
This PR closes #4842
#4842
> docs(debounce): extended docs, example and see also links

- src/internal/operators/debounceTime.ts
These changes are related to #4843 
For a full description on these changes please visit the related issue here: #4843.
See detailed description for the changes here: #4843 
closes  #4843
> docs(operators): Suggestions for `debounceTime` documentation improvements

- src/internal/operators/timeoutWith.ts
> docs(operators): fix typo

- src/internal/observable/of.ts
> docs(index): add missing console log onComplete

- spec/Subscription-spec.ts
* Cleaned up wording
* Moved positive cases to the top
* Grouped unsubscribe() tests together
> test(Subscription): Update subscription tests

- src/internal/operators/multicast.ts
> docs(operators): fixed typo

- src/internal/observable/bindCallback.ts
Changed one of the examples.
Closes: #4927
> docs(bindCallback): Change broken example

- spec-dtslint/helpers.ts
- spec-dtslint/operators/merge-spec.ts
**Description:** Add dtslint test for merge operator  
> test(dtslint): add dtslint test for merge operator (#4093)

- spec-dtslint/operators/zipAll-spec.ts
Description:
This PR adds dtslint tests for `zipAll`.
> test(dtslint): add zipAll

- src/internal/operators/delayWhen.ts
See also section extended with all related operators.
This closes #4922
> docs(delayWhen): Extended see also

- spec/operators/combineAll-spec.ts
- spec/operators/combineLatest-spec.ts
Use TestScheduler#run for the combineAll and combineLatest operator tests
> test(combineAll, combineLatest operators): execute tests with TestScheduler#run

- spec/operators/catch-spec.ts
Use TestScheduler#run for the catch operator tests
> test(catch operator): execute tests with TestScheduler#run

- src/internal/operators/expand.ts
> Syntax correction

- src/internal/observable/range.ts
Fix `range` function example in doc.
No
> docs(range): Fix example

- src/internal/operators/catchError.ts
Include description and see also section with all related operators.
This closes #4645
> docs(catchError): Enhance description, extended see also

- src/internal/observable/of.ts
> refactor(of): remove unused import

- src/internal/operators/retryWhen.ts
- Added example: Trigger retry after specified duration.
- Added a simple description about for what the operator is useful.
#4626
> docs(retryWhen): Add description and example #4626

- spec/operators/windowTime-spec.ts
- src/internal/operators/windowTime.ts
- Updates tests
- Adds test for errant race condition
- Fixes an issue where if there was a max window size while multiple windows were open, it mutated the array it was iterating over and caused an error.
Closes #4847 (as no test was ever added by request)
> Fix window time race condition

- docs_app/content/marketing/contributors.json
> docs(alumn): add Jay Phelps as core team alumn

- src/internal/observable/concat.ts
> docs(concat): improve short description

- spec-dtslint/observables/dom/ajax-spec.ts
This PR adds dtslint tests for `ajax`.
> test(dtslint): add ajax

- .github/workflows/ci_main.yml
- .github/workflows/ci_ts_latest.yml
As
As discussed in https://github.com/ReactiveX/rxjs/issues/5276, this PR try to setup ci using github actions to see if we can deprecate circleci.
> build(actions): setup initial gh actions script

- .github/workflows/rebase.yml
> build(rebase): add rebase command

- docs_app/content/guide/operators.md
Just fixing what I think was a copy-paste typo.
Didn't bother searching.
> Fix suspected typo

- src/internal/operators/switchAll.ts
> docs(switchAll): fixing comment issue

- package-lock.json
- package.json
> chore: update to TS 3.8

- spec-dtslint/observables/bindCallback-spec.ts
This PR adds dtslint tests for `bindCallback`.
> add dtslint bindCallback

- spec/util/subscribeWith-spec.ts
This PR removes an unused import that was effecting a lint failure.
> chore: remove unused import

- src/internal/observable/dom/WebSocketSubject.ts
Fix a code snip for server for better understanding
> docs(webSocket): fix the server part code demo

- src/internal/operators/sequenceEqual.ts
> docs(operators): typo

- spec-dtslint/observables/defer-spec.ts
- spec/observables/defer-spec.ts
- spec/operators/race-spec.ts
- spec/operators/raceWith-spec.ts
- src/internal/observable/defer.ts
> fix(defer) Disallow passing () => undefined to observableFactory

- src/internal/observable/empty.ts
> docs(index): fix EMPTY link

- .github/workflows/ci_main.yml
- package-lock.json
- package.json
- tools/rollup-bundle.js
This PR adds node.js 14 into ci matrix.
> build(ci): add node.js 14 into matrix

- package-lock.json
- package.json
> build(package): move devdeps properly

- spec/Observable-spec.ts
> test(Observable): add skipped test for edge case

- spec/Notification-spec.ts
- spec/Observable-spec.ts
- spec/Subject-spec.ts
- spec/observables/combineLatest-spec.ts
- spec/operators/zipAll-spec.ts
- spec/subjects/ReplaySubject-spec.ts
Going through and updating more tests to run mode. (Code also formatted)
> Run mode updates 1

- spec/observables/concat-spec.ts
- spec/observables/defer-spec.ts
- spec/observables/empty-spec.ts
- spec/observables/forkJoin-spec.ts
Updates `concat`, `defer`, `empty` and `forkJoin` tests to run mode.
> Run mode updates 2

- docs_app/content/guide/operators.md
> docs(operators.md): fix grammar v6

- .github/workflows/ci_main.yml
- .github/workflows/ci_ts_latest.yml
- api_guard/dist/typings/index.d.ts
- api_guard/dist/typings/testing/index.d.ts
- package-lock.json
- package.json
- tools/rollup-bundle.js
> build(actions): cherry-pick gh actions to 6.x 

- package.json
Change the homepage setting in package.json to the official docs site.
#5668
> fix(package.json): change homepage setting to official docs site.

- docs_app/tools/decision-tree-generator/package-lock.json
- docs_app/tools/decision-tree-generator/package.json
- docs_app/tools/decision-tree-generator/tsconfig.json
- Updates 111 high vulnerability packages
- Updates TS to latest version
- Updates jest, etc.
This PR was created more of a paper trail than anything. I'll merge once CI passes (because it's just a deps update)
> chore: update packages for decision tree

- src/internal/observable/dom/animationFrames.ts
This PR contains a minor refactor of the subscription management within `animationFrames` to make things a little simpler and somewhat more idiomatic.
> refactor(animationFrames): simplify subscription

- package-lock.json
- package.json
> chore: update check-side-effects

- src/internal/operators/map.ts
- Refactor and add comments
Before: 525B
After: 345B (65% of original size)
BREAKING CHANGE: `thisArg` will now default to `undefined`. The previous default of `MapSubscriber` never made any sense. This will only affect code that calls map with a `function` and references `this` like so: `source.pipe(map(function () { console.log(this); }))`. There wasn't anything useful about doing this, so the breakage is expected to be very minimal. If anything we're no longer leaking an implementation detail.
> refactor(map): reduce the size of the implementation

- src/internal/operators/mergeMap.ts
- Refactor with comments
Before: 1.1KB
After: 639B (58% of the original size)
> refactor(mergeMap): reduce the size of the implementation

- spec/operators/timeout-spec.ts
Looks like this test is now passing?
> test(timeout): enable skipped test

- spec/operators/take-spec.ts
> test: add test to take with passed string as parameter

- api_guard/dist/types/operators/index.d.ts
- spec/operators/throttle-spec.ts
- src/internal/operators/debounceTime.ts
- src/internal/operators/throttle.ts
- src/internal/operators/throttleTime.ts
- refactor(debounceTime): based off of debounce
- refactor(throttleTime): based off of throttle
- fix(throttle): trailing values will now emit after source completes
> Fix throttle, refactor throttle and debounce

- spec/observables/from-spec.ts
- src/internal/observable/from.ts
- Adds comments
- Adds a couple of tests to make sure iterator and generator specific logic were accounted for.
> refactor(from): reduce the size of fromIterable

- src/internal/operators/refCount.ts
- Update description for the `refCount` operator as suggested in #4799
- Do I also need to remove the marble image?
- Closes #4799
> docs(refCount): update description

- api_guard/dist/types/index.d.ts
- spec/observables/range-spec.ts
- src/internal/observable/range.ts
- Adds some new tests, and removes some irrelevant unit tests.
- Adds comments.
> refactor(range): Smaller implementation, tests added

- src/internal/operators/last.ts
- Add description, example, and See Also section for the `skip` operator
- Closes #4870
> docs(last): add description and example for the operator

- spec/operators/throttle-spec.ts
Add some tests to ensure the linked bug is fixed.
**Related issue (if exists):** 
https://github.com/ReactiveX/rxjs/issues/5732
> test(throttle): 5732

- spec-dtslint/operators/delayWhen-spec.ts
> test(delayWhen): dtslint case for $ExpectNoDeprecation

- spec/operators/concatMapTo-spec.ts
Updated `concatMapTo` tests to use run mode.
> Update concatMapTo tests to run mode

- spec/operators/debounce-spec.ts
Updated `debounce` tests to use run mode.
> Update debounce tests to run mode

- spec/operators/count-spec.ts
Update `count` tests to use run mode.
> chore: update count tests to run mode

- spec/operators/debounceTime-spec.ts
Updated `debounceTime` tests to use run mode.
> Update debounceTime tests to run mode

- spec/schedulers/TestScheduler-spec.ts
Added `TestScheduler.createTime` tests for both run mode and regular mode.
> test(TestScheduler): add createTime tests

- spec/operators/dematerialize-spec.ts
Updated `dematerialize` tests to use run mode.
> chore: update dematerialize tests to run mode

- spec/operators/distinct-spec.ts
Updated `distinct` tests to use run mode.
> chore: update distinct tests to run mode

- spec/operators/distinctUntilChanged-spec.ts
Updated `distinctUntilChanged` tests to use run mode.
> chore: update distinctUntilChanged tests to run mode

- spec/operators/delayWhen-spec.ts
Updated `delayWhen` tests to use run mode.
> chore: update delayWhen tests to run mode

- spec/operators/distinctUntilKeyChanged-spec.ts
Updated `distinctUntilKeyChanged` tests to use run mode.
> chore: update distinctUntilKeyChanged tests to run mode

- spec/operators/elementAt-spec.ts
Updated `elementAt` tests to use run mode.
> chore: update elementAt tests to run mode

- spec/schedulers/TestScheduler-spec.ts
- src/internal/testing/TestScheduler.ts
Adding tests for subscription marbles parser. Also, fixed error message.
> test(TestScheduler): add tests for subscription marbles parser

- spec/operators/exhaustMap-spec.ts
Updated `exhaustMap` tests to use run mode.
None
> chore: update exhaustMap tests to run mode

- spec/operators/expand-spec.ts
Updated `expand` tests to use run mode.
None
> chore: update expand tests to run mode

- .github/workflows/ci_main.yml
- .github/workflows/ci_ts_latest.yml
Let's bump up ci matrix. ci_ts_latest now points lts (14) as well.
> ci(actions): bump up versions on ci actions

- docs_app/content/guide/testing/marble-testing.md
I guess it’s a bad copy/paste from previous example …
> doc: fix error in marble testing example

- spec/operators/filter-spec.ts
Updated `filter` tests to use run mode.
None
> chore: update filter tests to run mode

- spec/operators/find-spec.ts
Updated `find` tests to use run mode.
None
> chore: update find tests to run mode

- spec/operators/findIndex-spec.ts
Updated `findIndex` tests to use run mode.
None
> chore: update findIndex tests to run mode

- spec/operators/first-spec.ts
Updated `first` tests to use run mode.
None
> chore: update first tests to run mode

- spec/operators/last-spec.ts
Updated `last` tests to use run mode.
None
> chore: update last tests to run mode

- spec/operators/map-spec.ts
Updated `map` tests to use run mode.
None
> chore: update map tests to run mode

- package-lock.json
- package.json
Nothing major. Just updating dependencies for audit warnings.
> chore: Update dependencies from npm audit

- spec/operators/mapTo-spec.ts
Updated `mapTo` tests to use run mode.
None
> chore: update mapTo tests to run mode

- src/internal/observable/combineLatest.ts
- no longer use an array to track first value emission
- inline a few things than can be inlined
- adds more comments
> refactor(combineLatest): small efficiency changes

- docs_app/content/guide/operators.md
> docs: Fix bad operator example in docs

- CONTRIBUTING.md
> Update creating operators link

- spec/operators/mergeAll-spec.ts
Updated `mergeAll` tests to use run mode.
None
> chore: update mergeAll tests to run mode

- spec/operators/min-spec.ts
Update `min` tests to run mode.
> chore: update min tests to run mode

- spec/operators/throttle-spec.ts
Migrate from `helpers/marble-testing'` functions to `TestScheduler`
I also opened #5360 which is a bug IMHO
> test(testScheduler): refactored to use testScheduler

- spec/operators/zip-spec.ts
This PR adds prettier formatting to `zip` operator tests.
None
> refactor(zip): update code formatting

- spec/operators/mergeMapTo-spec.ts
Updated `mergeMapTo` tests to use run mode.
None
> chore: update mergeMapTo tests to run mode

- spec/operators/multicast-spec.ts
Updated `multicast` tests to use run mode.
None
> chore: update multicast tests to run mode

- spec/operators/observeOn-spec.ts
Updated `observeOn` tests to use run mode. There was a PR (#6209) that had the same title as this one, but it was mistakenly titled that way - it was related to `subscribeOn` tests.
None
> chore: update observeOn tests to run mode

- package.json
This reverts commit 659a623c94bd6b210e9beb6bb6061be540b05538.
Related to #6067
> Revert "chore: Add typesVersions to package.json (#6229)"

- docs_app/content/6-to-7-change-summary.md
This PR adds the remaining v7 breaking changes from the CHANGELOG - some were added in #6299
> docs: add changelog breaking changes to summary

- README.md
This PR updates the branch information present within the `README.md` file.
* `master` now points to the current v7 development branch
* `stable` does not exist, so the link and description is changed to point to the v6 branch
None
> docs: update branch information in README.md

- docs_app/content/deprecations/breaking-changes.md
- docs_app/content/marketing/index.html
- docs_app/src/styles/1-layouts/_marketing-layout.scss
this pr adds a link to the breaking changes page so that it can be access from the v7 announcement card
> Improve homepage

- docs_app/content/6-to-7-change-summary.md
- docs_app/content/deprecations/to-promise.md
- docs_app/content/guide/observable.md
- docs_app/content/navigation.json
- src/internal/Observable.ts
- src/internal/firstValueFrom.ts
- src/internal/lastValueFrom.ts
- src/internal/util/EmptyError.ts
Introduce new guide "Conversion to Promises".
#5927
> docs: introduce "Conversion to Promises" guide

- README.md
Updated/Fixed UNPKG bundle path in the README, so that it works.
> Fixed UNPKG bundle path

- src/internal/operators/defaultIfEmpty.ts
> docs(operators): defaultIfEmpty

- src/internal/operators/scan.ts
> docs(operators): scan

- docs_app/content/guide/installation.md
Update the CDN Installation instructions to match the instructions from README.md.
> docs(Installation): Fix CDN links.

- src/internal/observable/throwError.ts
https://rxjs.dev/api/index/function/throwError
> chore(throwError): typo

- docs_app/src/app/app.component.ts
Fixes small typo in console output
Fixes a small typo in the source code.
> fix: fix typo in console output

- spec/operators/onErrorResumeNext-spec.ts
Updated `onErrorResumeNext` tests to use run mode.
None
> chore: update onErrorResumeNext tests to run mode

- src/internal/Observable.ts
there is an unnecessary if in the pipe, remove it
#6504
> refactor(Observable): remove unnecessary if

- src/internal/operators/finalize.ts
> docs(operators): Fix results comment

- spec/observables/forkJoin-spec.ts
- src/internal/observable/forkJoin.ts
> fix(forkJoin): now finalizes sources before emitting

- src/internal/operators/share.ts
Fix imports in "Delayed reset" example.
Closes #6552
> docs(share): fix imports in "Delayed reset" example

- src/internal/operators/retry.ts
**Description:** Improve the docs.
> docs: use the correct word

- src/internal/operators/switchScan.ts
Update the informal doc to refer to mergeScan instead of scan. lmk if I am wrong!
> Update switchScan doc

- spec/operators/throttleTime-spec.ts
**Description:** Fix typo in test name
> Fix typo in test name

- package-lock.json
- package.json
> fix: RxJS now supports tslib 2.x, rather than just 2.1.x

- src/internal/operators/dematerialize.ts
Replace casting with constant type declaration.
None, just [this comment](https://github.com/ReactiveX/rxjs/pull/6678#discussion_r778152428).
> docs(dematerialize): move away from bracket casts

- spec/helpers/marble-testing.ts
- tools/add-license-to-file.js
Hello,
I was browsing through the source code and found some vars that weren't being used, so I decided to remove them (although the "Tree Shaking" process probably already does it by default)...
> chore: remove unused variables

- src/internal/operators/shareReplay.ts
This is just a minor thing I noticed.
> refactor(shareReplay): Simplify code with a destructure

- docs_app/package-lock.json
- docs_app/package.json
- package-lock.json
> chore: Revert dependabot nonsense

- src/internal/operators/retryWhen.ts
Remove unnecessary colon that caused docs script to fail.
None
> chore: fix docs generation script

- spec/observables/merge-spec.ts
This PR converts `merge` unit tests to run mode.
None
> chore(merge): convert merge specs to run mode

- src/internal/ReplaySubject.ts
From:  with a couple fo exceptions
To: with a couple of exceptions
Description: typo
BREAKING CHANGE: N/A
Related issue (if exists): N/A
> docs(ReplaySubject): typo 'fo' should be 'of'

- src/internal/Subject.ts
"Create customize..." is grammatically incorrect and was changed based on the context.
> Fix wording

- docs_app/package-lock.json
- docs_app/package.json
This PR fixes an issue reported in #7009.
@carltheperson, it looks like that all we had to do was to update the `dgeni-packages` version to the latest. Thanks a lot for bringing this to my attention.
Closes #7009
> chore: update dgeni-packages to the latest version

- package-lock.json
- package.json
- spec-dtslint/observables/from-spec.ts
- src/internal/operators/tap.ts
- src/internal/types.ts
- tsconfig.mocha.json
Just updates TypeScript to the latest version. Fixes some typings errors with `tap`.
> chore(build): Update TypeScript to 4.9.4

- README.md
just correct a number in the readme.
> docs(readme): fix number version in readme

- docs_app/content/marketing/contributors.json
Fix url for Ben's website
Fixes #7210
> chore(docs): fix url for Ben's website

- scripts/release.js
+ Ensure the proper upstream is always selected
+ Display the options provided
+ Fixes a 1GB number to be a proper 1GB
> chore: improve release script
