src/internal/operators/distinct.ts
src/internal/operators/groupBy.ts

This fixes closure compiler issues, and also removes the only side-effect from these modules. We want our modules to be side-effect free. This was an oversight in that regard

fix(closure-compiler): remove top level throws

---

src/internal/Observable.ts

the internal flag was causing issues with _isScalar checks when combined with closure compiler, removing it and opting for a comment and an obviously internal _name

fix(closure-compiler): remove internal flag from _isScalar

---

src/MiscJSDoc.ts
src/internal/observable/SubscribeOnObservable.ts
src/internal/observable/dom/AjaxObservable.ts
src/internal/operators/observeOn.ts
src/internal/testing/TestScheduler.ts

There are a few issues with closure compiler and static members not flagged with nocollapse. This change is non-invasive.

fix(closure-compiler): adds nocollapse to static members

---

src/index.ts
src/internal/Scheduler.ts

There are a lot of people extending Scheduler, they really should not be, but we can give them time to fix things on their end before removing the reexport of Scheduler. Scheduler is an internal implementation detail.

fix(Scheduler): export but deprecate

---

src/internal/util/subscribeToArray.ts
src/internal/util/subscribeToObservable.ts

There were some params comments added that should not have been there, given that they were part of the result of a higher order function, not the initial arguments.

fix(closure-compiler): removes bad @params comments that caused issues

---

compat/Subscription.ts

Closes #3531
Adds a `TeardownLogic` export to `compat/Subscription` for 5.5.8 compatibility - see [this export](https://github.com/ReactiveX/rxjs/blob/5.5.8/src/Subscription.ts#L12) in 5.5.8.
**Related issue (if exists):** #3531

fix(compat): export TeardownLogic

---

.make-compat-package.js
.make-helpers.js
.make-packages.js
tsconfig/compat/tsconfig.base.json
tsconfig/tsconfig.base.json
tsconfig/tsconfig.legacy-reexport.json

This PR basically just adjusts the `sources` property of the `.js.map` files to point to the right places.
Fixes #3479

fix(sourcemaps): fix mappings for source maps so they will work

---

src/internal/observable/fromEvent.ts

There was a type mismatch in `observable/fromEvent.ts` which causes `tsc` compile error when I tried to compile the following.
```
Observable.fromEvent(new EventEmitter(), "foo")
```
Error I've got is below
```
src/my-library/index.ts:41:5 - error TS2352: Type 'EventEmitter' cannot be converted to type 'NodeStyleEventEmitter'.
Types of property 'addListener' are incompatible.
Type '(event: string | symbol, listener: (...args: any[]) => void) => EventEmitter' is not comparable to type '(eventName: string, handler: Function) => void'.
Types of parameters 'listener' and 'handler' are incompatible.
Type 'Function' is not comparable to type '(...args: any[]) => void'.
Type 'Function' provides no match for the signature '(...args: any[]): void'.
```
NOTE: There was also a same …

fix: fix type mismatch in `NodeStyleEventEmitter`

---

src/BUILD.bazel
src/operators/BUILD.bazel

Excludes backward compat code introduced in 6.0.0-rc.1 from Bazel build

build(bazel): exclude backwards compat code

---

package.json

Now that we're nearing release, locking TypeScript down to 2.8.x to prevent further breakage.
(For those of you who don't know, TypeScript does _not_ adhere to semver, and publishes breaking changes in minor releases)

chore(TypeScript): locked to 2.8.*

---

.travis.yml
appveyor.yml

It's time to update our CI.
This will run the builds in v8 (LTS) and v9 (current) of Node and stop running in 4, 5, and 6.

chore(CI): have CI run in Node current LTS and higher

---

src/internal/AsyncSubject.ts
src/internal/BehaviorSubject.ts
src/internal/Observable.ts
src/internal/ReplaySubject.ts
src/internal/Subject.ts
src/internal/Subscriber.ts
src/internal/observable/ConnectableObservable.ts
src/internal/observable/SubscribeOnObservable.ts
src/internal/observable/dom/AjaxObservable.ts
src/internal/observable/dom/WebSocketSubject.ts
src/internal/operators/bufferTime.ts
src/internal/operators/bufferWhen.ts
src/internal/operators/delayWhen.ts
src/internal/operators/groupBy.ts
src/internal/operators/repeatWhen.ts
src/internal/operators/retryWhen.ts
src/internal/operators/timeoutWith.ts
src/internal/operators/window.ts
src/internal/operators/windowToggle.ts
src/internal/scheduler/AsyncAction.ts
src/internal/testing/HotObservable.ts

Resolves an issue in Node and TypeScript where if a project had more than one copy of RxJS, even if it was the same version, types would be incompatable between say, Observable and Observable, due to protected fields in the dts files. As all of these fields are really implementation details of the library, and my be removed at any time do to architectural changes, it is prudent to mark them as deprecated. Marking them as public only serves to eliminate the type incompatibilities.

fix(node/TS): eliminate incompatable types to protected properties

---

spec/observables/from-spec.ts
src/internal/util/isArrayLike.ts

Added a `typeof x !== "function"` check to `isArrayLike`. `isArrayLike` was only checking for `length` and functions have a `length` property. This prevented functions from properly falling through to this case:
https://github.com/ReactiveX/rxjs/blob/6fd1fd7719e690d93ba3205db8b6b6e9e0990579/src/internal/util/subscribeTo.ts#L31

fix(isArrayLike): reject functions because functions have "length"

---

spec/operators/throttleTime-spec.ts
src/internal/operators/throttleTime.ts

BREAKING CHANGE: This changes the behavior of throttleTime, in particular when throttling with trailing set to true. Throttling now treats observable complete as a trailing edge in addition to the timer and emits the last throttled value when observable completes before the current timer is up.
closes #3351

fix(throttleTime): emit throttled values when complete if trailing=true

---

README.md

Fixes the link to the Rx.js bundle on the unpkg CDN in the README.

docs(readme): fix link to CDN

---

compat/observable/FromEventObservable.ts
src/internal/observable/fromEvent.ts

Adds interfaces to cover what is used from DOM in `fromEvent` so that types are carried through, but `dom` lib isn not required by default even if you are not using `fromEvent`
fixes: #3558

fix(rxjs): no longer requires `dom` lib

---

src/internal/operators/throttleTime.ts

Adding basic documentation for `config` parameter on throttleTime, copied verbatim from throttle.

docs(throttleTime): document config parameter

---

package-lock.json
spec/observables/dom/webSocket-spec.ts
src/internal/observable/dom/WebSocketSubject.ts

There was an issue where using operators on a WebSocketSubject resulted in errors being thrown
because the source was not set in lift.
This also updates the tests to use pipeable operators.

fix(websocket): no longer throws errors in operators applied to it

---

doc/writing-marble-tests.md

Closes #3581
Fixes an error introduced in a recent commit. The sync group example's `complete` event occurs at frame 80 - not frame 30.
**Related issue (if exists):** #3581

docs(marbles): fix sync group example

---

.make-packages.js
MIGRATION.md
compat/add/observable/dom/webSocket.ts
integration/systemjs/systemjs-compatibility-spec.js
package-lock.json
spec/observables/dom/webSocket-spec.ts
spec/websocket/index-spec.ts
src/BUILD.bazel
src/internal/observable/dom/WebSocketSubject.ts
src/internal/observable/dom/webSocket.ts
src/internal/umd.ts
src/webSocket/BUILD.bazel
src/webSocket/index.ts
src/webSocket/package.json
src/websocket/package.json
tsconfig/compat/tsconfig.base.json
tsconfig/tsconfig.base.json
tsconfig/tsconfig.legacy-reexport.json

BREAKING CHANGE: UNBREAKING websocket to be named `webSocket` again, just like it was in 5.0. Now you should import from `rxjs/webSocket`

refactor(webSocket): rename back to webSocket ala 5.0

---

MIGRATION.md

This PR fixes minor typo in URL pointing to TSLint rule's repository. It also fixes the heading so that it displays nicely on GitHub.

Fix URL and markdown typos in MIGRATION.md

---

spec/observables/fromEvent-spec.ts
src/internal/observable/fromEvent.ts

This PR adds a failing test and moves the check for a `length` property on the event source to last place - after the checks for DOM, JQuery and Node event sources.
It fixes the problem with using `fromEvent` on `window` - which has a `length` property.
**Related issue (if exists):** #3578

 fix(fromEvent): don't enumerate valid sources

---

spec/schedulers/TestScheduler-spec.ts
src/internal/scheduler/AsyncScheduler.ts
src/internal/scheduler/VirtualTimeScheduler.ts
src/internal/testing/TestScheduler.ts

Huge thank you to @benlesh for the countless hours helping me bikeshed testing infra in general and future related proposals, and @kwonoj for his input and work on [rx-sandbox](https://github.com/kwonoj/rx-sandbox) which provided a lot of the inspiration.
***
This PR adds a new `run` method on instances of TestScheduler. It accepts a callback which is then synchronously called with a single argument containing the helpers `hot` (short for `createHotObservable`), `cold` (short for `createColdObservable`), `expectObservable`, `expectSubscription`, and `flush`.
```ts
it('should do stuff', () => {
const testScheduler = new TestScheduler(assertDeepEquals);
testScheduler.run(({ cold, expectObservable }) => {
const output = cold('-a-b-c--------|').pipe(
debounceTime(5)
);
const expected = ' …
```

New testScheduler.run() auto-scheduler injection method and time progression syntax

---

spec/operators/delay-spec.ts
src/internal/operators/delay.ts

Hopefully fix leaking memory for delay operator
EDIT:
I had to bend the VirtualTimeScheduler to not `shift` the last action in order to properly test this. This could be potential breaking change if left as it is. I am not sure how to test the case without the change though. Any help is appreciated.
#3604

fix(delay): fix memory leak

---

src/internal/scheduler/AsyncScheduler.ts
src/internal/util/Immediate.ts

- deprecates properties that should only be internally used
- Updates asapScheduler schedule to always return a value > 1

Asap scheduler id fix

---

package-lock.json
spec/observables/from-spec.ts
spec/util/isObservable-spec.ts
src/index.ts
src/internal-compatibility/index.ts
src/internal/observable/from.ts
src/internal/observable/fromObservable.ts
src/internal/types.ts
src/internal/util/isInteropObservable.ts
src/internal/util/isObservable.ts

There are a lot of ways to check to see of something is an Observable, none of them are great. This is an attempt to provide a recommended way to see of an Observable is, in fact, an RxJS (5+) Observable or not.
- `instanceof` doesn't always work in node, as sometimes people have Observables from other copies of RxJS.
- `typeof o.subscribe === 'function'` doesn't always work, because older versions of RxJS (<4) have different APIs that still use `subscribe`
- I've seen `typeof o === 'object'` sort of checks to see if something is an Observable, which has obvious problems.
- Provide a library-blessed way to identify compatible observables
- Provide a future-proof way to identify observables, as implementation details are likely to change in upcoming versions
the type `ObservableLike<T>` is …

feat(isObservable): adds recommended method for checking objects to see if they're RxJS 5+ Observables

---

src/observable/FromEventObservable.ts

see #3530 
changes made here is exactly the same with #3530 except the file path.

fix: fix a typing mismatch in FromEventObservable

---

spec/operators/bufferTime-spec.ts

update bufferTime spec to use updated import sites and pipeable operators

refactor(bufferTime-spec): update bufferTime operator tests to use pipeable operators

---

spec/operators/count-spec.ts

update count spec to use updated import sites and pipeable operators

refactor(count-spec): update count operator tests to use pipeable operators

---

spec/operators/concat-spec.ts

update concat spec to use updated import sites and pipeable operators

refactor(concat-spec): update concat operator tests to use pipeable operators

---

.travis.yml
appveyor.yml
package-lock.json

build(package): bump npm on ci

---

spec/operators/bufferToggle-spec.ts

update bufferToggle spec to use updated import sites and pipeable operators

refactor(bufferToggle-spec): update bufferToggle operator tests to use pipeable operators

---

spec/operators/bufferWhen-spec.ts

update bufferWhen spec to use updated import sites and pipeable operators

refactor(bufferWhen-spec): update bufferWhen operator tests to use pipeable operators

---

spec/observables/dom/ajax-spec.ts
spec/operators/timeout-spec.ts
src/internal/observable/dom/AjaxObservable.ts
src/internal/util/TimeoutError.ts

Update the `name` property of the `AjaxTimeoutError` to be "AjaxTimeoutError" instead of "AjaxError".
@felixfbecker mentioned the following in the original issue: 
> Why not use instanceof? instanceof breaks when multiple RxJS versions are in play, or even just the same version had to be installed multiple times because deduping wasn't possible. It asserts the implementation, err.name asserts an interface. All browser errors use it (e.g. AbortError).
This still will cause problems if the implementation name changes.  Open to feedback for a more permanent solution.
https://github.com/ReactiveX/rxjs/issues/3602

fix(ajax): RxJS v6 TimeoutError is missing name property

---

README.md

The Google Doc's documentation has moved to MIGRATION.md
The Google Doc's documentation has moved to MIGRATION.md

docs(README): remove google docs URL

---

doc/marble-testing.md

The current link uses capital letters but needs to be lowercase to work correctly.

docs(marble-testing.md): fix #known-issues link

---

spec/operators/endWith-spec.ts
src/internal/operators/endWith.ts
src/operators/index.ts

endWith operator returns an Observable that emits given items last after items emitted by the source
Observable

feat(endWith): add new operator endWith

---

spec/util/isObservable-spec.ts
src/internal/util/isObservable.ts

Fix `isObservable` to test to make sure the test subject is a function or object before attempting to access properties on it.
https://github.com/ReactiveX/rxjs/issues/3687

fix(isObservable): Fix throwing error when testing isObservable(null)

---

spec/observables/dom/ajax-spec.ts
src/internal/observable/dom/AjaxObservable.ts

XHR Timeouts are not being handled properly.
It turns out the XHR timeouts fire the `readystatechange` event (with status=0, readyState=4) and then the `timeout` event.  This is causing `next` to be called before `error`.
Confirmed this behavior in Chrome, added a test for timeouts and fixed the behavior by pointing the main event handler to fire on `load`.  Definitely recommend confirming this behavior and compatibility in other browsers.
Fixed up our `MockXMLHttpRequest` to cause timeouts after the `send` method is called.  
Overall, I want to recommend moving away from this `MockXMLHttpRequest` so that we aren't re-implementing browser functionality in the tests.  I saw that the current browser tests are broken, wanted to take a stab at either fixing those or porting …

fix(ajax): Handle timeouts as errors

---

spec/operators/delay-spec.ts

update delay spec to use updated import sites and pipeable operators

refactor(delay-spec): update delay operator tests to use pipeable operators

---

spec/observables/range-spec.ts
src/internal/observable/range.ts

Range should be same for every subscriber. 
We were mutating the start parameter that was passed in so the second subscriber was starting at the end of the first subscriber.
https://github.com/ReactiveX/rxjs/issues/3706

fix(range): Range should be same for every subscriber

---

MIGRATION.md

spelling fix

---

src/internal/operators/catchError.ts

This PR adds an overload signature to `catchError` so that the correct return type can be inferred for callback functions that always throw - i.e. those that have a return type of `never`.
**Related issue (if exists):** #3395

chore(typings): improve catchError typings

---

spec/util/ArgumentOutOfRangeError-spec.ts
spec/util/EmptyError-spec.ts
spec/util/ObjectUnsubscribedError-spec.ts
spec/util/TimeoutError-spec.ts
src/internal/observable/dom/AjaxObservable.ts
src/internal/util/ArgumentOutOfRangeError.ts
src/internal/util/EmptyError.ts
src/internal/util/ObjectUnsubscribedError.ts
src/internal/util/TimeoutError.ts
src/internal/util/UnsubscriptionError.ts

Add `Error.name` to all custom errors.  Add tests for name and description. 
https://github.com/ReactiveX/rxjs/issues/3602
https://github.com/ReactiveX/rxjs/pull/3656

chore(Error): Make error name part of visible api contract

---

spec/operators/skipUntil-spec.ts
src/internal/operators/skipUntil.ts

**Description:** Fix a minor issue with skipUntil
https://github.com/ReactiveX/rxjs/issues/3685

fix(skipUntil): fix skipUntil when innerSubscription is null

---

spec/operators/dematerialize-spec.ts

update dematerialize spec to use updated import sites and pipeable operators

refactor(dematerialize-spec): update dematerialize operator tests to use pipeable operators

---

spec/observables/dom/webSocket-spec.ts
src/internal/observable/dom/WebSocketSubject.ts

Check to make sure that the `WebSocket` constructor is in the root before using it.  This is currently breaking in Node.
https://github.com/ReactiveX/rxjs/issues/3692

fix(WebSocketSubject): Check if WebSocket exists before using it

---

src/internal/observable/dom/WebSocketSubject.ts

Fix typo in the WebSocketSubject multiplex method documentation on line 118 .  Change `be` to `by`.

Fix docs typo in WebSocketSubject

---

src/internal/Observable.ts

Somewhat confusingly, `Observable` used to import from `./types` once via the
child path, and once via `../internal/types`, which does resolve to the same file.

chore(imports): import only once from `./types`

---

doc/introduction.md

In accordance to how most users of RxJS will use it, this PR changes all examples in `introduction.md` to use ES6 imports. I also snuck in some small spacing and line-breaking tweaks to make the examples a bit more readable, and closer to What Prettier Would Do (especially in regards to the method chaining).

docs(introduction.md): Use ES6 imports and improve readability

---

spec/operators/bufferTime-spec.ts
spec/operators/bufferToggle-spec.ts
spec/operators/bufferWhen-spec.ts
spec/operators/debounce-spec.ts
spec/operators/debounceTime-spec.ts
spec/operators/do-spec.ts
spec/tsconfig.check.json

Continues from PR #3680 and fixes operators tests for operators starting with `a` through to `d`.
**Related issue (if exists):** #3411 #3680

chore(test): fix operator test types a-d

---

spec/schedulers/TestScheduler-spec.ts
src/internal/testing/TestScheduler.ts

This PR adds a failing test and a `finally` block to the `TestScheduler`'s `run` method so that `runMode` changes are restored upon an error being thrown by a test.
Without the `finally` block, the `TestScheduler` is left in `runMode` and that breaks tests that depend upon the previous, deprecated behaviour. This is a problem when converting a suite of tests to use the new behaviour: a failing `runMode` test will cause all subsequent non-`runMode` tests to fail with useless messages, as their marble diagrams will be interpreted incorrectly.
/cc @jayphelps

 fix(TestScheduler): restore run changes upon error

---

spec/operators/delay-spec.ts
src/operators/delay.ts

This PR cherry picks PR #3605 into the `stable` branch. Given that it fixes a memory leak, I think there's something to be said for its application to v5, too.
**Related issue (if exists):** #3604

fix(delay): fix memory leak (in stable)

---

doc/marble-testing.md

replace 'output' with 'expected' in Time Progression Syntax section
#3709

docs(marble-testing): fix typo in marble testing docs

---

spec/operators/every-spec.ts
spec/operators/filter-spec.ts
spec/operators/find-spec.ts
spec/operators/findIndex-spec.ts
spec/operators/first-spec.ts
spec/operators/groupBy-spec.ts
spec/tsconfig.check.json

Continues from PR #3680 and fixes operators tests for operators starting with `e` through to `g`.
**Related issue (if exists):** #3411 #3680

chore(test): fix operator test types e-g

---

spec/operators/distinct-spec.ts

update distinct spec to use updated import sites and pipeable operators

refactor(distinct-spec): update distinct operator tests to use pipeable operators

---

modules/core/internal/operators/tap-spec.ts
modules/core/internal/operators/tap.ts

Commit c59212a9bb98da5ac5f5e587a045bf88b0f387a2 added `tap` in the experimental branch which did not accept partial observers.

fix(tap): accept partial observers

---

spec/helpers/marble-testing.ts
spec/operators/partition-spec.ts
spec/operators/pluck-spec.ts
spec/operators/publishReplay-spec.ts
spec/operators/reduce-spec.ts
spec/operators/repeat-spec.ts
spec/operators/sample-spec.ts
spec/operators/scan-spec.ts
spec/operators/sequenceEqual-spec.ts
spec/operators/shareReplay-spec.ts
spec/operators/single-spec.ts
spec/operators/skipUntil-spec.ts
spec/operators/skipWhile-spec.ts
spec/operators/take-spec.ts
spec/operators/takeLast-spec.ts
spec/operators/takeWhile-spec.ts
spec/operators/throttle-spec.ts
spec/operators/throttleTime-spec.ts
spec/operators/timeout-spec.ts
spec/operators/timeoutWith-spec.ts
spec/operators/windowTime-spec.ts
spec/operators/withLatestFrom-spec.ts
spec/tsconfig.check.json

Continues from PR #3680 and fixes operators tests for operators starting with `p` through to `z`.
**Related issue (if exists):** #3411 #3680

 chore(test): fix operator test types p-z

---

spec/operators/last-spec.ts
spec/operators/map-spec.ts
spec/operators/max-spec.ts
spec/operators/min-spec.ts
spec/operators/observeOn-spec.ts
spec/tsconfig.check.json

Continues from PR #3680 and fixes operators tests for operators starting with `i` through to `o`.
**Related issue (if exists):** #3411 #3680

chore(test): fix operator test types i-o

---

compat/operator/bufferTime.ts
src/internal/operators/bufferTime.ts

The tests for bufferTime verifies that it is possible to set
bufferCreationInterval to null, but the typings did not allow it
when strictNullChecks were set to true.
Fixes #3728

fix(typings): allow bufferCreationInterval null for bufferTime

---

spec/operators/delayWhen-spec.ts
src/internal/operators/delayWhen.ts

This fixes an issue where delayWhen would not re-emit a source emission if the duration selector
completed synchronously.
fixes #3663

fix(delayWhen): Emit source value if duration selector completes synchronously

---

spec/operators/catch-spec.ts
src/internal/Observable.ts

This PR adds a failing test and fixes the problem with the implementation of `subscribe` that sees the `catchError` operator bypassed in some circumstances.
This will fix the behaviour when `useDeprecatedSynchronousErrorHandling` is `false` - i.e. the default version 6 behaviour.
Elsewhere, the `syncErrorThrowable` flag has no meaning unless `useDeprecatedSynchronousErrorHandling` is `true`.
So, when `useDeprecatedSynchronousErrorHandling` is `false`, it makes no sense to consider `syncErrorThrowable` when deciding between a call to `_subscribe` or `_trySubscribe`.
Whether or not - as discussed in the related issue - a getter should be added to `InnerSubscriber` to attempt to fix the deprecated behaviour is another (more complicated) matter. And one that need not be …

fix(subscribe): ignore syncError when deprecated

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support-question.md

This PR utilizes issue template feature from github, categorize templates based on cases. I've limited major category in 3 (bug / feature / support question, documentation is just let redirect) for now, while I was tempting to have one another category around `setup` (i.e loader, browser, framework config can't import rx correctly), not sure how much needed though.
Probably need to discuss to handle support questions separately (i.e still need to followup or either close it similar to other project like electron does), but for now template just suggest to check other places first.

docs(issue): update issue template

---

src/internal/symbol/observable.ts

rxjs symbol declaration creates error when combined with other packages
closes #3697

fix(Symbol.observable): make observable declaration readonly (#3697)

---

.npmignore

Due to the publish.sh the docs-app shouldn't published within the rxjs node module. But to ensure that I think it is a good idea to add the docs-app folder to the .npmignore file.

build(docs): remove docs app from published node modules

---

CONTRIBUTING.md

Based on a conversation with @cartant during my first PR, it turned out that squashing commits containing the requested changes - even though it has the purpose of making the git history clean - makes the github review flow unclear. The original commits appear with annotation of being "outdated", and the PR author is not confident whether the comments they see pertain to the original or updated commits.
My understanding then is that the practice should be to append new commits, thus keeping the history of the feature branch linear and the flow clear. Therefore, I am updating the guidelines in CONTRIBUTING.md with an appropriate info.

docs(contributing): add guideline not to overwrite commit history

---

spec/observables/from-spec.ts
src/internal/observable/from.ts
src/internal/util/subscribeTo.ts

This PR ensures that `Observable.from` uses Observable Symbol interop mechanism before attempting any others. 
Closes #3779

fix(from): Changed the priority of observable detection

---

src/internal/Observable.ts

Added <any, any>[] as tyings for the generic type of operators provided to the pipe, as
OperatorFunctions can transform the type.
The fix is as suggested by @cartant  here: https://github.com/ReactiveX/rxjs/issues/3766#issuecomment-393447462
Travis CI passes for typescript current, but not for next (not related to my change): https://travis-ci.org/akehir/rxjs/builds/388179712
#3766

fix(Observable): Update typings of pipe

---

spec/operators/multicast-spec.ts

Update multicast spec to use updated import sites and pipeable operators.
Ran into a typing issue in this test. Not sure if it would be considered a separate issue (or an issue at all really?) but would appreciate some input. With the following example:
```
const expected = [1, 2, 3, 4];
const connectable = of(1, 2, 3, 4).pipe(multicast((new Subject<number>())));
connectable.subscribe((x) => { expect(x).to.equal(expected.shift()); },
(x) => {
done(new Error('should not be called'));
}, () => {
done();
});
connectable.connect();
```
I get a type error on the last line: `[ts] Property 'connect' does not exist on type 'Observable<number>'`
This looks to be because the `pipe` function return value is typed as `Observable<number>` when in this case we really need it to be …

refactor(multicast-spec): update multicast operator tests to use pipeable operators

---

.github/lock.yml

If you set up lock bot to _only_ lock, it won't make notifications on old threads. It does mean that users won't get told why the issue is locked though, so it's a bit of a tradeoff. For ye old issue reporters and PR makers (like myself), I want to get notifications on relevant threads I'm in rather than knowing about every locked one.

Don't comment on locked issues

---

docs_app/content/code-of-conduct.md
docs_app/content/marketing/index.html
docs_app/content/navigation.json
docs_app/src/styles/1-layouts/_marketing-layout.scss

closes #3791 
adds a page for the code of conduct and a link to get there directly from the start page.
Totally open for any kind of UI suggestions :D
The content of the code of conduct is just copied from the rxjs repo.

docs(CoC): add code of conduct to documentation

---

docs_app/src/app/custom-elements/contributor/contributor.service.spec.ts

docs(contributors): fix typo in the test

---

spec/observables/fromEvent-spec.ts
src/internal/observable/fromEvent.ts

React Native implements a similar interface to Node.js event listeners -- specifically, its Event Emitters have addListener and removeListener methods. These are compatible with the Node interface, but they are not identical to the Node.js *style* since the addListener method returns a subscription rather than the event emitter itself, and the removeListener method returns nothing.
These return values are not actually used by fromEvent, so creating an Observable from an Event Emitter where addListener returns something different and removeListener returns nothing should still work to create a compatible Observable that emits with the corresponding events.
Closes #3809

fix(fromEvent): Support React Native and node-compatible event sources.

---

doc/pipeable-operators.md

I've noticed some people on StackOverflow referring to this document and being surprised why it doesn't work with RxJS 6 (mostly when importing "creation" methods).

docs(pipable-operators.md): update for RxJS 6

---

src/internal/operators/endWith.ts

Add jsdoc examples for `endWith` operator.

docs(jsdoc): add examples for endWith operator

---

spec/observables/dom/ajax-spec.ts
src/observable/dom/AjaxObservable.ts

Switch to encodeURIComponent so characters like & and + are properly encoded. This fix is in RxJS 6
but is not in RxJS 5.
Fixes #3824

fix(AjaxObservable): switch to encodeURIComponent to properly encode body form data

---

docs_app/src/app/custom-elements/resource/resource.service.spec.ts
docs_app/src/app/navigation/navigation.service.spec.ts

docs(test): fix typo in the resource and navigation test

---

src/internal/Scheduler.ts

**Description:** Uses Date.now indirectly in the Scheduler, rather than getting the reference statically. Makes common testing infrastructure work, by making it possible to monkeypatch Date.now.
Just assigning Date.now as the default argument for the `now` constructor param would have the same problem as before. But it would be possible to use `() => Date.now()` there instead, if you don't need to keep backwards compatibility with the Scheduler API.
**Related issue (if exists):** #3847

fix(Scheduler): Wrap Date.now in arrow fn and drop existance check

---

doc/introduction.md

All the operator links in the [overview](https://rxjs-dev.firebaseapp.com/guide/overview) are broken.
For example:
- ❌ [filter (broken)](https://rxjs-dev.firebaseapp.com/class/es6/Observable.js~Observable.html#instance-method-filter)
- ✔️ [filter (fixed)](https://rxjs-dev.firebaseapp.com/api/operators/filter)

Fix operators links in Introduction docs

---

spec/operators/throwIfEmpty-spec.ts
src/internal/operators/throwIfEmpty.ts

I've noticed that the new `throwIfEmpty` operator doesn't have a marble diagram so this PR adds `asDiagram` test and also adds the image into its docblock.
This is what it looks like:

docs(throwIfEmpty): add missing marble diagram

---

src/internal/Observable.ts

I found it hard to read easily some of the documentation, which led me to clean up some of the sentences and the wording. Once this was done I found it easier to read and understand.

style(Observable): Inline Documentation Readability Changes

---

docs_app/package.json
docs_app/scripts/publish-docs.sh
package.json

This script should deploy the docs if the rxjs node module is published.
I am not completly sure if it is working completly because I couldn't test it :D
Mind that you have to enter the credentials for the firebase account each time.

docs(build): deploy docs to firebase on publish

---

docs_app/content/guide/v6/migration.md

I added mentions of `SubscriptionLike` and `PartialObserver` into "Import paths" migration guide: https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md#import-paths
The first bullet point already says:
> 1. rxjs: Creation methods, types, schedulers and utilities
so I only added `SubscriptionLike` and `PartialObserver` because these two are most common util interfaces I think.
#3681

docs(migration): mention util interfaces in migration import paths

---

src/internal/observable/ConnectableObservable.ts
src/internal/observable/combineLatest.ts
src/internal/observable/generate.ts
src/internal/operators/audit.ts
src/internal/operators/dematerialize.ts
src/internal/operators/groupBy.ts

**Description:** standardizes style of examples to use rxjs6-style .pipe() etc.
**Related issue (if exists):** n/a

doc: remove some legacy Rx.* usages in jsdoc

---

doc/introduction.md
docs_app/content/guide/overview.md
docs_app/content/guide/rx-library.md
spec/operators/repeatWhen-spec.ts
spec/operators/retryWhen-spec.ts
src/internal/operators/groupBy.ts

**Description:** replaces legacy uses of the flatMap operator with mergeMap or something else in docs
**Related issue (if exists):** n/a

doc: remove legacy uses of flatMap

---

src/internal/operators/publishLast.ts

Included formal summary, description, example and return values.

docs(publishLast): add publishLast operator docs

---

src/internal/operators/startWith.ts

Improve documentation of startWith operator by adding usage examples and an alternative description
of the behavior

docs(startWith-operator): add examples

---

src/internal/observable/of.ts

add description and examples for the rxjs/of observable creator

docs(of): add of operator docs

---

compat/operator/first.ts
compat/operator/last.ts
spec/operators/first-spec.ts
spec/operators/last-spec.ts
src/internal/operators/first.ts
src/internal/operators/last.ts

Uncomments the tests that were skipped when enabling type checking for the test suite. And adds overload signatures with type guards to `first` and `last`.
Note that because the predicates are optional, additional overload signatures that match calls made with no arguments or with a `null` or `undefined` predicate are required. Otherwise, the `S` type parameter is inferred as `{}` and the type of the output observable becomes `Observable<{}>`.
**Related issue (if exists):** #3717

chore(typings): add type guard overloads for first/last

---

spec/schedulers/TestScheduler-spec.ts
src/internal/testing/TestScheduler.ts

Adds a failing test for the `TestScheduler` and applies the fix from #3898.
**Related issue (if exists):** #3898

 fix(TestScheduler): flush expectations correctly

---

src/internal/observable/merge.ts

remove hanging 'javascript' after ``` which breaks formatting of documentation
Closes #3880
Incorrect closing of multiline JS code block broke formatting within the merge document.

docs (merge documentation): fix closing of code block

---

src/internal/operators/groupBy.ts

As pointed out in #3928, there is a linting problem in `master` that is causing the full-validation CI build to fail. This PR addresses that problem.
**Related issue (if exists):** N/A

chore(lint): remove trailing whitespace

---

src/internal/util/pipe.ts

`@internal` and similar tags are only parsed in JSDoc.

fix: convert @internal comment to JSDoc

---

docs_app/tools/transforms/templates/sitemap.template.xml

Fixed sitemap for docs which pointed to angular.io website.
https://github.com/ReactiveX/rxjs/issues/3888

docs(sitemap): fixed the sitemap for docs

---

src/internal/operators/shareReplay.ts

Added docs and code examples for shareReplay operator.
https://github.com/ReactiveX/rxjs/issues/3819

docs(test): Added docs and examples for shareReplay operator

---

spec/schedulers/TestScheduler-spec.ts
src/internal/testing/TestScheduler.ts

Adds types to the arguments of `TestScheduler` `createHot/ColdObservable` to allow type inference.
Fixes #3921

fix(testscheduler): type arguments to Observable creation functions

---

spec/observables/dom/ajax-spec.ts
src/internal/observable/dom/AjaxObservable.ts

Catch error when parsing json response and notify observer with thrown error.
JSON could be invalid if proxy overtakes the response and in IE responseType is empty.
closes #3138
Please find description under the issue. This is my first PR to rxjs, so any feedback is welcome.
**Related issue (if exists):** #3138

fix(AjaxObservable): notify with error if fails to parse json response

---

spec/operators/mergeAll-spec.ts
src/internal/operators/mergeMap.ts
src/internal/util/subscribeToResult.ts

Add subscriptions for source Observables to mergeAll composite subscription before actually subscribing to any of these Observables, so that if source Observable emits synchronously and consumer of mergeAll unsubscribes at that moment (for example `take` operator), subscription to source is unsubscribed as well and Observable stops emitting.
Closes #2476

fix(mergeAll): add source subscription to composite before actually subscribing

---

src/scheduler/AsyncAction.ts

I ran into a problem when using RxJS 5.5.11 with typescript newer than 2.6.
The type def for `VirtualAction` from `rxjs/scheduler/VirtualTimeScheduler` is not compatible with newer typescript, so I cannot compile my project.
```
ERROR in /home/---/workspace/project/node_modules/rxjs/scheduler/VirtualTimeScheduler.d.ts                               
ERROR in /home/---/workspace/project/node_modules/rxjs/scheduler/VirtualTimeScheduler.d.ts(24,15):                       
TS2416: Property 'work' in type 'VirtualAction<T>' is not assignable to the same property in base type 'AsyncAction<T>'.                           
Type '(this: VirtualAction<T>, state?: T | undefined) => void' is not assignable to type '(this: AsyncAction<T>, state?: T | undefined) => void'.
The 'this' …
```

fix: make TS type def of VirtualAction compatible with TS >= 2.6

---

compat/operator/first.ts
compat/operator/last.ts
spec-dtslint/operators/first-spec.ts
spec-dtslint/operators/last-spec.ts
src/internal/operators/first.ts
src/internal/operators/last.ts

Fixes problems with the implementation and type-guard signatures for the `first` and `last` operators.
**Related issue (if exists):** #3951

 fix(first/last): fix type-guard signatures

---

src/internal/observable/generate.ts
src/internal/operators/concatMap.ts
src/internal/operators/first.ts
src/internal/operators/mergeMap.ts
src/internal/operators/switchMap.ts
src/internal/operators/switchMapTo.ts

**Description:** makes it clearer for readers of the generated docs that resultSelector is deprecated
**Related issue (if exists):** n/a

doc: explicitly note that resultSelector is deprecated

---

src/observable/dom/MiscJSDoc.ts
src/observable/dom/WebSocketSubject.ts

Uff.. This one was really dense. ;)
* Create documentation describing what paramaters webSocket operator accepts and what it returns. * Describe WebSocketSubject API - both how Subject methods behave and what additional multiplex operator does. 
* Add examples for receiving messages, sending messages and multiplexing sockets. 
* Describe properties of WebSocketSubjectConfig object.
**Related**
I had problems justifying some desing decisions. Answering those might help me create better descriptions:
#2445 
#2442

docs(webSocket): create documentation for the operator

---

spec-dtslint/operators/concatAll-spec.ts
spec-dtslint/operators/exhaust-spec.ts
spec-dtslint/operators/mergeAll-spec.ts
spec-dtslint/operators/switchAll-spec.ts

I should have included these dtslint tests in #3945 to show that the change does fix the reported issue. It does.
**Related issue (if exists):** #3841

chore(dtslint): add higher-order observable tests

---

src/internal/observable/dom/AjaxObservable.ts
src/internal/util/ArgumentOutOfRangeError.ts
src/internal/util/EmptyError.ts
src/internal/util/ObjectUnsubscribedError.ts
src/internal/util/TimeoutError.ts
src/internal/util/UnsubscriptionError.ts

This reimplements all Error types as ES5 classes, and types them with TypeScript such that
we no longer need to rely on Object.setPrototypeOf, which was causing issues for users who had not
polyfilled it properly in IE10.
fixes #3966

fix(IE10): Remove dependency on Object.setPrototypeOf

---

spec/operators/concatMap-spec.ts
spec/operators/concatMapTo-spec.ts
spec/operators/delay-spec.ts
spec/operators/delayWhen-spec.ts
spec/operators/exhaustMap-spec.ts
spec/operators/expand-spec.ts
spec/operators/mergeAll-spec.ts
spec/operators/mergeMap-spec.ts
spec/operators/mergeMapTo-spec.ts
spec/operators/mergeScan-spec.ts
spec/operators/observeOn-spec.ts
spec/operators/onErrorResumeNext-spec.ts
spec/operators/sequenceEqual-spec.ts
spec/operators/switchMap-spec.ts
spec/operators/switchMapTo-spec.ts
spec/operators/zipAll-spec.ts
spec/schedulers/TestScheduler-spec.ts
src/internal/Observable.ts
src/internal/Subscriber.ts
src/internal/observable/dom/WebSocketSubject.ts
src/internal/testing/ColdObservable.ts
src/internal/testing/HotObservable.ts

This PR refactors #2457 for v6 and changes a few identifiers so that they are prefixed with underscores.
/cc @jayphelps
<s>I did try to use [git-blame-someone-else](https://github.com/jayphelps/git-blame-someone-else) to credit the PR's author, but the command left the branch in an indeterminate state, so I just aborted the rebase. If someone else wants to have a crack at updating the PR - to credit the author - the author's details are:</s>
`Mateusz Podlasin <Podlas29@gmail.com>`
**UPDATE**: I've edited the commits manually to credit the author.
**Related issue (if exists):** #2457 #2459

Refactor #2457 for v6

---

compat/Observable.ts

**Description:** Use more granular exports in compat/Observable.ts to enable tree shaking optimization even if the consumer is compiling to CommonJS (instead of ES2015) modules.
**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/3971
Importing `Observable` and calling `Observable.create`, with `"module": "commonjs"` vs `"module": "es2015"` in tsconfig.json:
| | `"module": "commonjs"` | `"module": "es2015"` |
|-|-|-|
| rxjs | 79.6 KiB | 14.7 KiB |
| rxjs-compat | 80 KiB | 80.1 KiB
| | `"module": "commonjs"` | `"module": "es2015"` |
|-|-|-|
| rxjs | 79.6 KiB | 14.7 KiB |
| rxjs-compat | 18.6 KiB | 18.7 KiB

fix(Observable): use more granular Observable exports in compat mode

---

docs_app/content/guide/v6/migration.md

With the v5 user-defined operator example, a non-arrow function needs to be used if the `this` context is to refer to the `Observable` instance.

docs(migration): use function for this context

---

spec-dtslint/operators/find-spec.ts
src/internal/operators/find.ts

Fixes the return types for the `find` operator to indicate that `undefined` is a value that could be emitted.
Removes unnecessary overload signatures and adds dtslint tests.
**Related issue (if exists):** #3969

fix(find): add undefined to return type

---

src/internal/observable/throwError.ts

throwError documentation is referenced as throw

docs(throwError): Fixed typo

---

compat/operator/find.ts

I forgot to update the compat signatures in #3970.
**Related issue (if exists):** #3969

chore(find): fix compat signatures

---

spec/operators/find-spec.ts
spec/operators/findIndex-spec.ts
spec/operators/first-spec.ts
src/internal/operators/find.ts

Fixes #3934 and adds unsubscribe-when-matched tests for `find`, `findIndex` and `first`.
**Related issue (if exists):** #3934

fix(find): unsubscribe from source when found

---

spec/Observable-spec.ts
src/internal/Observable.ts
src/internal/util/ObjectUnsubscribedError.ts
src/internal/util/isSubscription.ts

- Adds cancellation semantic to `forEach`, by allowing a `Subscription` to be passed as a sort of cancellation token.
- Adds documentation
- Fixes some bad tests
- **Deprecation** deprecates passing PromiseCtor to `forEach`. (That can be configured globally, and I'd like to remove it for v7)
You can read the docs in the PR for this, but basically:
If you call `forEach` with a second argument that is a `Subscription`, that subscription will act as a cancellation token, such that if you `unsubscribe` from it, the forEach's returned promise will reject with an `Error` with the message `Observable forEach unsubscribed`. This is done, so there's a way to gracefully handle cancellations in async-await code, and I think provides a better alternative to `takeUntil` in those use cases.

Cancellable forEach

---

docs_app/tools/transforms/angular-api-package/index.js
src/internal/observable/dom/ajax.ts

- Added ajax docs back to the list
- Added webSocket docs back to the list
https://github.com/ReactiveX/rxjs/issues/3961
https://github.com/ReactiveX/rxjs/issues/3962

docs(ajax): added ajax and webSocket docs back to the list

---

README.md

**Description:** fix typo in Versions In This Repository section: from "This all of the current" to "This *is* all of the current"

docs(readme): fix small typo to add missing "is" in Versions section

---

spec/Observable-spec.ts
src/internal/Observable.ts
src/internal/util/ObjectUnsubscribedError.ts
src/internal/util/isSubscription.ts

Reverts ReactiveX/rxjs#3977
Currently, there's an issue with what is in there if you unsubscribe from a synchronous observable, synchronously, but after the observable completes:
```ts
const subs = new Subscription();
of('test').forEach(x => console.log(x), subs)
.then(() => console.log('this should not be called'));
subs.unsubscribe();
// Logs
// "test"
// "this should not be called"
```
Solutions around this aren't too bad, but it adds a lot of bloat, mostly due to the fact we're accepting PromiseConstructorLike as an argument, and we're beholden to use it.
I want to revert this new feature until:
1. We deprecate and remove all Promise Constructor configuration (This is legacy, and users should use a proper polyfill)
2. We deprecate and update the behavior of `forEach` to call it's …

Revert "Cancellable forEach"

---

compat/operator/distinctUntilKeyChanged.ts
spec-dtslint/operators/distinctUntilKeyChanged-spec.ts
spec/operators/distinctUntilKeyChanged-spec.ts
src/internal/operators/distinctUntilKeyChanged.ts

With better typing constraint on `T[key]` looks up from **TypeScript**.

chore(distinctUntilKeyChanged): nail down key's typing with keyof T

---

spec-dtslint/tslint.json

Disables the [`no-unnecessary-generics`](https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md) TSLint rule that's applied to the dtslint tests. There are tests that deliberately involve generics that the rule thinks are unnecessary (in a `.d.ts` file context), but that's not the case.

chore(dtslint): disable no-unnecessary-generics

---

.travis.yml
package-lock.json
package.json

Since we're doing CI against `typescript@latest` and `@next` anyhow, building against 2.8 locally doesn't make any sense.

chore(TS): moves to use TypeScript@latest

---

src/internal/Rx.ts

Found that the Symbol properties were out of order and some minor sentence structure for readability.

docs(rxjs): Order JSDocs for Scheduler and Improve Readability

---

src/internal/observable/fromEventPattern.ts

There were some backticks missing for correct markdown and therefore the log printed out a huge amount of warnings building the docs. But this merge request fix one of these warnings:D

docs(fromEventPattern): add missing backticks

---

docs_app/content/guide/v6/migration.md

Fix for `#drop-compat` anchor in MIGRATION.md docs

docs(MIGRATION): fix `#drop-compat` anchor

---

src/internal/operators/groupBy.ts

Modifications that update the docs for `groupBy`  from the older docs to the newer.
related issue: https://github.com/ReactiveX/rxjs/issues/4029

docs(groupBy): Update to groupBy docs

---

src/internal/observable/forkJoin.ts

This is a follow up on 4005 that only fixes the typo and not touching the imports
Relates to the PR https://github.com/ReactiveX/rxjs/pull/4005

docs(forkJoin): Fix typo of jorkJoin

---

src/internal/operators/combineAll.ts

Modifications that update the docs for `combineAll` from the older docs to the newer.
related issue: https://github.com/ReactiveX/rxjs/issues/4026

docs(combineAll): Update docs for combineAll

---

src/internal/observable/from.ts

Update the new docs for `from` with the older docs and add live StackBlitz example.

docs(from): Convert docs for from

---

src/internal/observable/throwError.ts

This fixes issues with the markdown used for the code examples in the JSDocs. It also shows the results from the console for each of the examples.
#4044

docs(throwError): Fix markdown code examples

---

src/internal/observable/interval.ts

Updating the example to add import(s) into the example as is being done in other docs, as well as a cleaner usage.

docs(interval): more practical example

---

src/internal/operators/take.ts

The example has been cleaned up a bit along with having the look of the code example that is starting to be used around the docs.

docs(take): clean up example code

---

compat/operator/startWith.ts
spec-dtslint/operators/startWith-spec.ts
spec/operators/startWith-spec.ts
src/internal/operators/startWith.ts

This PR adds an overload to `startWith` that only takes a scheduler.
Closes #3947

fix(startWith): add empty signature

---

README.md

Link to cdn was not working for version 5. The fix was taken from the reactivex docs http://reactivex.io/rxjs/manual/installation.html#cdn

(docs cdn): Fix link to cdn for version 5.x

---

spec/operators/catch-spec.ts
spec/operators/exhaustMap-spec.ts
spec/operators/mergeScan-spec.ts
spec/operators/onErrorResumeNext-spec.ts
spec/operators/skipUntil-spec.ts
spec/operators/switchMap-spec.ts
src/internal/operators/catchError.ts
src/internal/operators/exhaustMap.ts
src/internal/operators/mergeScan.ts
src/internal/operators/onErrorResumeNext.ts
src/internal/operators/skipUntil.ts
src/internal/operators/switchMap.ts

This PR fixes teardown issues that arised when unsubscribing from an observable emitting values from inner-observable(s) synchronously after subscription, like reported in #4025. An even simpler example is available [here](https://stackblitz.com/edit/typescript-ecmb6g?file=index.ts&devtoolsheight=50).
Basically, the problem is that even after the unsubscription, the inner-observable(s) will continue to run until an asynchronous step is reached.
This was simply because most ``OuterSubscriber``s first call ``subscribeToResult`` on an inner-Observable and THEN call ``this.add`` on the returned Subscription. This sounds fair, but when we're dealing with an unsubscription happening synchronously after the subscription, ``this.add`` will not have been called yet, and so the teardown will happen …

Fix teardown issues with synchronous inner-observables

---

README.md

It seems to me that the instructions for contributing to the docs are misleading. The docs repo is no longer being used.

chore(README): Update documentation instructions

---

spec/operators/takeUntil-spec.ts
src/internal/operators/takeUntil.ts

This bug was introduced in #3504, which intended to not subscribe to the source if the notifier synchronously emits a value, but instead it only skipped subscribe if it completed
https://stackblitz.com/edit/js-j72dzx?file=index.js
```js
import { of, empty } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
// does not log anything, but it should
of(1, 2, 3).pipe(
takeUntil(empty())
).subscribe(d => console.log(d));
```
***
Like most bugfixes this could potentially be a breaking change if someone is knowingly or unknowingly relying on this fact. Dunno what the current policy is on breaking bug fixes.

fix(takeUntil): takeUntil should subscribe to the source if notifier synchronously completes without emitting

---

spec/operators/zipAll-spec.ts
src/internal/types.ts

The signature of `Subscribable.subscribe()` did not match that of `Observable.subscribe()`, which made the two types not compatible if `T=never` (see linked issue).
It also was wrong, because it allowed passing both an Observer and functions at the same time. 
This makes it match the signature of `Observable.subscribe()` exactly, which solves the type error in the issue.
It is not breaking (unless you passed both observer and functions, which is extremely unlikely and did not work at runtime anyway as `SafeSubscriber` checks if the first argument is a function and if yes, discards the other arguments, so this would only highlight a bug).
The alternative discussed in the issue was removing the 3-arg overload, but the discussion in the spec does not seem resolved yet, it is …

fix(subscribable): make subscribe() signature match Observable

---

docs_app/src/styles/1-layouts/_api-page.scss

The short description now has more of a visual separation that allows it to be identified quicker when scanning the page and wanting to find out as quickly as possible the description for the given API.
---
**Screenshot**

docs(UI): Add Larger Callout to the Short Description

---

src/internal/observable/dom/webSocket.ts

* Remove the use of you/we/us, rather going with a generic tone. 
* Found run on sentences
Working on improving the readability of the docs

docs(websocket): grammatical and sentence structure modifications

---

src/internal/observable/bindCallback.ts

Getting in the habit of looking at any documentation that can be cleaned up while reviewing the code.

docs(bindCallback): regularly scheduled maintenance checkup

---

docs_app/content/guide/installation.md
docs_app/content/guide/v6/migration.md

**Description:** Update sample in Installation section to use Rxjs 6+ convention.
**Related issue (if exists):** #3827

docs(installation): update imports to use rxjs 6+ convention (#3827)

---

compat/package.json

Per request of #3926 , adding the Apache license to the rxjs-compat package.json.
#3926

feat(compat): License added to rxjs-compat package

---

README.md
package.json
spec/migration/update-6_0_0/index-spec.ts

There is a npm script that can run - `npm run test_no_cache`, that will
run the test with `TS_NODE_CACHE` set to false.
#3948

feat(test): Add npm script to test with ts-node not caching

---

spec-dtslint/operators/switchMap-spec.ts

I'm on a quest to learn the insides of RxJS and its operators. 
While doing so I could add these kind of dtslint tests as I go, at least if this is OK for you 😄 .

test(dtslint): add switchMap

---

package-lock.json
spec/operators/mergeMap-spec.ts
src/internal/Subscriber.ts

This PR should fix the nested `concatMap`/`mergeMap` regression. The problem seems to have been related to a subscriber being added to itself as a parent.
**Related issue (if exists):** #4071

fix(mergeMap): fix nested mergeMaps

---

docs_app/src/app/app.component.html
docs_app/src/styles/1-layouts/_top-menu.scss

Adding GitHub Logo that allows a person to jump to the project on GitHub.
#3893 #3180

docs(UI): Add GitHub Logo to Docs

---

spec/Subscriber-spec.ts
src/internal/Subscriber.ts

- updates `isTrustedSubscriber` to check for `_addParentTeardownLogic`
resolves #4077

fix(node): will no longer error mixing RxJS 6.3 and 6.2

---

spec/Observable-spec.ts
spec/observables/from-spec.ts
wallaby.js

This PR corrects wallaby configuration with updated path mappings.

test(wallaby): setup wallaby configuration

---

spec-dtslint/operators/concatMap-spec.ts

This PR adds dtslint tests for `concatMap`.

test(dtslint): add concatMap

---

spec-dtslint/operators/takeWhile-spec.ts
spec/operators/takeWhile-spec.ts
src/internal/operators/takeWhile.ts

This pull request overloads the takeWhile operator with an additional signature to accept a type guard.
I tried to keep the code as similar as possible to the corresponding overload signature of the filter operator. Please let me know, if I should change something.
I wasn't sure if the JSDoc should be changed as well. The return type of the filter operator is just `Observable` (without a generic) whereas the one of the takeWhile operator is `Observable<T>`.
This PR fixes #4081.

Overload take while to accept a type guard

---

.make-compat-package.js

Previously the bundles were left behind in `dist-compat` but never copied into `dist-compat/package` prior to publish. This ensures the bundles are part of the compat release.
#4075

chore(build): Copy compat bundle output into package

---

index.html

The link in the body of the index file is now using the correct URL to redirect to the firebase docs.

fix(docs): Correct URL to Firebase Docs

---

docs_app/src/assets/js/devtools-welcome.js
docs_app/src/index.html

This brings back the custom ASCII art and sample code into the console of the dev tools as used in the older docs. I think it is pretty neat as a way to get a quick sample running.

docs(UI): Add DevTools RxJS Welcome Back

---

doc/README.md
docs_app/README.md

I hope that this pr makes the different usages of the `docs` and the `docs_app` folder clearer

docs(readme): improve the readme to point to the new docs

---

spec-dtslint/operators/switchMapTo-spec.ts

This PR adds dtslint tests for `switchMapTo`.

test(dtslint): add switchMapTo

---

spec/operators/shareReplay-spec.ts
spec/subjects/ReplaySubject-spec.ts
src/internal/operators/shareReplay.ts

shareReplay() uses a wrong default value for `windowTime` parameter since #3872. To disable the time function of the internal ReplaySubject the `windowTime` must be `Number.POSITIVE_INFINITY` and not `Number.MAX_VALUE`.
This makes shareReplay() faster because the ReplaySubject will not call `scheduler.now()`, when it is not needed.
This PR also adds a test, whichs checks if the ReplaySubject is in `_infiniteTimeWindow` mode, when no `windowTime` is given to shareReplay().
This will need merging with #4059 whatever comes first.

perf(shareReplay): use correct default paramter

---

spec-dtslint/operators/mergeMapTo-spec.ts

This PR adds dtslint tests for `mergeMapTo`.

test(dtslint): add mergeMapTo

---

spec-dtslint/operators/filter-spec.ts

This PR adds dtslint tests for `filter`.

test(dtslint): add filter

---

spec-dtslint/operators/exhaustMap-spec.ts

This PR adds dtslint tests for `exhaustMap`.

test(dtslint): add exhaustMap

---

spec-dtslint/operators/takeLast-spec.ts

This PR adds dtslint tests for `takeLast`.

test(dtslint): add takeLast

---

src/internal/AsyncSubject.ts
src/internal/BehaviorSubject.ts
src/internal/ReplaySubject.ts
src/internal/Subject.ts

This is at least partially #3553.
**Description:** This includes some basic descriptions about the various `Subject` classes. The documentation was acquired from doc/subject.md and contextually rewritten.
**Related issue (if exists):** #3553

docs(Subject): Clarity for Subject Implementations

---

src/internal/observable/combineLatest.ts

Minor typo fixes for docs of combineLatest

docs(combineLatest) Typo in combineLatest description

---

spec-dtslint/operators/retryWhen-spec.ts

This PR adds dtslint tests for `retryWhen`.

test(dtslint): add retryWhen

---

spec-dtslint/operators/count-spec.ts

**Description:** Add count dtslint test

test(dtslint): add dtslint test on count operator (#4093)

---

spec-dtslint/operators/distinctUntilChanged-spec.ts

This PR adds dtslint tests for `distinctUntilChanged`.

test(dtslint): add distinctUntilChanged

---

spec-dtslint/operators/distinct-spec.ts

This PR adds dtslint tests for `distinct`.

test(dtslint): add distinct

---

spec-dtslint/operators/findIndex-spec.ts

This PR adds dtslint tests for `findIndex`.

test(dtslint): add findIndex

---

spec-dtslint/operators/skipLast-spec.ts

This PR adds dtslint tests for `skipLast`.

test(dtslint): add skipLast

---

spec-dtslint/operators/skipUntil-spec.ts

This PR adds dtslint tests for `skipUntil`.

test(dtslint): add skipUntil

---

spec-dtslint/operators/skipWhile-spec.ts

This PR adds dtslint tests for `skipWhile`.
While doing this I noticed some inconsistency with the `predicate` parameter in comparison to other operators. For example some of them also have a `source` as 3rd parameter, and have `thisArg` parameter. Or the `filter` operator also has a type guard. I don't know if this is intended, just wanted to point this out 😄 

test(dtslint): add skipWhile

---

spec/Subscriber-spec.ts
spec/operators/mergeMap-spec.ts
spec/operators/observeOn-spec.ts
spec/operators/switch-spec.ts
src/internal/Observable.ts
src/internal/Subscriber.ts
src/internal/Subscription.ts
src/internal/observable/zip.ts
src/internal/operators/delay.ts
src/internal/operators/delayWhen.ts
src/internal/operators/exhaustMap.ts
src/internal/operators/expand.ts
src/internal/operators/mergeMap.ts
src/internal/operators/mergeScan.ts
src/internal/operators/observeOn.ts
src/internal/operators/onErrorResumeNext.ts
src/internal/operators/sequenceEqual.ts
src/internal/operators/switchMap.ts

This PR fixes a problem that was introduced in #3963 and was partially fixed in #4072.
The problem was introduced with this change - to `Subscriber` - in #3963 where a parent subscription is unsubscribed upon a `complete` notification:
```diff
complete(): void {
if (!this.isStopped) {
this.isStopped = true;
this._complete();
+   this._unsubscribeParentSubscription();
}
}
```
The parent subscription is added to the subscriber in `Observable.subscribe`:
```ts
const sink = toSubscriber(observerOrNext, error, complete);
if (operator) {
operator.call(sink, this.source);
} else {
sink._addParentTeardownLogic(
this.source || (config.useDeprecatedSynchronousErrorHandling && !sink.syncErrorThrowable) ?
this._subscribe(sink) :
this._trySubscribe(sink)
);
}
```
In numerous …

fix(subscriber): don't unsubscribe self

---

docs_app/content/marketing/index.html
docs_app/src/app/app.component.html
docs_app/src/app/custom-elements/api/api-list.component.html
docs_app/src/app/custom-elements/contributor/contributor.component.ts
docs_app/src/index.html
docs_app/src/styles/2-modules/_code.scss
docs_app/src/styles/2-modules/_notification.scss
docs_app/src/styles/_constants.scss

I reviewed the accessibility of the new website with aXe and pa11y.
These changes addresses some of the flaws.
I also change the notification style because it had the Angular styles applied (and also triggered the accessibility color contrast warning).
**Related issue (if exists):** /

docs(accessibility): minor tweaks to improve accessibility

---

spec-dtslint/operators/audit-spec.ts

This PR adds dtslint tests for `audit`.

test(dtslint): add audit

---

spec-dtslint/operators/auditTime-spec.ts

This PR adds dtslint tests for `auditTime`.

test(dtslint): add auditTime

---

spec-dtslint/operators/bufferCount-spec.ts

This PR adds dtslint tests for `bufferCount`.

test(dtslint): add bufferCount

---

spec-dtslint/operators/bufferTime-spec.ts

This PR adds dtslint tests for `bufferTime`.

test(dtslint): add bufferTime

---

spec-dtslint/operators/bufferWhen-spec.ts

This PR adds dtslint tests for `bufferWhen`.

test(dtslint): add bufferWhen

---

spec-dtslint/operators/combineAll-spec.ts

This PR adds dtslint tests for `combineAll`.

test(dtslint): add combineAll

---

spec-dtslint/operators/delayWhen-spec.ts

This PR adds dtslint tests for `delayWhen`.

test(dtslint): add delayWhen

---

spec-dtslint/operators/bufferToggle-spec.ts

This PR adds dtslint tests for `bufferToggle`.

test(dtslint): add bufferToggle

---

src/internal/observable/pairs.ts

docs(index): fix typos in Pairs example

---

spec-dtslint/operators/throttle-spec.ts

This PR adds dtslint tests for `throttle`.

test(dtslint): add throttle

---

spec-dtslint/operators/throttleTime-spec.ts

This PR adds dtslint tests for `thottleTime`.

test(dtslint): add throttleTime

---

docs_app/src/styles/2-modules/_api-pages.scss
package.json
spec/helpers/tests2png/diagram-test-runner.ts
src/internal/operators/buffer.ts

@JWO719 @benlesh - Not sure if this is completely correct, but it does output the diagrams as you will see with the buffer.ts test if you were to run `npm run tests2png`

docs(marbles): Fix for Marble Diagrams

---

docs_app/content/marketing/index.html

Description: 
* Updated the link `Getting Started` to point to the "Introduction" content.
* The link to API documentation aka "/api" already exists in the header under `Reference`
**Related issue (if exists):** #4148

docs(content): updated 'Getting Started' CTA link (#4148)

---

spec-dtslint/operators/endWith-spec.ts
src/internal/operators/endWith.ts

**Description:** add ability for endWith operator to end the Observable with different types.
**Related issue (if exists):** #4183

fix(endWith): ability to endWith different types (#4183)

---

spec-dtslint/util/pipe-spec.ts

Generic functions are never returned, as doing so is unsafe. In this PR, the test descriptions have been changed to better reflect what's tested.
**Related issue (if exists):** #4182, #4187

chore(dtslint): refine test descriptions

---

src/internal/Observable.ts
src/internal/operators/tap.ts
src/internal/types.ts

Per discussion on #4159, this deprecates the signatures for `.subscribe` and `.tap` that are `(null, null, complete)`, `(null, error, complete)`, and `(next, null, complete)`.
#4159

fix(subscribe): Deprecate null starting parameter signatures for subscribe

---

docs_app/README.md
docs_app/package.json

In angular.io (where the README was originally taken from), we use `yarn`, so the commands need minor modification when translating to `npm`.
(This is a follow-up to #4201.)

docs(docs_app): fix commands in `README.md`

---

src/internal/operators/onErrorResumeNext.ts
src/internal/operators/throttle.ts
src/internal/util/subscribeTo.ts

This allows rxjs to be compiled under a new tsetse check:
http://tsetse.info/ban-promise-as-condition

Explicitly cast thenable to boolean in conditional expression

---

docs_app/src/styles/2-modules/_api-pages.scss

This adds separation between the label and the first label as seen in the screenshot below.
closes #4200

docs(UI): Add Separation Between API Header and Labels

---

src/internal/operators/pluck.ts

**Description:** fix type inference for pluck operator
#4131

chore(typings): fix pluck operator inference (#4131)

---

docs_app/tools/transforms/templates/api/export-base.template.html

The See Also section is too high in the docs and is seen as having more
importance than anything below. See Also is more of an extension to the
current doc in being able to find more information or related
information.

docs(UI): Move See Also Section Down

---

src/internal/Subscription.ts

Make clear that add() can be used to add child subscriptions.
While learning how to use subscriptions, I found out that you can add child subscriptions to a parent subscription. 
Description in [this](https://blog.angularindepth.com/rxjs-composing-subscriptions-b53ab22f1fd5) great post: 
> The add method can be used to add a child subscription — or a tear-down function — to a parent subscription. When a parent subscription is unsubscribed, any child subscriptions that were added to it are also unsubscribed.
The official doc for `add()` does not mention this powerful feature.

docs(Subscription): add description for child subscription

---

doc/scheduler.md

The doc is mentioning `Rx.Scheduler.async` while everywhere else we always use `asyncScheduler`.

docs(scheduler): Fix inconsistency with the naming

---

docs_app/content/guide/overview.md

Fixes a broken internal link in the guide/overview page.
#4247

docs(overview): fix broken internal link (#4247)

---

docs_app/src/app/custom-elements/api/api-list.component.spec.ts

Small typo fix in api-list.component.spec.ts.

chore(typings): fix typo in api-list.component.spec.ts

---

src/internal/observable/throwError.ts

the demo shows that when 2 is emitted, an error throws, but description says 13. Maybe it's an previous version -.-

docs(throwError): mistake on description for demo

---

doc/observable.md

This is just a quick update to the existing observable documentation to make it more accurate. I plan on rewriting a good portion of this in the near future, not because it's wrong, but just to refresh the material.
:+1:

docs(observable): update observable docs real quick

---

spec-dtslint/operators/catchError-spec.ts

Description:
This PR adds dtslint tests for `catchError`.

test(dtslint): add catchError

---

spec-dtslint/operators/isEmpty-spec.ts

Description:
This PR adds dtslint tests for `isEmpty`.

test(dtslint): add isEmpty

---

spec-dtslint/operators/ignoreElements-spec.ts

Description:
This PR adds dtslint tests for `ignoreElements`.

test(dtslint): add ignoreElements

---

spec-dtslint/operators/mergeScan-spec.ts

Description:
This PR adds dtslint tests for `mergeScan`.

test(dtslint): add mergeScan

---

docs_app/content/marketing/index.html
docs_app/src/styles/1-layouts/_marketing-layout.scss

**Description: This adds a "API Docs" CTA link to the main page of the marketing site. This addresses the most recent comment made by @JWO719 in #4148**
**Related issue (if exists): #4148**

docs(content): add 'API DOCS' CTA link to main page (#4148)

---

spec-dtslint/operators/observeOn-spec.ts

Description:
This PR adds dtslint tests for `observeOn`.

test(dtslint): add observeOn

---

spec-dtslint/operators/min-spec.ts

Description:
This PR adds dtslint tests for `min`.

test(dtslint): add min

---

spec-dtslint/operators/pluck-spec.ts

This PR fixes a problem with the `dtslint` test for `pluck` in PR 4215 - which is currently breaking the build in Travis.
The problem seems to have been some sort of non-visible character hidden amongst the whitespace.
**Related issue (if exists):** #4215

test(pluck): fix problem with dtslint pluck test

---

spec-dtslint/operators/pairwise-spec.ts

Description:
This PR adds dtslint tests for `pairwise`.

test(dtslint): add pairwise

---

spec-dtslint/operators/concat-spec.ts

Description:
This PR adds dtslint tests for `concat`.

test(dtslint): add concat

---

spec-dtslint/operators/groupBy-spec.ts

Description:
This PR adds dtslint tests for `groupBy`.

test(dtslint): add groupBy

---

package-lock.json
package.json
tools/make-closure-compat.js
tools/make-closure-core.js
tools/make-closure.js
tools/make-umd-bundle.js
tools/make-umd-compat-bundle.js
tools/rollup-bundle.js

This PR adds AMD ids in UMD bundles, sourceMapUrl in UMD bundle, and remove Bazel files
//cc @alexeagle & @gregmagolan 
Ps: I can split this into multiple PR, if you'd like.

Build bazel umds

---

spec-dtslint/operators/throwIfEmpty-spec.ts

Description:
This PR adds dtslint tests for `throwIfEmpty`.

test(dtslint): add throwIfEmpty

---

spec-dtslint/operators/subscribeOn-spec.ts

Description:
This PR adds dtslint tests for `subscribeOn`.

test(dtslint): add subscribeOn

---

spec-dtslint/operators/timeInterval-spec.ts

Description:
This PR adds dtslint tests for `timeInterval`.

test(dtslint): add timeInterval

---

spec-dtslint/operators/timestamp-spec.ts

Description:
This PR adds dtslint tests for `timestamp`.

test(dtslint): add timestamp

---

spec-dtslint/operators/partition-spec.ts

Description:
This PR adds dtslint tests for `partition`.
The typings when using a pipeable operator were giving errors.
I resorted back to how the other specs are written for the `partition` operator at https://github.com/ReactiveX/rxjs/blob/master/spec/operators/partition-spec.ts.
I think if we want to support a pipeable `partition` operator, we would have to create "a lot" of extra `pipe` typings.

test(dtslint): add partition

---

spec-dtslint/operators/windowTime-spec.ts

Description:
This PR adds dtslint tests for `windowTime`.

test(dtslint): add windowTime

---

src/internal/Subscriber.ts

This PR removes a property (from `Subscriber`) that was added in https://github.com/ReactiveX/rxjs/pull/3963, but is no longer needed - since the changes made in the referenced PR were reverted and replaced with an alternate implementation.

chore(subscriber): remove _parentSubsciption

---

docs_app/content/guide/testing/internal-marble-tests.md
docs_app/content/guide/testing/marble-testing.md
docs_app/content/navigation.json
docs_app/src/styles/2-modules/_alert.scss

I have migrated the marble testing docs from the "old" docs.
I have also added the internal testing document but not linked it obviously. So we could use it for pointing in prs or similar

docs(content): add testing guide

---

src/internal/observable/dom/WebSocketSubject.ts
src/internal/observable/generate.ts
src/internal/util/TimeoutError.ts

There were some minor compilation errors in the doc.
2 ambigiouse links and one invalid (old docs related) annotation

docs(compile): fix ambigiouse links in doc compile

---

package.json

When `lint-staged` runs on `precommit` and lints the staged files, it should ignore any staged files that are in the `spec-dtslint` directory, as the `tslint.json` in that directory extends `dtslint/dtslint.json` and `dtslint` is not installed in `node_modules` - it's run using `npx` - so the `extends` will effect an error.
The configuration for `lint-staged` accepts an `ignore` option that takes an array of globs. It's documented [here](https://github.com/okonet/lint-staged#advanced-config-format).

chore(lint): ignore spec-dtslint in lint-staged

---

doc/external-references.md

**Description:** Updates the link of Egghead into [this new one](https://egghead.io/courses/for/rxjs)
**Related issue (if exists):** This PR fixes #3616

docs(external-references): Update Egghead link (#3616)

---

src/internal/Observable.ts
src/internal/Subject.ts

**Description:** deprecate all the create method, use `new` instead
**Related issue (if exists):** #3982

chore(Observable): deprecate create method (#3982)

---

src/internal/operators/derived/exhaust-spec.ts
src/internal/operators/derived/sampleTime-spec.ts
src/internal/operators/derived/sampleTime.ts
src/operators.ts

Adds `sampleTime` to the `experimental` branch.

chore(sampleTime): implement sampleTime

---

compat/umd.ts

At the moment operators are exported twice for UMDs.
https://github.com/ReactiveX/rxjs/blob/master/src/internal/Rx.ts#L181-L183
and
https://github.com/ReactiveX/rxjs/blob/master/src/internal/umd.ts#L9-L10
Follow up of https://github.com/ReactiveX/rxjs/pull/4309

fix(bundle): don't export `operators` twice

---

src/internal/observable/zip.ts

Simple documentation fix for `zip`
`If the latest parameter is a function, ...`
should be changed to
`If the last parameter is a function, ...`
Parameters are ordinal, not temporal. So "last" makes more sense than "latest".

docs(index): fix typo

---

src/internal/util/tryCatch.ts

clear tryCatchTarget to release reference of function for gc

---

spec-dtslint/operators/multicast-spec.ts
spec/operators/retry-spec.ts
src/internal/operators/multicast.ts

This PR adds the missing `multicast` signatures mentioned in #4451. And removes an unnecessary signature that allowed the type of the returned observable to be specified explicitly in situations in which the returned observable's type would always be that of the source observable.
It's arguable that the added signatures are for situations that are not best-suited to using a subject rather than a factory, but that's not something that should be enforced by the type system, as the implementation allows it.
**Related issue (if exists):** #4451

chore(typings): add missing multicast signatures

---

src/internal/operators/window.ts

docs(operators):correct example

---

src/internal/operators/takeUntil.ts

in example the const interval(1000); will result in error. so rename interval to i

docs(operators): variable interval rename to i

---

spec-dtslint/observables/race-spec.ts
src/internal/observable/race.ts
src/internal/operators/race.ts

The types returned by race were incorrect. This ought to resolve that.

fix(typescript): Update typings for race to support proper return types

---

spec-dtslint/observables/combineLatest-spec.ts
spec-dtslint/observables/from-spec.ts
src/internal/observable/combineLatest.ts

Existing typings did a poor job of getting proper types from code that passed an array of observables or observable inputs to combineLatest. This issue was caught while trying master in google3. This resolves that issue.

fix(combineLatest): improve typings for combineLatest

---

src/internal/operators/single.ts

docs(operators): emiited to emitted

---

src/internal/operators/sequenceEqual.ts

replace comparor with comparer
mistake spell comparer to comparor

comparor ->comparer

---

spec/util/isPromise-spec.ts
src/internal/util/isPromise.ts

isPromise returns a boolean like isObservable instead of a "falsy" value. isPromise is available for more than internal use since Observable has toPromise. Add tests to validate isPromise.
isObservable was exposed from the internal util methods in [6.1.0](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#610-2018-05-03) and had the null/undefined errors fixed in [6.2.0](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#610-2018-05-03). Exposing isPromise from the internal util methods and updating it to also return a boolean instead of a "truthy" / "falsy" seems consistent.
Related to #4424

feat(isPromise): change isPromise to return bool, add tests

---

spec/observables/dom/ajax-spec.ts
src/internal/observable/dom/AjaxObservable.ts

In RFC 7230 and RFC 7540 is written, that HTTP headers is case-insensitive, so this is fix for correct serializing request body based on HTTP headers.

fix(ajax): Fix case-insensitive headers in HTTP request

---

docs_app/tools/decision-tree-generator/package-lock.json
docs_app/tools/decision-tree-generator/package.json

Dependency bump to remove event-stream / flatmap vulnerability 
Fixes #4500

chore(docs): bump tools nodemon dep to remove flatmap vulnerability

---

src/internal/Subscription.ts

In `Subscription#add()` use `instanceof` to test whether `subscription`
must be wrapped in a `Subscription` (aka for presence of `_addParent`
method), instead of `typeof subscription._addParent === 'function'`,
as the latter is going to turn into a *megamorphic property access*
in any realistic application and cause quite a bit of contention on
the megamorphic stub cache in Node (aka V8).
The `instanceof` is definitely faster, even if the property access
would hit the megamorphic stub cache. For example in the case of a
simple [Angular Universal prerender][1] test, just changing this can
reduce the number of megamorphic stub cache misses by around **2%**.
Even in the case where the megamorphic stub cache hits all the time,
using `instanceof` is still faster. I put together a little micro- …

perf(Subscription): use `instanceof` to avoid megamorphic LoadIC

---

src/internal/observable/fromEventPattern.ts

The handler in fromEventPattern is typed as a Function, meaning it takes no arguments. Overwriting this requires a pretty awkward cast. By applying the same change as in https://github.com/ReactiveX/rxjs/pull/3530 this becomes a lot easier.

fix(fromEventPattern): improve typings for fromEventPattern

---

compat/Observable.ts

This PR fixes the problem reported in #4070 by removing `internal` from the import locations within `compat/Observable.ts`. Note that *no other import locations* within `compat` include `internal`.
For more information:
* [this comment](https://github.com/ReactiveX/rxjs/issues/4070#issuecomment-428075235) shows the commit that introduced the problem; and
* [this comment](https://github.com/ReactiveX/rxjs/issues/4070#issuecomment-428901656) explains how the problem is effected in Angular-CLI projects.
**Related issue (if exists):** #4070

fix(compat): remove internal from import locations

---

src/internal/Subscription.ts
src/internal/observable/dom/AjaxObservable.ts
src/internal/observable/dom/WebSocketSubject.ts
src/internal/operators/audit.ts
src/internal/operators/bufferWhen.ts
src/internal/operators/distinctUntilChanged.ts
src/internal/operators/expand.ts
src/internal/operators/mergeScan.ts
src/internal/operators/repeatWhen.ts
src/internal/operators/retryWhen.ts
src/internal/operators/sequenceEqual.ts
src/internal/operators/windowToggle.ts
src/internal/operators/windowWhen.ts

The `tryCatch` helper is a leftover from the CrankshaftScript days and
is considered bad practice for modern JavaScript engines. Same for the
`errorObject` trick.

refactor: remove uses of `tryCatch` helper

---

spec/observables/dom/webSocket-spec.ts
src/internal/observable/dom/WebSocketSubject.ts

Fix WebSocketSubject failing to close the underlying socket connection when it is unsubscribed
before the socket is in the open state. Currently, when unsubscribe is called on the subject or
when a subscription is unsubscribed there are checks on whether the socket is open (readyState = 1)
before it closes the connection. If unsubscribe is called before the connection is open, it will not
close the socket but will reset the state of the subject (_socket set to null), and it becomes
impossible to close the socket.
**Related issue (if exists):** #4447

fix(WebSocketSubject): fix subject failing to close socket

---

tools/make-closure.js

Sorry I've never been using umd bundle in a ES5 environment w/o external polyfill (i.e. `core-js`) already existed, am I right?
fixes: #4427

fix(bundle): closure to not rewrite polyfills for minification

---

src/index.ts
src/internal/create/bindCallback-spec.ts
src/internal/create/bindCallback.ts
src/internal/create/bindNodeCallback-spec.ts
src/internal/create/bindNodeCallback.ts

Add `bindCallback` and `bindNodeCallback` to the `experimental` branch.

chore(bindCallback): implement bindCallback

---

src/internal/Subject-spec.ts

Add remaining variations: should not error after complete, etc.

chore(subject): test error after complete, etc.

---

spec-dtslint/operators/race-spec.ts

Description:
This PR adds dtslint tests for `race`.

test(dtslint): add race

---

spec/Observable-spec.ts
src/internal/Observable.ts
src/internal/Subscription.ts

The `Observable.subscribe` method does not add `TeardownLogic` of a lifted `Operator` to the returned Subscription. Therefore the `TeardownLogic` of such an `Operator` is never called on unsubscriptions. This PR fixes that issue.

fix(Observable): Fix Observable.subscribe to add operator TeardownLogic to returned Subscription

---

spec/schedulers/VirtualTimeScheduler-spec.ts
src/internal/scheduler/VirtualTimeScheduler.ts

Previously VirtualTimeScheduler.flush would lose the action that was on a verge of maxFrames limit which rendered testing of observables that are ticking indefinitely impossible. After the fix the user can set maxFrames, flush, make assertions and repeat the process as many times as needed.
None

fix(VirtualTimeScheduler): rework flush so it won't lose actions

---

docs_app/src/app/layout/doc-viewer/doc-viewer.component.ts

As discussed in the Core Team Meeting. I have added some Meta Tags but I have not a single clue about seo and this stuff in particular.
That's the way it is looking (This shows the mergeMap Operators Page)
Don't know if we need any additional meta tags?!

docs(meta): add meta tags to docs

---

spec/Notification-spec.ts
src/internal/Notification.ts
src/internal/Rx.ts

Rather than using magic strings which are easily use incorrectly, this PR introduces a `enum NotificationKind`. 
This is not a breaking change as all clients that happen to already test the kind against a string will still have the same behaviour, both at compiletime and runtime, with the exception that if they use a notification kind letter that does not exist, they will get a compile time error.

style(Notification): Use enum to safely type the notification kinds

---

src/internal/operators/timeInterval.ts

add documentation for operator `timeInterval`

feat(docs) add doc for `timeinterval` operator

---

spec-dtslint/operators/takeWhile-spec.ts
spec/operators/takeWhile-spec.ts
src/internal/operators/takeWhile.ts

Description:
By default, the value that causes the predicate to return `false` is not emitted.
This change adds an `inclusive` option which changes the behavior of the operator to include the final value which made the predicate return `false`.
Typical use case: Polling an API until the response contains a certain value, and then doing something with the response.
Related issue: #4000

feat(takeWhile): add `inclusive` option to the operator which causes it to emit the final value

---

spec-dtslint/observables/from-spec.ts

There's one dtslint test that is failing no matter what you do, and it really shouldn't be failing. This just comments it out until it's resolved upstream (hopefully).

test(from): comment out test that dtslint is confused about

---

src/internal/Subscriber.ts
src/internal/Subscription.ts

Merge the `_parent` and `_parents` fields on the `Subscription` class
into a single `_parentOrParents` field, which can hold either `null`
(in case of no parents), a `Subscription` instance (in case of a
single parent), or an array of `Subscription`s (in case of multiple
parents). This not only shrinks the size of `Subscription` (and
subclass) instances, but more importantly reduces the number of
megamorphic property access sites in the hot `Subscription` methods,
especially in `unsubscribe()` and `add()`.
Also inline the `Subscription#_addParent()` method into
`Subscription#add()`, as it's the only call site anyways and
this removes another hot megamorphic `LoadIC` that was only needed
to lookup `subscription._addParent` in the call site.
Finally remove the `hasErrors` variable from …

perf(Subscription): improve parent management

---

src/internal/observable/dom/webSocket.ts

Removed ambiguous explaination of the messageFilter function of the multiplex() method.
#2193

docs(webSocket): added more info for multiplex() method

---

src/internal/operators/concatAll.ts

Fixes import of `map` operator for `concatAll` example.

docs(concatAll): fix map import

---

src/internal/operators/catchError.ts

Keeping things consistent with the other files I've been looking at 💄

Tidy style & docs in catchError

---

src/internal/operators/race.ts

Updating the documentation of  race operator to replace "emits an item" with "emits a next, error or complete notification"  #4561

docs(race): Update the race operator  docs

---

src/internal/operators/windowTime.ts

Fixes a copule glitches in the `windowTime` examples.

docs(windowTime): fix examples

---

src/internal/operators/windowWhen.ts

Fixes the `windowWhen` example imports.

docs(windowWhen): fix example

---

src/internal/operators/windowToggle.ts

The example was missing an import for `empty()`, but since that function is deprecated I figured it should be using `EMPTY` anyway? 🤔

docs(windowToggle): fix example

---

src/internal/operators/bufferToggle.ts

Swapping `empty()` for non-deprecated `EMPTY` in the example.

docs(bufferToggle): use non-deprecated syntax in example

---

src/internal/operators/buffer.ts

Fixes a duplicate declaration error in the `buffer` example.

docs(buffer): fix example

---

src/internal/operators/combineAll.ts
src/internal/operators/groupBy.ts

Update examples so they work standalone

docs(examples): Update examples so they work standalone

---

src/internal/operators/window.ts

Fixes small glitch in import syntax for `window` example.

docs(window): fix import syntax

---

docs_app/src/app/search/search-worker.js

This PR removes the stopWordFilter from the lunr pipeline. It filters words like "of" and "from" when indexing, missing some operators or functions when searching.
https://github.com/olivernn/lunr.js/blob/master/lib/stop_word_filter.js
Fixes #4524

fix(docs-app): remove stopWordFilter from lunr pipeline

---

src/internal/operators/publish.ts

- Fixes unterminated comment error.
- Adds missing `tap` import.
- Tidies formatting.
- Converts language identifier to `javascript` to match other examples.

docs(publish): fix example

---

src/internal/operators/repeat.ts

**Description:** `repeat` operator was described as "repeating source stream items", while actually it resubscribes to it
**Related issue:** #4586

docs(repeat): description change to reflect resubscription

---

src/internal/observable/dom/webSocket.ts

Fix typo unubscribe to unsubscribe

docs(webSocket): Fix typo unubscribe to unsubscribe

---

src/internal/operators/windowCount.ts

Fixes the `windowCount` example.

docs(windowCount): fix syntax error

---

src/internal/operators/concatMap.ts

docs(concatMap): fix example

---

src/internal/operators/subscribeOn.ts

Updated docs with descriptiond and example of the `subscribeOn` operator.
I took this issue to learn what schedulers are in RxJS.
Related to issue #4436

docs(subscribeOn): Updated docs for subscribeOn with description and example

---

src/internal/Observable.ts

Tidies up the `Observable` examples to they're immediately runnable.

docs(observable): fix examples

---

src/internal/operators/ignoreElements.ts

docs(operators): Fix typo

---

src/internal/operators/groupBy.ts

Fixes a few glitches so the examples are runnable.
This also includes stripping the type definitions since the example code blocks specify `javascript`, and the other examples I've seen so far don't seem to include these.

docs(groupBy): fix examples

---

docs_app/src/assets/js/devtools-welcome.js
docs_app/src/index.html

This adds rxjs to the global namespace in the docs app so that anyone can use the console as a playground in learning and testing while looking at the docs. An example would be:
```
rxjs.interval(4000).pipe(rxjs.operators.take(4)).subscribe(console.log);
```

docs(playground): Ability to use console for playground

---

spec-dtslint/observables/race-spec.ts
src/internal/observable/race.ts

- Actually accept other `ObservableInput` types (Promises, etc)
- Fixes issue where TypeScript would complain when you tried to subscribe to a race between to Observable types.
Fixes #4390
Fixes #4642

fix(race): better typings

---

spec/operators/throwIfEmpty-spec.ts
src/internal/operators/tap.ts
src/internal/operators/throwIfEmpty.ts

**Related issue (if exists):** 
https://github.com/ReactiveX/rxjs/issues/4565

feat(tap): reset throwIfEmpty hasValue on retry

---

src/internal/operators/mergeScan.ts

mergeScan import was missing in the example so it did not work
mergeScan import was missing in the example so it did not work

docs(operators): add missing import to the example

---

src/internal/operators/switchMap.ts

Add much simpler example to help understand what `switchMap` can do. It is easy to understand for document reader.

docs(operators): Add a simple example in doc string

---

src/internal/observable/combineLatest.ts

This PR deprecates all `combineLatest` signatures except `combineLatest([a, b, c])`, in order to make `combineLatest` smaller in an upcoming version, and in order for `combineLatest` to ever accept a dictionary of observables (and emit a dictionary of values), these extra functionsignatures need to be deprecated ahead of time to signal their future removal.
related #4640

feat(combineLatest): deprecated rest argument and scheduler signatures

---

docs_app/content/guide/testing/marble-testing.md

- Added usage example for marble syntax

docs(marble-testing): marble syntax

---

CONTRIBUTING.md
README.md

Update link to documentation
Closes #4517 
There are a couple of more places where `rxjs-dev.firebaseapp.com` is used:
* [sitemap.template.xml](https://github.com/ReactiveX/rxjs/blob/master/docs_app/tools/transforms/templates/sitemap.template.xml)
* [publish-docs.sh](https://github.com/ReactiveX/rxjs/blob/master/docs_app/scripts/publish-docs.sh)
but I'm not sure if I'm the right person to make changes there :)

docs(link): update link to documentation

---

src/internal/operators/switchAll.ts

tap is not defined for the example

docs(switchAll): missing tap import

---

src/internal/operators/repeat.ts

Updated documentation for `repeat` operator.
#4675

docs(repeat): Add repeat documentation, example, and see also

---

docs_app/content/guide/overview.md

So there was an issue with overview page of the rxjs docs. It used code examples which were in js and not working all. Fixed now!
**Related issue (if exists):** #4605

docs(overview): making all examples compile

---

spec-dtslint/observables/combineLatest-spec.ts
spec-dtslint/observables/concat-spec.ts
spec-dtslint/operators/pluck-spec.ts
spec-dtslint/operators/withLatestFrom-spec.ts
spec-dtslint/operators/zip-spec.ts
spec-dtslint/util/pipe-spec.ts

Unfortunately, there is no way to stop dtslint from testing in TS@next. RxJS 6 targets TS 2.8, and there is no `unknown` type. We'll need to uncomment these and correct types in v 7 when we updated to TS latest.

fix(dtslint): disable tests that break in TS@next

---

src/internal/Observable.ts

fix the error spell in the document of Observable.ts

docs(Observable): fix typo of document of Observable.ts

---

docs_app/tools/transforms/angular-api-package/index.js
integration/systemjs/systemjs-compatibility-spec.js
spec/observables/dom/fetch-spec.ts
spec/support/default.opts
src/fetch/index.ts
src/fetch/package.json
src/internal/observable/dom/fetch.ts
tools/make-umd-compat-bundle.js
tsconfig/tsconfig.base.json
tsconfig/tsconfig.legacy-reexport.json

- Adds `fromFetch` implementation that uses native `fetch`
- Adds tests and basic documentation
- DOES NOT polyfill fetch
I think, long term, we should deprecate the `ajax` methods and try to move people towards fetch now that both `fetch` and `AbortController` are universally implemented (everywhere but IE) and polyfills are available.
Maintaining our own ajax implementation is challenging, and this is lot more lightweight and full featured.

feat(fetch): Making fetch happen

---

src/internal/operators/throttleTime.ts

The example contains the simulation of double-clicks that happen within a time-range of 400ms.
#4647

docs(throttleTime): add double click example making use of throttle-config

---

src/internal/operators/repeatWhen.ts
src/internal/operators/single.ts

Added see also links to find,findIndex,elementAt operators
fix #4673

docs(single): Added see also links

---

src/internal/operators/onErrorResumeNext.ts

Removed type that would allow for a function to be passed.
Related issue: #4477

fix(types): Fixed signature for onErrorResumeNext

---

spec-dtslint/observables/forkJoin-spec.ts
spec/observables/forkJoin-spec.ts
src/internal/observable/forkJoin.ts
src/internal/types.ts

- Adds `forkJoin({ foo, bar })` such that it will return an `Observable<{ foo, bar }>` containing the values emitted from the sources held at the properties of the passed object.
- DEPRECATED: `forkJoin(a, b, c, d)` should no longer be used, rather, just pass an array such as `forkJoin([a, b, c, d])`.
- Reduces the size of the fork join code a bit
Been wanting to do this one for a while. Going to try to get `combineLatest` also. (Inspired to get to it by @cartant :heart:)

feat(forkJoin): accepts a dictionary of sources

---

src/internal/Notification.ts

This PR replaces the `NotiticationKind` const enum that was introduced in 6.4.0 with a string-literal union type. The latter is type-safe and compatible with single-module transpilation. Const enums are not, as the transpiler cannot know what should be used as a replacement for a reference to a const enum without using type information.
The `NotiticationKind` const enum is a problem for any projects using the `--isolatedModules` flag or for projects using the Babel TypeScript transform - which means any TypeScript projects generated with `create-react-app`.
**Related issue (if exists):** #4538

fix(Notification): replace const enum

---

spec/operators/throttleTime-spec.ts
src/internal/operators/throttleTime.ts

_throttleTime_ didn't emit single values when leading was disabled and trailing enabled.
e.g.:
```
source:   -a--------------------|
time:     ----|                  
previous: ----------------------|
current:  -----a----------------|
```
I've added tests to verify this behavior and added another commit to fix it.
Closes #2859 and #4491.
**perhaps irrelevant**  
I have another branch ready to fix some other problems related to throttleTime which I will create a PR for when this one is merged.

fix(throttleTime): emit single value with trailing enabled

---

src/internal/observable/dom/fetch.ts

docs(fromFetch): typo in docs

---

spec/observables/dom/fetch-spec.ts
src/internal/observable/dom/fetch.ts

This PR rearranges an existing test so that the expectations are performed after the complete - and subsequent unsubscribe - are finished. The rearranged test fails.
It also adds a flag to the `fromFetch` implementation so that `abort` is not called in the teardown if the promise returned by `fetch` has resolved.
This fixes the problem, but it also highlights a problem with the implementation: streamed data obtained using `fromFetch` cannot be aborted, as the `AbortController` passed to fetch also aborts the promises returned from `text` and `json`, etc.
**Related issue (if exists):** #4739

 fix(fromFetch): don't abort if fetch resolves

---

spec/observables/forkJoin-spec.ts
src/internal/observable/forkJoin.ts

This PR fixes a problem with `forkJoin`'s inspection of its first argument to determine whether or not it should be joining the properties of an object literal.
The current code checks to see if the argument is not an `Observable` and if it isn't, it proceeds as if it has been called with an object literal. However. the argument could be another `ObservableInput` - like a `Promise`.
This PR adds a failing test and changes the check to compare the argument's prototype to `Object.prototype`.
**Related issue (if exists):** #4737

fix(forkJoin): test for object literal

---

src/internal/umd.ts

Oops. I forgot to make sure this was available in the umd bundle (which people use for playground apps)

fix(umd): export fetch namespace

---

spec/operators/endWith-spec.ts
src/internal/operators/endWith.ts

This PR spreads the arguments passed to `endWith` into a call to `of` which is then passed to `concat.
The current implementation spreads the args directly into `concat` which is incorrect. The tests pass because strings are iterable and are therefore valid observable inputs. And the strings in the tests each contain only a single character. The test added in this PR uses numbers for values, and their use effects an error from the current, incorrect `endWith` implementation.
**Related issue (if exists):** #4731

fix(endWith): wrap args - they are not observables - in of before concatenating

---

docs_app/content/navigation.json

Remove the duplicated 'Operator' side nav link in the docs site.
Before:
After:
N/A

docs(navigation): remove duplicated nav link

---

src/internal/operators/switchMap.ts

Missing the third 1 from the output
The doc for switchMap() states that the output for the first example is: 
> const switched = of(1, 2, 3).pipe(switchMap((x: number) => of(x, x ** 2, x ** 3)));
> switched.subscribe(x => console.log(x));
> // outputs
> // 1
> // 1
> // 2
> // 4
> // 8
> // ... and so on
The example when ran is giving:
1
1
**1**
2
4
8
...

missing output from the example

---

src/internal/observable/concat.ts

Since an array is itself an ObservableInput and so considered as an observable source, this specifies the use of spread operator to pass an array of observables.
#4697

docs(concat): clarify array as input

---

src/internal/operators/skipUntil.ts

The example contains two base observables. An interval and a click listener. The resulting observable is the interval but skipping all the values, until the click event is fired.
#4631

docs(skipUntil): add description and example with an interval waiting for click

---

spec/operators/pairwise-spec.ts
src/internal/operators/pairwise.ts

**Description:** `pairwise` calls `next` before saving the current value as the previous one, which makes it not recursively re-enterable. If its subscriber synchronously triggers the input observable, `pairwise` erroneously emits a pair with the wrong previous value.
**Related issue:** https://github.com/reduxjs/redux/issues/3404

fix(pairwise): make it recursion-proof

---

src/internal/observable/dom/webSocket.ts

Remove manual serialization of payload using JSON.stringify since it is default serializer. In the sample code of the WebSocket operator. 

Remove manual serialization of payload.

---

src/internal/observable/of.ts

Typescript picks the deprecated signature when using `of`. ~~By moving the signature to the bottom it will pick the correct one.~~ Removed the deprecation comment instead
closes https://github.com/ReactiveX/rxjs/issues/4723

fix(of): deprecation warning when using of as intended

---

compat/operator/reduce.ts
compat/operator/scan.ts
spec-dtslint/operators/reduce-spec.ts
spec-dtslint/operators/scan-spec.ts
spec/operators/reduce-spec.ts
spec/operators/scan-spec.ts
src/internal/operators/reduce.ts
src/internal/operators/scan.ts

This solves an issue where if you would reduce over `T` you can get `T` out reliably, but you could
not get out `R` in anyway without manually typing the reduce method call
#4086
cc @cartant

fix(scan): fixed declarations to properly support different return types

---

src/internal/Subscription.ts

Subscription.add breaks if teardown function is null. (works with undefined)
`typeof teardown` returns object when null. It breaks later when rxjs tries to access the closed property.
The commit fixes that by first checking for null/undefined.
Haven't found an issue

fix(Subscription): Return Empty when teardown === null

---

src/internal/observable/concat.ts
src/internal/observable/defer.ts
src/internal/operators/elementAt.ts
src/internal/operators/first.ts
src/internal/operators/last.ts
src/internal/operators/mergeAll.ts
src/internal/operators/mergeMapTo.ts
src/internal/operators/multicast.ts
src/internal/operators/switchMapTo.ts
src/internal/operators/timeInterval.ts
src/internal/operators/timeout.ts
src/internal/operators/timestamp.ts
src/internal/util/isObservable.ts

I find some unused imports while viewing the operators code.

chore: remove unused imports

---

src/internal/Notification.ts

This PR removes a useless import - that appears to have been added by VS Code's autocomplete/autoimport feature.

chore: remove useless import

---

compat/operator/pluck.ts
spec-dtslint/operators/pluck-spec.ts
spec/operators/pluck-spec.ts
src/internal/operators/pluck.ts

Fixing the overloading type define ~~off-by-one~~ being widen

fix(pluck): key union type strictness

---

docs_app/content/guide/operators.md

**Description:** there is a missing ")" in this first() operator example in Rxjs guide. in the operators section [https://rxjs-dev.firebaseapp.com/guide/operators](url)
**Related issue (if exists):** i submitted an issue here [https://github.com/ReactiveX/rxjs/issues/4812](url)

fix first operator

---

docs_app/src/index.html
docs_app/src/pwa-manifest.json

The documentation site was still using Angular blue for `theme_color`. This updates the colors to match the rest of the site.
| Before | After |
| ------------- | ------------- |
| ![Screenshot_20190531-010607](https://user-images.githubusercontent.com/3341/58685583-df102180-8341-11e9-8d8c-6a7ea1138c4d.png) | ![Screenshot_20190531-010955](https://user-images.githubusercontent.com/3341/58685590-e46d6c00-8341-11e9-9e81-7c83fbfa8f4e.png) |
| ![Screenshot_20190531-011918](https://user-images.githubusercontent.com/3341/58685708-3a421400-8342-11e9-8f95-f7f4408f7376.png) | ![Screenshot_20190531-011149](https://user-images.githubusercontent.com/3341/58685613-f9e29600-8341-11e9-846d-ec8eb2bde038.png) |

docs: update theme_color to match site colors

---

spec-dtslint/observables/defer-spec.ts
src/internal/observable/defer.ts

This PR adds a failing dtslint test and then fixes the problem it exposes by separating the `defer` signatures, so that the signature that accepts a factory that returns `void` returns `Observable<never>`.
**Related issue (if exists):** #4804

 fix(defer): use overload sig for void factory

---

spec/operators/race-spec.ts
src/internal/observable/race.ts

The implementation of `race` ignores latter sources if an earlier source emits a `next` notification. This PR fixes the implementation so that latter sources are also ignored if an earlier source wins the race by emitting either a `complete` or an `error` notification.
This PR adds failing tests that are fixed by the change.
For more information, see the related issue - it contains code snippets that highlight the inconsistent behaviour.
**Related issue (if exists):** #4808

fix(race): ignore latter sources after first complete or error

---

spec-dtslint/operators/defaultIfEmpty-spec.ts
src/internal/operators/defaultIfEmpty.ts
src/internal/operators/first.ts
src/internal/operators/last.ts

This follows https://github.com/ReactiveX/rxjs/pull/4816 and uses the same fix (but for a different operator).

fix(TS): fix type inference for defaultIfEmpty.

---

package-lock.json
package.json
tslint.json

This PR enables the `no-const-enum` rule that's in `tslint-etc`.
ATM, `tslint-etc` is used in the dtslint tests to catch malformed type expectations. This PR bumps the `tslint-etc` version and enables the above-mentioned rule in the project's `tslint.json` file.
The reason const enums cannot be used is outlined in #4556. Basically, using a const enum prohibits isolated module transpilation, as it's necessary to refer to another file to determine the literal that should replace a reference to a const enum member. That means that versions of RxJS that export const enums cannot be used with `create-react-app`-generated projects or any other projects that build using isolated modules.
As configured, the rule forbids all use of const enums. The rule does have an `allowLocal` …

chore(lint): add no-const-enum rule

---

docs_app/content/guide/testing/marble-testing.md

When I first read this document original, I had difficulty understanding the following:
1. How to create a `testScheduler.run()` clause because the example had a different variable name - which sounds simple, but when you're scanning help pages, requires you to stop and think.
2. How to 'wait' in virtual time for the hot or cold Observables to complete before making an assertion.
3. Why `flush()` is described as 'Not often used', when my Angular Observable subscription code calls actions or updates to variables _almost_ as often as they just `map` to another Observable.
Therefore, my main reason for submitting this update is to make it easier for newbies to Marble Testing  like myself can:
a) Googling on 'marbles testing wait', 'marbles testing pause', 'marbles testing …

Marble testing docs update

---

doc/subject.md

Clarify that refCount is an operator and not a method used directly on a ConnectableObservable.
Closes #4664

docs(subject.md): clarify that refCount is an operator

---

spec-dtslint/observables/defer-spec.ts
src/internal/observable/defer.ts

This PR fixes a problem with the `defer` type signatures that was introduced in #4810 - the PR that ensured that `Observable<never>` was inferred for factory functions that return `void`.
The problem was that `() => void` will match functions returning any value - as the return value is ignored - which meant that factories could return anything - e.g. a `number`.
See the discussion on [this commit](https://github.com/ReactiveX/rxjs/commit/362d1d4fc1d7f15e7168453ea640079d0ca19dba#commitcomment-33814932).
The PR includes a failing dtslint test that is fixed by the change.
**Related issue (if exists):** #4804 #4810

 fix(defer): restrict allowed factory types

---

src/internal/operators/buffer.ts

Updating to proper marble diagram image src property
Fixing src property of marble diagram, in RxJS buffer operator documentation. 
N/A

docs(operators): fix marble-diagram image src

---

src/internal/observable/combineLatest.ts

Description:
Fix typo in combineLatest docs
Related issue (if exists):
None

docs(combineLatest): fix startWith typo

---

src/internal/operators/every.ts

**Description:** Added description for `every`
**Related issue (if exists):** #4614

docs(every): Added description for `every`

---

docs_app/content/guide/observable.md

The link to Observable in the first table in this page was broken
https://rxjs.dev/guide/observable
It looks like the link was still using the format used in the old version of the docs.
This PR fixes the link and I've built and run the docs locally to confirm it now works.

docs(observable.md): Fixed broken link in Observable guide

---

docs_app/content/guide/operators.md

docs(operators): Fix typo in Operators guide documentation.

---

src/internal/observable/empty.ts

docs(empty): Fixed broken syntax and import in example

---

src/internal/operators/throttle.ts

docs(operators): Add interval to import

---

src/internal/observable/generate.ts
src/internal/observable/pairs.ts
src/internal/operators/tap.ts

Noticed that the documentation for [`tap`](https://rxjs.dev/api/operators/tap) references a missing marble diagram.
n/a

docs(operators): fixed references to marble diagrams

---

docs_app/content/guide/v6/migration.md

"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358

Remove --save option as it isn't required anymore

---

src/internal/observable/onErrorResumeNext.ts

docs(onErrorResumeNext): fix typo

---

src/internal/observable/empty.ts

At some point we’d need to move `empty()` examples to `EMPTY` so I just moved it now,
since I already moved my codebase to `EMPTY` and there’s still no description in official docs

docs(EMPTY): fix broken link, updated description

---

src/internal/Observable.ts

fix #4923 
Adds a description to the toPromise() method.

docs(observable): add a description for toPromise()

---

spec/schedulers/TestScheduler-spec.ts
src/internal/scheduler/VirtualTimeScheduler.ts
src/internal/testing/TestScheduler.ts

- Makes `frameTimeFactor` public so people do not have to cast in TypeScript
- Deprecates `frameTimeFactor` on `VirtualTimeScheduler` as it is not used in that class, it
is really only intended to be used for `TestScheduler` marble diagrams
- Deprecates `index` on `VirtualTimeScheduler` because it is a leaked implementation detail
- Adds documentation

feat(TestScheduler): expose `frameTimeFactor` property

---

spec-dtslint/observables/dom/animationFrames-spec.ts
spec/helpers/test-helper.ts
spec/observables/dom/animationFrames-spec.ts
src/index.ts
src/internal/observable/dom/animationFrames.ts
tsconfig.base.json

- Also adds tests and test harness for requestAnimationFrame stubbing with sinon
- Updates TypeScript lib to use ES2018 (so we can use `findIndex` on `Array`).
Example 1: Just a simple use.
```ts
import { animationFrames } from 'rxjs';
// Log the elapsed milliseconds at each animation frame.
animationFrames().subscribe(elapsed => console.log(elapsed));
```
Example 2: Tweening animation function
```ts
import { animationFrames } from 'rxjs';
import { map, takeWhile, endWith } from 'rxjs/operators';
function tween(start: number, end: number, duration: number) {
const diff = end - start;
return animationFrames().pipe(
// Figure out what percentage of time has passed
map(elapsed => elapsed / duration),
// Take the vector while less than 100%
takeWhile(v => v < 1),
// Finish with 100% …
```

feat(animationFrames): Adds an observable of animationFrames

---

.make-packages.js

fix the issue which causes rxjs/fetch to behave wrongly
https://github.com/ReactiveX/rxjs/issues/4820
https://github.com/ReactiveX/rxjs/issues/4999

fix: missing package.json in rxjs/fetch

---

CONTRIBUTING.md

Fixes minor grammar issues on CONTRIBUTING.md
N/A

docs(contributing): fix minor grammar issues

---

doc/operator-creation.md

Remove apostrophe from possessive "its" in operator-creation.md
N/A

docs(operator-creation): fix typo

---

doc/pipeable-operators.md

Remove apostrophe from possessive "its" in pipeable-operators.md
N/A

docs(pipeable-operators): fix typo

---

spec/operators/auditTime-spec.ts

Use TestScheduler#run for the auditTime operator tests
- align marbles inside string literals
- fix times because timeFrameFactor is set to 1 not 10 in this context

test(auditTime operator): execute tests with TestScheduler#run

---

spec-dtslint/operators/filter-spec.ts
src/internal/operators/filter.ts

The provided test will create an `Observable<never>` with the order unchanged.

fix(filter): Fix overload order for filter to support inferring the generic type

---

spec/operators/audit-spec.ts

Use TestScheduler#run for the audit operator tests
As with #5038 and #5040 , run the specs with TestScheduler: 
- align the marbles with inner spaces
- uses '-' for ticks in subscription marbles
The alignment was tricky in a few cases: I'll highlight two examples of what I'm concerned about

test(audit operator): execute tests with TestScheduler#run

---

spec/operators/delay-spec.ts
src/internal/testing/TestScheduler.ts

This switches the `delay` operator tests over to use the `TestScheduler#run` method.
A made a couple of assumptions:
- I removed the  `declare const rxTestScheduler: TestScheduler;` line to instantiate the `TestScheduler` instance in a consistent way (see #5038) I assumed the declaration was for the typescript interpreter and it's not needed with this change.
- I added time to the run helpers - I think it was omitted deliberately but maybe we need it now so that we can have spaces in the time marbles for Prettier-safe alignment. I added a `trim()` to the  `createTime()` method to do this.

test(delay operator): execute tests with TestScheduler#run

---

spec/operators/take-spec.ts

This switches the `take` operator tests over to use the `TestScheduler#run` method.
It looks like the subscription marbles syntax is changed for `TestScheduler` - ticks are denoted by a `-` and not a space - so those expectations needed to be updated too. Other than that the content of the tests should be the same as before.

test(take operator): use TestScheduler for tests

---

README.md

Moving away from `@reactivex/rxjs`.

chore(readme): update npm badge ref to rxjs

---

docs_app/content/guide/scheduler.md

Remove link to Stackblitz example because each code snippet provides such link anyway.

docs(scheduler): remove link to Stackblitz example

---

src/internal/observable/of.ts
src/internal/observable/zip.ts
src/internal/operators/distinct.ts

Update `of`, `zip` and `distinct` examples

docs(examples): update examples

---

src/internal/operators/ignoreElements.ts

Added description text copy for the `ignoreElements` operator documentation based on the ReactiveX docs for the `ignoreElements` operator.
http://reactivex.io/documentation/operators/ignoreelements.html
#4618

docs(ignoreElements): add description text copy

---

src/internal/operators/shareReplay.ts

- Fix missing documentation due to incorrect line ordering
- Add additional documentation for the refCount parameter
Fixes #4796
Documentation for the shareReplay operator was not shown due to the function overloads being positioned between the documentation and the actual implementation. Moving the overloads above the JSDocs fixes the issue.
Furthermore, documentation was added to explain the refCount parameter. Understanding how the shareReplay operator behaves with regards to the refCount setting is critical.
#4796

docs (shareReplay): fix missing and add additional documentation

---

src/internal/observable/generate.ts

Fix `generate` function examples in doc.
Following #4996

docs(generate): Fix examples (#4996)

---

src/internal/operators/observeOn.ts

Update observeOn Docu, missing import

---

src/internal/observable/forkJoin.ts

I noticed that description didn’t mention the fact that observable had to emit as well, which actually introduced a bug in my personal code, so I thought it was a good idea to just add 2 more words for more clarity.
Also while working on it noticed unused import and expired TODO so I just removed them as well

docs(forkJoin): removed unused code, improved definition

---

src/internal/operators/share.ts

create example usage of share operator
closes #4797
**Description:** Add an example of `share()` usage, although there is no text under the `Description` area, I think the initial description describes the operator in-depth and I don't find any room for meaningful clarifications.
The description as seen in the docs  :
`Returns a new Observable that multicasts (shares) the original Observable. As long as there is at least one Subscriber this Observable will be subscribed and emitting data. When all subscribers have unsubscribed it will unsubscribe from the source Observable. Because the Observable is multicasting it makes the stream hot. This is an alias for multicast(() => new Subject()), refCount().`  
**Related issue (if exists):** #4797

docs: create example for share

---

README.md

Update the main readme file
Since there's no `stable` branch, I thought using the `6.x` will be more correct.
And I've also copied a line from `5.x` branch about making PRs. I've seen at least one person asking for this in a comment. Another option could be adding that line to the PR template.

docs(readme): update readme file

---

spec/observables/dom/fetch-spec.ts
src/internal/observable/dom/fetch.ts

Fix two issues with abort signal handling in `fromFetch`:
- The `signal` property on the init object was modified, which could lead to issues if the init object is reused for multiple requests.
- The `fromFetch` function basically ignored the incoming signal if it is already aborted.

fix(fromFetch): abort signal ignored if already aborted

---

src/internal/operators/map.ts

Since the return type of the `MapSubscriber`'s `project` method is defined as generic `R`, the result returned when calling this method could also be of type `R` (instead of `any`).

refactor(map): set generic type instead of any

---

src/internal/observable/concat.ts

Extended `@see` with `startWith` and `endWith`  as they are also concat variants

Extended `@see` with `startWith` and `endWith`

---

src/internal/observable/dom/WebSocketSubject.ts

docs(webSocket): fix typo

---

src/internal/observable/forkJoin.ts

The observable array example in the forkJoin documentation wasn't importing the `timer` operator, so it broke when I opened the example in StackBlitz. This PR just adds the missing import to the example.
None I could find.

docs(forkJoin): Add missing import in forkJoin array example

---

src/internal/operators/buffer.ts

Fix broken image of marble diagram for buffer operator in docs
#5095

Fix docs buffer marble diagram missing

---

src/internal/ReplaySubject.ts

Closure thinks `next()` is `UnusableType` instead of `(value: T) => void`, adding an `@override` annotation when overriding the method fixes this issue

fix(closure): Annotate next() for ReplaySubject

---

spec-dtslint/tsconfig.json

As mentioned in #4968, the TypeScript compiler options could be more strict. Changing this is going to involve code changes. However, there's no reason we cannot enable `strict` for the dtslint tests right now. Doing so will allow us to use `$ExpectError` in more situations in our dtslint tests - the `'strictNullChecks': false` in the current configuration will prevent some types of errors from being reported. 
**Related issue (if exists):** #4968

chore: use strict TS option for dtslint

---

package-lock.json

This fixes #5099 by bumping the version of `es-abstract` from the unpublished 1.14.0 to 1.14.2.
Version 1.14.2 is the latest patch version within the currently used minor range. There's also 1.15.0 and 1.16.0 but I decided to upgrade conservatively.
I usually use Yarn so I'm not sure on the canonical way to upgrade a transitive dependency using npm. I just ran `npm i es-abstract@1.14.2` and then did a diff on `package-lock.json`.
Since none of `es-abstract`'s dependencies apparently changed between 1.14.0 and 1.14.2, it looks safe to only bump the resolved package version itself (and its fingerprint), so that's what this PR achieves.

chore: Bump es-abstract dependency in package-lock.json

---

spec/helpers/observableMatcher.ts

I was working on updating the operator specs to execute in the context of `TestScheduler#run` and I noticed failing specs reporting "ReferenceError: chai is not defined"
eg. (contrived example)
```
1) delay operator
should delay by absolute time period:
ReferenceError: chai is not defined
at TestScheduler.observableMatcher [as assertDeepEqual] (spec/helpers/observableMatcher.ts:45:5)
at src/internal/testing/TestScheduler.ts:186:14
at Array.filter (<anonymous>)
at TestScheduler.flush (src/internal/testing/TestScheduler.ts:184:39)
at TestScheduler.run (src/internal/testing/TestScheduler.ts:419:12)
at spec/operators/delay-spec.ts:33:19
at Context.modified (spec/helpers/testScheduler-ui.ts:199:13)
```
It looks like this import statement is all that's needed to fix

fix(observableMatcher): add chai import to observableMatcher

---

src/internal/scheduled/scheduled.ts

Add links to "See Also" section

docs(scheduled): add links to see also section

---

src/internal/observable/empty.ts

Make the examples a bit more clear.

docs(empty): make examples clearer

---

src/internal/operators/shareReplay.ts

In `shareReplay`, the subscription needs to be cleared to prevent the implementation holding a reference to the completed source. In Angular, not clearing the reference can lead to components not being garbage collected.
Using the DevTools, I've verified that the fix in this PR is required, but I have no idea how a test could be written for this sort of thing.
**Related issue (if exists):** #5034

fix: clear subscription on shareReplay completion

---

src/internal/operators/isEmpty.ts

* Change code examples to `ts`
* Fix link to `EMPTY`
* General improvements

docs(isEmpty): improve documentation

---

doc/observable.md

remove unnecessary try/catch
fix #4982
**Description:** according to the following issue change the example of error handling in Observable docs section 
**Related issue (if exists):**  #4982

docs(Observable): change the example with error handling

---

src/internal/operators/onErrorResumeNext.ts

Be more specific when the next observable is subscribed in `onErrorResumeNext`.
This closes #4654

docs(onErrorResumeNext): Enhance short description

---

src/internal/observable/combineLatest.ts

"Use project function to dynamically calculate the Body-Mass Index" example in the combineLatest documentations was using "map" operator instead of the project function.
None

docs(combineLatest) Use project function instead of map operator

---

docs_app/ngsw-config.json

Till now the service worker configuration was slightly misconfigured so that all marble diagrams were loaded eagerly. This is totally unnessacary, therefore I changed it to load completly lazily.
I'm not very familar with service worker so I'd appreciate any feedback here!

docs(serviceWorker): change marble diagrams to load lazily

---

src/internal/observable/timer.ts

change
```
0`
```
to
```
`0`
```

docs(index): fix markup typo

---

docs_app/content/guide/operators.md

fix broken anchor link at guide (https://rxjs.dev/guide/operators#creation-operators)
at this section
```
See the list of all static creation operators here.
```
The `all the static creation operators here` anchor link not working due to have same id reference

docs(guide): fix broken anchor link

---

.eslintignore
src/internal/operators/finalize.ts

- Added the fact that to the documentation of finalize operator that it will also call its callback if the subscriber explicitly unsubscribes. (This was missing from the documentation before.)
- Added example for finalize basic usage and when the subscriber explicitly unsubscribes.
I'm not sure if this is the correct approach to submit a PR and I'm open to any feedback.
Thanks and Regards,
Dávid
#4578

docs(finalize): examples, improvement #4578

---

src/internal/observable/dom/ajax.ts

Import is missing in one of the examples related to AJAX

Import is missing in the documentation

---

src/internal/util/isPromise.ts
src/internal/util/subscribeTo.ts

add generics to help type inference

chore: remove useless type assertion

---

.circleci/config.yml

This PR bumps the explicit version of TypeScript used in the CI tests and adds a comment about the purpose of the test.
Prior to the change in this PR, the explicit TypeScript version was 3.5. As per the comment, this version should always be equal to or greater than the minimum-supported TypeScript version - the version of TypeScript in the `package.json`.
**Related issue (if exists):** #5166

chore: bump CI typescript version

---

src/internal/observable/combineLatest.ts

In a recent commit [https://github.com/ReactiveX/rxjs/commit/6661c796ea6f2918d4e6c0b68dfbecd4fbb7da74](https://github.com/ReactiveX/rxjs/commit/6661c796ea6f2918d4e6c0b68dfbecd4fbb7da74) a whole bunch of combineLatest calling forms were deprecated, but the docs weren't updated. I've now updated the docs for combineLatest to remove any references to the old way.

docs(combineLatest): changed examples of code to not use deprecated code

---

spec/helpers/interop-helper-spec.ts
spec/helpers/interop-helper.ts
spec/operators/catch-spec.ts
spec/operators/exhaustMap-spec.ts
spec/operators/mergeMap-spec.ts
spec/operators/onErrorResumeNext-spec.ts
spec/operators/skipUntil-spec.ts
spec/operators/switchMap-spec.ts
spec/util/toSubscriber-spec.ts
src/internal/operators/catchError.ts
src/internal/operators/exhaustMap.ts
src/internal/operators/mergeMap.ts
src/internal/operators/mergeScan.ts
src/internal/operators/onErrorResumeNext.ts
src/internal/operators/skipUntil.ts
src/internal/operators/switchMap.ts
src/internal/util/subscribeToResult.ts

This PR fixes a bug in which subscriptions returned from interop observables are ignored - instead of being composed into the subscription chain. Prior to this fix, when an interop observable was returned to a flattening operator - like `mergeMap` or `switchMap` - the interop observable would not be unsubscribed upon explicit unsubscription from the flattening operator.
The bug was introduced in the changes made in https://github.com/ReactiveX/rxjs/pull/2479 and https://github.com/ReactiveX/rxjs/pull/4037.
This PR:
* adds a test helper for simulating an interop observable;
* copies existing, chaining-related tests and uses an interop observable within them;
* ensures subscriptions returned from interop observables are added to the subscription chain;
* fixes another bug …

fix: chain subscriptions from interop observables

---

spec/helpers/interop-helper-spec.ts
spec/helpers/interop-helper.ts
spec/operators/catch-spec.ts
spec/operators/exhaustMap-spec.ts
spec/operators/mergeMap-spec.ts
spec/operators/onErrorResumeNext-spec.ts
spec/operators/skipUntil-spec.ts
spec/operators/switchMap-spec.ts
spec/tsconfig.json
spec/util/toSubscriber-spec.ts
src/internal/operators/catchError.ts
src/internal/operators/exhaustMap.ts
src/internal/operators/mergeMap.ts
src/internal/operators/mergeScan.ts
src/internal/operators/onErrorResumeNext.ts
src/internal/operators/skipUntil.ts
src/internal/operators/switchMap.ts
src/internal/util/subscribeToResult.ts

**Description:** This PR cherry-picks #5059 and applies it to the `6.x` branch.
**Related issue (if exists):** #5059

fix: chain subscriptions from interop observables for 6.x

---

spec-dtslint/observables/iif-spec.ts
src/internal/observable/iif.ts

This PR combines the changes in #4478 and #4520 - cherry picking the commits and making minor changes - so that the typings changes and the dtslint tests are in the same PR.
With these changes, when optional arguments are not passed to `iif`, they are inferred to be `never` rather than `{}`.
**Related issue (if exists):** #4494

chore: fix iif typings to infer never

---

spec/util/Immediate-spec.ts
src/internal/util/Immediate.ts

This is just a PR for v6 based off of work done in #5016 (and some clean up in another commit)

fix memory leak in asapScheduler (via Immediate)

---

spec/operators/catch-spec.ts

This PR adds a (commented-out) test that reproduces the problem in the issue linked below. It's not possible to easily fix the bug in the current implementation, but the re-implementation that's planned for v8 should take this situation into account and the test should be made to pass.
**Related issue (if exists):** #5115

test: add v8 subscriber-should-stay-closed test

---

src/internal/util/Immediate.ts

Description: When the promise was being created right away it caused an issues with Zones that was breaking Angular tests at Google.

Create promise lazily

---

src/internal/observable/race.ts
src/internal/operators/subscribeOn.ts

Small changes to docs and examples for `subscribeOn` and `race`.

docs: small improvements

---

spec-dtslint/operators/pluck-spec.ts
src/internal/operators/pluck.ts

**Description:** Change pluck's catch-all signature that is causing troubles when the
passed string is not a key in the argument object.
**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/5188

fix(pluck): fix pluck's catch-all signature for better type safety

---

CONTRIBUTING.md
spec/observables/dom/ajax-spec.ts
src/internal/observable/dom/AjaxObservable.ts

Fixed AjaxTimeoutError not inheriting AjaxError's and Eerror's
prototype. While the TypeScript typings were correct, actual code
using instanceof operator would fail.
The following statements are now true:
* AjaxError instanceof Error === true
* AjaxTimeoutError instanceof Error === true
* AjaxTimeoutError instanceof AjaxError === true

Fix AjaxTimeoutErrorImpl to extend AjaxError

---

spec/helpers/observableMatcher.ts
spec/operators/concat-spec.ts

**Description:** 
Adjusts to run mode tests for concat operator.

test(operator-concat): using run mode tests

---

spec/observables/dom/fetch-spec.ts
src/internal/observable/dom/fetch.ts

This PR fixes the problem reported in #5233. It:
* adds a failing test; and
* uses a local variable instead of reassigning to a closed-over parameter that's shared between subscribers.
**Related issue (if exists):** #5233

fix: don't reassign closed-over parameter in fromFetch

---

spec-dtslint/tsconfig.json
tsconfig.json

This PR tweaks the options in the root and dtslint `tsconfig.json` files so that the latest builtin types are included - via the `lib` option - and so that the default `target` is no longer the TypeScript default of `es3` (!!!). The problem with the latter is that IDE's pick up the root `tsconfig` and if the `target` is inferred to be `es3`, errors like this are shown:

chore: tweak tsconfig options

---

spec/helpers/interop-helper-spec.ts
spec/helpers/test-helper.ts
spec/helpers/testScheduler-ui.ts
spec/observables/dom/ajax-spec.ts
spec/observables/dom/fetch-spec.ts
spec/observables/dom/webSocket-spec.ts
spec/observables/from-spec.ts
spec/operators/concatMap-spec.ts
spec/operators/exhaustMap-spec.ts
spec/operators/expand-spec.ts
spec/operators/groupBy-spec.ts
spec/operators/mergeMap-spec.ts
spec/operators/switchMap-spec.ts
src/internal/observable/dom/AjaxObservable.ts
src/internal/observable/dom/WebSocketSubject.ts
src/internal/observable/forkJoin.ts
src/internal/observable/fromEvent.ts
src/internal/observable/pairs.ts
src/internal/operators/pluck.ts
src/internal/scheduled/scheduleIterable.ts
src/internal/scheduled/scheduleObservable.ts
src/internal/util/subscribeTo.ts
src/internal/util/subscribeToIterable.ts
src/internal/util/subscribeToObservable.ts
src/internal/util/toSubscriber.ts
tsconfig.json

This PR disables the `suppressImplicitAnyIndexErrors` TypeScript option - which is another escape hatch for non-strict code.
**Related issue (if exists):** #5240 (somewhat related)

chore: disable suppressImplicitAnyIndexErrors

---

spec-dtslint/operators/publishBehavior-spec.ts
spec-dtslint/operators/tap-spec.ts

Just noticed that the code isn't syntactically correct there.

fix syntax errors in spec-dtslint

---

docs_app/src/app/custom-elements/api/api-list.component.ts

As this document is inspired by Angular docs. There were some extra types in the filters So I think they are not necessary.

Removed Extra Filters

---

src/internal/observable/generate.ts

I read the code and realised that the name of one of the parameters of the `generate` function are is incorrect,
So basically I renamed `resultSelectorOrObservable` -> `resultSelectorOrScheduler`,
Just for clarity.

refactor(generate): rename parameter

---

src/internal/types.ts

I'm getting build errors since our updates to strictness. They revolved around the call signatures of SchedulerLike and SchedulerAction in a few operators. This resolves that by being a little more explicit.

chore: fix build errors

---

spec-dtslint/operators/endWith-spec.ts
src/internal/operators/endWith.ts

endWith now supports N-arguments for typings.. HOWEVER, if the user is using the deprecated Scheduler argument, and they are past 6 values as arguments, they will just get an incorrect type back and be forced to cast. This is an extreme corner-case though, so I feel it's worth the risk.

fix(endWith): will properly type N arguments

---

spec-dtslint/observables/combineLatest-spec.ts
spec-dtslint/observables/of-spec.ts
spec-dtslint/operators/combineLatestWith-spec.ts
spec-dtslint/operators/concatWith-spec.ts
spec/operators/combineLatest-legacy-spec.ts
spec/operators/combineLatestWith-spec.ts
src/internal/operators/combineLatestWith.ts
src/internal/operators/index.ts
src/operators/index.ts

- creates tests for new operator
- really just a renamed version of the old operator that was deprecated
- updates deprecations

feat(combineLatestWith): adds combineLatestWith

---

src/internal/operators/startWith.ts

I *think* (not sure) that the function definition of `startWith` is incorrectly typed. Because `startWith` has function overloads, this incorrect typing has no direct user impact. Except! this incorrect function signature is shown in the documentation for `startWith` (at the top), creating a source of confusion: https://rxjs-dev.firebaseapp.com/api/operators/startWith
This change can be thought of as a documentation fix, though it is also updates (fixes) the internal typing of the `startWith` operator function.

fix(startWith): fix incorrect types

---

src/internal/operators/mapTo.ts

Reduce the number of generics used in the 'mapTo' function to 1 generic parameter. Mark the 2 generic variant as a deprecated variant
issue #5090

refactor(mapTo): update function signature

---

spec-dtslint/observables/of-spec.ts
spec-dtslint/types-spec.ts
src/internal/observable/concat.ts
src/internal/observable/forkJoin.ts
src/internal/operators/concatWith.ts
src/internal/types.ts

This PR:
* Renames the `ObservedValuesFromArray` type to `ObservedValueUnionFromArray` and deprecates the former.
* Adds the `ObservedValueTupleFromArray` type.
The differences between the two are best shown by example:
```ts
type S = Observable<string>;
type N = Observable<number>;
ObservedValueUnionFromArray<[S, N]> // string | number
ObservedValueTupleFromArray<[S, N]> // [string, number]
```
It also adds an `Unshift` type - which adds a type to the beginning of a tuple - that should be useful in typing the `combineLatestWith` and `zipWith` operators.
These types should be sufficient to allow for N-args support in those operators:
```ts
export function zipWith<T, A extends ObservableInput<any>[]>(
...otherSources: A
): OperatorFunction<T, …
```

feat: add ObservedValueUnion/TupleFromArray

---

spec-dtslint/Observable-spec.ts
src/internal/Observable.ts

As described in #4196, the typing of `toPromise` does not match reality as it may return `undefined` in the case that no value is ever emitted. We have hit this bug in practice and believe it would be very useful to fix the actual typing.
(This does not implement the `default` argument as suggested in #4196 - while this seems like a reasonable addition, there are cases today where returning undefined is in fact desired, and it would be nice if the typing was correct for this case.)
*    #4196 - Typing of toPromise is wrong
(cc @sadarby)

fix(toPromise): correct toPromise return type

---

spec/operators/toPromise-spec.ts

This PR removes explicit parameter types from arrow functions in the `toPromise` spec. With the changes made in #5072, `toPromise` is now typed as potentially resolving with `undefined`.
The problem is currently breaking CI for all PRs.
**Related issue (if exists):** N/A

fix: remove explicit types in toPromise spec

---

src/internal/observable/generate.ts

docs(generate): add `the` and other improvements

---

src/internal/observable/defer.ts

Use EMPTY instead of deprecated function `empty()`
#5258

docs(defer): improve documentation and use EMPTY

---

spec/Observable-spec.ts
spec/observables/dom/ajax-spec.ts
spec/observables/interval-spec.ts
spec/operators/catch-spec.ts
spec/schedulers/AnimationFrameScheduler-spec.ts
spec/schedulers/AsapScheduler-spec.ts
spec/schedulers/QueueScheduler-spec.ts

Migrate from the deprecated `sinon.sandbox.create()` to `sinon.createSandbox()`. This PR upstreams internal changes to unblock Google's migration to sinon 8.1.

Replace deprecated sinon sandbox factory method

---

src/internal/observable/forkJoin.ts

docs(forkJoin): add `the` and other improvements

---

spec/operators/concatAll-spec.ts

Uses run mode for `concatAll` operator tests.

test(operator-concatAll): use run mode

---

spec/helpers/interop-helper.ts
spec/subjects/BehaviorSubject-spec.ts

This PR adds a failing - but skipped - test for the bug reported in #5105 - which cannot be easily fixed.
The problem is that the subject isn't seen as a safe/trusted subscriber because the interop source won't see the per-package `Symbol` that identifies the subject as trusted.
And that means that the subject will be 'cloned' so that an `unsubscribe` method can be added to it:
https://github.com/ReactiveX/rxjs/blob/f8a487617d6eb96b6f702cc1546c0cac59927d4b/src/internal/Subscriber.ts#L189-L193
And that means the the subject's original state will remain unchanged.
**Related issue:** #5105

test: add test for #5105

---

spec-dtslint/operators/combineLatestWith-spec.ts
spec-dtslint/operators/zipWith-spec.ts
src/internal/operators/combineLatestWith.ts
src/internal/operators/mergeWith.ts
src/internal/operators/zipWith.ts

This PR changes `combineLatestWith` and `zipWith` by:
* removing the overload signatures; and
* replacing them with a single signature that uses the `ObservedValueTupleFromArray` and `Unshift` types.
The return type for N-args usage is now a correctly-typed tuple - instead of an array with union-type elements.
**Related <s>issue</s> PR:** #5254

fix: use N-args tuple for combineLatestWith and zipWith

---

spec/Scheduler-spec.ts
spec/schedulers/AsapScheduler-spec.ts
spec/schedulers/QueueScheduler-spec.ts
spec/schedulers/VirtualTimeScheduler-spec.ts
src/internal/Scheduler.ts
src/internal/observable/SubscribeOnObservable.ts
src/internal/observable/bindCallback.ts
src/internal/observable/bindNodeCallback.ts
src/internal/observable/generate.ts
src/internal/observable/interval.ts
src/internal/observable/pairs.ts
src/internal/observable/throwError.ts
src/internal/observable/timer.ts
src/internal/operators/bufferTime.ts
src/internal/operators/debounceTime.ts
src/internal/operators/delay.ts
src/internal/operators/expand.ts
src/internal/operators/observeOn.ts
src/internal/operators/throttleTime.ts
src/internal/operators/timeoutWith.ts
src/internal/operators/windowTime.ts
src/internal/scheduler/Action.ts
src/internal/scheduler/AnimationFrameAction.ts
src/internal/scheduler/AsapAction.ts
src/internal/scheduler/AsyncAction.ts
src/internal/scheduler/AsyncScheduler.ts
src/internal/scheduler/QueueAction.ts
src/internal/scheduler/VirtualTimeScheduler.ts
src/internal/testing/ColdObservable.ts
src/internal/types.ts

This PR reverts the changes made to the `SchedulerLike` interface. As discussed in the core-team Slack channel - with @MichaelJamesParsons - the changes broke user-land schedulers. (Angular Zone-related schedulers are not uncommon.)
Although the typing of the `SchedulerLike` interface in arguably incorrect, it might be best to leave it as-is and delay any changes to the scheduler infrastructure until version 8.
The reversion has necessitated the liberal use of `as any` assertions, as all of the dispatch/work functions assume a `state` that is not `undefined`. This problem was hidden until the `strict` typescript option was enabled. I did try a few other approaches - including using a conditional type instead of the `as any` assertion - but they didn't work out.
**Related …

chore: revert SchedulerLike interface changes

---

src/internal/observable/bindCallback.ts

fix the docs error:
Rx.Scheduler.async is deprecated, change it to Rx.asyncScheduler

docs(index): fix docs Rx.Scheduler.async is deprecated

---

spec/operators/concatAll-spec.ts

This PR fixes an incorrect import path that was introduced in #5144.
**Related issue (if exists):** #5144

test: use correct test helper import path

---

src/internal/operators/groupBy.ts

docs(groupBy): replace elsewhere with otherwise

---

spec-dtslint/observables/race-spec.ts
spec/observables/race-spec.ts
src/internal/observable/race.ts

This PR:
* Adds a failing test and fixes a bug in the static `race` implementation in which a single `ObservableInput` argument was returned without `from` being called upon it to ensure that an `Observable` was returned.
* Adds support for N args to the static `race` types.
**Related issue:** None

fix: support N args in static race and ensure observable returned

---

docs_app/content/guide/operators.md

`switchAll` was missing from the operators page

added missing `switchAll` link

---

src/internal/Observable.ts

update documentation since toPromise signature was changed
I have not stated in the docs when this change was introduced. Should I do that?
Closes #5277

update toPromise documentation with undefined

---

src/internal/operators/first.ts

In the docs for the `first` operator add a note that `first()` is different from `take(1)`. First throws `EmptyError` if there are no elements in the source.
see also https://twitter.com/fmalcher01/status/1213417124036784128

docs(operators): add note about first() vs take(1)

---

src/internal/observable/empty.ts

Add a simple example for the `EMPTY` constant, add corresponding marble diagram.
N/A

docs(EMPTY): add example

---

src/internal/observable/forkJoin.ts

docs(forkJoin): add example of empty array

---

src/internal/Notification.ts
src/internal/operators/repeat.ts
src/internal/operators/take.ts
src/internal/operators/takeLast.ts

Replaced `empty` import leftovers with `EMPTY` constant.

refactor(EMPTY): replace deprecated empty imports with EMPTY constant

---

src/internal/observable/merge.ts

"it's" means "it is", and "its" is the proper form for possession.

doc(typo): use the correct form of "its"

---

spec-dtslint/firstValueFrom-spec.ts
spec-dtslint/lastValueFrom-spec.ts
spec/firstValueFrom-spec.ts
spec/helpers/test-helper.ts
spec/lastValueFrom-spec.ts
src/index.ts
src/internal/firstValueFrom.ts
src/internal/lastValueFrom.ts

The idea here is to add at least one static method to convert an Observable to a Promise. Given that `toPromise` is flawed (citation from elsewhere in the repo needs to go here). The idea is to use static methods and deprecate `toPromise`.
The basic API is this:
```ts
async function test() {
const data = await lastValueFrom(source$);
}
```
and additionally this features this idea:
```ts
async function test() {
const data = await firstValueFrom(source$);
}
```

RFC: Strawman Proposal for toPromise replacement

---

integration/side-effects/snapshots/esm/ajax.js
integration/side-effects/snapshots/esm/fetch.js
integration/side-effects/snapshots/esm/index.js
integration/side-effects/snapshots/esm/operators.js
integration/side-effects/snapshots/esm/testing.js
integration/side-effects/snapshots/esm/websocket.js
package-lock.json
spec/Observable-spec.ts
spec/observables/from-spec.ts
src/internal/Observable.ts
src/internal/asyncIteratorFrom.ts
src/internal/scheduled/scheduleAsyncIterable.ts
src/internal/scheduled/scheduled.ts
src/internal/types.ts
src/internal/util/deferred.ts
src/internal/util/subscribeTo.ts
src/internal/util/subscribeToAsyncIterable.ts

This adds support for the following:
`for await` loops consuming RxJS observables:
```ts
const ticker = interval(1000).pipe(take(100));
async function test() {
for await (const number of ticker) {
console.log(number);
}
}
test();
```
RxJS consuming async iterables:
```ts
function snooze(ms) {
return new Promise(resolve => setTimeout(snooze, ms));
}
async function* values() {
for (let i = 0; i < 3; i++) {
await snooze(1000);
yield i;
}
}
from(values()).subscribe(x => console.log(x));
of(1).pipe(mergeMap(() => values())).subscribe(x => console.log(x));
```
Async Iterables are currently supported in all major browsers, but not IE. They are also supported in Node 10 and higher.
The goal of the implementation is as such that it simply won't work in runtimes that do not support it. But as we …

RFC: AsyncIterable Support

---

spec-dtslint/operators/startWith-spec.ts
src/internal/operators/startWith.ts

- Improves documentation a bit
- Updates type tests
NOTE: Calls with more than 7 arguments that have a Scheduler at the end will return the wrong time. This is consider a corner case and low-risk
BREAKING CHANGE: `startWith` will return incorrect types when called with more than 7 arguments and a scheduler. Passing scheduler to startWith is deprecated

fix(startWith): accepts N arguments and returns correct type

---

docs_app/content/guide/operators.md

This PR add one missing operator that should listed on `operators.md` page.
Closed: #5341

docs: add `partition` to the operators list

---

doc/subject.md
spec/Subject-spec.ts
spec/observables/from-spec.ts
spec/operators/bufferCount-spec.ts
spec/operators/skipUntil-spec.ts
src/internal/Subject.ts
src/internal/operators/repeatWhen.ts
src/internal/operators/share.ts
src/internal/operators/windowTime.ts

Make type definition of `Subject` more strict to avoid common bugs when using Subject.
This issue been discussed extensively in #2852 and #5066 .
**Sensitive points**
As discussed in the issues linked above, it is possible to omit the argument to `next` when the Subject is of type `Subject<void>`.
When the template type is anything other than `void`, then an argument for `next` is required.
The primary case where this can be a problem is when people instantiate `Subject<any>` and then use `subject.next()` with no arguments. This will break.
The present change makes the default template type of Subject `void` instead of `any`. This means that when you write `new Subject()`, you get a `Subject<void>` (instead of `Subject<any>`) and are …

Stricter type definition of Subject

---

src/internal/operators/mergeMapTo.ts

This generic is completely unused in the signature, so I don't see any reason to include it?
Added in https://github.com/ReactiveX/rxjs/commit/c2ac39cd4636f493bb147b6ba5eb50fece8fc24d
(I discovered this because of Wotan's `no-uninferred-type-parameter` lint rule.)

fix(`mergeMapTo`): remove redundant/unused generic

---

spec/util/pipe-spec.ts
src/internal/util/pipe.ts

Optimize calling `pipe` with 0 args.
Closes #4933
There is an `if (!fns)` check in the `pipeFromArray` helper, and it results in `noop`. The test for `pipe` says the 0-arg case returns a no-op, but it checks for `identity`. The test is probably meant to test for that check, but the check is for the lack of an args array, so I added a check for that test to test and fixed the test's label.
The `if (!fns)` check might not be necessary at all. It is unreachable from client code, since `pipeFromArray` is internal, and is only used from `pipe`, which will never pass null/undefined.

fix(pipe): Special handling for 0-arg case.

---

spec-dtslint/operators/pluck-spec.ts
spec/operators/pluck-spec.ts
src/internal/operators/pluck.ts

Fix: The parameter type of pluck does not accept numbers as array indices while the operator itself already supports arrays.

fix(pluck): param type

---

spec/operators/delay-spec.ts
spec/operators/mergeScan-spec.ts
spec/schedulers/TestScheduler-spec.ts
src/internal/operators/delay.ts

This is an attempt to fix #4249. `delay` will now emit complete notification as soon as possible. This means that if there are no values queued it'll emit immediately. If there are queued values then it'll emit complete right after the last scheduled value.
Since complete shouldn't be delayed I'm not even adding it into the queue which means complete might be sent in the same frame as the last value. For this reason I had to change this test https://github.com/ReactiveX/rxjs/compare/master...martinsik:fix-4249?expand=1#diff-dd8d0ea30be1698896e447581ec91fffR379
This is a breaking change although probably not many people rely on this behavior.
Closes #4249

fix(delay): emit complete notification as soon as possible

---

spec/observables/dom/fetch-spec.ts
src/internal/observable/dom/fetch.ts

This PR adds a failing test and ensures that `removeEventListener` is called upon unsubscription if `addEventListener` was called on a passed in `AbortSignal`.
**Related issue:** None

fix(fetch): don't leak event listeners added to passed-in signals

---

src/testing/index.ts

Until now, folks subclassing `TestScheduler` needed to `run(callback: (helpers: RunHelpers...` method. This was super brittle so we need to properly export this so it can be used more sanely

fix(google): Subclassing TestScheduler needs RunHelpers

---

integration/side-effects/snapshots/esm/websocket.js
integration/side-effects/snapshots/esm2015/websocket.js
integration/side-effects/snapshots/esm5/websocket.js
spec/operators/timestamp-spec.ts
src/internal/ReplaySubject.ts
src/internal/operators/timestamp.ts
src/internal/types.ts

Refactors `ReplaySubject`, `timeInterval`, and `timestamp` to remove reliance on Schedulers that were not necessary. This should help drastically reduce the amount of code pulled in for default `shareReplay` usage or `timestamp` usage.
See commit messages for more details.
NOTE: Breaking change in that `ReplaySubject` will no longer have inherent `observeOn` behavior if provided a scheduler.

Reduce scheduler footprint for default usage of shareReplay, timeInterval, and timestamp

---

docs_app/src/styles/1-layouts/_top-menu.scss

Top menu had position: absolute what was leading to its disappearing on scrolling
(#5336)

style(docs): top menu position: fixed on external resources page

---

spec-dtslint/operators/startWith-spec.ts
src/internal/operators/startWith.ts

Fixes broken types with start with. This was the solution proposed by Ben.
https://github.com/ReactiveX/rxjs/issues/5382

Fix startWith type signature

---

README.md

docs(readme): fix maintainer guidelines link

---

docs_app/tools/transforms/README.md

There is a small typo in docs_app/tools/transforms/README.md.
Should read `stored` rather than `stoted`.

docs: Fix simple typo, stoted -> stored

---

src/internal/operators/concatMapTo.ts
src/internal/operators/switchMapTo.ts

This PR makes similar changes to those #5299 makes to `mergeMapTo`: it removes the redundant type parameters from `concatMapTo` and `switchMapTo`.
**Related PR:** #5299

chore: remove redundant mapTo type parameters

---

spec-dtslint/observables/dom/fetch-spec.ts
spec-dtslint/tsconfig.json
spec/observables/dom/fetch-spec.ts
src/internal/observable/dom/fetch.ts

This PR adds an optional selector  to `fromFetch` so that it's better able to support chunked transfer encoding.
When chunked transfer encoding is used, the headers are received and the `Response` is resolved before the entire content is received. Without a using selector, it's not possible to abort the promises returned from the `Response`'s methods - `text`, `json`, `blob`, et al.
```ts
const mapped = fromFetch('/foo').pipe(
mergeMap(res => res.text())
);
```
In the above snippet, once the headers are received, the `Response` will be emitted and mapped to the `text()` promise. Whilst the chunked content is being received, the `fromFetch` will complete, so explicit unsubscription from the `mapped` observable will not abort the `text()` promise and all of the content will …

feat(fetch): add selector

---

spec/util/subscribeWith-spec.ts
src/internal/operators/catchError.ts
src/internal/operators/exhaustMap.ts
src/internal/operators/mergeMap.ts
src/internal/operators/mergeScan.ts
src/internal/operators/onErrorResumeNext.ts
src/internal/operators/skipUntil.ts
src/internal/operators/switchMap.ts
src/internal/util/subscribeToObservable.ts
src/internal/util/subscribeWith.ts

This PR refactors the fix to #5051 that was made in #5059.
Instead of testing for interop subscribers/subscriptions in operator implementations, this refactor moves the test into `subscribeToObservable` - which is where the interop subscription takes place - and ensures that function behaves like `subscribe` calls made to this package's observables.
That is, it ensures that the subscriber that's passed in is what's returned. If the subscription that's received is not the subscriber, said subscription is added to the subscriber so that unsubscription chains correctly.
The code is much simpler and all of the tests that were added in #5059 pass.
---
I've made some changes to this PR, as it can be used to resolve the problem that #5239 and #5243 sought to address.
It's …

refactor(subscribeToObservable): use subscribeWith util

---

spec/schedulers/AnimationFrameScheduler-spec.ts
spec/schedulers/AsapScheduler-spec.ts
src/internal/scheduler/AnimationFrameScheduler.ts
src/internal/scheduler/AsapScheduler.ts

This PR fixes a problem with the `animationFrame` and `asap` schedulers. The loop initialization logic in the `flush` implementation for both schedulers was incorrect and resulted in the execution of any actions that were rescheduled when executed.
This fixes the problem of the animation frame scheduler effecting too many notifications - see #4972. Regarding that issue, the `of(0, animationFrameScheduler).pipe(repeat())` snippet 'works' only because the implicit unsubscription cancels the action's additional `requestAnimationFrame` call.
The PR adds failing tests for both schedulers and then fixes the problems.
**Related issue (if exists):** #4972 and #5397

fix: don't execute rescheduled animation frame and asap actions in flush

---

spec-dtslint/operators/raceWith-spec.ts
spec/operators/raceWith-spec.ts
src/internal/operators/index.ts
src/internal/operators/raceWith.ts
src/operators/index.ts

This PR adds `raceWith` - another operator deprecated because it had the same name as a static `Observable` creator.
The `raceWith` operator drops support for passing an array instead of using a rest parameter and spread. It's unclear why both are supported in the first place. TBH, this is something that we are going to have to sort out in the signature review: should these situations use rest parameters or arrays? This is something that can be sorted out elsewhere, but to make this consistent with the new `concatWith`, etc. this operator drops support for passing an array.
**Related issue:** None

feat: add raceWith

---

spec-dtslint/types-spec.ts
src/internal/operators/combineLatestWith.ts
src/internal/operators/zipWith.ts
src/internal/types.ts

This PR renames the `Unshift` type that was added in #5257 to the more conventional - for tuples - `Cons` and adds the related `Head` and `Tail` types - which I anticipate needing for the refactoring of some signatures to better handle N-args typing in some circumstances.
I originally went with `Unshift` 'cause that's the JS array-related terminology and thought that might be more familiar for folks. However, now that I anticipate needing the other typical tuple-manipulating types, I think the conventional names should be used.
**Related PR:** #5257

refactor: rename Unshift to Cons

---

spec/helpers/interop-helper.ts
spec/operators/finalize-spec.ts
src/internal/operators/finalize.ts

The change in this PR is very similar to the changes that were made in #5059: when an interop subscriber is created within `finalize`, it'll be wrapped when a subscription is made to the source observable in `FinallyOperator#call`. The interop subscriber needs to be added to the subscription so that unsubscription chains property and the finalize callback is invoked.
The adding of the interop subscription is now handled in `subscribeWith` - which was added in https://github.com/ReactiveX/rxjs/pull/5333.
This PR also includes a failing test that is fixed by the above change.
**Related issue (if exists):** #5237

fix: chain subscriptions for interop with finalize

---

src/internal/firstValueFrom.ts
src/internal/lastValueFrom.ts

I updated examples for `firstValueFrom` and `lastValueFrom` which were bad. I also changed parameter name in `firstValueFrom` from `source$` to `source` because:
- `lastValueFrom` is also using `source`;
- the documentation uses `@param source`;
- although it's common to add `$` to Observable variables outside RxJS world, I couldn't find any other place inside RxJS that adds `$` to Observable parameters so I wanted to be consistent with the rest of the library.

docs: update non-working examples in firstValueFrom and lastValueFrom

---

README.md
spec-dtslint/operators/startWith-spec.ts
src/internal/operators/startWith.ts
src/internal/operators/windowTime.ts

Due to the wrong position of the windowTime tsdoc comments in the docs it is listing all the information just for that single overload instead of the general information block

docs(windowTime): fix documentation issue

---

spec/operators/bufferTime-spec.ts
spec/operators/expand-spec.ts
spec/operators/publishReplay-spec.ts
spec/schedulers/TestScheduler-spec.ts
spec/subjects/ReplaySubject-spec.ts
src/internal/ReplaySubject.ts
src/internal/observable/merge.ts
src/internal/operators/bufferTime.ts
src/internal/operators/expand.ts
src/internal/operators/mergeAll.ts
src/internal/operators/mergeMap.ts
src/internal/operators/mergeMapTo.ts
src/internal/operators/mergeScan.ts
src/internal/operators/shareReplay.ts
src/internal/operators/windowTime.ts
src/internal/scheduler/VirtualTimeScheduler.ts
src/internal/testing/SubscriptionLog.ts
src/internal/testing/TestScheduler.ts

We were using Number.POSITIVE_INFINITY, which is not only YELLING at me, but unnecessarily verbose. It technically was probably adding to bundle sizes, as well, but not very much. Either way, Infinity is better.
Also I just typed `git push origin infinity` and I felt super cool doing it.

refactor: Use Infinity

---

src/internal/operators/groupBy.ts

I have three small changes/additions in `groupBy` docs:
* added better formatting for GroupedObservable's `key` field;
* removed extra comma from example;
* added subjectSelector param to docs.

docs(groupBy): update groupBy docs

---

spec/operators/take-spec.ts
spec/operators/takeLast-spec.ts
src/internal/operators/take.ts
src/internal/operators/takeLast.ts

Add runtime assertions for JavaScript usage, where invalid argument may be passed causing strange behavior.
BREAKING CHANGE: `take` will throw a `TypeError` if called as `take()` or with an isNaN argument passed.
BREAKING CHANGE: `takeLast` will throw a `TypeError` if called as `takeLast()` or with an isNaN argument passed.

Fix take and takeLast

---

spec/operators/single-spec.ts
src/index.ts
src/internal/operators/single.ts
src/internal/util/NotFoundError.ts
src/internal/util/SequenceError.ts

Per our discussion of #5320, this is a set of fixes to the behavior of single, which was wildly incorrect. Modernizes and updates tests. Rewrites the operator in the newer functional style.
BREAKING CHANGES:
- `single()` will now throw if more than one value comes from the source. Previously it would not emit.
- `single(predicate)`, in cases where nothing matches the predicate, will now throw a `NotFoundError` if nothing matched, and an `EmptyError` if the source simply did not emit any values.
- `single(predicate)` on an empty source will now emit an `EmptyError`. Previously it would erroneously emit `undefined`.

Single operator fixes

---

spec/operators/dematerialize-spec.ts

This PR specifies the type for the `values` record that effected a compilation error with TypeScript 3.9 in CI.

chore: fix TS 3.9 error in dematerialize test

---

package-lock.json
package.json

typecript 3.9 was released, updated the repo typescript version to 3.9

chore: update to TS 3.9

---

spec-dtslint/AsyncSubject-spec.ts
spec-dtslint/BehaviorSubject-spec.ts
spec-dtslint/ReplaySubject-spec.ts
spec-dtslint/Subject-spec.ts
spec/Subject-spec.ts
spec/observables/dom/animationFrames-spec.ts
spec/operators/take-spec.ts
src/internal/Subject.ts

- Changes Subject to not have a default generic of `void`
- Adds dtslint tests for Subject, ReplaySubject, BehaviorSubject, and AsyncSubject
BREAKING CHANGE: `new Subject()` will return `Subject<unknown>`.

fix(Subject): no default generic

---

spec-dtslint/operators/groupBy-spec.ts
src/internal/operators/groupBy.ts

A couple of notes here. I couldn't figure out how to test this since it doesn't work in oldish versions of TS like 2.8 which is where the dtslint tests run. If there was some way to enable/disable for TS versions that would be one solution.
Note that in the example in #5439 you need to test `key === true` in order to get the type checking to work for both the if and else blocks. This may be related to https://github.com/Microsoft/TypeScript/issues/26852
Another item and this is probably a TS issue is that while all 4 of the following usages work, the 5th one, using an inline type guard with no explicit arg type, doesn't work. I'm guessing there's some TS weirdness going on that's probably a bug but I can't explain what is making it behave that way
```ts
function isNumberFromAny(input: …
```

feat(groupBy): Add typeguards support for groupBy

---

spec/operators/mergeMap-spec.ts
spec/util/subscribeToResult-spec.ts
src/internal/util/subscribeToIterable.ts

Resolves an issue where if you were trying to use an iterator to do something like examine and flatten an array in one go, it would not properly handle the error, particularly in async cases:
```ts
const requestData$: Observable<void> = buttonClicksOrSomething$;
requestData$.pipe(
concatMap(() => {
const dataStream$: Observable<Data[]> = getDataStream();
return dataStream$.pipe(concatMap(function* (rows) {
for (const row of rows) {
if (isInvalidRow(row)) {
throw new Error('invalid row');
}
yield row;
}
})
}
)
```
Closes #5436

fix: errors thrown from iterables now properly propagated

---

spec/operators/finalize-spec.ts
src/internal/operators/finalize.ts

This PR changes the implementation of `finalize` so that the callback passed to the operator is not called until *after* the subscriber unsubscribes from its source. The effect of this is that - with this change - finalization happens in same order as completion and unsubscription.
Specifically, with unsubscription, we can be sure that when a subscription's `unsubscribe` method returns, every source observable in the chain will have been guaranteed to have been unsubscribed.
Without this change, `finalize`'s behaviour is very different to that of unsubsciption.
The problem is that when `finalize` calls its callback, the observable to which it is applied is still subscribed to any sources and any `finalize` operators applied to sources further up the composed chain will …

fix: finalize after unsubscription from source

---

spec-dtslint/operators/endWith-spec.ts
spec-dtslint/operators/startWith-spec.ts
src/internal/operators/endWith.ts

This PR makes a change to the `endWith` signature that's similar to the one made to `startWith` - in #5383 - and adds a dtslint test.
**Related issue (if exists):** #5383

chore: add default varargs type to endWith

---

integration/side-effects/snapshots/esm2015/fetch.js
spec-dtslint/observables/dom/fetch-spec.ts
spec-dtslint/tsconfig.json
spec/observables/dom/fetch-spec.ts
src/internal/observable/dom/fetch.ts

* feat(fetch): add selector
This PR cherry picks the fix in #5306 for v6.
**Related issue (if exists):** #5306

feat(fetch): add selector (cherry pick #5306 for v6)

---

docs_app/content/guide/operators.md

Changes the `Observalbes` to `Observable` in Higher-order Observables section.

Fixes typo in operators.md file

---

spec/operators/shareReplay-spec.ts

As discussed in #5455: it would be useful to have a test that removes the ambiguity on what should happen with the `shareReplay` operator if `refCount` is `true` once the source completes.
I've also added a second commit that gets rid of the redundant variable `isComplete`. This variable became unnecessary after [this change](https://github.com/josepot/rxjs/commit/35e600fb031ba2814d65b586ca0664af85b179ba#diff-a3e23feeea8613de90d70844292403e3). I guess that this second commit is a "nit pick", so I don't mind removing it from this PR. Although, it may marginally reduce the bundle size?
**Related issue**
#5455

test(shareReplay): don't restart when refCount if the source has completed

---

src/internal/operators/shareReplay.ts

This PR removes the redundant variable `isComplete` from the `shareReplay` operator. This variable became unnecessary after [this change](https://github.com/josepot/rxjs/commit/35e600fb031ba2814d65b586ca0664af85b179ba#diff-a3e23feeea8613de90d70844292403e3).

chore(shareReplay): remove redundant variable `isComplete`

---

docs_app/src/extra-files/stable/robots.txt
docs_app/tools/transforms/templates/sitemap.template.xml

The sitemap.xml generated in the docs build process was pointing to angular.io and the old firebase instance

docs(sitemap): pointing to rxjs.dev

---

src/internal/Observable.ts

Link to firstValueFrom or lastValueFrom instead.

Deprecate toPromise.

---

docs_app/content/guide/installation.md

**Description:** Improve installation page.
The idea behind swapping the `entire core set` example with `import only what you need` is to encourage people to use the second one since that's preferable. 

docs(installation): improve installation page

---

src/internal/Subscription.ts

Fix type definition to show in proper way in documentation.
(https://rxjs-dev.firebaseapp.com/api/index/class/Subscription#closed)
Before: 
```
class Subscription implements SubscriptionLike {
.....
closed: [object Object]
....
}
```
After:
```
class Subscription implements SubscriptionLike {
.....
closed: boolean
....
}
```
Fix #5035

docs: fixed showing type in docs of Subscription

---

spec/operators/expand-spec.ts
src/internal/operators/expand.ts

Using `expand()` on synchronous outer source/inner sources with the async and asap schedulers causes expand to terminate prematurely. The inner active counter is incremented when the scheduled task fires, not when it's enqueued. This PR fixes that.

operator(expand): fix expand with async/asap schedulers

---

src/internal/Observable.ts
src/internal/config.ts
src/internal/firstValueFrom.ts
src/internal/lastValueFrom.ts

We need to remove these configuration options for v8, to help streamline the library and reduce size. Adding deprecations messages that give a little bit about why they are deprecated and some workaround information
Also adds some additional blurbs to documentation for promise-related methods on Observable.
Also adds some documentation to forEach with an example.

chore: deprecate old config options

---

src/internal/observable/merge.ts

Fix typo on usage examples on comments.
A `scheduled` function called with `scheduler`.

Chore: Fix typo on deprecation comments of `merge`

---

spec/observables/timer-spec.ts
src/internal/observable/timer.ts
src/internal/operators/delay.ts
src/internal/operators/timeoutWith.ts
src/internal/scheduler/VirtualTimeScheduler.ts
src/internal/util/isDate.ts

Fixes for `TestScheduler` and `VirtualTimeScheduler`:
- Resolves an issue where scheduling at non-finite numbers would result in marbles showing up in tests that had a `frame` of `null`.
Fixes for `timer`:
- Adds tests for cases where `Infinity` could be passed
- Adds a test for dueTime `Date` objects in the past
- Completely rewrites and improves documentation and updates examples
- Renames internal utility function `isDate` to `isValidDate` to better convey what it is doing and why
This is just part of my march through the code to fix up things that were using `isNumeric`, which I find highly suspect.

Timer fix unhappy numbers

---

src/internal/observable/ConnectableObservable.ts
src/internal/operators/refCount.ts

Since the `source` and the `connectableObservable` is the same thing in RefCountOperator, there is no need to hold the variable `connectable` int the RefCountOperator
NONE

chore(refCount): remove unnecessary reference of object

---

src/internal/operators/repeatWhen.ts

This PR makes a trivial change to the type of the `notifications` observable passed to the `notifier` in `repeatWhen`. The observable emits when the source completes and it does not emit a value - there is an internal `Subject<void>` that's used for notifications.
This PR types the `notifications` as `Observable<void>` instead of `Observable<any>`.
No dtslint test is added because there is no inference involved here.

chore: type repeatWhen notifier as void

---

spec/schedulers/TestScheduler-spec.ts
src/internal/testing/TestScheduler.ts

Correctly interprets subscription marble diagrams that do not include a subscribe character as not being subscription expectations. See related issue for more details.
This PR adds failing tests and then filters subscription logs that are associated with marbles that lack subscription characters.
**Related issue (if exists):** #5499

fix: support empty subscription marbles

---

spec-dtslint/Notification-spec.ts
spec-dtslint/operators/dematerialize-spec.ts
spec-dtslint/operators/materialize-spec.ts
spec/Notification-spec.ts
spec/operators/dematerialize-spec.ts
spec/operators/groupBy-spec.ts
spec/schedulers/TestScheduler-spec.ts
src/internal/Notification.ts
src/internal/operators/delay.ts
src/internal/operators/dematerialize.ts
src/internal/operators/materialize.ts
src/internal/operators/observeOn.ts
src/internal/testing/ColdObservable.ts
src/internal/testing/HotObservable.ts
src/internal/testing/TestMessage.ts
src/internal/testing/TestScheduler.ts
src/internal/types.ts

- Ensures Notification methods only accept appropriate arguments
- Ensures Arbitrary objects of the proper shape my be passed through dematerialized
- Utilizes hot path functions to create lightweight objects for internal notification use
- Deprecates the Notification class
- Adds a deprecation message for materialize to notify users that soon the emitted object type will change to not have all of the same methods as Notification
- Updates a few tests that were relying on the shape of Notification instances to pass, as we are now using POJOs internally in the TestScheduler
- Adds dtslint tests for notifications
- Adds dtslint tests to enforce types on dematerialize
BREAKING CHANGE: Notification.createNext(undefined) will no longer return the exact same reference everytime.
BREAKING …

fix: fix up notification types

---

docs_app/content/resources.md

Continuing the discussion from https://github.com/ReactiveX/rxjs/issues/5538 which was closed, I feel like there is a fragmentation problem where important context for making good use of RxJs is missing from the docs. This attempts to bridge the gap, and implements the suggestion I was trying to discuss before 5538 was abruptly closed, it takes a step in the right direction by making these 3rd party packages actually visible, so readers of the docs are actually aware there is more to the ecosystem than just what is shown on the official docs.

Add https://rxjs.xyz/

---

spec/operators/pluck-spec.ts
src/internal/operators/pluck.ts

Add a fix to prevent the pluck operator from breaking on null or undefined inputs. 
https://github.com/ReactiveX/rxjs/issues/5505

fix(pluck): operator breaks with null/undefined inputs.

---

spec/operators/shareReplay-spec.ts
src/internal/operators/shareReplay.ts

fix(shareReplay): subscribe to subject before source subscription starts

---

docs_app/content/guide/operators.md

operator map and the first example are wrong.

Example code is wrong.
