ReactiveX/rxjs

spec/observable/value-spec.js, spec/scheduler-spec.js, src/NextTickScheduler.ts, src/Observable.ts, src/Observer.ts, src/RxNext.ts, src/Scheduler.ts, src/SchedulerActions.ts, src/observable/empty.ts, src/observable/fromArray.ts, src/observable/fromPromise.ts, src/observable/never.ts, src/observable/range.ts, src/observable/return.ts, src/observable/throw.ts, src/observable/value.ts, src/operator/concatAll.ts, src/operator/flatMap.ts, src/operator/map.ts, src/operator/mapTo.ts, src/operator/mergeAll.ts, src/operator/selectMany.ts, src/operator/skip.ts, src/operator/take.ts, src/scheduler/NextTickScheduler.ts, src/scheduler/Scheduler.ts, src/scheduler/SchedulerActions.ts, src/scheduler/immediate.ts, src/scheduler/nextTick.ts, src/util/Symbol_observer.ts
Simplified many operators after discussing RxJava's approach with @benjchristensen 
Moved Schedulers around a bit, better modularization.
Split `map` into `map` and `mapTo`
Got rid of clunky names like `selectMany` in favor of `flatMap`
Added `Observable.return` which is *different* than `Observable.value`, because return actually carries a value now.
Added really, really simple `Symbol.observer` polyfill. (this could be improved, I'm sure)
Added `forEach` method per the spec.
`subscribe` is now "zalgo safe"
Everything needs tests.
=> Typescriptify simplification of operators

package.json
This adds a couple of meta hints to the package config to enable easy usage via jspm, which is set up for a primarily ES6/TypeScript source use case (where consumers are doing their own ES6 transpiliation)
JSPM leverages npm and github, and for sanity reasons modules installed from npm are treated as commonJS by default - the `format: "es6" ` override instructs jspm to use ES6 module semantics.
The ` directories: { lib: "src" } ` hint tells JSPM to treat src/ as the root of the package and ignores other files when installed by consumers. This should be updated to the appropriate dist directory once the npm publishing pipeline is set up - in angular2 for example, its `lib: "es6/prod"`
In pre-alpha states this allows us to `jspm install github:reactivex/rxjs` to install directly from …
=> add jspm meta config

README.md, package.json
It is not necessary to have those prerequisite packages installed globally. When running npm scripts, the bin (e.g. browserify) is found automatically in /node_modules/.bin/, before it tries to find it globally. This commit also includes browserify as a devDependency, since it was the only one missing in order for
`build_all` to run.
=> Fix devDependencies and mention of global packages

src/operators/switchLatest.ts, src/operators/switchLatestTo.ts
I checkout'd the master branch, removed my old `node_modules`, and ran `npm install`, which after installing packages started running `prepublish`, which ran `npm run build_all`:
```
> RxJS-Next@0.0.0-prealpha.1 prepublish /Users/amed/RxJSNext
> npm run build_all
> RxJS-Next@0.0.0-prealpha.1 build_all /Users/amed/RxJSNext
> npm run build_es6 && npm run build_amd && npm run build_cjs && npm run build_global
> RxJS-Next@0.0.0-prealpha.1 build_es6 /Users/amed/RxJSNext
> rm -rf dist/es6 && tsc src/Rx.ts --outDir dist/es6 --target ES6 -d
src/operators/switchLatest.ts(25,14): error TS2415: Class 'SwitchLatestSubscriber<T, R>' incorrectly extends base class 'FlatMapSubscriber<T, R>'.
Property 'project' is protected in type 'SwitchLatestSubscriber<T, R>' but public in type 'FlatMapSubscriber<T, …
```
=> Fix TS compiler errors related to SwitchLatestSubscriber

src/Observable.ts, src/operators/filter.ts, src/operators/map.ts, src/util/bindCallback.ts
This should optimize the `.call` attempts on `map` and `filter` so that if the `thisArg` is not supplied, there is no perf hit.
=> Adding thisArg and bindCallback

spec/operators/catch-spec.js, src/Observable.ts, src/Rx.ts, src/operators/catch.ts
Note this implementation adds a second argument of the source observable to catch. See unit tests for details.
=> add catch operator, related to #141, closes #130

spec/operators/toPromise-spec.js, src/Observable.ts, src/Rx.ts, src/operators/toPromise.ts
I didn't add a configuration option yet, because I'm still unsure where we're going to put that. But for now, it's the basic implementation.
It *might* be worth adding a custom `toPromise` method on `ScalarObservable` for performance reasons, but I have my doubts that will be game-changing for anyone.
=> feat(operator): add toPromise operator. closes #159

src/operators/merge.ts
Prevent MergeSubscriber from setting its _isUnsubscribed flag to true before its inner subscriptions have all completed.
=> bugfix(merge)

spec/operators/withLatestFrom-spec.js, src/Observable.ts, src/Rx.ts, src/operators/withLatestFrom.ts
=> feat(operator): add withLatestFrom

spec/operators/timeout-spec.js, spec/operators/timeoutWith-spec.js, src/Observable.ts, src/Rx.ts, src/operators/timeout.ts, src/operators/timeoutWith.ts, src/util/isDate.ts
adds two operators timeout and timeoutWith. The former is for sending errors on timeout
the latter is for continuing with an Observable on timeout.
closes #244
=> feat(operator): add timeout and timeoutWith

spec/observable-spec.js, src/Observable.ts, src/Subscriber.ts
- adds more tests around Observable
- adds some code to assure isUnsubscribed is always boolean in Subscriber
closes #255
=> feat(Observable): add static create method

spec/scheduler-spec.js, spec/subject-spec.js, spec/subjects/behavior-subject-spec.js, src/Scheduler.ts, src/observables/ArrayObservable.ts, src/observables/EmptyObservable.ts, src/observables/ErrorObservable.ts, src/observables/IntervalObservable.ts, src/observables/IteratorObservable.ts, src/observables/PromiseObservable.ts, src/observables/RangeObservable.ts, src/observables/ScalarObservable.ts, src/observables/SubscribeOnObservable.ts, src/observables/TimerObservable.ts, src/operators/bufferTime.ts, src/operators/debounce.ts, src/operators/delay.ts, src/operators/observeOn-support.ts, src/operators/sampleTime.ts, src/operators/throttle.ts, src/operators/timeout.ts, src/operators/timeoutWith.ts, src/operators/windowTime.ts, src/schedulers/ImmediateScheduler.ts, src/schedulers/NextTickScheduler.ts
schedule is now: schedule(work, delay?, state?)
also cleaned up some tests that still used scheduling from the early days when subscription was still async
closes #265
=> refactor(Scheduler): change order of arguments to schedule method

src/observables/PromiseObservable.ts, src/observables/ScalarObservable.ts, src/operators/expand.ts, src/operators/flatMap-support.ts, src/operators/merge-support.ts
- add _isScalar property to Observables that could be scalar
- check for _isScalar rather than instanceof ScalarObservable
- add _isScalar property to PromiseObservable that defaults to false
- set _isScalar property to true when PromiseObservable's promise resolves
- also set the value property of the PromiseObservable
closes #276
=> refactor(Scalar): move to _isScalar from instanceof ScalarObservable

perf/micro/current-thread-scheduler/operators/catch.js, perf/micro/immediate-scheduler/operators/catch.js
The new method isn't polymorphic, and can only be called with a function
```sh
old catch with immediate scheduler x 235,384 ops/sec ±0.64% (94 runs sampled)
new catch with immediate scheduler x 1,621,709 ops/sec ±0.56% (96 runs sampled)
588.96% faster than Rx2
old catch with current thread scheduler x 217,551 ops/sec ±1.02% (94 runs sampled)
new catch with current thread scheduler x 637,311 ops/sec ±0.54% (93 runs sampled)
192.95% faster than Rx2
```
closes #283
=> chore(perf): fix catch micro perf test

CONTRIBUTION.md, README.md
- this is partially pulled from Angular's guidelines, and partially from guidelines
that are specific to this repository.
- Adds performance testing guidelines
- Adds commit message guidelines
- this does NOT including anything we'd still like to pull over from current RxJS Contribution Guidelines
closes #135
=> docs(CONTRIBUTION): add the beginnings of contribution guidelines

spec/operators/switchAll-spec.js, spec/operators/switchLatest-spec.js, src/Observable.ts, src/operators/buffer.ts, src/operators/bufferToggle.ts, src/operators/bufferWhen.ts, src/operators/combineLatest-support.ts, src/operators/expand.ts, src/operators/flatMap-support.ts, src/operators/groupBy.ts, src/operators/merge-support.ts, src/operators/retryWhen.ts, src/operators/sample.ts, src/operators/switchAll.ts, src/operators/switchLatest.ts, src/operators/takeUntil.ts, src/operators/window.ts, src/operators/windowToggle.ts, src/operators/windowWhen.ts, src/operators/withLatestFrom.ts, src/operators/zip-support.ts
Many operators with inner subscriptions were calling `subscribe` when they could
have been calling `_subscribe`, thus avoiding an `instanceof Subscriber` check.
- makes sure `_subscribe` is being called where possible
- cleans up inner subscription handling in a few places
- seperates `switchAll` tests from `switchLatest` tests
closes #290
=> refactor(operators): ensure _subscribe is being called where possible

perf/micro/immediate-scheduler/operators/last-predicate-this.js, perf/micro/immediate-scheduler/operators/last-predicate.js, perf/micro/immediate-scheduler/operators/last.js, spec/operators/last-spec.js, spec/schedulers/TestScheduler-spec.js, src/Observable.ts, src/Rx.ts, src/operators/last.ts, src/schedulers/TestScheduler.ts, src/util/EmptyError.ts
- adds EmptyError error type
- adds ability to group values in marble tests
- adds last operator
closes #304
closes #306
=> feat(operator): add last operator and update marble tests to support grouping

CONTRIBUTION.md, doc/writing-marble-tests.md
Adds information about "marble tests" as well as porting over some guidelines for testing from RxJS 2/3
=> chore(docs): add documentation for marble test syntax

spec/operators/switchAll-spec.js, spec/operators/switchLatest-spec.js, src/operators/switchAll.ts, src/operators/switchLatest.ts
- completely refactors switchLatest to be a standalone implementation
- adds a lot of tests around switch latest
=> refactor(switchLatest): make switchLatest a standalone impl, add virtual time tests

spec/operators/skipUntil-spec.js
Continuing effort to cover #309, plan to tackle case uses actual timer first. Adding more test coverage will be done with separate PR in further.
=> chore(test): use test marbles for skipUntil operator spec

spec/helpers/test-helper.js, spec/observable-spec.js, spec/operators/toPromise-spec.js, src/Observable.ts, src/Rx.ts, src/operators/toPromise.ts
- Adds a minimal global configuration for Promises
- Adds a PromiseCtor optional parameter to `Observable.prototype.forEach`
- Adds some basic tests for `Observable.prototype.forEach`
closes #115
=> feat(config): add global configuration of Promise capability

src/schedulers/TestScheduler.ts
one line of (no, actually couple of) change to align test failure output format between actual vs. expected, 
*Before*
*After*
=> chore(test): format test failure output more aligned

spec/observables/zip-spec.js, src/operators/zip-support.ts
- adds support for never-ending iterables
- adds fast-track for arrays
- adds additional tests for zip
- fixes issues where completion does not happen at the appropriate moment
closes #397
=> feat(zip): zip now supports never-ending iterables

package.json, spec/helpers/test-helper.js, spec/schedulers/TestScheduler-spec.js, spec/schedulers/VirtualTimeScheduler-spec.js, src/CoreOperators.ts, src/Observable.ts, src/Rx.KitchenSink.ts, src/operators/extended/distinctUntilKeyChanged.ts, src/operators/extended/elementAt.ts
- moves non-core operators to entended directory
- adds Rx.KitchenSink module
- removes non-core operators from Rx module
- removes TestScheduler from Rx module
- removes VirtualTimeScheduler from Rx module
- updates tests appropriately
- adds Rx.KitchenSink to es6 build process
- reorganizes operators as they appear in files to be in alphabetical order and separated by static and members
closes #401
=> refactor(Rx): split core from extended operators

perf/micro/immediate-scheduler/operators/find-predicate-this.js, perf/micro/immediate-scheduler/operators/find-predicate.js, perf/micro/immediate-scheduler/operators/findindex-predicate-this.js, perf/micro/immediate-scheduler/operators/findindex-predicate.js, spec/operators/find-spec.js, spec/operators/findindex-spec.js, src/Rx.KitchenSink.ts, src/operators/extended/find-support.ts, src/operators/extended/find.ts, src/operators/extended/findIndex.ts
- add find, findIndex operator
- add SingleValueSubscriber for common behavior to notify and complete
immediately
Continue effort to add operator exists in current RxJS.
In document of [`findIndex`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/findindex.md), return value is `undefined` if there isn't matching element
>... defined by the specified predicate, if found; otherwise, undefined.
while example, and actual code returns `-1` instead. This PR follows existing code behaviors to return `-1`.
One of common pattern of subscriber is let subscriber notify and complete immediately, usually related with operators using predicate like `find`, `findIndex`, `isEmpty`, `single`, `last`, and others not yet implemented. `SingleValueSubscriber` exposes …
=> feat(operator): add find, findIndex operator

spec/operators/first-spec.js, spec/operators/last-spec.js, src/CoreOperators.ts, src/operators/first.ts, src/operators/last.ts
Just what it says. This was primarily for
1. to enable a user to use `first` to select an `index` if they so choose, effectively replacing `findIndex` as any sort of need in CoreOperators.
2. Consistency, so that `first` and `last` have identical signatures...
To be bikeshedded: 
- the usefulness of the `thisArg`
- argument order
=> Add resultSelector argument to both `first` and `last` operators

perf/micro/immediate-scheduler/operators/share.js, perf/micro/index.js, spec/operators/share-spec.js, src/CoreOperators.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/operators/share.ts
=> feat(share): add the share operator

perf/micro/immediate-scheduler/operators/share-replay.js, spec/operators/shareReplay-spec.js, src/CoreOperators.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/operators/shareReplay.ts
Add shareReplay() as a core operator. Vaguely relates to issue #439 and issue #298.
=> feat(shareReplay): add the shareReplay() operator

spec/operators/merge-map-spec.js, src/schedulers/VirtualTimeScheduler.ts, src/testing/ColdObservable.ts, src/testing/TestScheduler.ts
- fixes an issue where actual results were being sorted when they should not have been
- ensures rescheduled Actions will be added to subscription and torn down when appropriate
- uses state to convey notification information to action work function rather than closure
closes #422
=> fix(TestScheduler): stop sorting actual results

spec/subject-spec.js, src/Observable.ts, src/Subject.ts
Calling `Subject.create` with an `Observable` that had never had an operator applied to it resulted in this error. This was because it called `Observable.prototype._subscribe` internally, and that method assumed there was an operator instance in `this.operator`, which in that case there would not have been.
This fix adds a check to see if there's an operator or not, and just uses the original subscriber if there isn't one.
This seems like a case for any subclassed observables that call `super._subscribe`, prior to having any operators applied.
=> Subject.create fix

spec/helpers/test-helper.js, spec/operators/bufferWhen-spec.js, spec/operators/windowTime-spec.js, spec/operators/windowToggle-spec.js, spec/operators/windowWhen-spec.js, spec/scheduler-spec.js
Started removing more timer-based tests.
- updates tests for `bufferWhen` to more of a full-suite of marble tests.
- fixes `windowWhen` to use marble tests
ATTENTION @staltz ... the windowWhen tests will interest you. We can probably weaponize that approach into something you can use for `groupBy`.
=> Faster tests

spec/operators/map-to-spec.js
add tests from `map()` that makes sense to `mapTo()`.
relates to #389.
=> test(mapTo): add new test cases

package.json, perf/micro/immediate-scheduler/operators/count-scalar.js, perf/micro/immediate-scheduler/operators/count.js, perf/micro/immediate-scheduler/operators/filter-scalar-false.js, perf/micro/immediate-scheduler/operators/filter-scalar-true.js, perf/micro/immediate-scheduler/operators/map-scalar.js, perf/micro/immediate-scheduler/operators/reduce-scalar-noseed.js, perf/micro/immediate-scheduler/operators/reduce-scalar.js, perf/micro/immediate-scheduler/operators/scan-scalar-noseed.js, perf/micro/immediate-scheduler/operators/skip-scalar-0.js, perf/micro/immediate-scheduler/operators/skip-scalar-outofbounds.js, perf/micro/immediate-scheduler/operators/take-scalar.js, spec/observables/ScalarObservable-spec.js, spec/operators/retry-spec.js, src/observables/ScalarObservable.ts
Adding a bunch of overrides to ScalarObservable to optimize performance. This is an approach different than what we've done in the past, in that it puts an override directly on ScalarObservable, rather than doing type-checking in the functions themselves.
Here is a list of results (Before and After):
```
Before
|                     RxJS 4.0.1 |             RxJS 5.0.0-alpha.3 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
filter-scalar-false - immediate |               717,228 (±1.17%) |             1,516,863 (±0.45%) |           2.11x |          111.5%
filter-scalar-true - immediate |               524,921 (±0.62%) |               966,993 (±0.65%) | …
```
=> Scalar perf

spec/operators/skipUntil-spec.js, src/Subscriber.ts, src/operators/skipUntil.ts
=> skipUntil: fixes and tests

src/util/Immediate.ts
=> fix(Immediate): set immediate should no longer throw in Chrome

perf/micro/current-thread-scheduler/operators/concatall.js, perf/micro/immediate-scheduler/operators/concatall.js
The `concatAll` benchmarks had the same issues as `mergeAll` (see #670).
=> chore(concatall): fix concatall perf benchmarks

README.md
Clarify instructions on how to install this library using npm 3 or npm 2.
Avoids issues such as #727 from happening.
=> docs(README.md): clarify npm install instructions

package.json
- closure compiler will target ES5, suppress ES3 specific warnings
closes #692 
This PR changes closure compiler build targets, now all builds are targeting ES5+ as minimum supported runtime.
=> chore(package.json): target closure compiler to ES5

spec/observables/fromEvent-spec.js, spec/operators/bufferWhen-spec.js
Originated from https://github.com/ReactiveX/RxJS/pull/729#issuecomment-156780408 , with some of async test observables are not unsubscribed after test case is completed. 
In most cases it'll be harmless but would be better to unsubscribe it explicitly.
@staltz , would like to ask opinions tests for `bufferWhen`, if this revise would be legit or there should be better way to handle it.
=> fix(test): make explicit unsubscription for observable

spec/observables/combineLatest-spec.js, spec/operators/combineLatest-spec.js, src/Observable.ts, src/operators/combineLatest-static.ts, src/operators/combineLatest.ts
closes #594
Applies same mechanics of `forkJoin` to support array of observables, to close issue.
=> feat(combineLatest): accept array of observable as parameter

src/Notification.ts
Minor type definition updates for `notification` to allow `error` parameter to be optional.
=> refactor(Notification): update type definition for Notification

src/operators/expand-support.ts
relates to #766 
Partially resolves expand operator behavior by adding recursive call terminating condition. Still inifnite expand causes stack overflow though.
Feeling this might not be best way to solve issue, any suggestions would be gladly welcome.
=> fix(expand): terminate recursive call when destination completes

spec/helpers/test-helper.js
This has been annoying me for a while, every time I tried to use `fit()` to run just one Jasmine test for debugging, it didn't work because we are monkey patching `it()`. So this PR just does the same monkey patching for `fit()`.
=> chore(spec): add support for Jasmine focused specs (fit())

src/Observable.ts
- make Promistctor parameter as optional in type definition
closes #864
=> refactor(toPromise): update type definition for toPromise

.make-packages.js
This change makes sure the README.md and LICENSE.txt files are
included in the CJS and ES6 distributions. The change also
removes all scripts from the npm package, since no scripts are
expectd to be run when installed by end-users.
Fixes #845
=> fix(publish): copy readme and license, remove scripts

spec/operators/publishLast-spec.js, src/CoreOperators.ts, src/Observable.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/add/operator/publishLast.ts, src/operator/publishLast.ts
closes #883
This PR adds `publishLast` operator with initial test coverage, mostly mirrored from `publish` operator's test cases.
=> feat(publishLast): add publishLast operator

.markdown-doctest-setup.js, README.md
In order to avoid having to update the config for this style of operator in future, I think I will add the ability to specify a fallback require function for `markdown-doctest`, so that we can handle this automatically.
Happy to note that it did catch a legitimate error :smile:
=> docs(README): Update markdown-doctest config and fix import typo

spec/observable-spec.js, spec/subject-spec.js, spec/subscriber-spec.js, spec/symbol/rxSubscriber-spec.js, spec/util/SymbolShim-spec.js, src/Observable.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/Subject.ts, src/Subscriber.ts, src/symbol/rxSubscriber.ts, src/util/SymbolShim.ts
Add an `rxSubscriber` symbol that can be used to designate any object as "safe" to use an an Rx Subscriber (sort of)...
The idea is basically this: If any object has `Rx.Symbol.rxSubscriber` implemented as a function, that function is expected to return an `Rx.Subscriber`. This allows Rx to shortcut the wrapping of observers (such as Subjects and the like) by calling this method and using what it returns instead.
It seems like a more flexible solution for this scenario than other solutions.
Other work done:
- Refactored SymbolShim (almost completely) to include a `for` method on the polyfill.
- Added `rxSubscriber` to both `Rx` and `Rx.KitchenSink` output
- Tests
=> Add rxSubscriber symbol

spec/operators/switchFirstMap-spec.js, src/Observable.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/add/operator/switchFirstMap.ts, src/add/operator/switchMapFirst.ts, src/operator/switchFirstMap.ts
Renaming `switchMapFirst` to `switchFirstMap` to match the naming scheme of `<mergingStrategy>Map`
related #915
=> feat(switchFirstMap): rename switchMapFirst to switchFirstMap

package.json
closes #465
Long awaited changes are finally landed in dev version of tslint, bump up dependency version to close opened issue.
=> chore(package.json): bump up tslint dependency version

spec/observable-spec.js, spec/operators/skipWhile-spec.js, src/CoreOperators.ts, src/Observable.ts, src/operator/skipWhile.ts
- removes `thisArgs` from `skipWhile`
- adds `thisArgs` to `forEach`
- removes some `thisArgs` cruft from `CoreOperators` interface.
- eliminates some closure in the `forEach` method
=> Updates for thisArgs issue

spec/util/SymbolShim-spec.js, src/util/SymbolShim.ts
In some engines, Symbol exists but does not impelment the for method.
fixes #999
=> fix(SymbolShim): ensure for function even if Symbol already exists

spec/operators/buffer-spec.js, spec/operators/concat-spec.js, spec/operators/concatAll-spec.js
Remove duplicate tests related to verifying unsubscription chains not broken, on buffer-spec,
concat-spec, and concatAll-spec.
=> test(operators): remove duplicate tests for buffer, concat, concatAll

src/operator/debounceTime.ts
due to current null check, debounceTime does not allow value
to be `undefined`. This change updates behavior to align behavior
as same as RxJS4 does.
closes #1081
=> fix(debounceTime): align value emit behavior as same as RxJS4

src/Rx.ts
First of all, getting started with this library in a typescript project is really easy. However, I found that adding custom operators is kind of annoying now. The Observable.lift() method is publicly exposed as I would expect, but its parameter is an Operator. Since that's not directly exposed by Rx.ts, it feels needlessly hard to implement your own operators. I read the part on the wiki about defining operators ([here](https://github.com/ReactiveX/RxJS/blob/master/doc/operator-creation.md)), but it seems needlessly convoluted to me. 
I would expect to be able to do this:
```TypeScript
import {Operator,Subscriber} from "@reactivex/rxjs";
export class MyOperator<T, R> implements Operator<T, R> {
call<T, R>(subscriber: Subscriber<T>): Subscriber<T> {
return new MySubscriber(subscriber);
}
} …
```
=> feat(Operator): Expose the Operator interface to library consumers

package.json, spec/helpers/ajax-helper.js, spec/observables/dom/ajax-spec.js, src/observable/dom/ajax.ts
- ensures body being sent properly.
- ensures proper content-type by default
- readds body url-formdata serialization
- ensures response JSON.parsed at proper time
- Adds proper XMLHttpRequest mock and removes jasmine-ajax
- fixes a variety of false positive tests from jasmine-ajax
- removes `create2` static method, which was cruft
=> More ajax fixes

spec/observables/dom/ajax-spec.js, src/observable/dom/ajax.ts
@trxcllnt discovered an issue with accessing both response and responseText in Chrome if responseType was set
I copy-pastad his code in the name of speed with his blessing. I <3 Paul
Related: #1154
=> fix(ajax): response properly based off responseType

.eslintrc, spec/Observable-spec.js, spec/operators/retry-spec.js, src/Observable.ts
There are a few merge errors fixed in here as well. 
This introduces some closure in the forEach implementation, but I'm not super concerned about it for now.
=> fix forEach: nextHandler errors will reject returned Promise.

src/util/ArgumentOutOfRangeError.ts, src/util/EmptyError.ts
This PR aligns derived object extends `Error`, removes inconsistency when error is thrown on some browser.
=> refactor(Error): let derived error objects extends error

karma.conf.js, wallaby.js
This PR updates karma configuration to let browser test have more sufficient to not to be disconnected while test is running. Test disconnection usually occurs on VM based test (IOS, etcs).
=> chore(test): update karma, wallaby configuration

src/Observable.ts, src/operator/race-static.ts, src/operator/race-support.ts, src/operator/race.ts
- Clearfy `race()`'s type definition.
- See also [RxJS v4's one](https://github.com/Reactive-Extensions/RxJS/blob/master/ts/core/linq/observable/amb.ts)
- ...And some micro refactoring
=> refactor(race): Make Type paramerter more compatible with RxJS v4

src/operator/mergeMap.ts
- `MergeMapSubscriber.buffer` should be `T[]` (`Array<T>`) because it is given a source value `T`.
- The type of 1st argument of `MergeMapSubscriber._innerSub` should be `Observable<R>` because the result of `MergeMapSubscriber.project` will be passed to it.
=> fix(MergeMapSubscriber): clearfy type definitions for MergeMapSubscriber's members

src/observable/FromEventObservable.ts
This makes the type definition more compatible with [RxJS v4](https://github.com/Reactive-Extensions/RxJS/blob/8f12f812d497acf639588e90f74d504a9fc801ec/ts/core/linq/observable/fromevent.ts)
=> refactor(fromEvent): clearfy the type definition of Observable.fromEvent()

spec/Subscription-spec.js, src/Rx.DOM.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/Subscription.ts
Relates to discussion in #1256 
Basically this adds a context that is passed around internally that collects all errors and throws them as a group in an `UnsubscriptionError` when the subscription tree is unsubscribed completely.
=> Fix leaks when unsubscribe functions error

src/operator/exhaustMap.ts
Before:
```
|     RxJS 4.0.7 | RxJS 5.0.0-beta.1 | factor | % improved
----------------------------------------------------------------------------------
exhaustMap - immediate | 1,449 (±0.95%) |   17,023 (±0.88%) | 11.75x |   1,075.1%
exhaustMap | 4,732 (±0.34%) |   80,795 (±0.38%) | 17.07x |   1,607.4%
```
After:
```
|     RxJS 4.0.7 | RxJS 5.0.0-beta.1 | factor | % improved
----------------------------------------------------------------------------------
exhaustMap - immediate | 1,452 (±1.14%) |   18,523 (±0.68%) | 12.76x |   1,175.5%
exhaustMap | 4,941 (±0.29%) |   87,146 (±0.39%) | 17.64x |   1,663.8%
```
=> perf(exhaustMap): remove tryCatch/errorObject (~10% improvement)

src/Notification.ts, src/Observable.ts, src/Observer.ts, src/Subscriber.ts, src/operator/mergeMapTo.ts, src/operator/observeOn.ts, src/operator/zip.ts, src/util/toSubscriber.ts
- caveat is that there is no way to require \_at least one\_ method on Observer in TypeScript, at least that I can find
related #1260
=> fix(Observer): observer interface now allows partial Observers

MIGRATION.md
This PR updates migration guide to includes delay operator splits.
=> docs(MIGRATION): update operator split for delayWhen

src/observable/ConnectableObservable.ts, src/observable/dom/WebSocketSubject.ts
- `ConnectableObservable<T>`'s members may be overridden by user. So this change make them `protected` for extensibility.
- `RefCountSubscriber<T>_resetConnectable()` belongs to ``RefCountSubscriber<T>` which is private class in ConnectableObservable.ts. So this change make it `private`.
- To protect unexpected modifying `ConnectableObservable<T>.subject/subscription` from others, this change make them `protected` and add `_closeSubscription()` for  `ConnectableSubscription`
=> refactor(ConnectableObservable): hide ConnectableObservable's members from public

perf/micro/current-thread-scheduler/operators/takewhile.js, perf/micro/immediate-scheduler/operators/takewhile.js, src/operator/takeWhile.ts
Before:
```
|      RxJS 4.0.7 | RxJS 5.0.0-beta.1 | factor | % improved
----------------------------------------------------------------------------------
takewhile - immediate | 22,885 (±1.53%) |   17,473 (±0.38%) |  0.76x |     -23.6%
takewhile |  7,270 (±2.49%) |   14,739 (±0.58%) |  2.03x |     102.7%
```
After:
```
|      RxJS 4.0.7 | RxJS 5.0.0-beta.1 | factor | % improved
----------------------- ----------------------------------------------------------
takewhile - immediate | 21,872 (±1.02%) |  114,560 (±0.39%) |  5.24x |     423.8%
takewhile |  7,197 (±1.19%) |   93,207 (±1.85%) | 12.95x |   1,195.0%
```
=> perf(takeWhile): remove tryCatch/errorObject (~6x improvement)

perf/micro/current-thread-scheduler/operators/throttle.js, perf/micro/immediate-scheduler/operators/throttle.js, src/operator/throttle.ts
- This change is same kind of #1251.
- I have not benchmarked this yet. So this is purely refactoring to unify code style.
- The current codebase does not have any benchmark about `throttle()`.
- `throttle()` suppress the value traffic. How do we benchmark this without a throughput benchmark?
=> refactor(throttle): remove tryCatch/errorObject

spec/operators/cache-spec.js, src/Observable.ts, src/Rx.ts, src/add/operator/cache.ts, src/operator/cache.ts, src/subject/ReplaySubject.ts
The `cache` operator is effectively `publishReplay` and `refCount`.
The main reasons it's not named `shareReplay`:
1. "`share`" no longer means "publishTypeX + refCount" in RxJS 5. It's not publish().refCount() it's a replayable refCounted observable. So `shareReplay` doesn't make sense, as this has little to do with `share`.
2. `cache` is more terse and descriptive to the general user. What does it do? It caches values. Does it share a replay? sure. Will new users ever search for that... probably not? Debatable.
Bike shedding is bike shedding. I think it's cleaner.
(ATTN: @staltz ... I think there's probably a better way to write the tests than what I did)
=> feat(cache): add cache operator

src/operator/expand.ts
This was removed because it was redundant and it could cause errors, but I was unable to
produce any, I think because of the nature of the operator.
As mentioned by @trxcllnt in #1315
=> refactor(expand): remove superfluous _isScalar check

spec/operators/do-spec.js, src/operator/do.ts
Presently, if you pass a Subject as the Observer to the `do` operator, this error happens when the Observable emits:
```
Object #<DoSubscriber> has no method 'throwIfUnsubscribed
```
:(
This PR uses the `SafeSubscriber` internals to call the `do` Observer in the right context.
=> fix(do): fix do operator to invoke observer message handlers in the right context.

README.md
I also recommend adding a link to the docs in the project description (can only be done by the admin)
> A reactive programming library for JavaScript http://reactivex.io/RxJS/
=> Add ReactiveX docs link to README

src/Rx.KitchenSink.ts
- export Operator as same as Rx core does
Found kitchenSink does not exports operator, amending quickly.
=> chore(KitchenSink): export Operator

karma.conf.js
Some of browsers are continuously fail to start without helpful log to triage from selenium side, blocking those temporarily for now. Once got more clues and resolution, will followup with separate PR to enable those again.
>[60.165][INFO]: RESPONSE InitSession unknown error: Chrome failed to start: exited abnormally
=> chore(test): disable some of browser test

src/CoreOperators.ts, src/Observable.ts, src/Rx.KitchenSink.ts, src/add/operator/mergeMap.ts, src/add/operator/mergeMapTo.ts, src/observable/BoundNodeCallbackObservable.ts, src/observable/FromObservable.ts, src/observable/dom/WebSocketSubject.ts, src/operator/combineAll.ts, src/operator/concat.ts, src/operator/concatAll.ts, src/operator/concatMap.ts, src/operator/concatMapTo.ts, src/operator/exhaust.ts, src/operator/exhaustMap.ts, src/operator/map.ts, src/operator/mapTo.ts, src/operator/merge.ts, src/operator/mergeAll.ts, src/operator/mergeMap.ts, src/operator/mergeMapTo.ts, src/operator/race.ts, src/operator/switch.ts, src/operator/switchMap.ts, src/operator/switchMapTo.ts, src/operator/zipAll.ts
also adds signatures for the "All", "Map", and "MapTo" variants.
=> chore(typings): added type signatures for concat/exhaust/merge/switch

spec/operators/takeLast-spec.ts, src/operator/takeLast.ts
closes #1407 
This PR tries to fix behavior of `takeLast` by changing ring buffer indexing routines. Maybe I miss something, but so far it looks work correctly.
/cc @staltz for visibility.
=> fix(takeLast): fix takeLast behavior to emit correct order

doc/asset/devtools-welcome.js, doc/index.md, esdoc.json, package.json
Add Rx.umd.js script to the ESDoc-generated page, so RxJS can be experimented in the DevTools. Also add a welcome message in the console, and a hint text in index.md.
To see this page live, open http://rxjs5-esdoc-rxjs-playground.surge.sh/
=> docs(esdoc): add playground environment in ESDoc-generated page

spec/observables/interval-spec.ts, src/Rx.DOM.ts, src/Rx.KitchenSink.ts, src/Rx.ts, src/observable/IntervalObservable.ts, src/observable/TimerObservable.ts, src/operator/bufferTime.ts, src/operator/debounceTime.ts, src/operator/delay.ts, src/operator/inspectTime.ts, src/operator/sampleTime.ts, src/operator/throttleTime.ts, src/operator/timeInterval.ts, src/operator/timeout.ts, src/operator/timeoutWith.ts, src/operator/windowTime.ts, src/scheduler/AsyncScheduler.ts, src/scheduler/FutureAction.ts, src/scheduler/async.ts
Adds `Scheduler.async` which will always schedule an action to happen in the future. Fixes #1339. Updates `FutureAction` to use `setInterval` instead of repeated `setTimeout` calls as discussed with @mattpodwysocki in #1391.
=> feat(async): adds AsyncScheduler and updates appropriate operators.

package.json
Tiny PR. :baby: :baby_bottle: 
use postinstall hook, not preinstall hook, to run typings install.
This was important because `typings install` cannot be run before `typings` itself is installed (and I don't have it installed globally. Also Travis won't have), otherwise we get this error:
```
$ RxJSNext (master) npm install
> @reactivex/rxjs@5.0.0-beta.2 preinstall /Users/amed/Development/RxJSNext
> typings install
sh: typings: command not found
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/amed/.nvm/versions/node/v4.2.2/bin/node" "/Users/amed/.nvm/versions/node/v4.2.2/bin/npm" "i"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @reactivex/rxjs@5.0.0-beta.2 preinstall: `typings install`
npm ERR! spawn …
```
=> fix(package.json): install typings only after packages are installed

package.json, spec/observables/if-spec.ts, src/Observable.ts, src/Rx.KitchenSink.ts, src/add/observable/if.ts, src/observable/IfObservable.ts
=> feat(if): add static Observable.if creation operator.

package.json
This PR's minor correction to dependency version bump, to not to use specific version of RxJS 4 but to use latest.
=> chore(package.json): correct RxJS 4 dependency

package.json
There isn't provided way to override `install` script itself (and strongly not recommended), have to rely on lifecycle scripts. `prepublish` is more appropriate lifecycle hook for this issue (https://docs.npmjs.com/misc/scripts) which expected to be triggered after local dev system's `install`. though name's somewhat not clear, `prepublish` is expected to chained after `npm install` (parameterless install) (https://github.com/npm/npm/issues/3059#issuecomment-12282746)
closes #1504
=> chore(package.json): change typing update script execution lifecycle

package.json
This PR removes redundant `postInstall` script after https://github.com/ReactiveX/rxjs/pull/1509 is introduced.
=> chore(package.json): remove redundant script

package.json
This PR makes `build_test` explicitly clean up existing test case build, to avoid possible confusions such as switching branches, etcs. Individual command chain (npm run build && ...) will allows to work with preserved test build.
=> chore(package.json): build_test cleans up existing test cases

spec/helpers/test-helper.ts, spec/operators/publish-spec.ts
We had a couple of tests that *should* have been erroring for months. This a disturbing part of Jasmine, but when you added an arbitrary number of tests to our testing suite, then suddenly some of our tests would fail with `ObjectUnsubscribedError`. 
Work done:
1. Added about 100 tests that were just `expect(1).toBe(1)` inside of them until I saw the errors happening.
2. Verified, empirically, that there were no timing errors where the global `rxTestScheduler` was being used/trampled by multiple tests.
3. Removed unnecessary `setTimeout` calls from test helpers and added an additional assurance that `rxTestScheduler` was being cleared at the end of the test.
4. Fixed two tests that *should* have been throwing errors this entire time, to assert the expected errors rather than just throw. …
=> Fix a few tests

src/Observable.ts, src/Subject.ts, src/Subscription.ts, src/observable/ArrayLikeObservable.ts, src/observable/ArrayObservable.ts, src/observable/EmptyObservable.ts, src/observable/ErrorObservable.ts, src/observable/IfObservable.ts, src/observable/IteratorObservable.ts, src/observable/PromiseObservable.ts, src/observable/RangeObservable.ts, src/observable/ScalarObservable.ts, src/observable/TimerObservable.ts, src/observable/UsingObservable.ts, src/observable/dom/AjaxObservable.ts, src/subject/AsyncSubject.ts, src/subject/BehaviorSubject.ts, src/subject/ReplaySubject.ts, src/testing/HotObservable.ts
- Updates the types around `Subscription`.
- Adds an `AnonymousSubscription` that will fit any duck-typed subscription
- Adds an `ISubscription` that will fit any composite-subscription (generally this was added to reduce structural surface area for type checking)
- `Subscription.prototype.add` now returns a reference to any `Subscription` it creates internally, so it can be used to `remove` the subscription.
#1532 is related, in part, because this is a step in the right direction.
This also relates to @saneyuki's PR here #1521
=> Subscription refactor: Part 1

spec/helpers/testScheduler-ui.ts
different to jasmine, mocha's async callback requires `Error` object explicitly. This PR updates custom interface bit to allow to throw any object (i.e `throw 'bad';`) by wrap into error object.
p.s : in case of explicit call to async callback, it's still requires to deliver error object.
=> chore(test): allow to throw non error object

perf/micro/current-thread-scheduler/observable/defer.js, perf/micro/immediate-scheduler/observable/defer.js, src/observable/DeferObservable.ts
This is the benchmark result on Node v5.9.0,
MacBook Pro (Retina, 15-inch, Mid 2014, 2.8 GHz Intel Core i7, 16 GB 1600 MHz DDR3).
```
|                     RxJS 4.1.0 |              RxJS 5.0.0-beta.3 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
defer - immediate |             1,117,475 (±1.08%) |             1,979,565 (±1.09%) |           1.77x |           77.1%
defer |               905,413 (±1.15%) |             1,187,348 (±1.42%) |           1.31x |           31.1%
```
```
|                     RxJS 4.1.0 |              RxJS 5.0.0-beta.3 |          factor |      % improved
------------------------------------------------------------------------------ …
```
=> chore(DeferObservable): add benchmarks & minor perf

package.json
This PR removes override to `npm install` script which causes implicit installation of typings on repository.
relates to #1580
=> chore(package.json): remove override to install script

doc/observable.md
I'm not sure I made correct changes, but it definitely feels like something is missing in current docs here:
> Each call to observable.subscribe triggers its own **independent for** that given Observer.
It seems like a word belongs after "independent", but I'm not sure what, so I just suggested "setup".
And for this one:
> This shows how **a subscribe calls are** not at all shared among multiple Observers of the same Observable.
My removal of "a" is fixing a typo, but my removal of "at all" is just simplification. I see why you might want to keep it for emphasis.
=> docs(Observable): fix typos

doc/introduction.md, doc/styles/main.css
Fix CSS property of the brightness of the Github logo, to make it white,
and fix typo lodash => Lodash.
#1597
=> docs(page): fix tiny CSS issue and typo

spec/operators/finally-spec.ts, src/operator/finally.ts
- Adds additional, virtually scheduled tests to the finally battery of tests. Covers basic usage.
- Renames `finallySelector` as just `callback`, because it doesn't really "select" anything.
=> Improve finally tests

src/operator/finally.ts
This PR updates interface definition for `finally` to properly pass source observable's type.
- pass type of source observable
closes #1672
=> chore(typings): update type definition for finally

src/operator/catch.ts
This allows catch to flow it's types by default, but also allows for additional casting if needed.
#1672
=> chore(typings): updated catch signature to allow T to flow through

README.md
The default on npmcdn is to redirect to the latest version. The previous link 404s.
=> Fix npmcdn link

MIGRATION.md
Was added in #1679 but MIGRATION guide still listed it as excluded from v5.
Cc/ @kwonoj
=> docs(MIGRATION): onErrorResumeNext was added to v5

spec/Subject-spec.ts, spec/Subscriber-spec.ts, spec/operators/cache-spec.ts, spec/operators/do-spec.ts, spec/operators/groupBy-spec.ts, spec/operators/multicast-spec.ts, spec/operators/publish-spec.ts, spec/operators/publishBehavior-spec.ts, spec/operators/publishReplay-spec.ts, spec/subjects/BehaviorSubject-spec.ts, spec/subjects/ReplaySubject-spec.ts, src/AsyncSubject.ts, src/BehaviorSubject.ts, src/Observable.ts, src/ReplaySubject.ts, src/Subject.ts, src/SubjectSubscription.ts, src/Subscriber.ts, src/Subscription.ts, src/observable/ConnectableObservable.ts, src/observable/dom/WebSocketSubject.ts, src/operator/groupBy.ts, src/testing/HotObservable.ts, src/util/toSubscriber.ts
This is a rewrite of Subjects for RxJS 5 with the following effects:
- Better align with RxJS 4 behaviors around disposal and when ObjectUnsubscribedError is thrown
- Cleans up Subject implementation and separates out AnonymousSubject as a different class.
- This is prep work for a few fixes in ConnectableObservable.
This is a big set of changes. Breaking changes are listed in the commit.
Attn: @trxcllnt @mattpodwysocki @staltz @kwonoj @jayphelps
=> BIG: Subject rewrite

spec/observables/combineLatest-spec.ts, spec/observables/forkJoin-spec.ts, spec/observables/zip-spec.ts, src/observable/ForkJoinObservable.ts, src/observable/combineLatest.ts, src/operator/zip.ts
I noticed a few ergonomic issues with using `combineLatest` and `zip`. The single tuple type doesn't really make much sense, plus it conflicts with sending in an array value.
Also added typings for `forkJoin` as it's fairly similar to `combineLatest` in shape (obviously the behaviors are different).
=> Improved typings for combineLatestStatic, forkJoin and zipStatic

spec/operators/window-spec.ts, spec/operators/windowCount-spec.ts, spec/operators/windowTime-spec.ts, spec/operators/windowWhen-spec.ts, src/operator/window.ts, src/operator/windowCount.ts, src/operator/windowTime.ts, src/operator/windowWhen.ts
This PR removes behavior in the window operators that tracked the window Subjects as Subscriptions. This could lead to race conditions where the Subscriber unsubscribes while the window operator is still active and attempting to send messages to the windows.
#1698
=> fix(window): don't track internal window subjects as subscriptions.

src/observable/FromEventPatternObservable.ts
There is no perf regression.
This is the benchmark result on Node v5.6.0,
MacBook Air (13-inch, Mid 2012, 1.8 GHz Intel Core i5, 8 GB 1600 MHz DDR3).
```
|                     RxJS 4.0.7 |              RxJS 5.0.0-beta.2 |          factor |      % improved
---------------------------------------------------------------------------------------------------------------------------------------------------
fromeventpattern - immediate |               148,483 (±1.75%) |               347,956 (±2.42%) |           2.34x |          134.3%
```
```
|                     RxJS 4.0.7 |              RxJS 5.0.0-beta.2 |          factor |      % improved
--------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> refactor(FromEventPatternObservable): remove to use tryCatch

src/observable/BoundCallbackObservable.ts, src/observable/FromEventObservable.ts, src/operator/zip.ts
This fixes two of the compiler errors that are issues with the `vNext` version of TypeScript (currently named 1.9, soon to be 2.0 I believe).
The third error is a compiler issue, so I have made no changes to `FromEventObservable`.
#1697
=> chore(typings): fixed compiler errors when using @next version of typescript

spec/observables/dom/webSocket-spec.ts
Hello
This PR contains a test for the issue #1466 - WebSocketSubject cannot be retried. It looks, that the issue does no longer exists since beta 8. Because I want to fix it and I started my work with a test, I'm able to submit the test with this PR ;-)
On branch 5.0.0-beta.6 and 5.0.0-beta.7 the test fails with an "ObjectUnsubscribedError".
If something needs to be changed, let me know.
Finally I have to say thanks for the great work - its damn impressive!
=> Test for issues 1466

doc/external-references.md, esdoc.json
Add an external resources section to reactivex.io. The current docs are still a work in progress, but there are already many great resources for people interested in learning RxJS. 
Most of the links are directly copied over from the old repository and I haven't had time to go through them all. I figure that if they seemed at least somewhat relevant then they could be kept but I am open to adding or removing any that are no longer appropriate or that I missed, respectively.
closes #1666
=> docs(Manual): add external resources section

src/operator/zip.ts
- Add the case for ~T9 type parameters which are defined in v4
- https://github.com/Reactive-Extensions/RxJS/blob/9d6ea94244c2f40a29373f9ed6b12d951d3f2238/ts/core/linq/observable/zip.ts
- Restrict cases which accepts arrays as the 1st argument of `zip()`
- From `any` to `T`.
- As my thought, It would be rare case to pass multiple types with stuffing into an array.
=> chore(typings): increase zip's signature compatibility with v4

src/observable/combineLatest.ts, src/operator/combineLatest.ts
- retry #1626
- Add the case for ~`T9` type parameters which are defined in v4
- https://github.com/Reactive-Extensions/RxJS/blob/9d6ea94244c2f40a29373f9ed6b12d951d3f2238/ts/core/linq/observable/combinelatestproto.ts
- https://github.com/Reactive-Extensions/RxJS/blob/9d6ea94244c2f40a29373f9ed6b12d951d3f2238/ts/core/linq/observable/combinelatest.ts
- Restrict cases which accepts arrays as the 1st argument of `combineLatest()`
- From `any` to `T`.
- As my thought, It would be rare case to pass multiple types with stuffing into an array.
=> chore(typings): increase combineLatest's signature compatibility with v4

src/operator/mergeMap.ts
This just intends to clarify & make strictly types.
=> refactor(MergeMap): clarify any types which are used in MergeMapSubscriber

doc/observable.md, doc/operators.md, doc/subject.md
Motivation:
First of all I would like to say bravo on the docs. It's a lot more user friendly than what I recall from v4. The language is more accessible and api generally easier to navigate. This pull request attempts to smooth some rough edges in an attempt to keep the barrier of entry low, so that people like me--very much on the beginner's end of Rx--don't feel overwhelmed or trip on some confusing sentences. 
Notes: 
- Moved placement of adjectives / adverbs to be more typically "English"
ex: `Multiply by 10 this value` -> `Multiply this value by 10`
- Instances of `just`, `simply`, `obviously` don't usually add quality (they can, but not usually), and often give a condescending tone. It's safer to remove them I believe.
- "Four core Observable concerns": `subscribe` …
=> docs(manual): simplify language, improve flow

spec/operators/cache-spec.ts, src/operator/cache.ts
This is an initial pass at fixing the cache operator. There is still a lot to do, but this is merge-worthy IMO. Ideally, the cache operator would use the lift mechanism. Also this is not well optimized as it is introducing a lot of closures. But it works, and that's the point for now.
fixes #1628
=> fix(cache): get correct caching behavior

src/operator/mergeMapTo.ts
This just intends to clarify & make strictly types.
=> refactor(MergeMapTo): clarify 'any' types in MergeMapToSubscriber

.gitignore, package.json, src/Observable.ts, src/Rx.ts, src/observable/FromObservable.ts, src/util/subscribeToResult.ts, tools/make-system-bundle.js
with my :heart: to @blesh ...
- bump up `symbol-observable@1`
- bump up `systemjs-builder@latest` with updating breaking change to its api
#1766 
I've created this PR only for demonstrating based on #1766 , so feel freely close this after updating original one. 
One thing I'm not sure is how to verify sanity of systemjs build with updated scripts.. /cc @robwormald  also.
=> refactor(symbol-observable): bump up symbol-observable@1

spec/operators/multicast-spec.ts, spec/operators/publish-spec.ts, spec/support/debug.opts, src/observable/MulticastObservable.ts, src/operator/multicast.ts
Multicast with a selector function should create a new ConnectableObservable for each subscriber to
the MulticastObservable. This ensures each subscriber creates a new connection to the source
Observable, and don't share subscription side-effects.
Multicast with selector now matches Rx4's behavior.
=> fix(multicast): Fixes multicast with selector to create a new source connection per subscriber.

spec/helpers/ajax-helper.ts, spec/observables/dom/ajax-spec.ts, spec/support/default.opts, src/observable/dom/AjaxObservable.ts
This PR updates `AjaxRequest` accepts `withCredentials` flag to be used when create CORS request by setting `crossDomain`, replicating [RXJS-DOM] (https://github.com/Reactive-Extensions/RxJS-DOM/blob/35271e7ddd7e68838d181beae3cee696b657f7f4/src/ajax/ajax.js#L214) implementation.
closes #1732, #1711
=> fix(AjaxObservable): support withCredentials for CORS request

spec/operators/bufferTime-spec.ts, src/operator/bufferTime.ts
This PR updates behaviors of `openContext` and `closeContext`, do not try to update if contexts are cleared by synchronous unsubscription right after emitting value (i.e, `take`).
closes #1763
=> fix(bufferTime): handle closing context when synchronously unsubscribed

src/Subject.ts
This PR updates type definition to `Subject::next` to allow next value optionally.
This does not changes actual behavior, it was allowed to `next()` in JS already.
closes #1728
=> fix(Subject): allow type definition to next value optionally

spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
allow undefined content-type header if body is formdata
references GitHub issue https://github.com/ReactiveX/rxjs/issues/1729
=> fix(AjaxObservable): ignore content-type for formdata

src/observable/dom/WebSocketSubject.ts
=> fix(WebSocketSubject): use the supplied WebSockeCtor, and support source/destination arguments in the constructor.

MAINTAINERS
If we want to use https://lgtm.co/, there are two steps required:
- Add a MAINTAINERS file (this PR)
- Enable the service by logging in at https://lgtm.co/ (@blesh **needs to do this with access rights to reactivex org**)
=> chore(MAINTAINERS): add MAINTAINERS file for lgtm.co

src/Subscriber.ts
This is just for readability and explain the design.
=> chore(Subscriber): add comment why Subscriber.destination is 'PartialObserver<any>'

doc/scripts/theme-toggler.js, doc/styles/main.css, esdoc.json
Okay, referencing my GIT havoc here: https://github.com/ReactiveX/rxjs/pull/1578. This is a fresh single commit addition of the theme toggler based on latest master.
The THEME toggler will save the current theme to localStorage, if available. Dark theme is default.
=> docs(design): Theme toggler

src/Rx.ts
This moves the `async` property to be the last one defined, because babel will then not choke on the `,` after the property.
fixes #1806
related to https://phabricator.babeljs.io/T7479
=> fix(babel): fix an issue where babel could not compile `Scheduler.async`

spec/operators/switch-spec.ts
This test case appears to be the victim of a copy paste error, this particular test for switch was not calling switch at all. Updated to call switch and it still passes.
=> test(switch): update test case to use correct operator

package.json
This PR introduces module `lint-staged` via wiring existing git hooks to pre-commit. Since checked in codebase is already guarded by full lint, it doesn't necessarily required to trigger full lint each time per check in. This PR makes automatically trigger lint only against staged files, reduced daily-flow time consumption on lint.
- Per each `commit`, lint will be triggered automatically only for staged files. Failure will block commit.
- All other `lint` tasks remain, allows manual full lint if possible.
- `lint_staged` task will allow trigger lint manually against staged files, do not need try commit each time for trigger lint.
- `travis` will run full lint per each build to serve as guard.
NOTE : I think #1731 is still valid when codebase grown, need frequent full …
=> chore(package.json): trigger lint against staged files only

src/BehaviorSubject.ts, src/util/throwError.ts
This PR removes utility function `throwError`, which simply wraps `throw` and only being used in single place. Error can be thrown directly.
=> refactor(throwError): remove utility throwError() function

spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
This PR drops support of `resultSelector` in `ajax*()` mehod.
- by removing `resultSelector`, ajax method delivers strict `AjaxResponse` type resolve type inference issues on subscription.
- when it's needed to select specific values, encourage chain `map` as necessary. 
closes #1783
BREAKING CHANGE: ajax.*() method no longer support resultSelector, encourage to use `map` instead
=> fix(AjaxObservable): drop resultSelector support in ajax method

spec/subjects/AsyncSubject-spec.ts, src/AsyncSubject.ts
This PR updates `AsyncSubject::next` adds guard to now allow to change value if it's already completed.
closes #1800
=> fix(AsyncSubject): do not allow change value after complete

src/Subject.ts, src/observable/BoundNodeCallbackObservable.ts, src/observable/GenerateObservable.ts
- This just for enhancement to fix the errors when using tsc v2.0.
- ...and intend to decrease our effort when we upgrade our typescript compiler.
=> chore(typings): fix compiler errors when using tsc v2.0

spec/symbol/iterator-spec.ts, spec/symbol/observable-polyfilled-spec.ts, spec/symbol/observable-spec.ts, src/Observable.ts, src/Rx.ts, src/observable/FromObservable.ts, src/symbol/observable.ts, src/util/subscribeToResult.ts
per discussion with @blesh, removing the hard dependency on symbol-observable to allow existing implementations (see: corejs/es7/observable) to polyfill instead of `symbol-observable`, and provide a fallback.
=> chore(observable): remove hard dependency on symbol-observable

src/Observable.ts
=> docs(#1794): remove unnecessary `imply`

spec/observables/fromEvent-spec.ts, src/observable/FromEventObservable.ts
Updating `fromEvent` to accept event listeners options to reflect W3C
DOM specification.
#1836
=> feat(fromEvent): Pass through event listener options

spec/Observable-spec.ts, src/Operator.ts
This PR replaces implementation `Operator<T, R>`  into `interface` by base implementation `Operator::call` is not necessarily needed, since creating new operator requires to override it any time. Instead, this PR makes operator as contract interface only.
=> refactor(Operator): replace operator<T, R> to interface

spec/operators/reduce-spec.ts, spec/operators/scan-spec.ts, src/add/operator/scan.ts, src/operator/reduce.ts, src/operator/scan.ts
This change makes working with scan/reduce a little easier in TypeScript based applications.
None that I'm aware of.
This change makes working with scan and reduce a little easier without having to cast the types.
=> style(scan): updated signatures for scan and reduce

spec/Subscription-spec.ts, src/Subscription.ts
BREAKING CHANGE:
This fixes ReactiveX#1656.
This makes Subscription.add() returns always subscription.
if you checks the returned value of it. you might need to change it.
=> refactor(Subscription): return always subscription when calling Subscription.add()

spec/operators/combineLatest-spec.ts, src/operator/combineLatest.ts
Fixes `combineLatest` to emit unique array instances when using the default projection. Without this fix, the default projection emits a shared array (which causes all sorts of problems).
The included test fails against the un-patched `combineLatest` thusly:
```
combineLatest should emit unique array instances with the default projection
(expected c === 3, actual c === 1)
```
#1686
=> fix(combineLatest): emit unique arrays from the default projection

spec/observables/pairs-spec.ts, src/Rx.ts, src/add/observable/pairs.ts, src/observable/PairsObservable.ts, src/observable/pairs.ts
This PR adds `PairObservable` to support generate observable from object has keys.
Marking as 'discussion' for now, since may debatable if this need to be included or not, creating PR as discussion point as implementation is somewhat straightforward.
closes #1804
=> feat(PairsObservable): add PairsObservable creation method

spec/helpers/test-helper.ts, spec/operators/catch-spec.ts, src/operator/catch.ts
This PR utilizes `subscribeToResult` to accept selectors of `catch` can return any kind of `ObservableInput`.
closes #1857
=> fix(catch): accept selector returns ObservableInput

spec/helpers/test-helper.ts, spec/util/subscribeToResult-spec.ts, src/util/subscribeToResult.ts
This PR adds separate test coverage to `subscribeToResult`, as discussed in https://github.com/ReactiveX/rxjs/pull/1859#issuecomment-236697002. 
Also updated logic in `subscribeToResult` for subscribing iterables to mimic behavior of `IteratorObservable`, by found out `for...of` iteration does not work with custom iterables used in test cases, fall back into explicit `iterator::next()` call instead.
=> test(subscribeToResult): add test coverage to subscribeToResult

doc/introduction.md
While going through the introduction I found that the examples that used throttle threw an error due to it showing the previous usage of taking an integer to describe the interval length in milliseconds. It currently takes a function that returns an Observable, so I updated the document.
=> Updated introduction examples to use throttleTime in place of throttle

README.md
Add spaces to import statement on line 44 as per issue #1868.
=> docs(README.md): fix import formatting

spec/observables/IteratorObservable-spec.ts, spec/observables/from-spec.ts, spec/support/default.opts, src/observable/ArrayLikeObservable.ts, src/observable/ArrayObservable.ts, src/observable/FromObservable.ts, src/observable/IteratorObservable.ts, src/observable/PromiseObservable.ts
Arguments supplied to `Observable.from` are not being propagated correctly. I've chased this a couple of levels down the rabbit hole and whilst this patch fixes some issues, I'm starting to think that Iterators and Schedulers just don't work together. I supply this patch only because the code is so obviously wrong.
N.B. I tried adding tests but I don't understand enough about your testing primitives and their behavior to get the results I would expect. However, I believe the code is currently so obviously wrong that the tests are unnecessary to prove correctness, only to prevent regression.
=> fix(Observable.from): use scheduler if supplied

spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts, src/operator/map.ts
This PR updates behavior of `ajax.getJSON`, internally relies on observable to have `map` operator patched to select response, which causes failure if consumer imports observable without operator patched. Instead, explicitly imports map operator.
closes #1874
=> fix(ajaxObservable): remove implicit dependency to map operator patch

src/operator/catch.ts
This is a really strange issue that I've been fighting with today.   When returning an `Observable<T>` to `mergeMap` I was having the resulting value come out as `Observable<any>` and I couldn't figure out why.  If I returned a `Promise<T>` or returned `T[]` everything was working correctly.
I used `git bisect` to determine that the issue originated with [`e55c62df9`](https://github.com/ReactiveX/rxjs/commit/e55c62df92228c0e71dbea587d6d68c28988829b).  After playing with the commit a little bit I able to reduce the problem down to.
What the full problem comes down to is using `TypeScript 2.0+` and `rxjs beta11`.  With TS1.8 this is not a problem.  The test added in this case only fails in TypeScript 2.0.
```ts
export interface CatchSignature<T> {
(selector: (err: any, …
```
=> fix(catch): removed unneeded overload for catch

perf/micro/immediate-scheduler/operators/sequenceEqual-comparor.js, perf/micro/immediate-scheduler/operators/sequenceEqual.js, spec/operators/sequenceEqual-spec.ts, src/Rx.ts, src/add/operator/sequenceEqual.ts, src/operator/sequenceEqual.ts
=> feat(sequenceEqual): adds sequenceEqual operator

src/scheduler/VirtualTimeScheduler.ts, src/testing/TestScheduler.ts
This PR amends ctor of `virtualTimeScheduler` to not to have default maxframe values (== positive infinity) let `testScheduler` specifies it. Anyone create instance of `virtualTimeScheduler` may set maxframe value if needed.
closes #1889
=> fix(VirtualTimeScheduler): remove default maxFrame limit

spec/observables/dom/webSocket-spec.ts, src/observable/dom/WebSocketSubject.ts
Passes websocket constructor error onto the returned observable.
#1891
=> fix(WebSocketSubject): pass constructor errors onto observable

README.md, doc/installation.md
=> Update links from npmcdn to unpkg

spec/helpers/ajax-helper.ts, spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
JSON.parse('') will throw a syntax error (in any browser). Fix is to return a null value. I saw this when my server returned HTTP 204 No Content.
=> Return null value from JSON.Parse

MIGRATION.md, src/operator/timeoutWith.ts
This PR updates signature of `timeoutWith` to accept `withObservable` as `ObservableInput`, as internal implementation already able to support it via utilizing `subscribeToResult`. In addition to those, updated migration document to list timeout operator split.
=> updates signature / documents for timeoutWith

MIGRATION.md
from https://github.com/ReactiveX/rxjs/pull/1877#issuecomment-239577722, this PR updates operator migration table to have better explanation of not yet implemented operators. For now everything is marked as `not yet implemented`, while some operator may need clarification like `will not implement`, etcs. 
also, additionally updated few operator status
- `sequenceEqual` removed as it's implemented
- `tapOn*` now refer to `do`
=> docs(MIGRATION): update operator table

doc/decision-tree-widget/tree.yml, doc/operators.md, spec/operators/repeatWhen-spec.ts, src/Rx.ts, src/add/operator/repeatWhen.ts, src/operator/repeatWhen.ts
It still has four test from retryWhen, that are disabled as they don't make sense for repeatWhen. Maybe there are some alternative tests that should be included instead. 
=> feat(operator): Add repeatWhen operator

spec/operators/max-spec.ts, spec/operators/min-spec.ts, src/operator/max.ts, src/operator/min.ts
min (&max) operators have now the expected behavior when used with a comparer:
- previously they were behaving like _reduce_ and emitting (last) comparer return value
- they now emit original observable min/max value by comparing the comparer return value to 0
method signatures were changed to have comparer return a number instead of T
unit tests have been updated, the ones relying on a constant comparer have been removed when their outcome should be undefined (more than 1 value in stream and no error/unsub) and replaced by ones with either a basic or reverse comparer.
I can split the PR in 2 commits (one for min and one for max) if you think that'd help on the release notes.
**Related issue :**
#1892
=> fix(min/max): do not return comparer values (#1892)

src/add/operator/catch.ts, src/add/operator/do.ts, src/add/operator/finally.ts, src/add/operator/switch.ts
=> fix(operators): export reserved name operators on prototype

spec/Observable-spec.ts, src/observable/dom/AjaxObservable.ts, src/util/toSubscriber.ts
Supply the Subscriber constructor the empty observer destination if `Observable.subscribe` is called with no arguments. This ensures the Subscriber wraps the empty Observer in a `SafeSubscriber` which will catch `error` messages and dispose of the subscription.
#1921
=> Fixes 1921

spec/operators/cache-spec.ts
Minor fix, declaring a constant that was missing. Just keeping my editor from barking at me.
=> fix: add missing expectSubscriptions constant

doc/tutorial/basics.md
=> Typo in the comments/documentation

spec/util/root-spec.ts, src/util/root.ts
Fixes #1930
Unfortunately this isn't something we can really unit test AFAIK. It's pretty meta.
The `objectTypes` stuffs appeared to be a left over from earlier refactors cause none of these should ever be a function.
=> fix(root): find global context (window/self/global) in a more safe way

src/Observable.ts
It appears that there are still some typing issues related to `catch` on both `Promise<T>` and `Observable<T>`.
This change simply reduces what we consider a `Promise<T>` just the thenable interface.  I double checked our code and our promise handling code only requires `then` and does not require `catch`.  This change will also make it easier for TypeScript consumers to return promise like items, instead of true promises.
Much like with the catch issue before I don't really have a valid test case, because all the unit tests do not use the `...Signature<T>` interfaces, and instead just the methods.
Once we move to TS2.0 that will change, as we remove the signature interfaces and move them to the methods themselves.
=> style(typings): updated ObservableInput<T> to use PromiseLike<T> instead of Promise<T>

src/operator/filter.ts, src/operator/find.ts, src/operator/first.ts, src/operator/last.ts
By the previous code base, we need to use `filter()` + `map()`
```typescript
interface SuperClass {}
interface DerivedClass extends SuperClass {}
const bar: Observable<SuperClass> = someobservable;
const derived: Observable<DerivedClass> = bar.filter((v): boolean => {
// some type guard logic
}).map<DerivedClass>((v) => v as DerivedClass);
```
By this change, we can write this code:
```typescript
const bar: Observable<SuperClass> = someobservable;
const derived: Observable<DerivedClass> = bar.filter<DerivedClass>((v): v is DerivedClass => {
// some type guard logic
});
```
https://github.com/Microsoft/TypeScript/pull/10027
=> feat(filter): Observable<T>.filter() can take a type guard as the predicate function

doc/tutorial/applications.md
dispose() is no longer the way to dispose of a subscription handle
=> unsubscribe() instead of dispose()

README.md, doc/installation.md
Only importing `Obervable` does not give it the `of` method.
This imports `of` and uses the appropriate bind syntax in the README.md
This was my experience anyway. I'm not sure if the _correct_ way to do this is to `import { Observable } from 'rxjs'`, in which case the `of`-method would exst on the `Observable`-object, but this way should execute less code (as in, not import all of RxJS which I'm guessing `from 'rxjs'` would do?)
Edit: If someone wants (no need) to throw in a quick explanation as to why (if) one should import the methods separately from the `Observable`-object itself, that would be very interesting :smile:
=> docs(readme): Import observable method correctly

spec/operators/take-spec.ts, src/operator/take.ts
The TakeSubscriber compares the instance variable `count` to determine if it should complete or not.
If the source Observable is re-entrant, this check fails (because `count` is updated in each `next`), and take never completes.
I encountered this issue with expand and take on a multicast Observable, but here's a much simpler repro example:
```es6
import { Subject } from 'rxjs';
const subject = new Subject();
subject
.take(10)
.subscribe(
(i) => {
console.log(i);
subject.next(i + 1);
},
(err) => {},
() => console.log('done') // never gets printed
);
subject.next(0);
```
=> fix(operator): Fix take to complete when the source is re-entrant.

src/operator/merge.ts
The documentation was misleading to me today when I was using the static merge operator of an Observable. You can pass in multiple Observables but the documentation claimed there was "input1" and "input2". This update changes the param type to be a spread type as the function expects.
=> fix(docs): Fix esdoc for Observable.merge spread argument

spec/observables/interval-spec.ts, spec/schedulers/AnimationFrameScheduler-spec.ts, spec/schedulers/AsapScheduler-spec.ts, spec/schedulers/QueueScheduler-spec.ts, src/scheduler/AnimationFrameAction.ts, src/scheduler/AnimationFrameScheduler.ts, src/scheduler/AsapAction.ts, src/scheduler/AsapScheduler.ts, src/scheduler/QueueAction.ts
Asap and AnimationFrame Schedulers should act like the Async Scheduler if delay > 0.
#1952
=> fix(schedulers): Fix Asap and AnimationFrame Schedulers to act like the Async Scheduler if delay > 0

src/Observable.ts
This was annoying me a long time already. So this patch describes better how to call the `.subscribe()` method, ruling out invalid combinations (like a partial observer object and an error handler).
- Overloads subscribe signature for usage with an empty subscriber, PartialObserver<T>, or next, error and complete handlers
=> fix(Observer): fix Observable#subscribe() signature to suggest correct usage

spec/operators/bufferTime-spec.ts, src/operator/bufferTime.ts
Ensures that a buffer context is not created if the subscriber is closed
fixes #1944
=> fix(bufferTime): no errors with take after bufferTime with maxBufferSize

spec/operators/timeout-spec.ts, src/Rx.ts, src/operator/timeout.ts, src/util/TimeoutError.ts
This PR addes `TimeoutError` to be thrown as default error of timeout.
closes #1997
=> refactor(TimeoutError): timeout throws typed TimeoutError

doc/tutorial/basics.md
`new Subject()` does something very different from `Subject.create()`.
fixes #1975
=> docs(tutorial): creating observables docs fixing typo

package.json, spec/subjects/BehaviorSubject-spec.ts
BREAKING CHANGE: TypeScript definitions are now for TS 2.0 and higher
Even if we use getter for class, they are marked with `readonly` properties
in d.ts.
this is a "fixed" version of #1968, retaining @saneyuki's work, just rebasing and updating the commit message.
=> feat(package.json): update TypeScript to v2.0

spec/observables/dom/webSocket-spec.ts, src/observable/dom/WebSocketSubject.ts
When the internal socket is `null`-ed out, we weren't ensuring that all other Subjects that are being used internally were also being reset. This caused issues where sometimes internal subjects found themselves in a bad state when you tried to reconnect. This was even more nefarious in multiplexed web sockets.
This PR adds a single private method called `_resetState` that will reset the socket and all other Subjects to their original state.
fixes #1863
=> fix(WebSocketSubject): ensure all internal state properly reset

.make-packages.js, package.json
BREAKING CHANGE: `rxjs-es` is no longer being published
BREAKING CHANGE: `@reactivex/rxjs` no longer has `/dist/es6` output
related #2016
related #1992
closes #1671
related #1954
=> feat(ES2015): stop publishing `rxjs-es`

CHANGELOG.md
this was missed in the commit message so it wasn't listed as breaking.
Cc/ @blesh
=> chore(CHANGELOG): add cache operator removal as breaking change

src/Subject.ts
This addresses the problem described in #2029.
`Observable<T>` implements `lift<R>(...)`
`Subject<T>` implements `lift<T, R>(...)`
The extra generic type argument `T`, causes type inference to break in horrible ways.
#2029
=> fix(typings): fixed Subject<T>.lift to have the same shape as Observable<T>.lift

README.md
This PR changes `npm install rxjs-es` (which is deprecated) to `npm install rxjs`.
https://github.com/ReactiveX/rxjs/pull/2019
=> Fix documentation to install `rxjs`, not `rxjs-es`

README.md
Add instructions to install missing Ghostscript fonts on Mac.
Homebrew's `ghostscript` package does not install any fonts;
`gm convert` will fail without them.  Add instructions to install these
fonts manually.
=> docs(readme): add further instructions for building docs on Mac

src/util/isScheduler.ts, src/util/root.ts
- This removes needless type parameters & declarations.
- Just a minor refactoring.
- I found this refactoring chance in playing with codes for #1969
=> refactor(util): remove unused variables in src/util/

src/observable/dom/AjaxObservable.ts
BREAKING CHANGE: 
- Remove the unused type parameter `T`
- By this change, the user does not have to specify needless type parameter.
=> refactor(AjaxObservable): remove needles type param T from AjaxObservable.getJSON()

src/observable/IteratorObservable.ts
- Before this change, if call `IteratorObservable.create<number>()` with specifying type parameter, the return type of it was `IteratorObservable<{}>`. This pull request fix this.
- This might be potential breaking change.
=> fix(IteratorObservable): clarify the return type of IteratorObservable.create()

src/observable/FromEventObservable.ts, src/observable/FromEventPatternObservable.ts
- By this change, the consumer does not simplify the type to specify to use them
- BREAKING CHANGE: `FromEventObservable<T>` & `FromEventPatternObservable<T>` are no longer take type parameter `R`.
You don't have to pass 2nd type parameter.
=> refactor(FromEventObservable): remove needless type parameter from FromEventObservable & FromEventPatternObservable

spec/schedulers/VirtualTimeScheduler-spec.ts, src/Scheduler.ts, src/scheduler/Action.ts, src/scheduler/AnimationFrameAction.ts, src/scheduler/AsapAction.ts, src/scheduler/AsyncAction.ts, src/scheduler/QueueAction.ts, src/scheduler/VirtualTimeScheduler.ts
- For more readability, more consistently.
- I think this would not be a breaking change by these reasons:
- There are no problem if we pass the function which does not has `this` specifying.
- There are no problem if we pass the function which has `this: any` or `this: Action<T>`.
- This case is valid with the actual behavior.
- If we pass the function which has `this: SomeNonValidTypeWithAction<T>`,
then, basically, its code would be wrong.
=> refactor(Scheduler): clearify the signature which `Scheduler.schedule()` takes as `work`.

spec/util/assign-spec.ts, src/util/assign.ts
RxJS should not be responsible for polyfilling `Object.assign`.
This should also increase code coverage around the alternate method used for assign
BREAKING CHANGE: RxJS will no longer polyfill `Object.assign`. It does
not require `Object.assign` to function, however, your code may be
inadvertently relying on this polyfill.
=> fix(Object.assign): stop polyfilling Object assign

package.json, yarn.lock
This PR updates TS to latest, which includes several fixes also improves build speed.
=> chore(package.json): bump up dependencies to TS@2.0.6

.markdown-doctest-setup.js, spec/observables/fromEvent-spec.ts, src/observable/FromEventObservable.ts
Added `removeEventListener` mock to #1852 and rebased (didn't have permission to push -f to his  branch.
=> fix(fromEvent): Throw if event target is invalid

spec/Notification-spec.ts, spec/helpers/testScheduler-ui.ts, src/Notification.ts
- changed notification's `exception` property to by named `error`
BREAKING CHANGE: `Notification.prototype.exception` is now `Notification.prototype.error` to match Rx4 semantics
fixes #2105
=> fix(Notification): `materialize` output will now match Rx4

spec/operators/first-spec.ts, src/operator/first.ts
adds guard after first emitted value to prevent reentrant behavior
fixes #2098
=> fix(first): will now only emit one value in recursive cases

spec/helpers/test-helper.ts
This fix is related to saucelabs tests failing in Safari 8.
The suspicion is that it is a problem with the fact a line of code was
using `Symbol.observable` directly instead of `56526symbolObservable`
since we're no longer polyfilling `Symbol.observable` unless `Symbol`
exists properly. Might also be related to `symbol-observable` dependency.
=> chore(fix-test-helpers): fix Symbol.observable refernce for Safari 8

src/observable/ErrorObservable.ts
- BREAKING CHANGE - `ErrorObservable.create()` (`Obserbable.throw()`)
takes a new type parameter `E` that express a error type instead on old
one's `T`.
- Their functions return `ErrorObservable<E>`.
- It is still the drived type of `Observable<any>`, it's not changed from
old one.
- But it contains the error typed as `E` now.
=> refactor(ErrorObservable): clarify an error type `E` for ErrorObservable.

src/operator/filter.ts, src/operator/find.ts, src/operator/first.ts, src/operator/last.ts
These updates allow the use of type guard predicates to flow narrowed types through Observable operator chains using the `filter`, `find`, `first`, and `last` operators without requiring casting. Unfortunately, direct use of `typeof x === 'string'` style boolean predicates are not able to be supported yet in this context, even though typescript understands how to use them in other contexts (e.g. `if/else` statements and such). However, type guard functions can still reduce a lot of boilerplate casting noise with these new definitions.  Examples for each operator appear below.
```typescript
// x is `Observable<string | number>`
let x = Observable.from([1, 'aaa', 3, 'bb']);
// This type guard will narrow a `string | number` to a string in the examples below
let isString = …
```
=> feat(filter, find, first, last): support type guard predicates that don't requiring casting

spec/Observable-spec.ts, spec/helpers/testScheduler-ui.ts, spec/operators/sequenceEqual-spec.ts, spec/support/mocha.sauce.runner.js, spec/tsconfig.json, typings.json
It seems IE browser testing fails by not able to look up promise implementation, which some of spec creates as test fixture. This PR patches global if promise doesn't exists to let test works correctly.
=> test(browser): polyfill promise for unsuppoerted browser

CHANGELOG.md
The commit message for #2120 was not marked as `fix()` so it wasn't picked up. Understand why it wasn't, cause...it's not really a "bugfix" in the sense of a runtime bug...just a compile/typings bug.
Cc/ @kwonoj @blesh
=> chore(CHANGELOG): add message about chai typings fix

doc/operators.md
Some links are missed on the documentation, see:
http://reactivex.io/rxjs/manual/overview.html#categories-of-operators
=> docs(operators): Add some missed links

src/operator/timeout.ts
This PR updates behaivor of `timeout` operator for better readibility of stack trace when `TimeoutError` thrown. 
For example, with given code snippet
```js
Rx.Observable.never().timeout(10).subscribe(console.log.bind(console));
```
stacktrace will be like below
```js
D:\github\rxjs\dist\cjs\scheduler\AsyncScheduler.js:45
throw error;
^
TimeoutError: Timeout has occurred
at new TimeoutError (D:\github\rxjs\dist\cjs\util\TimeoutError.js:17:26)
at TimeoutSubscriber.notifyTimeout (D:\github\rxjs\dist\cjs\operator\timeout.js:99:40)
at AsyncAction.TimeoutSubscriber.dispatchTimeout [as work] (D:\github\rxjs\dist\cjs\operator\timeout.js:75:20)
at AsyncAction._execute (D:\github\rxjs\dist\cjs\scheduler\AsyncAction.js:111:18)
at AsyncAction.execute …
```
=> fix(timeout): throw traceable TimeoutError

spec/operators/partition-spec.ts, src/operator/partition.ts
This fix ensures that the `partition` will call `predicate` with`thisArg` as expected if it is specified.
This fix ensures that the `partition` will call `predicate` with`thisArg` as expected if it is specified.
=> fix(partition): handles `thisArg` as expected

spec/observables/fromEvent-spec.ts, src/observable/FromEventObservable.ts
Objects created with a null prototype do not have a toString method.
=> fix(event): uses `Object.prototype.toString.call` on objects

README.md, doc/installation.md
Add a missing import statement for `Observable.of`. Without this fix, the
example code would generate an error message like
'Uncaught TypeError: _Observable.Observable.of is not a function(…)'
at runtime.
=> docs(README): add missing import in example

spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
Currently when `XMLHttpRequest::send()` throws, AjaxObservable does not deliver those failures to observer different to other XHR behaviors. This PR updates behavior of `AjaxObservable` to change those behavior to deliver error to observer as well.
=> fix(AjaxObservable): catch XHR send failures to observer

spec/util/subscribeToResult-spec.ts, src/util/subscribeToResult.ts
```js
item$.mergeMap(() => {})
// You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
item$.mergeMap(() => ({}))
// You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```
One thing I thought about doing is having operators (who are the ones who call `subscribeToResult`) pass in the operator name, so that the error message could also say which operator it thinks it occured in. **But**, what about operator aliases? i.e. mergeMap/flatMap, etc. And also, this could potentially be _more_ confusing if it's a custom operator that calls other operators inside of it--but perhaps that's rare enough in the wild to discount it.
So for example: `You provided 'undefined' to …
=> fix(errors): Better error message when you return non-observable things,

spec/operators/filter-spec.ts, spec/operators/find-spec.ts, spec/operators/first-spec.ts, spec/operators/last-spec.ts, src/operator/filter.ts, src/operator/find.ts, src/operator/first.ts, src/operator/last.ts
This is a fix for the recently-added type guard support in the `filter`, `find`, `first` and `last` operator typings. Please see the test cases for details of what's working now, and be sure to let me know if I missed anything this time! ;-)
Apparently, my previous PR in #2119 is being reverted in #2164 due to the important missed case mentioned in #2163. Unfortunately, I didn't receive any notifications about it, but I'm glad I saw it today while lurking through the repo! :-) Hopefully, this PR should address the problem (which I'm embarrased that I missed), and let us keep the new support without breaking previous behavior.
=> Fix type guard additions

spec/operators/timeout-spec.ts, src/operator/timeout.ts
The `errorToSend` argument did not make much sense, so we are removing it ahead of the 5.0 release. All timeout errors will be thrown as `TimeoutError`, which can be tested with an assertion against `instanceof Rx.TimeoutError`.
BREAKING CHANGE: `timeout` no longer accepts the `errorToSend` argument
related #2141
=> feat(timeout): remove `errorToSend` argument, always throw TimeoutError

spec/operators/race-spec.ts, src/operator/race.ts
This fixes a bug with the `race` operator: whenever a raced Observable emitted a value **immediately** when subscribed (with the default scheduler), any following Observables were subscribed but never unsubscribed.
Now, if any raced Observable emits a value immediately, any latter Observables are ignored, because for them "the race is already lost".
Also, it is now ensured that the immediately emitting Observable is still added to the `RaceSubscriber` and will be unsubscribed once the outer Observable is unsubscribed.
=> fix(race): unsubscribe raced observables with immediate scheduler

MIGRATION.md
The migration docs need a little love. The idea here was just to make it easier to find operators that you're trying to migration, and provide a little more guidance and context for people trying to deal with migrating operators we aren't going to add or haven't added yet.
=> Update migration docs

README.md
As discussed [in today's RxJS team meeting](https://github.com/ReactiveX/rxjs-core-notes/blob/master/2016-12/december-20.md#branching-strategy), we feel it would be more simple to use two branches instead of three.
- [master](https://github.com/ReactiveX/rxjs/commits/master) - commits that will be included in the next _minor_ or _patch_ release
- [next](https://github.com/ReactiveX/rxjs/commits/next) - commits that will be included in the next _major_ release (breaking changes)
We need to make the actual branches for `next` still.
***
We haven't really thought through the name `"next"` much. It is ambiguous, since it is intended to mean "next **major** release" (right now 6.0) not "next release in general" (e.g. 5.0.2) We didn't want to name the branch the literal version number, e.g. …
=> chore(README): Update our branching strategy

spec/operators/groupBy-spec.ts, src/operator/groupBy.ts
Not sure how groupBy is passing current unit tests, as we seem to be covering this case.
This PR fixes a bug where groupBy wasn't unsubscribing from its source when the outer subscription has been disposed and all inner subscriptions are inactive.
If you see [here](https://github.com/trxcllnt/rxjs/blob/04b7757dd6e661e7a7be48231d0261790327b9f5/src/operator/groupBy.ts#L250), the inner refCount subscription calls `parent.unsubscribe()` if `parent.count === 0` and `parent.attemptedToUnsubscribe` is true. But the parent only unsubscribes if `parent.attemptedToUnsubscribe` is false, which means the subscription to the source is never disposed.
This is easily replicated with groupBy on a Subject, where you'll see the observers list grow indefinitely.
=> fix(groupBy): Fix groupBy to dispose of outer subscription.

spec/helpers/ajax-helper.ts, spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
progress event should be set before `xhr.open`,
see: https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
=> Fix ajax upload progress event is not set correctly

spec/Subscription-spec.ts, spec/operators/observeOn-spec.ts, src/Subscription.ts, src/operator/observeOn.ts, src/scheduler/VirtualTimeScheduler.ts
- ensures child subscriptions created via `Subscription.prototype.add` remove themselves from the internal subscriptions list.
- ensures scheduled notifications from observeOn remove themselves from the subscription by calling unsubscribe on themselves.
fixes #2244
=> Observe on leak

package.json, src/Observable.ts, src/Subject.ts, src/util/errorObject.ts, tslint.json
Small ergonomics enhancement for linting, now it'll fix possible errors automatically when try to commit.
=> chore(package.json): auto fix possible lint errors when commit

spec/Observable-spec.ts, spec/helpers/testScheduler-ui.ts, spec/subjects/BehaviorSubject-spec.ts, spec/subjects/ReplaySubject-spec.ts
This PR includes minor enhancements to `testSchedulerUi`, do not convert sync test to async unnecessarily. also converted some tests to sync, use fake timers to reduce test execution time where possible.
#1660
=> test(testSchedulerUi): do not convert synchronous test to async test

src/operator/every.ts
=> docs(operators): examples for 'every' operator

src/operator/distinct.ts, src/operator/distinctUntilChanged.ts, src/operator/distinctUntilKeyChanged.ts
Examples for distinct, distinctUntilChanged and distinctUntilKeyChanged operators.
=> docs(operators): examples for distinct* operators

src/operator/combineLatest.ts
`combineLatest` was mutating the array of observables passed to it. This is a very simple fix to clone the array before modifying it.
See this codepen for example of the problem: https://codepen.io/anon/pen/qRNBVJ?editors=1111
=> fix(combineLatest): Don't mutate array of observables passed to combineLatest

spec/operators/catch-spec.ts, src/operator/catch.ts
This is a non-breaking change to make track and dispose its subscription to the Observable returned from the catch selector if the catch subscriber is disposed early.
Without this fix, subscriptions to Observables returned by the catch selector don't get cleaned up, and will leak memory if the `catch` is used on a Subject, and the catch selector returns a sequence that uses the second `caught` Observable argument :-(
=> fix(catch): update the catch operator to dispose inner subscriptions if the catch subscription is disposed

.lgtm
the LGTM service we use as an approval system has been discontinued and no longer works, so we can't merge PRs. This PR removes the .lgtm config file, but I believe @blesh will have to remove it from our status checks in the admin Settings to unblock us.
https://lgtm.co
=> chore(lgtm): remove .lgtm

MIGRATION.md
When using a number interval, we must now use `sampleTime` instead of `sample`. This was not specified in the document.
=> Add sample/sampleTime operator split

src/Subscription.ts
Originated from https://github.com/ReactiveX/rxjs/pull/2234, doesn't add any code changes but only update type definition for interface clarity. 
Currently it's not so benefitable even for TS user since all of codebase just return `Subscription` everywhere instead of using interfaces, that need to be dealt with separate refactoring.
#2234
=> fix(ISubscription): update type definition of ISubscription::closed

doc/tutorial/basics.md
The `keypress` event is send before the value has been set on the input element : it always returns the last value of the element.
When `keyup` is send, the value has already been set on the input; returning the actual value.
=> docs(tutorial): wrong keyboard event

src/observable/FromEventObservable.ts
Description:
Related issue (if exists):
Typo correction
=> style(FromEventObservable): fix typo Emmitter => Emitter

package.json
This PR replaces deprecated `ghooks` into `husky`.
Other than deprecation new hook provides one additonal utility to bypass hooks if necessary via `--no-verify`, like 
`git commit -m "dumb" --no-verify` -> validating commit will be skipped
for helping some cases (like middle of work commits, etcs).
***Note: SHOULD REMOVE EXISTING HOOKS FIRST (`rm -rf ./.git/hooks`) then install new package to setup new hooks***
=> chore(package.json): replace ghooks into husky

spec/observables/fromEventPattern-spec.ts, src/observable/FromEventPatternObservable.ts
This PR aligns `fromEventPattern`'s behavior to RxJS v4, including 2 changes
- `removeHandler` is now optional
- `removeHandler` signature now accepts optional `signal` parameter, `(handler: Function, signal?: any) => void` forwarded value of `addHandler` for eventlistener disposal.
This PR is currently ⚠️ Targeting master ⚠️, since both of changes are optional probably won't breaking any existing usecases. 
#1900, #2088
=> Align fromEventPattern behavior to RxJS v4

src/operator/count.ts
Fix a typo ("an value" --> "a value").
=> docs(count): fix typo

src/operator/windowTime.ts
This PR separates https://github.com/ReactiveX/rxjs/pull/2240 , refactor type definition around windowTime to have better clarity.
=> refactor(windowTime): clarify type definition of windowTime

spec/subjects/AsyncSubject-spec.ts, src/AsyncSubject.ts
I think It can be some wrong behaviours in the current AsyncSubject:
- AsyncSubject can emit complete event after the subject has finished with an error
- AsyncSubject can emit an error event after the subject is completed
This PR fixes that wrong cases.
If this is the intended behaviour please let me know, I check the http://reactivex.io/documentation/subject.html web and other implementations first.
I hope this will be helpful :)
=> fix(AsyncSubject) some cases don't behave correctly

spec/operators/reduce-spec.ts, src/operator/reduce.ts
This PR updates `reduce` to forward index of an element as same as native reduce operator does. 
- closes #2290
=> fix(reduce): forward index to accumulator

src/testing/TestScheduler.ts
Return HotObservable and ColdObservable instead of simply Observable, in order to give users access to subscriptions parameter.
**Motivation:**
Previously getting subscriptions of observables for `expectSubscriptions` assertions was impossible without typecasting:
```javascript
const hot = scheduler.createHotObservable('--a---b--|');
hot.subscriptions // does not compile
```
=> refactor(TestScheduler): return hot and cold observables

src/observable/dom/WebSocketSubject.ts
Documentation of webSocket operator
=> docs(operators): webSocket documentation

spec/operators/groupBy-spec.ts, src/Observable.ts
This PR align type of subscriber param to `<T>`, same as observable.
- closes #2166
=> fix(Observable): align type definition of subscriber with Observable

spec/operators/repeatWhen-spec.ts, src/operator/repeatWhen.ts
After notifier completes wait for source observable to complete instead
of ending stream immediately
Closes #2054
=> fix(repeatWhen): wait for source to complete after notifier completes

src/operator/windowTime.ts
This PR separates https://github.com/ReactiveX/rxjs/pull/2240, updates clear up closed instance of window to when invoked via timespan only.
=> fix(windowTime): clean up closed window with timeSpanOnly

spec/operators/buffer-spec.ts, src/operator/buffer.ts
This fixes an issue with the bufffer operator.
If the source emits values and completes before the notifier emits, those values are lost. 
```
source  = --a--b--c--d--e--|
notifer = ----x-----x-------
source.buffer(notifer)
results
[a]
[b, c]
d & e are never emitted
```
**Related issue:** https://github.com/ReactiveX/rxjs/issues/2154
Fix buffer operator not emitting the last buffer when the source
completes. This is closer to rxjs v4* behaviour and matches the
behaviour of the other buffer operators. The _complete method is very
similar to thoses in bufferCount, bufferTime and bufferWhen.
*rxjs v4 will always emit the buffer if the source completes even if the
buffer is empty. This fix only emits if the buffer is non empty.
BREAKING CHANGE:
extra value may be emitted when …
=> fix(buffer): emit last buffer if source completes

spec/observables/bindCallback-spec.ts, src/observable/BoundCallbackObservable.ts
**Current behaviour:**
Currently when input function (function that is passed as argument to `bindCallback`) is internally called, its context is set to context of underlying observable. If input function is not bound beforehand it is possible to implement:
```ts
function intercept(cb) {
const observable = this;
// do something with underlying observable
}
const boundIntercept = Observable.bindCallback(intercept);
boundIntercept(); // intercept is called with underlying observable as this
```
**Expected behaviour**
Since output function (function returned by `bindCallback) should behave identically as input function (apart from changing callback to observable) it is reasonable to assume that context of ouput function will become context of input function.
```ts
const boundMethod = …
```
=> fix(bindCallback): properly set context of input function

spec/observables/bindNodeCallback-spec.ts, src/observable/BoundNodeCallbackObservable.ts
Set context of input function to context of output function, so that
context can be controlled at call time and underlying observable is
not available in input function
Detailed description in another pr, where situation is basically identical:
https://github.com/ReactiveX/rxjs/pull/2319
=> fix(bindNodeCallback): properly set context of input function

.travis.yml, dangerfile.js, package.json, spec/operators/filter-spec.ts, src/observable/DeferObservable.ts, src/observable/FromEventPatternObservable.ts, src/observable/FromObservable.ts, src/observable/dom/WebSocketSubject.ts, src/operator/catch.ts, src/operator/concatMapTo.ts, src/operator/distinct.ts, src/operator/distinctUntilChanged.ts, src/operator/distinctUntilKeyChanged.ts, src/operator/every.ts, src/operator/materialize.ts, src/operator/max.ts, src/operator/mergeMap.ts, src/operator/min.ts, src/operator/zip.ts
⚠️ Targeting master ⚠️
This PR resolves long-pending issue #1633, provides type inference to marble-diagram based test cases while does not hurt documentation for specs. It is using TypeScript compiler's feature to import type signature without real module import and assign it to existing ambient declaration - ambient declaration will provide same type inference to exported modules.
**Why Targeting master?**
Originally test case were designed to be used as validating type definition as well for most common use cases to prevent issue like https://github.com/ReactiveX/rxjs/issues/2163 . Due to current setup ergonomics, all of tests are running without any compiler validation so there wasn't any regression testing for type definitions which would be considered as breaking …
=> test(filter): enable type inference to marble diagram

dangerfile.js
Hi, I just made two prs: #2329 #2328 and automatic checks fail on them, claiming I used `hot` and `cold` helpers in modified specs without type declarations for them.
Problem is, modified files seem to not use hot and cold helpers at all.
After checking `dangerfile.js` I suspect that logic in that file is flawed, so here is my attempt to fix it.
**Warning**
Note that I had no idea how to test this file, so please do yourself, or just carefully review.
Failing prs: #2329 #2328
=> chore(dangerfile): fix test for hot and cold usages without types

spec/operators/observeOn-spec.ts, spec/operators/switch-spec.ts, src/Subscriber.ts, src/Subscription.ts, src/operator/catch.ts, src/operator/observeOn.ts, src/operator/repeat.ts, src/operator/repeatWhen.ts, src/operator/retry.ts, src/operator/retryWhen.ts
The addition of ChildSubscription to fix #2244 accidentally introduced a different memory leak. Most operators that add and remove inner Subscriptions store the inner Subscriber instance, not the value returned by Subscription#add. When they try to remove the inner Subscription manually, nothing is removed, because the ChildSubscription wrapper instance is the one added to the subscriptions list.
Fixes #2355, and supersedes the fix in #2358. Thanks again to @johncvrs for reporting this.
=> fix(Subscription): fold ChildSubscription logic into Subscriber to prevent operators from leaking ChildSubscriptions.

.npmignore
It's 5.5mb that people installing this don't need :)
**RxJS version:**
<= 5 beta 12
**Code to reproduce:**
> npm install @reactivex/rxjs@5.0.0-beta.12
**Expected behavior:**
> test -e node_modules/@reactivex/rxjs/coverage
> echo $?
1
**Actual behavior:**
> test -e node_modules/@reactivex/rxjs/coverage
> echo $?
0
=> Ignore coverage

spec/util/subscribeToResult-spec.ts, src/observable/FromObservable.ts, src/util/isArrayLike.ts, src/util/subscribeToResult.ts
`Observable.from` and operators using `subscribeToResult` both use interface `ObservableInput` for describing their input, so it follows that they should accept and work properly on the same kind of input.
And yet
```ts
Observable.from({0: 0, 1: 1, length: 2});
```
works as expected on array-likes, while
```ts
Observable.merge({0: 0, 1: 1, length: 2});
```
errors, saying that given argument is not proper observable.
Since array-likes belong to `ObservableInput` interface, I submit fix that makes operators using `subscribeToResult` work properly with array-likes.
=> fix(subscribeToResult): accept array-like as result

spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
Add support of the 'PATCH' request type based on the already existing 'PUT' request.
=> feat(AjaxObservable) : support 'PATCH' request type

spec/helpers/test-helper.ts, spec/observables/merge-spec.ts, src/operator/merge.ts
Currently when `merge` is used with lower case observable, it returns lower case observable itself, instead of adapting it to RxJS Observable.
```ts
Observable.merge(lowerCaseO).map(...); // throws, since 'map' is not on lower case observable
```
=> fix(merge): return Observable when called with single lowerCaseO

spec/observables/dom/webSocket-spec.ts, src/observable/dom/WebSocketSubject.ts
Add `binaryType` to websocket config object, so that it is possible to set that parameter on underlying socket before any data emits happen.
**Related**
Closes #2353
=> feat(webSocket): Add binaryType to config object

spec/observables/forkJoin-spec.ts, src/observable/ForkJoinObservable.ts
Previously there was no adequate type signature for use-case (which is handled properly by operator):
```ts
Observable.forkJoin(observable, selector);
```
Use-case
```ts
Observable.forkJoin(observable)
```
is properly handled by signature
```ts
static create<T>(...sources: SubscribableOrPromise<T>[]): Observable<T[]>;
```
so I did not add signature for that use-case.
**Related**
Closes #2347
=> fix(forkJoin): add type signature for single observable with selector

dangerfile.js
This PR updates dangerfile to have one additional checker, to validate commit messages if it conforms conventional change log. If commits in PR does not conforms it, bot will leave messages like below to ask to update commit messages.
=> chore(danger): update dangerfile to validate commit message

spec/observables/bindCallback-spec.ts, src/observable/BoundCallbackObservable.ts
Related to issue #2254 in `bindNodeCallback`. It turns out `bindCallback` has the same problem:
When wrapped function calls its callback without any arguments, resulting Observable will emit empty array, intead of undefined.
```javascript
function callback(cb) {
cb();
}
Observable.bindCallback(callback)
.subscribe(value => console.log(value)); // value is []
```
In RxJS 4 in `fromCalllback` resulting Observable emits undefined as seen here:
https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/perf/operators/fromcallback.js#L20-L21
(when array is empty, calling `results[0]` results in `undefined`, which is emitted).
**Related to**
#2254
=> fix(bindCallback): emit undefined when callback is without arguments

src/operator/mergeAll.ts
This PR applies same type definition variant to `concatAll` (https://github.com/ReactiveX/rxjs/pull/1603) to `mergeMap`
Same as concatAll, note this doesn't provide auto-inference for types, only provides generic variant to explicitly specify types due to current design of typescript compiler.
- closes #2372
=> fix(mergeAll): introduce variant support <T, R> for mergeMap

spec/operators/windowTime-spec.ts, src/operator/windowTime.ts
Adds new parameter in windowTime operator to control how much values given
window can emit.
Closes #1301
=> feat(windowTime): maxWindowSize parameter in windowTime operator

src/MiscJSDoc.ts, src/observable/DeferObservable.ts, src/observable/combineLatest.ts, src/operator/audit.ts, src/operator/combineLatest.ts, src/operator/concat.ts, src/operator/concatMap.ts, src/operator/concatMapTo.ts, src/operator/debounce.ts, src/operator/exhaustMap.ts, src/operator/merge.ts, src/operator/mergeMap.ts, src/operator/mergeMapTo.ts, src/operator/switchMap.ts, src/operator/switchMapTo.ts, src/operator/throttle.ts, src/operator/withLatestFrom.ts
Add `ObservableInput` and `SubscribableOrPromise` interface descriptions, as well as link these interfaces in type descriptions of operators, so that users always know what kind of parameters they can pass to used methods.
**Related issues:**
#2326 
#2344 
#2351
=> docs(ObservableInput): add ObservableInput and SubscribableOrPromise descriptions

dangerfile.js
This PR lower failure checker for conventional change log commit message into warning, to avoid checker fails due to commit like merge commits.
=> chore(danger): warn only for non conventional changelog

src/operator/repeat.ts
The RxJS 5.0 repeat operator does not take a scheduler as a param but is documented as having it as a parameter. I deleted this line. Where is the ReactiveX website version control hosted so I can change the documentation for the RxJS implementation of repeat?
=> docs(repeat): Remove scheduler as param.

src/observable/dom/AjaxObservable.ts
IE10 throws an `InvalidStateError` due to `withCredentials` being set **before** `open()`.  This seems to be due to the release of IE10 stuck on an older spec [as described in this StackOverflow ticket](http://stackoverflow.com/questions/19666809/cors-withcredentials-support-limited)
None.
=> Ensure withCredentials is set after open for IE10

doc/index.md
It just occurred to me that we still had that "once this is ready" text on the site. This PR updates the description on the landing page, making it more credible now that it's already released as stable.
=> docs(site): reword the landing description for post-release

spec/operators/single-spec.ts, src/operator/single.ts
When using the predicate function in the `single()` operator it passes indices starting at `1` instead of `0`. 
```
Observable.from(['a', 'b', 'c', 'd', 'e'])
.single((val, i) => {
console.log(val + ' ' + i);
return val === 'b';
})
.subscribe();
```
This prints to console:
```
a 1
b 2
c 3
d 4
e 5
```
Live demo: https://jsbin.com/raveji/2/edit?js,console
That's because it's first incremented [(single.ts#L65)](https://github.com/ReactiveX/rxjs/blob/master/src/operator/single.ts#L65) and then read again from property [(single.ts#L75)](https://github.com/ReactiveX/rxjs/blob/master/src/operator/single.ts#L75).
In RxJS 4 the indices start at `0` (which is probably more expected behavior). Live demo: https://jsbin.com/qihaqur/3/edit?js,console
If the user is relying on indices starting at `1` …
=> fix(single): predicate function receives indices starting at 0

src/MiscJSDoc.ts
* Flesh out what is an `Observable Contract`. 
* Add note about returning `TeardownLogic` in passed function. 
* Change `subscribe` to `onSubscription` so that there is no confusion when function is called. 
* Switch `Subscriber` instance as a function argument to `Observer` interface, so that users are not encouraged to use Subscribers implementation details. 
* Add note about TS signature issue. 
* Add examples with calling observers error and returning teardown logic.
* Do not mark function passed to create as optional, since subscribing to Observable created in such way will throw an Error.
=> docs(create): add more details about static create function

spec/observables/concat-spec.ts, src/operator/concat.ts
When static `concat` is passed single lower case observable, it returns that lower case observable, instead of adapting it to RxJS Observable.
https://github.com/ReactiveX/rxjs/pull/2363 <- we had exactly the same issue with merge
=> fix(concat): return Observable when called with single lowerCaseO

src/scheduler/animationFrame.ts, src/scheduler/asap.ts, src/scheduler/async.ts, src/scheduler/queue.ts
Schedulers are probably the most mysterious for newcomers (they were for me and in a way still are).
I believe it would help to show some examples of using schedulers without operators, so that users can
have good intuition what given scheduler can achieve.
I have put descriptions next to already created Schedulers, since these are the ones that should be used primarily.
**Problems:**
* I can not make `{@link async}` in docs, since there is already `async` property on `AjaxRequest` interface. 
* Schedulers and `root` are in the same html file, because they are all variables. Is there a known way to separate them?
**Related issues:**
https://github.com/ReactiveX/rxjs/issues/2379 - question about animationFrame scheduler
=> docs(Scheduler): add docs for async, asap, queue and animationFrame

src/observable/combineLatest.ts
Yet another pr with more detailed documentation for operator.
I struggled to meaningfully describe what scheduler actually does with this operator. This is related to my issue here: https://github.com/ReactiveX/rxjs/issues/2350. 
Irony is that I know how this operator behaves with different schedulers, but I have no idea how to describe it without going into implementation details (calling out `ArrayObservable` implementation and the fact that `combineLatest` subscribes to input Observables in its `complete` function). I would really appreciate some help or pointers here.
**Other doc prs**
https://github.com/ReactiveX/rxjs/pull/2322 - here is more background what do I do and why
https://github.com/ReactiveX/rxjs/pull/2326
=> docs(combineLatest): add details about static version of operator

src/observable/BoundNodeCallbackObservable.ts
`bindNodeCallback` with schedulers have different behaviour for errors from selector function and different for errors passed to callback. When selector throws, scheduler is used to schedule error as seen in
https://github.com/ReactiveX/rxjs/blob/master/src/observable/BoundNodeCallbackObservable.ts#L160
Yet when error comes from error object passed to callback by input function, error is just passed to subscriber, ignoring current scheduler:
https://github.com/ReactiveX/rxjs/blob/master/src/observable/BoundNodeCallbackObservable.ts#L156
I decided to let scheduler send error, since for me personally it is more predictable behaviour, when scheduler is passed. But if I am wrong and all errors should be sent synchronously, let me know and I will switch that change in other …
=> fix(bindNodeCallback): use scheduler on error in callback

src/observable/BoundNodeCallbackObservable.ts
Another attempt to make docs more in-depth and complete, with descriptions of all modes of usage and more examples.
More background on what and why I am doing is here: https://github.com/ReactiveX/rxjs/pull/2322
=> docs(bindNodeCallback): add more details and examples

doc/tutorial/basics.md
We want to log the input values and not the keypress events.
=> docs(tutorial): Log target values and not the events

src/observable/ErrorObservable.ts
This PR updates type signature of static creation method for `ErrorObservable` to no longer carry type constraint to value of error.
- closes #2395
=> fix(ErrorObservable): remove type constraint to error value

spec/operators/multicast-spec.ts, src/observable/ConnectableObservable.ts
This fix ensures ConnectableObservables created by multicast start with null _subject, _connection,
and 0 _refCount. Fixes #2401.
=> fix(multicast): Ensure ConnectableObservables returned by multicast are state-isolated

src/observable/BoundCallbackObservable.ts
- boundSomeFunction should be called
[#2430](https://github.com/ReactiveX/rxjs/issues/2430)
=> docs(bindNodeCallback): fix boundSomeFunction should be called

spec/operators/delayWhen-spec.ts, src/operator/delayWhen.ts
This PR adds current index to the selector function in `delayWhen`operator.
```
source.delayWhen((value, index) => {
...
});
```
#2388
=> feat(delayWhen): add index to the selector function

spec/operators/zipAll-spec.ts, src/operator/zip.ts
This fixes the situation where the `zipAll()` operator doesn't send `complete` notification when the source Observable is empty:
```
Observable
.empty()
.zipAll()
.subscribe(null, null, () => console.log('complete 1'));
```
This doesn't print anything. Demo: https://jsbin.com/fucijuz/2/edit?js,console
This problem occurs only when using `zipAll()` and not `zip()`. The `zip()` operator internally [wraps `zipAll()` with `ArrayObservable`](https://github.com/ReactiveX/rxjs/blob/master/src/operator/zip.ts#L99). So the following works fine:
```
Observable
.zip(Observable.empty())
.subscribe(null, null, () => console.log('complete 2'));
```
This is internally called as:
```
Observable
.from([Observable.empty()])
.zipAll()
.subscribe(null, null, () => console.log('complete 3')); …
```
=> fix(zipAll): complete when the source is empty

doc/decision-tree-widget/tree.yml, spec/operators/smooth-spec.ts, src/Rx.ts, src/add/operator/smooth.ts, src/operator/smooth.ts
Demo: http://jsbin.com/wufawuq/edit?js,output (turn your volume up)
Prior art: https://en.wikipedia.org/wiki/Smooth_Operator
This is mostly a port of this video to RxJS https://www.youtube.com/watch?v=4TYv2PhG89A
Credit: I can't remember who first came up with this. May have been @benlesh. Let's just say it was all of us.
=> feat(smooth): Adds the smooth() operator, the cool operator

doc/index.md
I commonly tell people about the decision tree widget and _every_ time I do they alway say the same thing: "Oh you should make that more noticeable" 😆 
So...I did the laziest thing I could think of, gave it a header.
If someone has better suggestions, go with them instead 😄 
I thought about moving it to be at the top, but absolute first-timers might be confused. **then again** maybe that's an acceptable risk at the expense of helping tons of people discover it. I really is useful to them (and me even). On my laptop, the wizard is below the fold which is likely one of the reasons it's never seen.
=> docs(decision-tree-widget): Add header to decision tree widget section

src/operator/catch.ts
The catch operator is returning an observable with the type of the innerObservable (observable returned when error occur). 
It should be a union of the outerObservable's type and the innerObservable's type :
```ts
function _catch<T, R>(this: Observable<T>, selector: (err: any, caught: Observable<T>) => ObservableInput<R>): Observable<T | R>
```
=> fix(catch): fix catch typings

perf/micro/current-thread-scheduler/operators/buffercount-skip.js, perf/micro/immediate-scheduler/operators/buffercount-skip.js, src/operator/bufferCount.ts
The `bufferCount()` operator can be used as `bufferCount(5, 3)` or `bufferCount(5)` (= `bufferCount(5, 5)`.
My assumption is that the second use-case `bufferCount(5)` is very common (maybe even more common that the first one) and can be handled in an simpler way. This means instead of keeping an array of buffers `T[][]` we can have just a single buffer `T[]`. This simplifies the subscriber class significantly and runs faster.
For this reason I split the original subscriber into two classes `BufferSkipCountSubscriber` and `BufferCountSubscriber` each handling one use-case.
**Performance of `bufferCount(5)`:**
Before:
```
$ node perf/micro buffercount 
|                     RxJS 4.1.0 |                     RxJS 5.1.0 |          factor |      % improved …
```
=> perf(bufferCount): optimize bufferCount operator

spec/operators/reduce-spec.ts, src/operator/reduce.ts
Type inference for `Observable.prototype.reduce` currently behaves incorrectly, resulting in spurious type errors, in many common cases, when the type of `seed` is a different type than the value type of the Observable.
One of the declared overloads is intended to specifically cater to this scenario but fails to do so because of its ordering with respect to the other overload declared.
The overload in question takes two type arguments, `T` and `R`, making it more specific than the overloads declared before it.
Due to TypeScript's overload resolution algorithm, which picks the first matching overload, this overload does not have the intended effect.
This is documented here https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html in the section …
=> fix(reduce): fix overload ordering

spec/observables/forkJoin-spec.ts
* Add tests with Observable that never completes, so that it is clear how forkJoin operator behaves with it.
* Add test which shows that forkJoin unsubscribes from other Observables when one of them errors.
I am writing docs for `forkJoin` and felt bad making assertions about how it behaves, without having unit tests to back me up.
=> test(forkJoin): add tests with never and with unsubscribing after error

src/Observable.ts, src/Rx.ts, src/Subject.ts, src/Subscriber.ts, src/observable/FromObservable.ts, src/observable/IteratorObservable.ts, src/operator/zip.ts, src/symbol/iterator.ts, src/symbol/observable.ts, src/symbol/rxSubscriber.ts, src/util/subscribeToResult.ts, src/util/toSubscriber.ts
=> Fix symbols to work with Babel UMD exporting

src/observable/dom/WebSocketSubject.ts
**Description:** Fixes the example showing the usage of `WebSocketSubject` on Node.js.
**Related issue (if exists):** none
=> docs(webSocket): fix node.js example

src/Observable.ts
According to the ES6 spec and the implementation in V8, accessing a lexically scoped construct like const or let before it is assigned is a ReferenceError. Unlike var, it is not implicitly undefined. Because the closure handed to subscribe is immediately invoked and accesses `subscription` before it is assigned, this causes a ReferenceError in compliant engines.
The error is only triggered when running in plain ES6, i.e. without transpilation.
=> fix(forEach): fix a temporal dead zone issue in forEach.

src/MiscJSDoc.ts
remove unnecessary import statement - MiscJSDoc.ts was moved and a new import statement was added but the outdated import statement was not removed
Fixes #2453
=> style(MiscJSDoc): remove unnecessary import statement

MIGRATION.md
Due to typo in Schedulers Renamed section, the table reflecting changes was not being properly displayed as Markdown aware document.
=> Fixed MIGRATION.md not being properly displayed.

package.json
This is simple pkg pin down, I found latest ^ bump up (above 3.2.7) has regressions to deal with windows paths.
=> chore(package.json): pin down lint-staged pkg version

src/operator/toPromise.ts
Examples used `.just()` which doesn't exist in RxJS 5.
=> docs(toPromise): replace just() with of() in examples

src/util/root.ts
Closure compiler does not allow this. We need this modification to use RxJS in Angular projects.
Addresses https://github.com/angular/tsickle/issues/420
=> fix(closure): don't throw at top-level scope

package.json
Add missing babel-polyfill to package.json, so that tests
run in the browsers that do not support ES6 features run
without issues.
Closes #2261
Dependency is used here: https://github.com/ReactiveX/rxjs/blob/master/spec/support/mocha-browser-runner.html#L11
=> fix(tests): add missing babel-polyfill to package.json

spec/operators/withLatestFrom-spec.ts
=> fix(withLatestFrom): change from hot to cold observable in marble test

doc/styles/main.css
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling
All other mobile and desktop platforms with built-in momentum scrolling
enable it by default. iOS requires an explicit CSS rule.
=> docs(css): enable momentum scrolling for iOS

src/scheduler/AsyncAction.ts
Rescheduling an async action with the same due time before its executed should cause it to cancel
its current interval and schedule a new one.
Fixes #2579
=> fix(AsyncAction): Make AsyncAction update its timeout if rescheduled before its executed

spec/observables/race-spec.ts, src/operator/race.ts
I just noticed `Observable.race([o1, o2])` is not working cause current definition is shaped for rest param args only (so `Observable.race(...[o1, o2])` works. This PR aligns type definition to support those forms to actual operator behavior.
=> fix(race): support array of observables other than rest param

spec/operators/delayWhen-spec.ts, src/operator/delayWhen.ts
This PR fixes outersubscriber behavior of delayWhen operator, to complete it correctly when duration selector returns synchronous observable. Similar to https://github.com/ReactiveX/rxjs/pull/1490 in crux.
- closes #2587
=> fix(delayWhen): correctly handle synchronous duration observable

src/operator/onErrorResumeNext.ts
* Create documentation for 'onErrorResumeNext' operator. 
* Describe what it accepts and returns. 
* Compare it to 'concat' operator. 
* Add note about 'catch' operator.
* Provide example of usage.
=> docs(onErrorResumeNext): create documentation for the operator

spec/Subscriber-spec.ts, src/Subscriber.ts
This PR makes to call observer's complete function without delivering one param as undefined value all times. While observer is requested to follow its contract interfaces, change seems trivial to avoid this behavior in code as well. 
I think this is non-breaking changes maybe?
- closes #2502
=> fix(Subscriber): do not call complete with undefined value param

src/util/root.ts
=> refactor(root): a slightly more concise definition borrowed from Angular

MIGRATION.md, doc/decision-tree-widget/tree.yml, doc/operators.md, perf/micro/current-thread-scheduler/operators/skiplast.js, perf/micro/immediate-scheduler/operators/skiplast.js, spec/operators/skipLast-spec.ts, src/Rx.ts, src/add/operator/skipLast.ts, src/operator/skipLast.ts
Adds skipLast operator from RxJS 4. Its internals and tests are based on takeLast for better performance.
Closes #1404
=> feat(skipLast): add skipLast operator 

spec/helpers/marble-testing.ts, spec/operators/shareReplay-spec.ts, src/Rx.ts, src/add/operator/shareReplay.ts, src/observable/ConnectableObservable.ts, src/operator/shareReplay.ts
`shareReplay` returns an observable that is the source multicasted over a `ReplaySubject`. That replay subject is recycled on error from the `source`, but not on completion of the source. This makes `shareReplay` ideal for handling things like caching AJAX results, as it's retryable. It's repeat behavior, however, differs from `share` in that it will not repeat the `source` observable, rather it will repeat the `source` observable's values.
related #2013, #453, #2043
=> feat(shareReplay): adds `shareReplay` variant of `publishReplay`

spec/operators/throttle-spec.ts, spec/operators/throttleTime-spec.ts, src/operator/throttle.ts, src/operator/throttleTime.ts
related to #1625  see commits for details.
=> Leading/Trailing throttle and throttleTime configuration

spec/observables/from-promise-spec.ts, src/observable/PromiseObservable.ts
I can not use `Observable.fromPromise` with promises from [when](https://github.com/cujojs/when).  
The class is clearly documented that it should accept Promises/A+ spec compliant Promise.  
I think the type should be relaxed.
=> fix(PromiseObservable): fromPromise does not accept PromiseLike object

spec/helpers/doNotUnsubscribe.ts, spec/operators/find-spec.ts, src/operator/find.ts
Force unsubscribe when resulting Observable completes or errors, even when following operator does not unsubscribe reliably, so that source Observable is not being subscribed unnecessarily.
General description of this type of issue - #2459 
The same fix for other operators - #2501 #2463 #2470
=> fix(find): force unsubscribe when it completes or errors

spec/operators/catch-spec.ts, src/observable/ErrorObservable.ts
Added a failing test describing unexpected behavior between throw Error and Observable.throw(Error) when the source of an observable is a Promise. In my opinion this behavior is confusing as the catch handler needs to know if the source is from a Promise vs another source. Thanks for taking a look. 
Added fix by forcing `sync.syncErrorThrowable` on `ErrorObservable`. Let me know if this is a good fix and if I should add a unit test for ErrorObservable.
Related #2485.
=> fix(ErrorObservable): Added and fixed failing test for Observable.catch

.travis.yml
Seems latest version caused regressions make checker failure, simply pin down to known good.
=> chore(travis): pin danger version

src/operator/mapTo.ts
In the example of mapTo operator, there is duplicated word as belowing:
`@example <caption>Map every every click to the string 'Hi'</caption>`
=> docs(mapTo): remove duplicated word in the example caption

src/operator/pluck.ts
It's the same as #2621 , in the example of pluck operator, there is duplicated word as belowing:
`@example <caption>Map every every click to the tagName of the clicked target element</caption>`
=> docs(pluck): remove duplicated word in the example caption

src/operator/exhaust.ts, src/operator/exhaustMap.ts
In the example code of exhaust and exhaustMap operators, the finite timer need a operator to work with `interval`, such as `take`. The current code that need to be fixed as following:
`var result = clicks.exhaustMap((ev) => Rx.Observable.interval(1000));`
=> docs(exhaust/exhaustMap): fix the example code of exhaust and exhaustMap

doc/decision-tree-widget/tree.yml
In the decision-tree-widget, the instance operator merge was assigned to the static operator by mistake.
=> docs(decision-tree-widget): fix the type of `merge` operator

src/observable/NeverObservable.ts
In the  docs of the never operator, there is a typo, see below:
'Please **_not_** that by never emitting a complete notification'
I think that It should be 'note' rather than 'not'.
=> docs(never): fix a typo

src/operator/do.ts
Hi, @kwonoj . It's the same as #2621 and #2632 , and I had checked that it's the last opeator which have the same issues. 
In the example of do operator, there is duplicated word as belowing:
`@example <caption>Map every every click to the clientX position of that click, while also logging the click event</caption>`
=> docs(do): remove duplicated word in the example caption

src/Observable.ts
Document subscribe method, focusing on what it accepts and returns, how it differs from regular operators and whether it calls its callbacks synchronously or asynchronously.
Closes #2449
=> docs(subscribe): create the documentation

doc/operator-creation.md
There is a typo In the `doc/operator-creation.md`, seen as below:
> by pulling in operator methods **an** adding them to observable in their own module.
It should be a typo and correct one is **and**.
=> docs(operator-creation): fix a typo

src/operator/concatMap.ts
In the docs of  concatMap operator, there are two `@return` tags, the first one is unused.
```
* @return {Observable} An observable of values merged from the projected
* Observables as they were subscribed to, one at a time. Optionally, these
* values may have been projected from a passed `projectResult` argument.
* @return {Observable} An Observable that emits the result of applying the
* projection function (and the optional `resultSelector`) to each item emitted
* by the source Observable and taking values from each projected inner
* Observable sequentially.
```
=> docs(concatMap): remove the unused @return tag

src/operator/toPromise.ts
This PR is need you guys to check because I'm not so sure the format and the type of the params whether it is correct. @kwonoj  @staltz @benlesh 
In the param of toPromise operator, now the `PromiseCtor` param is as below:
`@param PromiseCtor promise The constructor of the promise. If not provided, it will look for a constructor first in Rx.config.Promise then fall back to the native Promise constructor if available.`
First the `PromiseCtor` is optional, and secondly there is no type for it.
=> docs(toPromise): fix the type and attribute of `PromiseCtor` param

src/operator/throttleTime.ts
Hi, @kwonoj , it's me again. 
In the params of throttleTime operator, there is a issues within the description of `scheduler` param:
`The IScheduler to use for managing the timers that handle the sampling.`
It should be `throttling` rather than `sampling`.
=> docs(throttleTime): fix the description of `scheduler` param

spec/Observable-spec.ts, src/Observable.ts
This PR fixes regression caused by https://github.com/ReactiveX/rxjs/pull/2313. While given PR sends errors thrown via `create`, it catches any exception thrown observable without having operator, so some of internals like `Subject.asObservable` doesn't throw errors in subscriber as well for cases doesn't chain any operator. This change checks if given observable created have sources, and let throw if it has source. Any exception thrown in `Observable.create` will be handled in source observable in those case.
- closes #2565
=> fix(Observable): do not swallow error thrown in subscriber

spec/schedulers/AnimationFrameScheduler-spec.ts, spec/schedulers/AsapScheduler-spec.ts, src/scheduler/AsyncAction.ts
Fixes #2594 and #2625. props to @dreamershl for pinpointing the fix!
=> fix(AsapScheduler): Fix issue where canceling an asap or animationFrame action early could throw

spec/observables/dom/ajax-spec.ts, src/observable/dom/AjaxObservable.ts
Setting `async: false` in the call to `Observable.ajax` results in an error:
> DOMException: Failed to set the 'timeout' property on 'XMLHttpRequest': Timeouts cannot be set for synchronous requests made from a document.
You can observe the behavior here: https://jsfiddle.net/jkrehm/k4o9do0q/1/
My solution is simply to wrap the code that sets `timeout` and `responseType` (also a problem) in an if-statement so they're only set if `async: true` (the default).
=> fix(ajax): Only set timeout & responseType if request is asynchronous

spec/operators/audit-spec.ts, src/operator/audit.ts
The `audit` operator was suppressing all events if the duration was `Observable.empty()` or any observable that was already complete.
There was already a similar test for this, but it relied upon `cold('|')`. It might be worth considering either duplicating tests involving `cold('|')` to use `Observable.empty()` or special-casing it to return `Observable.empty()`
=> fix(audit): mirror source if durations are Observable.empty()

spec/helpers/doNotUnsubscribe.ts, spec/operators/elementAt-spec.ts, src/operator/elementAt.ts
Force unsubscription logic in elementAt, when resulting Observable completes or errors, so that all resources are disposed as fast as possible, even if next operator in chain does not unsubscribe reliably when given complete or error notification.
General issue is described here: #2459 
Same fixes for other "`take`-like" operators: #2463 #2470
=> fix(elementAt): force unsubscribe when it completes or errors

spec/operators/reduce-spec.ts, src/operator/reduce.ts
**Description:** Update overload type definitions of operator reduce so returning type T takes precedence over returning type T[].
**Related issue (if exists):** #2519
=> fix(reduce): change order of reduce overload type definitions

spec/operators/groupBy-spec.ts, src/operator/groupBy.ts
The `groupBy` operator has a `durationSelector` argument that we can use to specify additional closings for the produced groups. However, the durationSelector produces Observables that were never unsubscribed.  (#2660)
Furthermore even if the durationSelector Observable was auto-unsubscribed (due to for example a `take(1)` in that Observable) its subscription would not be removed from the `GroupBySubscriber`, which causes memory usage to grow and eventually causes a OOM exception in @crunchie84's application. (#2661)
This PR solves both problems by explicitly unsubscribing & removing the subscription from the GroupBySubscriber. I also added a test for the unsubscribing part, but could not easily create a test in the same style as the other groupBy-tests without poking into the …
=> fix(groupBy): unsubscribe & cleanup GroupDurationSubscriber

spec/helpers/doNotUnsubscribe.ts, spec/operators/takeWhile-spec.ts, src/operator/takeWhile.ts
Force unsubscribe on `takeWhile` when it completes or errors, even when used with operator that does not unsubscribe reliably, so that source Observable is never subscribed longer than it needs to.
**Related issues:**
`takeWhile` suffered from the same problem as `first`: #2455 
It is a concrete case of more general problem: #2459
=> fix(takeWhile): force unsubscribe when it completes or errors

spec/helpers/doNotUnsubscribe.ts, spec/operators/first-spec.ts, src/operator/first.ts
Force unsubscription logic when operator completes or errors, so that source Observable is only subscribed as long as it has to, even when combined with operators that do not immediately unsubscribe
from 'first' when it completes or errors.
Introduces test-only `doNotUnsubscribe` operator, which simulates operators that are unreliable with managing subscriptions (like `switchMap` for example - see #2459).
Closes #2455
This issue is a concrete example of more general one: #2459
=> fix(first): force unsubscription logic on complete and error

spec/operators/find-spec.ts, src/operator/find.ts
It is my fault when I implemented `find` and `findIndex` operator, make emit `undefined` when there is no match to given predicate, while RxJS v4 states to emit empty observable when it does (https://github.com/ReactiveX/rxjs/issues/2515#issuecomment-291194777). 
This PR changes behavior to align with v4, when there isn't no match sequence will complete without emitting anything.
BREAKING CHANGES: if anyone used `undefined` emitted by unmatched predicate via find operator, it
won't work anymore
- closes #2515
=> fix(find): emit empty observable when predicate find no match

src/Subject.ts
https://github.com/ReactiveX/rxjs/issues/2539
=> fix(subject): Fixes signature of Subject::lift

CHANGELOG.md
Add missing entry about unsubscriptions in takeWhile. At the same time remove doubled entry about first.
Related to #2470
=> [NEXT] chore(changelog): add missing entry about takeWhile

spec/operators/elementAt-spec.ts, src/operator/elementAt.ts
=> [NEXT] fix(elementAt): force unsubscribe when it completes or errors

dangerfile.js
- adds colorization to reporting (grey for no change, red for size increase, green for size decrease)
- fixes formatting of decimals for differences
=> chore(danger): tweak size reporting

spec/observables/empty-spec.ts, spec/observables/from-spec.ts, spec/observables/never-spec.ts, spec/operators/debounce-spec.ts, spec/operators/race-spec.ts, src/Notification.ts, src/observable/ArrayLikeObservable.ts, src/observable/ArrayObservable.ts, src/observable/EmptyObservable.ts, src/observable/ForkJoinObservable.ts, src/observable/NeverObservable.ts, src/operator/ignoreElements.ts, src/operator/repeat.ts, src/operator/startWith.ts, src/operator/take.ts, src/operator/takeLast.ts
fixes #2640
BREAKING CHANGE: Previously, `Observable.never()` `Observable.empty()`
and the `.ignoreElements()` operator all returned `Observable<T>` which
was incorrect since they actually never emit anything. Now they all
return `Observable<never>` (`never` was added in TS 2.0 as a special
type)
=> fix(never): Observable.never() Observable.empty() .ignoreElements () now return Observable<never>

spec/observables/IteratorObservable-spec.ts, src/Observable.ts, src/observable/FromObservable.ts, src/observable/IteratorObservable.ts, src/util/isIterable.ts
Now that TypeScript supports down level compilation, we can safely bring back `Iterable<T>` and `Iterator<T>`.
Fixes #2306 #2535
=> Bring back Iterable<T> and Iterator<T> interfaces

spec/helpers/marble-testing.ts, spec/operators/combineAll-spec.ts, spec/operators/concatAll-spec.ts, spec/operators/concatMap-spec.ts, spec/operators/exhaust-spec.ts, spec/operators/exhaustMap-spec.ts, spec/operators/expand-spec.ts, spec/operators/filter-spec.ts, spec/operators/map-spec.ts, spec/operators/mergeAll-spec.ts, spec/operators/mergeMap-spec.ts, spec/operators/pluck-spec.ts, spec/operators/switch-spec.ts, spec/operators/switchMap-spec.ts, spec/operators/zipAll-spec.ts, src/operator/combineAll.ts, src/operator/concatAll.ts, src/operator/exhaust.ts, src/operator/mergeAll.ts, src/operator/switch.ts, src/operator/zipAll.ts
fixes concatAll, combineAll, exhaust, mergeAll, switch, zipAll.  Also made a few improvements to
how hot and cold observables are typed.  A few compiler errors were fixed due to this change.
fixes #2658 #2493 #2551
=> fix(typings): fix typings for error prone operators like concatAll

src/Notification.ts
Fixes bug caused by referencing `this` from static methods. 
=> fix(Notification): Don't reference `this` from static methods.

package.json
we were importing tslib in next major, but didn't bump it up as dependency but left it as devDep.
- closes #2709
=> fix(build): set tslib as dependency

src/Observable.ts
Fix several typos in document of Observable.ts
=> docs(Observable): fix typo

src/operator/timeout.ts
Create documentation for timeout operator, describing its two modes of usage, providing examples for both and describing inputs and outputs of the operator.
**Relates to:**
https://github.com/ReactiveX/rxjs/issues/2656
=> docs(timeout): create documentation for the operator

spec/operators/multicast-spec.ts
results1 repeated twice. changed one to results2 to check both
results1 and results2.
**Description:** Bug in tests (misprint?)
**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/2698
=> fix(multicast.spec): typo fix

src/operator/onErrorResumeNext.ts
Hi, just noticed this typo when reading the onErrorResumeNext source. Are you interested in stuff like this? Sorry if I'm just creating clutter for you, feel free to close this if that's the case.
=> docs: fix typo in jsdoc

src/operator/filter.ts
I was looking at the generated javascript today and saw that `this.predicate` was being set twice. The declaration of the `private predicate` should suffice to set the property to the argument. The additional setting is unnecessary.
=> refactor(filter): remove extra predicate setting

doc/operator-creation.md
For issue #2299. We need to educate people to publish operators as libraries, in this way fostering an RxJS ecosystem, instead of making this library thicker and harder to navigate and maintain.
=> docs(repo): add guidelines for operator PRs

spec/exports-spec.ts, src/add/observable/generate.ts, src/add/observable/onErrorResumeNext.ts, src/add/observable/race.ts, src/observable/generate.ts, src/observable/onErrorResumeNext.ts, src/observable/race.ts
Noticed there were a few static operators not exported at `rxjs/observable/*`
This PR currently fails. I can't figure out how to get these new files to be compiled into `dist/cjs/observable/`. I must be missing something cause I can't figure out how some of the other ones like `src/observable.forkJoin.ts` are being compiled but these aren't. Anyone?
If I have time, I'll add similar tests for the instance operators since it's a good idea to verify the public API is actually available.
=> add exports for missing static operators

src/observable/FromObservable.ts, src/operator/catch.ts, src/operator/defaultIfEmpty.ts
TypeScript 2.4 is more strict about assignability with generics,
and in some cases (when calling a generic function) it will infer
that the generic parameter is <{}> rather than the <T> that rxjs
typically wants.
Fix this by explicitly passing <T> in the cases where compilation
fails.
=> fixes for typescript 2.4

src/operator/timeoutWith.ts
Create documentation for timeoutWith operator, comparing it
to timeout operator, describing what fallback Observable is
needed for, showing example of usage and providing descriptions
for all parameters of the operator.
#2656
=> docs(timeoutWith): create documentation for the operator

src/observable/GenerateObservable.ts
=> fix(GenerateObservable): fix type definition for GenerateObservable

spec/operators/every-spec.ts, spec/operators/filter-spec.ts, spec/operators/find-spec.ts, spec/operators/findIndex-spec.ts, spec/operators/map-spec.ts, spec/operators/partition-spec.ts, spec/operators/switch-spec.ts, src/operator/every.ts, src/operator/filter.ts, src/operator/find.ts, src/operator/findIndex.ts, src/operator/map.ts, src/operator/partition.ts
updated all operators to use this context, if they supply a thisArg, (map, filter, etc)
=> feat(typings): propogate thisArgs using this syntax

spec/util/subscribeToResult-spec.ts, src/util/subscribeToResult.ts
#2626 fixed error to be thrown when observable have sources, but it doesn't cover cases of inner observable with `subscribeToResult` as it doesn't have sources. This PR explicitly sets subscriber's `syncErrorThrowable` for inner observables, let exception in subscribers correctly thrown with inner observables as well.
- closes #2618
=> fix(subscribeToResult): throw error in subscriber with inner observable

src/operator/isEmpty.ts, src/operators/index.ts, src/operators/isEmpty.ts
=> feat(isEmpty): add higher-order lettable version of isEmpty

src/operator/merge.ts, src/operators/index.ts, src/operators/merge.ts
=> feat(merge): add higher-order lettable version of merge

src/operator/multicast.ts
Make clear that multicast can be used in two separate modes. Describe two modes and provide examples for both. Add note how multicast relates to Subjects and several publish and share operators.
=> docs(multicast): enhance the documentation

spec/operators/zip-spec.ts, src/operator/zip.ts
Add signature to zipProto so it's consistent with zipStatic.
**Description:** Add a rest parameters signature that does not include a `project` function.
At the moment, `zipProto` is not consistent with `zipStatic`, as the only rest parameter signature accounts for a project function, and if it's not specified, the result is of type `Observable<{}>` - losing the type information.
**Related issue (if exists):** #2784
=> chore(typings): improve zip typings

src/observable/dom/AjaxObservable.ts
A non-2xx HTTP response may include a body to provide context to the error. Provide the ability to
retrieve the response from the AjaxError as you would from an AjaxResponse.
=> feat(AjaxError): Include the response on instances of AjaxError

src/operator/share.ts
Improve documenation on how .share() is different from .publish().refCount().
Please let me know if I should change the verbage, documentation is hard.
=> chore(documentation): Update share documentation

src/operator/takeUntil.ts
If this takeUntil test is correct then I believe the comment is wrong, it will not stop taking values if the notifier completes without emitting any values (empty).
https://github.com/ReactiveX/rxjs/blob/master/spec/operators/takeUntil-spec.ts#L38-L48
=> Correct takeUntil comment - does not stop taking values if notifier completes without emitting

spec/operators/partition-spec.ts, src/operator/partition.ts, src/operators/partition.ts
This PR adds the index parameter to the predicate signature for the partition operator. This change matches the docs as well as the existing `filter` operator.
=> fix(partition): update signature to match docs and filter operator

doc/lettable-operators.md
=> docs: Fix typo in lettable operators article

spec/Observable-spec.ts
interestingly path resolution for module import on windows doesn't seem to work 🤔 
=> build(test): fix build failure on windows

doc/lettable-operators.md
`let` me just say I'm super freakin' excited for the lettable operators, thanks for this
=> dont' -> don't

.make-packages.js
Related to #2857
This PR gets rid of the TypeScript sources that are currently being distributed. They were added some time ago unintentionally and shouldn't be there.
It also changes where the `d.ts` files live, which should fix a problem where IDEs using features such as `Quick Fix` will import from the wrong location.
=> fix(package): remove src directory and fix typings location

doc/lettable-operators.md
=> docs: fix typo in lettable operators doc

src/Rx.ts
=> feat(global): export lettables as Rx.operators

.make-packages.js, package.json
Changing the build slowed down the `npm run build_test` command significantly. This PR should improve speed by only building one copy of the sources. It still runs the same packaging code, skipping packaging of ESM5 and ESM2015.
=> fix(build): make build_test run the minimum to speed it up

src/operator/concatAll.ts, src/operator/mergeAll.ts
Correct lettable operators:
```
mergeAll
concatAll
```
=> Lettable operators4

src/operators.ts
* This re-export was added to support CJS and internal require statements.
Those internal requires were require('rxjs/operators') and with SystemJS
this would try to find a "rxjs/operators.js" file. Now that the internal
references have changed to deep imports, we should remove this re-export
to ensure we don't again add internal references to rxjs/operators.
=> refactor: remove src/operators.ts re-export

src/observable/FromEventObservable.ts
**Description:** Fix compilation error in FromEventObservable.ts file:
```bash
static create<T>(target: EventTargetLike, eventName: string, selector: SelectorMethodSignature<T>): Observable<T>;
~~~~~~
dist/cjs/src/observable/FromEventObservable.ts(57,10): error TS2394: Overload signature is not compatible with function implem
entation.
```
This is my first contribution to this repo so if there is something missing please let me know =)
Thanks.
=> [Fix] Make overload signature compatible in FromEventObservable

spec/observables/from-promise-spec.ts, src/observable/dom/WebSocketSubject.ts
**Description:** This PR fixes remaining compiler errors in unit tests along with [this one](https://github.com/ReactiveX/rxjs/pull/2893).
Once both merged you should have all tests passing.
BTW:
There is one small change in the `WebSocketSubjectConfig` type and I just want to make sure that the change I made actually makes sense.
So basically there is a property named `resultSelector` which is a function - result of which was generic.
And I bound it's generic type to `WebSocketSubject` generic type (in order to fix compiler error) assuming that this is what user will get after this function will run.
And now basically `resultSelector` prop of `WebSocketSubjectConfig` (if provided) will drive inferred type of the whole `WebSocketSubject` for ex:
```ts
const sock$ = …
```
=> [Test] Fix types in WebSockerSubject and from-promise-spec

doc/styles/main.css
When the website  chosen theme is on the light mode, and you search something, mouse hovering on link will make it disappear because the `: hover` of the link is still white but there is not any background (same as dark-theme) for the search-result container. 
The simple style will resolve the problem
The image below show the problem, you will see a white space which is where I put the mouse on a link.
=> docs: style problem in light theme

src/observable/FromEventObservable.ts
* Add list of types of event targets fromEvent accepts.
* Add details and and example about optional parameters for addEventListener. 
* Add note about callback-oriented APIs and operators that might be more useful in that case.
* Describe when fromEventPattern would be more useful.
* Add note that only first argument from event handler will appear in Observable and describe how optional project function mitigates that problem.
=> docs(fromEvent): add more details about the operator

spec/operators/scan-spec.ts
Test the .scan operator from `scan-spec.ts` instead of `.reduce`
=> test(scan-spec): Change use of .reduce to .scan in scan-spec.ts

spec/operators/multicast-spec.ts, spec/operators/publish-spec.ts, src/operator/multicast.ts, src/operator/publish.ts, src/operators/multicast.ts, src/operators/publish.ts
Fixes the typings for `publish` and `multicast`, so that selectors that change the observable's type are supported.
Adds some typings tests for `publish` and `multicast`.
**Related issue (if exists):** #2889
=> fix(publish): fix selector typings

appveyor.yml, package.json
There are recent script updates doesn't work on windows, this PR fixes and enables windows CI as well to catch platform specific issues.
=> ci(appveyor): enable windows build test

src/operator/toPromise.ts, src/operators/toPromise.ts
Add overload signatures that use TypeScript's built-in `PromiseConstructorLike` and
`PromiseLike` types.
**Related issue (if exists):** #2904
=> chore(typings): improve toPromise typings

spec/operators/shareReplay-spec.ts, src/operators/shareReplay.ts
When the refCount hits zero, and the source has neither completed nor errored, `shareReplay` will now properly stay subscribed to the source, and retain the internal ReplaySubject that is caching values
fixes #2908
=> fix(shareReplay): properly retains history on subscribe

src/operators/shareReplay.ts
This PR changes `isComplete` from being always `true` to representing whether or not
the source is actually complete and changes the logical test accordingly.
Without the change, `isComplete` is always `true` and the `unsubscribe` call made using the subscription to the source can never occur - regardless of the `refCount`.
With the change, the call will happen, but only if the `refCount` is zero and the source has completed.
If the source has completed, the `unsubscribe` call is redundant and the `refCount` is irrelevant. If you want, the implementation could be simplified to take that into account, like this:
```ts
export function shareReplay<T>(bufferSize?: number, windowTime?: number, scheduler?: IScheduler ): MonoTypeOperatorFunction<T> {
let subject: …
```
=> refactor(shareReplay): align logic with var names

spec/operators/shareReplay-spec.ts, src/operators/shareReplay.ts
- adds a test to ensure lift it being used.
- uses lift.
NOTE: this is a first attempt also at using `lift` in a non-class-based (but also non-breaking) way.
=> fix(shareReplay): again uses `lift`

src/operators/index.ts
=> fix(flatMap): reexport flatMap as alias of mergeMap

src/operators/shareReplay.ts
As @kwonoj mentioned in the other PR, #2924, we don't need to export that the operator function.
=> fix(shareReplay): no longer exporting function unnecessarily

.make-packages.js
We need this additional mapping so Webpack never passes through the CJS version of `rxjs/operators` (which will result in a much larger bundle size).
=> refactor: add mapping for rxjs/operators to help with treeshaking

doc/lettable-operators.md
Docs on how to use `rxjs/operators`. If users don't follow these docs/steps, they will end up bloating their applications by pulling in more of Rx than they intend to.
=> Document lettable imports

spec/operators/publishReplay-spec.ts, src/operator/publishReplay.ts, src/operators/publishReplay.ts
This PR adds selector function to the `publishReplay` operator similarly to `publish`.
I didn't modify any existing tests. However, this could be probably a breaking change because I added the parameter before `scheduler` (I'm not sure this is a problem or not).
#2844
=> feat(publishReplay): add selector function to publishReplay

src/observable/dom/AjaxObservable.ts
https://github.com/ReactiveX/rxjs/issues/2971
=> fix(ajaxobservable): fix operator import path

.make-packages.js, doc/lettable-operators.md
Using `__dirname` directly in the `path-mapping.js` file should be more reliable and should always be accurate. This simplifies setting up the aliases for Webpack to map to the `esm` distribution.
Output in the `path-mapping.js` file will now look like this:
```
"use strict"
var path = require('path');
module.exports = function() {
return {
"rxjs/AsyncSubject": path.resolve(__dirname, "AsyncSubject.js"),
"rxjs/add/observable/interval": path.resolve(__dirname, "add/observable/interval.js"),
"rxjs/util/tryCatch": path.resolve(__dirname, "util/tryCatch.js"),
// ...
};
}
```
=> Simplify webpack alias

.make-packages.js
=> build: remove 'module' and 'es2015' keys to avoid resolution conflicts

src/operators/share.ts
As suggested by https://github.com/ReactiveX/rxjs/issues/2937 this updates the docs on the share
operator to better reflect it's actual behaviour.
This now correctly references the correct alias for the `share` operator.
https://github.com/ReactiveX/rxjs/issues/2937
=> docs(Observable): fix docs about the share operator

.make-packages.js
Needed due to Webpack issue where sequence of the "alias" object keys matters:
https://github.com/webpack/webpack/issues/5870
=> refactor: move re-export file mapping to bottom of mapping file

doc/lettable-operators.md
**Description:** Small fix to lettable-operators.md that changes "utils" to "util" when describing the "pipe" utility function.
=> docs: Small fix to lettable-operators.md

src/operator/publishReplay.ts
In src/operator/publishReplay.ts, the delegating call to higherOrder (which is an alias for publishReplay in src/operators/publishReplay.ts), has arguments that don't provide enough information to infer type arguments. That's because the third argument is cast to any, which is because it's just a delegation; a call to publishReplay could delegate to any of the three overloads of higherOrder. The compiler has to choose one, however, and it chooses the wrong one in Typescript 2.6.
This change provides the type arguments explicitly so that the most general overload gets called. This results in the the correct return type, `OperatorFunction<T, R>`.
#2991
=> operator/publishReplay.ts:give type arguments to higherOrder call

spec/operators/multicast-spec.ts, spec/operators/publish-spec.ts, spec/operators/publishBehavior-spec.ts, spec/operators/publishLast-spec.ts, spec/operators/publishReplay-spec.ts, src/operators/multicast.ts, src/operators/publish.ts, src/operators/publishLast.ts
Use `ConnectableObservable` in signatures that do not have selectors.
This PR updates the overload signatures for lettable/pipeable `publish`, `publishLast` and `multicast` operators so that `ConnectableObservable` is specified where appropriate.
<s>I've not included `type` tests, as it's not apparent where they should be placed. That is, the lettable operators appear to be tested via the prototype-patched operators in `spec/operators`. If you'd like the typings tests for the lettables added in the same location, please let me know and I'll add them.</s>
The PR does not completely resolve the issue below, but it is directly related to it. And these changes would need to be made as the first step in resolving the issue.
**Related issue (if exists):** #2972
=> chore(typings): improve publish typings

src/observable/combineLatest.ts, src/operators/zip.ts
Most of the TypeScript overloads for operators that take a projection function place the overloads that include projection functions before the overloads that do not. That's the way it should be.
However, there are two that do not:
* the static `combineLatest` operator; and
* the static `zip` operator.
The problem is that a projection function can be matched against `ObservableInput<any>`, as any function will match `ArrayLike<any>`. That means the overloads that include projection functions are more specific and should be placed first. If they are not, this:
```ts
const ob = Observable.combineLatest<any, any>(
Observable.of(1),
(value: any) => value
);
```
will match this:
```ts
export function combineLatest<T, T2>(v1: ObservableInput<T>, v2: ObservableInput<T2>, …
```
=> chore(typings): reorder project overloads

src/observable/BoundCallbackObservable.ts
Documentation Updates for BoundCallbackObservable.
I noticed the documentation was missing a lot of articles which made it harder to read, and at times harder to understand.  I've updated the documentation to improve readability and increase clarity with minimal impact on voice and meaning.
N/A
=> Updated BoundCalbackObservable Docs

spec/observables/IteratorObservable-spec.ts, src/observable/IteratorObservable.ts
Our `IteratorObservable` gets an iterator from the object once only when it's constructed, so any subsequent subscription is not able to iterate since the first subscription will make iterator completes.
This PR updates behavior to get corresponding new iterator per each subscription, allows any subscription can correctly iterate object. I'm labeling this for next patch version, since I believe this isn't breaking changes.
- closes #2496
=> fix(IteratorObservable): get new iterator for each subscription

spec/operators/partition-spec.ts, spec/operators/repeat-spec.ts
We had a few slip past the radar on us that weren't really testing anything of value. See the commit messages for more detail.
=> Removing tests that don't make any sense

doc/decision-tree-widget/tree.yml, src/operator/takeUntil.ts, src/operators/takeUntil.ts
This PR only updates `takeUntil` docs to reflect its functionality.
#2160
=> docs(takeUntil): update docs to match operator's behavior

doc/writing-marble-tests.md
Description: Small fix to the examples that were missing their closing single quotation mark.
=> docs: Small fix to writing-marble-tests.md

spec/helpers/test-helper.ts, tsconfig.json
**Description:** This fixes all the warnings output by running `tsc` at the project's root by adding types for `node` and `mocha`, and also fixing a TS4023 issue.
**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/3020
=> fix(TSC): Fixing TSC errors. Fixes #3020

spec/helpers/test-helper.ts, tsconfig.json
Reverts ReactiveX/rxjs#3022
This PR doesn't solve problem.
=> Revert "fix(TSC): Fixing TSC errors. Fixes #3020"

spec/observables/combineLatest-spec.ts, spec/observables/forkJoin-spec.ts, spec/observables/from-spec.ts, spec/observables/zip-spec.ts, spec/operators/mergeMap-spec.ts, spec/operators/mergeMapTo-spec.ts, spec/operators/reduce-spec.ts, spec/operators/scan-spec.ts, spec/operators/toArray-spec.ts
This is a maintenance PR. In looking to add some tests for #2855, I found a bunch of typings tests - see the [`type`](https://github.com/ReactiveX/rxjs/blob/5.4.3/spec/helpers/testScheduler-ui.ts#L91-L100) function - that are wrapped in `it` calls. I've unwrapped them.
I've made the changes in three commits so that it should be a little easier to review what was changed. I'll squash them, if you're happy with the changes made in the PR.
**Related issue (if exists):** None.
=> chore(typings): unwrap it-wrapped type tests

src/observable/UsingObservable.ts
Document 'using' operator, describing what it accepts and returns. Describe how resulting Observable will behave and when unsubscribe method from resource object will be called.
@trxcllnt Since you contributed that operator, can you help me out with finding some decent example? I was able to provide description, but couldn't come up with realistic scenario for using `using`.
=> docs(using): document the operator

MIGRATION.md
Remove `shareReplay` from the **Operators Renamed or Removed** list in `MIGRATION.md`, as it was implemented in [5.4.0](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#540-2017-05-09) and its listing is causing confusion.
**Related issue (if exists):** #3034
=> docs(MIGRATION): remove shareReplay

.gitignore
Make Git ignore IntelliJ IDEA module (*.iml) files.
Depending on the personal preferences user can keep IntelliJ IDEA module (*.iml) files  in project root directory. This change makes Git ignore these files.
N/A
=> chore(gitignore): ignore IntelliJ IDEA module files

src/operators/tap.ts
This is possible at runtime, but the typings don't reflect it and it's annoying when only wanting to tap into error or complete.
closes #2534
=> fix(tap): make next optional

src/interfaces.ts
Regarding [this issue](https://github.com/Microsoft/TypeScript/issues/19198) - that was opened in the TypeScript repo - there is a simple resolution: replace the type aliases with interfaces.
The TypeScript documentation for [advanced types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) includes these comments in the **Type Aliases** section:
> One difference is that interfaces create a new name that is used everywhere. Type aliases don’t create a new name — for instance, error messages won’t use the alias name. [...]
>
> A second more important difference is that type aliases cannot be extended or implemented from (nor can they extend/implement other types). Because an ideal property of software is being open to extension, you should always use an …
=> refactor(interfaces): replace type aliases

spec/schedulers/AsapScheduler-spec.ts, src/scheduler/AsyncAction.ts
In `AsyncAction`, `this.pending` was assigned before the call to `recycleAsyncId`. That prevented the interval from being re-used resulting in the interval being cleared and re-created for each notification.
<s>I cannot see how a test could be easily written for this, but the logic is straightforward.</s>
**Related issue (if exists):** #3042
=> fix(scheduler): prevent unwanted clearInterval

.travis.yml
Seems we're having too frequent failure around caching whole node_modules, instead caching npm cache location itself as recommended.
=> chore(travis): update cache configuration

spec/operators/toArray-spec.ts, src/operators/toArray.ts
The current implementation of `Observable.toArray` reuses the same array instance for multiple subscriptions.
This example clarifies why that's wrong.
```js
const Rx = require('rxjs/Rx');
const observable = Rx.Observable.from([1,2]).toArray();
observable.take(1).subscribe(console.log); // prints [ 1, 2 ]
observable.take(1).subscribe(console.log); // prints [ 1, 2, 1, 2 ]
```
=> fix(Observable.toArray): Fix Observable.toArray with multiple subscriptions.

CODE_OF_CONDUCT.md
Just updating to the latest version of Contributor Covenant. 
I does occur to me that it's not optimal that there are only men to contact in order to report an issue. Some people might not be comfortable with that. We might want to invite a non-core team member to help field any issues that come up, at least until (hopefully) we have some more diverse contributors and core team members we can get to join us.
The best I can do at this time is vow that we'll be fair and just and try to protect our contributors and community from harm.
Thus far we have had zero incidents, but our contributor community is small and growing. Please continue to be kind and respectful. Thanks!
=> chore(CodeOfConduct): Update Code of Conduct

src/Observable.ts
Remove the no-arg overload. If not removed, any Observable will be compatible with any ObservableInput regardless of type - as T does not appear in the no-arg overload.
Closes #3052
The overload signatures for `subscribe` include a signature that takes no parameters. This is a problem and results in any `Observable` being deemed compatible with any `ObservableInput`.
For example, this code will compile without error:
```ts
import { Observable, ObservableInput } from "rxjs/Observable";
import "rxjs/add/observable/of";
const numbers = Observable.of<number>(1);
const strings = Observable.of<string>("1");
let input: ObservableInput<string>;
input = numbers;
input = strings;
```
The problem is caused by `T` not appearing in the signature. The signature should be removed and …
=> fix(typings): fix subscribe overloads

src/observable/merge.ts, src/operator/concat.ts, src/operator/merge.ts, src/operators/concat.ts, src/operators/merge.ts
Export of `concatStatic` from `operator/concat` was removed on 5.5.
While I could easily replace : 
```ts
import { concatStatic } from 'rxjs/operators/concat';
```
with
```ts
import { concat } from 'rxjs/observable/concat';
```
this is still a breaking change that could affect other projects.
=> fix(concatStatic): missing export creating breaking change

spec/schedulers/AsapScheduler-spec.ts, src/scheduler/AsyncAction.ts
This reverts commit 7d722d4d36debcf5bb79fa4006f455bd72caeee1.
fixing regressions.
- closes #3151
=> fix: Revert "fix(scheduler): prevent unwanted clearInterval (#3044)"

spec/schedulers/AsapScheduler-spec.ts, src/scheduler/AsyncAction.ts
This reverts commit 7d722d4d36debcf5bb79fa4006f455bd72caeee1.
=> Cherry pick #3152 into stable

package.json, spec/schedulers/AsapScheduler-spec.ts, src/scheduler/AsyncAction.ts
This reverts commit 7d722d4d36debcf5bb79fa4006f455bd72caeee1.
cherry-pick https://github.com/ReactiveX/rxjs/pull/3152
#3151
=> fix(scheduler): resolve regression on angular router with zones

README.md
Since I got confused and did mistake while cherrypicking.. :p
=> docs(readme): update branch description

.travis.yml, appveyor.yml, package.json
We don't use `symbol-observable` for dependency anywhere, moving it into devdep.
=> fix(dependency): move symbol-observable into devdependency

.make-packages.js, src/BUILD.bazel, src/WORKSPACE
Same as #3131 but onto the stable branch
=> build(bazel): adds bazel build files to support building rxjs with bazel from dist [stable branch]

spec/Observable-spec.ts, src/Observable.ts, src/Subscriber.ts
This is an attempt at fixing the rethrow issues in #2813. Some of them have been fixed by previous PRs, but other cases still remain. _So far_ every one I've seen has been fixed by this PR.
I'll be totally honest though, why this works isn't 100% clear. The `syncErrorThrowable` stuff is pretty hairy. I tried to map out what `syncErrorThrowable` is being used for, when its set correctly, when its not, etc and noticed a pattern that errors were going down the `_trySubscribe` when there was a `this.source` but that **always** expected `syncErrorThrowable = true` otherwise the [condition right after](https://github.com/jayphelps/rxjs/blob/541b49db0ca4079760f92f670a49a8f06dc83dd2/src/Observable.ts#L205-L210) wouldn't do the rethrowing.
Mostly what's not clear is why this only happens with …
=> fix(Observable): Another attempt at fixing error rethrows in v5

doc/operator-creation.md
The operators creation guide was recommending the usage of `let` method in Observables.
But from v5.5, we have lettable operators. Better suggest new users to use `pipe` instead.
=> docs: use `pipe` method for showing usage of operators as pure functions

src/scheduler/AnimationFrameAction.ts
When you use .bind in typescript you lose type safety
https://www.typescriptlang.org/play/#src=class%20Person%20%7B%0D%0A%20%20%20%20private%20name%3A%20string%3B%0D%0A%0D%0A%20%20%20%20speak(msg)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%60%24%7Bmsg%7D%20%24%7Bthis.name%7D%60)%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20look%20no%20exceptions!%0D%0A%20%20%20%20%20%20%20%20setTimeout(this.speak.bind(this)%2C%2010)%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aclass%20PersonSafe%20%7B%0D%0A%20%20%20%20private%20name%3A%20string%3B%0D%0A%0D%0A%20%20%20%20speak(msg)%20%7B%0D%0A%20%20%20%20%20%20%20%20console.log(%60%24%7Bmsg%7D%20%24%7Bthis.name%7D%60)%0D%0A%0D%0A%20%20%20%20%20%20%20%20%2F%2F%20look%20no%20exceptions!%0D%0A%20%20%20%20%20%20%20%20setTimeout(()%20%3D%3E%20this.speak()%2C%201 …
=> 🛑 Remove .bind loss of type safety.

doc/lettable-operators.md
Tell folks migrating to 5.5 that the  `let` operator is now `pipe`.
Also tell them about:
* `Observable.toPromise` (no more `toPromise` operator
* `Observable.throw` is on the prototype and `import { throw } from 'rxjs/observable/throw'` won't work (for obvious reasons).
=> docs: explain where let operator went in lettable-operators.md

src/operator/mergeScan.ts, src/operators/mergeScan.ts
should be able to use `async await` in `mergeScan`
```ts
Observable.of(1, 2, 3)
.pipe(
mergeScan(async (acc, cur) => {
await sleep(cur)
acc.push(cur)
return acc
}, [])
)
```
=> fix(typings): the return type of project of mergeScan should be ObservableInput<R>

spec/operators/debounce-spec.ts, spec/operators/debounceTime-spec.ts, src/operators/debounce.ts, src/operators/debounceTime.ts
Currently the second value is swallowed because `hasValue` is set to `false` in between the scheduling of the second and its execution.
fixes #2748
```js
const results = [];
const source = new Rx.Subject();
const scheduler = new VirtualTimeScheduler();
source.debounceTime(0, scheduler).subscribe(value => {
results.push(value);
if (value === 1) {
source.next(2);
}
});
source.next(1);
scheduler.flush();
expect(results).to.deep.equal([1, 2]);
```
@kwonoj you had mentioned in #2748 that rxjs doesn't guarantee reentrancy, though I think in this case the fix is simple. Are there reasons to explicitly not do it in this case?
FWIW the regular `debounce` operator [already supports reentrancy](https://github.com/ReactiveX/rxjs/blob/master/src/operators/debounce.ts#L132-L134), so I added a test for …
=> fix(debounceTime): synchronous reentrancy of debounceTime no longer swallows the second value

doc/lettable-operators.md
=> docs(lettable-operators): add missing quote

src/operators/ignoreElements.ts
Minor optimization in `ignoreElements` operator.
We don't need to call any kind of `noop` function, simply do not call anything.
I mean, sure, it's not a bottleneck by no means, but better without, right?
=> Minor optimization in ignoreElements operator

doc/styles/main.css
The selector in body.light-theme. layout-container doens't work, because the class light-theme is apply with layout-container in same element
Example ![Example](https://i.imgur.com/W21titb.jpg)
=> Fix menu item hover and active in light theme

.make-packages.js, src/BUILD.bazel, src/WORKSPACE
Adds `WORKSPACE` and `BUILD.bazel` files to `/src` folder so they end up in `/dist/package/src` and copies `/tsconfig.json` to `/dist/packages/src` for external bazel build support.
Bazel built projects that pull in rxjs from npm can build it with Bazel with the following configuration in their WORKSPACE file:
```
local_repository(
name = "rxjs",
path = "node_modules/rxjs/src",
)
```
and using the following dependency on targets that depend on rxjs:
```
"@rxjs//:rxjs"
```
An example of this can be found here: https://github.com/gregmagolan/webpack-typescript-benchmarking/tree/bazel-rxjs
=> build(bazel): adds bazel build files to support building rxjs with bazel from dist

README.md, package.json
I've noticed there were some leftovers from #2851.
I added more comments to appropriate lines in code.
=> chore(README.md, package.json): Update npm script documentation

spec/Observable-spec.ts, spec/Subscription-spec.ts
This PR adds types needed to fix type errors/warnings in tests. It doesn't change any functionality.
=> fix: correct compilation warnings from missing types in tests

spec/operators/debounce-spec.ts, src/internal/operators/debounce.ts
Adds a failing test and then fixes `debounce` so that selectors returning scalar observables are supported.
**Related issue (if exists):** #3232
=> fix(debounce): support scalar selectors

src/internal/observable/DeferObservable.ts
should be able to defer a `ArrayLike` result
```ts
Observable.defer(() => [1, 2, 3])
```
=> fix(typings): the return type of factory of defer should be ObservableInput<T>

spec/operators/throttle-spec.ts, src/internal/operators/throttle.ts, src/internal/patching/operator/throttle.ts
Changes the typings for the `throttle` method's selected observable to `any` - in line with the typings used for other methods that include selectors for notification observables. E.g. [`audit`](https://github.com/ReactiveX/rxjs/blob/5.5.4/src/operators/audit.ts#L52).
**Related issue (if exists):** #3204 (also see PR #3169)
=> fix(typings): relax throttle selector type

spec/operators/debounce-spec.ts, src/internal/operators/debounce.ts, src/internal/patching/operator/debounce.ts
Changes the typings for the `debounce` method's selected observable to `any` - in line with the typings used for other methods that include selectors for notification observables. E.g. [`audit`](https://github.com/ReactiveX/rxjs/blob/5.5.4/src/operators/audit.ts#L52).
**Related issue (if exists):** #3164
=> fix(typings): relax debounce selector type

spec/observables/forkJoin-spec.ts, src/internal/observable/ForkJoinObservable.ts
Fixes `forkJoin` so that errors thrown from within the selector are no longer unhandled.
**Related issue (if exists):** #3216
=> fix(forkJoin): catch and forward selector errors

spec/util/subscribeToResult-spec.ts, src/internal/observable/from.ts, src/internal/observable/fromArray.ts, src/internal/observable/fromIterable.ts, src/internal/observable/fromObservable.ts, src/internal/observable/fromPromise.ts, src/internal/util/subscribeTo.ts, src/internal/util/subscribeToArray.ts, src/internal/util/subscribeToIterable.ts, src/internal/util/subscribeToObservable.ts, src/internal/util/subscribeToPromise.ts, src/internal/util/subscribeToResult.ts
This is a multistep refactor, please review each commit separately to help you grok the refactor.
`subscribeToResult` was responsible for optimizations when subscribing to inner observables in operators like `mergeMap`, `switchMap`, et al.
`from` is... well... `from`.
This PR unifies the logic from `subscribeToResult` and `from`, because they were basically doing exactly the same thing. The former was taking some object and tying a Subscriber to it.. the later was returning an Observable, which in subscription, takes some object and ties a Subscriber to it.
Notes:
- Error messages are now also unified, so they have changed slightly for `from(wrongThingHere)`
=> Functional refactor of `from` and `subscribeToResult`

src/internal/observable/dom/AjaxObservable.ts
TypeScript seemed to have an issue with XHR all of a sudden, I presume it's some TS update, quick fix any for now to fix the build
=> chore(BUILD): fix broken build

spec/observables/onErrorResumeNext-spec.ts, src/internal/observable/onErrorResumeNext.ts
Reduces the size of onErrorResumeNext. 
Fixes an issue where `onErrorResumeNext` was holding onto all inner subscriptions for the lifetime of the resulting observable.
Updates documentation
related #2459
closes #3178
=> fix(onErrorResumeNext): no longer holds onto subscriptions too long

src/internal/Observable.ts
The spread overload of the `pipe` method was not present in the typings for `Observable`.  This PR corrects this.  This is required for TS 2.7 compatibility as it provides stricter parameter checking.
=> fix(Observable): expose pipe rest parameter overload

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
[ReactiveX/rxjs-docs#249](https://github.com/ReactiveX/rxjs-docs/issues/249)
hey @benlesh and @ladyleet, like discussed here is the pr to reference to documentation project. If there is another file where I should add a reminder, please let me know :)
=> docs(documentation): reference the rxjs-doc repository

.make-packages.js
=> fix(rxjs): make sure esm imports from index.js by default, not Rx.js

.gitattributes, spec/Observable-spec.ts, spec/observables/IteratorObservable-spec.ts, spec/observables/empty-spec.ts, spec/observables/from-promise-spec.ts, spec/observables/from-spec.ts, spec/observables/of-spec.ts, spec/observables/onErrorResumeNext-spec.ts, spec/observables/throwError-spec.ts, spec/observables/timer-spec.ts, spec/symbol/iterator-spec.ts, spec/tsconfig.json, spec/util/pipe-spec.ts, spec/util/subscribeToResult-spec.ts, src/add/observable/throw.ts, src/internal/Observable.ts, src/internal/observable/from.ts, src/internal/observable/fromObservable.ts, src/internal/observable/fromPromise.ts, src/internal/observable/of.ts, src/internal/symbol/observable.ts, src/internal/types.ts, src/internal/util/isIterable.ts, src/internal/util/isObservable.ts, src/internal/util/isPromise.ts, tsconfig.json, tsconfig.vscode.json, tsconfig/tsconfig.base.json
Follow up to #3265 (merge/rebase after the above is done).  The best commit to compare against is https://github.com/ReactiveX/rxjs/pull/3317/commits/43fdddc03a9459a19a853534686aa10be2133a1b
* Moved `Subscribable<T>`, `SubscribableOrPromise<T>` and `ObservableInput<T>` to `types.ts`.
* Added `ObservableLike<T>` using `[Symbol.observable]()`
* Added augmentation to make `Symbol.observable` resolve properly.
* `fromObservable` now requires `ObservableLike<T>`
* `of` now creates a type union for the first few overloads of the method.
* `isIterable` now returns `input is Iterable<any>`
* `isObservable` now returns `input is ObservableLike<any>`
* `isPromise` now returns `value is PromiseLike<any>` instead of `Promise<T>`
* Cleaned up tests for the related specs that were …
=> refactor(typings): updated typings to support symbol observables and iterables

spec/operators/multicast-spec.ts, spec/operators/publish-spec.ts, spec/operators/publishBehavior-spec.ts, spec/operators/publishLast-spec.ts, spec/operators/publishReplay-spec.ts, src/internal/operators/multicast.ts, src/internal/operators/publish.ts, src/internal/operators/publishReplay.ts, src/internal/patching/operator/multicast.ts, src/internal/patching/operator/publish.ts, src/internal/patching/operator/publishReplay.ts
* `multicast` now returns ConnectableObservable when not given a selector.
* `publish` had an issue with overload resolution
* Fixes typing errors in related spec files
=> feat(typings): fixed some cases where multicast and publish would not return a ConnectableObservable

.make-packages.js, src/ajax/package.json, src/operators/package.json, src/testing/package.json, src/websocket/package.json
See #3227
I didn't do anything for `@reactivex/rxjs` package because I'm hopeful for its elimination (#2916) and I'm not entirely sure how it works lol.
=> fix(ESM): Add operators/package.json for ESM support, fixes #3227

src/internal/observable/dom/AjaxObservable.ts
The XMLHttpRequest type is defined to always have the `request`
property. This will lead 2.7 to infer `never` for the else
part of any test of the form `'request' in xhr` as this, as far
as the declarations are concerned, is always true and TypeScript
then infers the else part will `never` run.
This change prevents this inference wihtout removing the type
checking of the other members of xhr such as `responseText`.
See commit text above.
=> refactory: improve hack for XMLHttpRequest usage with TypeScript 2.7

src/observable/dom/AjaxObservable.ts
TypeScript seemed to have an issue with XHR all of a sudden, I presume it's some TS update, quick fix any for now to fix the build
cherry-pick of #3285 to stable branch
/cc @chuckjaz
=> chore(BUILD): fix broken build (#3285)

spec/observables/forkJoin-spec.ts, spec/operators/concatMap-spec.ts, spec/operators/concatMapTo-spec.ts, spec/operators/exhaustMap-spec.ts, spec/operators/first-spec.ts, spec/operators/last-spec.ts, spec/operators/mergeMap-spec.ts, spec/operators/mergeMapTo-spec.ts, spec/operators/switchMap-spec.ts, spec/operators/switchMapTo-spec.ts, src/internal/observable/forkJoin.ts, src/internal/operators/concatMap.ts, src/internal/operators/concatMapTo.ts, src/internal/operators/exhaustMap.ts, src/internal/operators/first.ts, src/internal/operators/last.ts, src/internal/operators/mergeAll.ts, src/internal/operators/mergeMap.ts, src/internal/operators/mergeMapTo.ts, src/internal/operators/switchMap.ts, src/internal/operators/switchMapTo.ts, src/internal/patching/operator/concatMap.ts, src/internal/patching/operator/concatMapTo.ts, src/internal/patching/operator/exhaustMap.ts, src/internal/patching/operator/first.ts, src/internal/patching/operator/last.ts, src/internal/patching/operator/mergeMap.ts, src/internal/patching/operator/mergeMapTo.ts, src/internal/patching/operator/switchMap.ts, src/internal/patching/operator/switchMapTo.ts
This is an experimental PR that is aiming to remove all superfluous resultSelector arguments from operators and observable creators.
To start with I've done `mergeMap`, `mergeMapTo`, `switchMap`, `switchMapTo`, `concatMap`, `concatMapTo` and `forkJoin`.
See commit messages for more detail.
This is aimed at smaller size, simplifying the API, simplifying the code base, and simplifying TypeScript typings. 
Just doing it makes it clear that it's a solid decision, as the code cleans up substantially everywhere it's done.
Relates to #2929
=> Removing resultSelectors (WIP)

spec/index-spec.ts, src/index.ts
Realized we weren't exporting custom error types so people couldn't do `instanceof` checks.
=> fix(rxjs): once again exports custom error types

spec/observables/bindNodeCallback-spec.ts, src/internal/observable/bindNodeCallback.ts
- Removes the optional result selector to simplify the API
BREAKING CHANGE: resultSelector removed, use `map` instead: `bindNodeCallback(fn1, fn2)()` becomes `bindNodeCallback(fn1)().pipe(map(fn2))`
=> feat(bindNodeCallback): remove resultSelector

src/internal/types.ts
[`PartialObserver` is defined in `types.ts`](https://github.com/ReactiveX/rxjs/blob/1e4ca05ab247eedc3d7db233874e650439f09fbd/src/internal/types.ts#L69) . Importing it again causes a build error in google3.
=> fix(rxjs): remove types.ts importing from itself.

spec/ajax/index-spec.ts, spec/index-spec.ts, src/ajax/index.ts, src/index.ts, src/internal/operators/timeInterval.ts, src/internal/operators/timestamp.ts, src/internal/types.ts
Includes:
`rxjs`:
Operator
Subscriber
AsyncSubject
ConnectableObservable
TimeoutError
VirtualTimeScheduler
`rxjs/ajax`:
AjaxRequest
AjaxResponse
AjaxError
AjaxTimeoutError
`rxjs/operators`:
Timestamp (made an interface)
TimeInterval (made an interface)
=> fix(rxjs): add exports for symbols/interfaces that were missing

spec/index-spec.ts, src/index.ts
Reverts ReactiveX/rxjs#3375
To decrease the API surface area, we shouldn't export `fromPromise`, as any operator or function that accepts an Observable (such as `mergeMap` or `defer`) will include most of `from`'s logic anyhow.
=> Revert "refactor(fromPromise): expose fromPromise through rxjs export"

doc/pipeable-operators.md
An example in `pipepable-operators.md` showed incorrect sample output:
```js
interval(1000).pipe(
takeEveryNth(2),
map(x => x + x),
takeEveryNthSimple(3),
map(x => x * x),
takeEveryNthSimplest(4),
take(3),
toArray()
)
.subscribe(x => console.log(x));
// [0, 12, 24]
```
The correct result is `[0, 2304, 9216]` and not `[0, 12, 24]`, see the working example on StackBlitz: https://stackblitz.com/edit/rxjs-pipeable-example
`[0, 12, 24]` would be the result if `map(x => x * x)` and `takeEveryNthSimplest(4)` were not in the chain.
=> docs(pipeable-operators): correct sample output in "takeEveryNth" example

spec/Observable-spec.ts, spec/operators/toPromise-spec.ts, src/internal/Observable.ts, src/internal/Rx.ts, src/internal/config.ts
Moves Rx.config to a module so it can be used via any module system as well
This is part of the path to removing `root`.
It also moves some of the duplicate logic for getting the proper Promise constructor to a single function.
=> refactor(config): Move config to a module

package.json, spec/helpers/tests2png/diagram-test-runner.ts, spec/helpers/tests2png/painter.ts, spec/helpers/tests2png/types.ts, spec/operators/forkJoin-spec.ts, spec/support/tests2png.opts, src/internal/testing/TestMessage.ts, src/internal/testing/TestScheduler.ts
forkJoin diagram is missing, to add this I added Tests and fixed some issues with tests2png to make
it work again
tests2png uses ts now instead of creating a new dist copy
`tests2png` wasn't working and there we're some files migrated to `*.ts` (`testScheduler-ui.ts`), so I migrated `diagram-test-runner.js` and `painter.js` to typescript and ran tests2png using the same way `npm run test` works. 
Fixes #3352
=> test(forkJoin): Add forkJoin diagram, fix tests2png

spec/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
Fixes the problem reported in #3349. In Chrome, at least, if options are passed in the call to `addEventListener`, but not in the call to `removeEventListener`, the listener is not removed.
The PR adds an expectation to an existing test and passes the options in the call to `removeEventListener`, too.
**Related issue (if exists):** #3349
=> fix(fromEvent): pass options in unsubscribe

src/internal/symbol/iterator.ts
Removes the console.warn as it's liable to cause more trouble and confusion than it is to help.
=> refactor(Symbol_iterator): remove warning

package.json, tsconfig/tsconfig.esm2015.json, tsconfig/tsconfig.esm5.json
I intentionally didn't use the flag for cjs builds because that would
make cjs builds incompatible with SystemJS without further configuration
on the client-side - this would be highly undesirable.
=> build: use tsc importHelpers flag to remove duplicate helpers from esm5 and esm2015 builds

src/internal/observable/fromEvent.ts
Compiling RxJS with Closure currently fails with `rxjs/src/internal/observable/fromEvent.closure.js:204: ERROR - variable toString is undeclared`. This fix is copied from [here](https://github.com/ReactiveX/rxjs/blob/1d100d3c34ebee5d2484a3b664a56f8600cc1f2c/src/observable/FromEventObservable.ts#L8).
=> fix(fromEvent): Defines toString to fix Closure compilations

src/internal/operators/catchError.ts
Reverts ReactiveX/rxjs#3421
This change actually ended up breaking typings for several cases at Google, and will undoubtedly breaking typings for many other people elsewhere.
=> Revert "refactor(catchError): add type overloads for functions that do not re…"

.make-packages.js, dangerfile.js, src/internal/umd.ts, tools/make-closure-core.js, tools/make-umd-bundle.js, tsconfig/tsconfig.base.json
For example, if you want to do the same thing as  but using the global file, you would use , If you wanted to do , that will be available at . Thus making the import/access points more predictable between the UMD and the ESM and CJS versions.
=> feat(umd): UMD now mirrors export schema for ESM and CJS

.make-packages.js
This file is not necessary and breaks closure compiler.
=> build: delete umd.js from the final package

spec/support/tests2png.opts, src/internal/operators/ignoreElements.ts, src/internal/patching/operator/ignoreElements.ts
Per #2640 ignoreElements should resolve to Observable<never>, #3340 asks for this explicitly, there was also another issue with tests2png that I fix here (not sure where that came from)
Closes #3340
- Makes ignoreElements return `Observable<never>` instead of whatever you feed into it (for example if you use `Observable<string>` it returns `Observable<string>`, fixing #3340 and #2640 
- `tests2png` got broken again, fixed that too (see `spec/support/tests2png.opts`)
#3340 and #2640
=> refactor(ignoreElements): ignoreElements now returns Observable<never>

src/internal/operators/single.ts
Expands docs for the Single operator to cover the behaviour where `undefined` is emitted.
Behaviour already has test coverage [test](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/single-spec.ts#L143)
Closes #3182
=> docs(single): Describe case where `undefined` is emitted

src/internal/observable/forkJoin.ts
Solves an issue where we were hitting the wrong typings for forkJoin if passed an Array of observables.
=> fix(forkJoin): fix forkJoin typings for forkJoin(Observable<any>[])

doc/external-references.md
The parleys.com domain has expired. The new Reactive Angular link will go directly to YouTube
=> docs: correct broken Reactive Angular video link

src/internal/operators/publishReplay.ts
=> fix(publishReplay): type inference improved

spec/config-spec.ts, src/internal/config.ts
We need to make sure promise is undefined initially because systems like Zones need to have a chance to pick up Promise and patch it, and we're doing a runtime check for configuration anyhow. This makes the runtime check worthwhile and solves the problem with Zones (without needing to reference Zones in anyway)
=> fix(config): make sure that Promise config is undefined initially

spec/index-spec.ts, src/index.ts
We weren't exposing configuration in a meaningful way from the rxjs module, this remedies that
=> fix(config): expose configuration via rxjs exports

spec/observables/dom/ajax-spec.ts, src/internal/observable/dom/AjaxObservable.ts
w3 rfc2616 defines 4xx,5xx status codes as errors, but anything below is a valid response.
AjaxObservable errors when a request status returns 1xx and 3xx, passing only 2xx requests.
#3308
w3 rfc2616 defines 4xx,5xx status codes as errors, but anything below is a valid response.
AjaxObservable errors when a request status returns 1xx and 3xx, passing only 2xx requests.
#3308
=> fix(AjaxObservable): 1xx,2xx,3xx requests shouldn't error, only 4xx,5xx

spec/observables/dom/ajax-spec.ts, src/internal/observable/dom/AjaxObservable.ts
=> feat(ajax): default to opting into CORS

src/BUILD.bazel
we have no target setup for this, we should set it up or be ok with not having backwards compat
story for external bazel users. I'll leave it up to @alexeagle and @jasonaden to decide and
potentially fix in a followup PR.
=> build: fix BUILD.bazel specification by excluding all backwards compat code

README.md
Very minor update of README to change from saying `alpha` to `beta`.
=> docs(readme): update readme to mention beta instead of alpha

src/internal/observable/dom/MiscJSDoc.ts
**Description:** Documentation for AjaxRequest missing `withCredentials` property
**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/3448
=> docs(dom): Updated to include missing withCredentials property on AjaxRequest

spec/operators/repeatWhen-spec.ts, src/internal/operators/repeatWhen.ts
This PR is an attempt at fixing #3444. However, in making the changes, I found some conflict between a test, the documentation and the current behaviour. My changes were made in favour of the docs and the behaviour. In particular, [this test](https://github.com/ReactiveX/rxjs/blob/master/spec/operators/repeatWhen-spec.ts#L67-L81) attempts to assert that the observable repeats when an empty notifier is used:
```ts
it('should retry when notified and complete on returned completion', (done: MochaDone) => {
const expected = [1, 2, 1, 2];
Observable.of(1, 2)
.map((n: number) => {
return n;
})
.repeatWhen((notifications: any) => Observable.empty())
.subscribe((n: number) => {
expect(n).to.equal(expected.shift());
}, (err: any) => {
done(new Error('should not be called'));
}, () …
```
=>  fix(repeatWhen): support synchronous notifier

spec/Observable-spec.ts, src/internal/Observable.ts
Before if you subscribed such as `(new Observable()).subscribe()` it would throw an error, this remedies that and will effectively return a never observable, however _not_ the same instance as `NEVER`
=> fix(Observable): empty ctor returns valid Observable

src/internal/Notification.ts, src/internal/Observable.ts, src/internal/Scheduler.ts, src/internal/Subject.ts, src/internal/Subscriber.ts, src/internal/Subscription.ts
Add @nocollapse to prevent closure compiler from dropping static members that are reexported
twice.  The static members are kept in the first export, but if that symbol is then exported
again the static members are not kept.
=> chore: add @nocollapse to static members.

node-tests/run.sh, node-tests/test.js, package-lock.json, src/internal/Subscriber.ts
This resolves a very nasty issue that happens when more than one copy of rxjs exists in node_modules. This is something that can organically happen to users if they have a dependency that hard-depends on one version of rxjs, but they try to use another version of rxjs for their app. Sometimes even if they revert back, they end up with, say, 2 or 3 copies of `rxjs@5.5.7` in their node_modules
The problem is that the `Subscriber` constructor was doing an `instanceof` check to see if the `destination` was a known/trusted RxJS subscriber. When that fails, it causes RxJS to treat the destination subscriber as any other POJO would be. Due to optimizations involving lift, InnerSubscriber, and a behavior where we're setting the context of the `next`, `error` and `complete` functions manually, …
=> Multi package issue

spec/operators/repeatWhen-spec.ts, src/operators/repeatWhen.ts
* test(repeatWhen): rename to repeat in descriptions
* test(repeatWhen): align expectations with docs
* test(repeatWhen): add failing empty notifier test
* test(repeatWhen): add failing notifier test
* fix(repeatWhen): support synchronous notifier
This PR cherry picks the commits made in #3460 into the `stable` branch.
The problem with the `repeatWhen` operator has been present for sometime, so I guess it should be fixed in `stable`, too.
**Related issue (if exists):** #3444
=> fix(repeatWhen): support synchronous notifier

package-lock.json, package.json, spec/observables/dom/webSocket-spec.ts, src/internal/observable/dom/WebSocketSubject.ts, src/internal/observable/dom/webSocket.ts
- Fixes the build for latest TypeScript
- Adds a `serializer` and `deserializer` config setting that defaults to JSON serialization both in and out of the socket
- deprecates the `resultSelector` (use `deserializer` instead)
- updates tests
- adds documentation
BREAKING CHANGE: WebSocketSubject will now JSON serialize all messages sent over it by default, to return to the old behavior, pass a config setting of `serializer: x => x` like so: `websocket({ url, serializer: x => x })`
=> feat(websocket): Add serializer/deserializer config settings

src/internal/observable/bindCallback.ts
This is currently blocked, as it doesn't seem that TypeScript can really handle inferring types here like I hoped it could
=> fix(bindCallback): add better type overloads

spec/operators/last-spec.ts, src/internal/operators/last.ts
- updates tests
- last is now based off of takeLast and other operators
- resolves unfound issue where defaultValue was unable to be falsy
=> refactor(last): smaller last

compat/operator/exhaust.ts, compat/operator/exhaustMap.ts, spec/operators/concatMap-spec.ts, spec/operators/concatMapTo-spec.ts, spec/operators/exhaustMap-spec.ts, spec/operators/mergeMap-spec.ts, spec/operators/mergeMapTo-spec.ts, spec/operators/switchMap-spec.ts, spec/operators/switchMapTo-spec.ts, src/internal/operators/concatMap.ts, src/internal/operators/concatMapTo.ts, src/internal/operators/exhaustMap.ts, src/internal/operators/mergeMap.ts, src/internal/operators/mergeMapTo.ts, src/internal/operators/switchMap.ts, src/internal/operators/switchMapTo.ts
Readds the resultSelector, as deprecated, to 
- mergeMap
- mergeMapTo
- switchMap
- switchMapTo
- concatMap
- concatMapTo
- exhaustMap
... relies on map tests for error handling
=> refactor(mergeMap): readd resultSelector as deprecated

spec/observables/bindCallback-spec.ts, src/internal/observable/bindCallback.ts, src/internal/util/isScheduler.ts
Also updates tests to have proper inferred typings
=> refactor(bindCallback): readd resultSelector as deprecated

spec/observables/forkJoin-spec.ts, src/internal/observable/forkJoin.ts
- updates tests
- readds resultSelector with deprecated flags.
=> refactor(forkJoin): readd resultSelector as deprecated

spec/observables/dom/ajax-spec.ts, src/internal/observable/dom/AjaxObservable.ts
=> fix(ajax): properly encode body with form data that includes URLs

README.md
=> Added RxJs Logo to README, Similar to RxSwift README

perf/micro/current-thread-scheduler/operators/asobservable.js, perf/micro/current-thread-scheduler/operators/pluck-nested.js, perf/micro/current-thread-scheduler/operators/pluck.js, perf/micro/immediate-scheduler/operators/asobservable.js, perf/micro/immediate-scheduler/operators/buffertime.js, perf/micro/immediate-scheduler/operators/pluck-nested.js, perf/micro/immediate-scheduler/operators/pluck.js
I've noticed that `pluck()`, `bufferTime()` and `asObservable()` operators don't have any performance tests so this PR adds them. All three of them have their RxJS 4 counterparts.
There're more operators without performance tests (for example `audit()` or `windowToggle()`) but these don't have any RxJS 4 alternative to compare them to and the current benchmark runner requires always two tests per suite. But this is probably for a separate another issue.
=> perf(pluck,bufferTime,asObservable): add performance tests for pluck(), bufferTime() and asObservable() operators

README.md
=> docs(README): mention lettable operators

compat/operator/timeoutWith.ts, src/internal/operators/timeout.ts, src/internal/operators/timeoutWith.ts
Just a size reduction to timeout Not a hot path operator.
=> refactor(timeout): implement in terms of timeoutWith

src/internal/operators/timeInterval.ts
reducing the size of timeInterval. A non-hotpath operator.
=> refactor(timeInterval): implement in terms of scan

spec/operators/throttle-spec.ts, src/internal/operators/throttle.ts
BREAKING CHANGES: This changes the behavior of throttle, in particular
throttling with both leading and trailing behaviors set to true, to more
closely match the throttling behavior of lodash and other libraries.
Throttling now starts immediately after any emission from the
observable, and values will not be double emitted for both leading and
trailing values
closes #2864
=> fix(throttle): now properly trailing throttles for individual values

compat/operator/elementAt.ts, src/internal/operators/elementAt.ts
- fixes an issue where falsy default values would not have worked in all cases.
- makes the implementation of elementAt much smaller.
=> Fix elementAt defaultValue, make elementAt impl smaller
