spec/operators/shareReplay-spec.ts, src/internal/operators/shareReplay.ts
This PR adds a failing test and reverts #5458 - which removed the `isComplete` variable from `shareReplay`. With the reversion, the test passes. There was an existing test that attempted to test what's tested by the new test, but there was a subtle difference because of this problem: https://github.com/ReactiveX/rxjs/issues/5523
**Related issue (if exists):** #5458
=> fix: revert #5458

spec-dtslint/observables/defer-spec.ts, src/internal/observable/defer.ts
=> fix(defer) allow passing () => any to observableFactory

spec/helpers/testScheduler-ui.ts, spec/observables/combineLatest-spec.ts, spec/observables/forkJoin-spec.ts, spec/observables/from-spec.ts, spec/observables/fromEvent-spec.ts, spec/observables/zip-spec.ts, spec/operators/combineAll-spec.ts, spec/operators/concatAll-spec.ts, spec/operators/debounce-spec.ts, spec/operators/exhaust-spec.ts, spec/operators/expand-spec.ts, spec/operators/finalize-spec.ts, spec/operators/mergeAll-spec.ts, spec/operators/mergeMapTo-spec.ts, spec/operators/multicast-spec.ts, spec/operators/publish-spec.ts, spec/operators/publishBehavior-spec.ts, spec/operators/publishLast-spec.ts, spec/operators/publishReplay-spec.ts, spec/operators/reduce-spec.ts, spec/operators/switch-spec.ts, spec/operators/throttle-spec.ts, spec/operators/toArray-spec.ts, spec/operators/window-spec.ts, spec/operators/zipAll-spec.ts
I believe our test cases for types have been migrated to dts-lint, prior legacy test using dummy fn just left behind. Trying to clear things up.
=> test(type): deprecate legacy type test

docs_app/content/guide/glossary-and-semantics.md
This is an effort on my part to clearly define the language we use (and should be using) in our documentation and our articles. This is an important step to improving our resources in my opinion, and a long time coming.
=> docs: Add the start of a glossary

src/internal/operators/timeout.ts
This PR try to change timing behavior of `timeout` operator creating its timeout error object. Instead of eagerly creating new object each time operator is being called, now it defers creation until timeout's being raised.
Initially thought of using constant timeouterror object, but that'll make fixed stack instead of actual point of error being thrown.
- closes #5491
=> fix(timeout): defer error creation until timeout occurs

api_guard/dist/types/index.d.ts, spec-dtslint/observables/combineLatest-spec.ts, spec/observables/combineLatest-spec.ts, src/internal/observable/combineLatest.ts
Support for passing a dictionary of observables to `combineLatest`, removing the need to pass an array then directly using `map` to turn it back into an object.
I mostly based this on the similar work that was done on `forkJoin`.
#5022 and #5362
=> feat(combineLatest): support for observable dictionaries (#5022)

src/internal/operators/tap.ts
Renaming `DoOperator` to `TapOperator` to follow the rest of the `tap` operator stuff: the `tap` itself is no longer `do` operator and the `TapSubscriber` is [no longer](https://github.com/ReactiveX/rxjs/commit/cd9626a4f93cac6f631d5a97dd9c9b2aa8e4b5db) `DoSubscriber`.
This is a leftover that some may love to keep, but if possible, it would be nice to have this merged so that `tap` is now completely renamed.
=> refactor(tap): rename DoOperator to TapOperator

spec/Subscriber-spec.ts, spec/Subscription-spec.ts, src/internal/Subscription.ts
`null` out the `unsubscribe` callback after unsubscribing.
The `any` is kind of ugly but that is also how it's assigned in the constructor.
**Related issue (if exists):** Fixes #5464
=> null out _unsubscribe after unsubscription

src/internal/innerSubscribe.ts, src/internal/observable/combineLatest.ts, src/internal/observable/race.ts, src/internal/observable/zip.ts, src/internal/operators/audit.ts, src/internal/operators/buffer.ts, src/internal/operators/bufferToggle.ts, src/internal/operators/bufferWhen.ts, src/internal/operators/catchError.ts, src/internal/operators/debounce.ts, src/internal/operators/delayWhen.ts, src/internal/operators/distinct.ts, src/internal/operators/exhaust.ts, src/internal/operators/exhaustMap.ts, src/internal/operators/expand.ts, src/internal/operators/mergeMap.ts, src/internal/operators/mergeScan.ts, src/internal/operators/onErrorResumeNext.ts, src/internal/operators/repeatWhen.ts, src/internal/operators/retryWhen.ts, src/internal/operators/sample.ts, src/internal/operators/skipUntil.ts, src/internal/operators/switchMap.ts, src/internal/operators/switchMapTo.ts, src/internal/operators/takeUntil.ts, src/internal/operators/throttle.ts, src/internal/operators/timeoutWith.ts, src/internal/operators/window.ts, src/internal/operators/windowWhen.ts, src/internal/operators/withLatestFrom.ts
this is the duplicate of #5610, it is refactoring to ensure outer values are not retained when they do not have to be. It needs to be done in a separate PR because the branches diverge just enough to require it. This PR also has some mild, internal type fixes.
=> refactor: Improve memory pressure

api_guard/dist/types/index.d.ts, api_guard/dist/types/testing/index.d.ts, docs_app/content/guide/testing/marble-testing.md, spec/helpers/test-helper.ts, spec/observables/dom/animationFrames-spec.ts, spec/operators/timeoutWith-spec.ts, spec/schedulers/TestScheduler-spec.ts, src/internal/ReplaySubject.ts, src/internal/Scheduler.ts, src/internal/observable/dom/animationFrames.ts, src/internal/operators/timestamp.ts, src/internal/scheduler/dateTimestampProvider.ts, src/internal/scheduler/performanceTimestampProvider.ts, src/internal/scheduler/requestAnimationFrameProvider.ts, src/internal/testing/TestScheduler.ts
This PR:
* Adds a `Date` timestamp provider.
* Adds a `performance` timestamp provider.
* Adds a `requestAnimationFrame` provider.
* All providers have `delegate` properties that are `undefined` by default but are used - by `TestScheduler#run` - to override the default behaviour. This mirrors the `delegate` implementation detail that's used with the schedulers.
* Removes the arrow function from the static `Scheduler.now` - it's unnecessary, as the `Date.now` call now occurs within the `dateTimestampProvider`.
* The `animationFrames` observable now uses the `requestAnimationFramesProvider`.
* `TestScheduler#run` sets the delegates for the providers, with the `requestAnimationFramesProvider`'s delegate working in conjunction with a `animate()` marble that's added to the run …
=> feat(TestScheduler): add an animate "run mode" helper

api_guard/dist/types/index.d.ts, spec-dtslint/observables/dom/animationFrames-spec.ts, spec/observables/dom/animationFrames-spec.ts, src/internal/observable/dom/animationFrames.ts
Emit the timestamp provided by rAF to align better with the rAF
specification. Multiple scheduled rAF callbacks within the same frame
will be called with the same timestamp.
This fixes #5194 
**Further notes**
I kept the possibility to supply a custom `TimestampProvider` to the `animationFrames` function.
=> fix(animationFrames): emit the timestamp from the rAF's callback

api_guard/dist/types/ajax/index.d.ts, spec/observables/dom/ajax-spec.ts, src/internal/observable/dom/AjaxObservable.ts, src/internal/observable/dom/ajax.ts
Refactors the existing AJAX implementation. (Unrelated to OJ's rewrite)
- Gets it inline, browser-support wise, with contemporaries like Axios, et al.
- Removes old optimizations from several years ago that were no longer relevant.
- Adds documentation for the various functions, at least at some level.
- Removes funky code paths that were CLEARLY never hit or we'd have had complaints about them. For example [people probably are not using this against IE9 and under based off of the existance of this line here](https://github.com/ReactiveX/rxjs/blob/edd67313814bfc32e8a5129d8049e4d4678cd35d/src/internal/observable/dom/AjaxObservable.ts#L378-L384). Which means that all of the ActiveXObject and IE9 and under support was useless. Also, in that case, checks for `XDomainRequest` were no longer …
=> Yet another ajax refactor

src/internal/operators/shareReplay.ts
This PR is an attempt to address[ the following comment](https://github.com/ReactiveX/rxjs/pull/5550#issuecomment-652729169) from @cartant on #5550 
> the problem the reverted PR caused exposed a separate issue that probably needs to be looked at: sources that complete synchronously won't end up with an undefined subscription and that wasn't the intention. In short, this reference-releasing behaviour needs more thought, so we've reverted it for now.
Somewhat related to this issue #5548
=> refactor(shareReplay): avoid memory leaks

src/internal/operators/timeout.ts
In an effort to simplify the code base, along with the other work to retry, retryWhen, repeat, and repeatWhen, this should help us get rid of `_unsubscribeAndRecycle` and move us toward simplifying Subscriber in the long run. There are obviously some memory trade offs using functions on POJOs over on prototypes, but given other recent memory improvements, I think that is probably not a big deal.
All part of a cohesive plan that you might see coming together with #5625 #5623 #5621 #5620 et al.
=> refactor(timeout): Getting rid of _unsubscribeAndRecycle

spec/operators/retryWhen-spec.ts, src/internal/operators/retryWhen.ts
Fixes an issue where subscriptions would not tear down until all retries were exhausted in the synchronous case.
=> fix(retryWhen): Ensure subscription tears down between retries

spec/operators/repeatWhen-spec.ts, src/internal/operators/repeatWhen.ts
Resolves an issue where teardowns would wait until the resulting observable ended before being executed.
=> fix(repeatWhen): Ensure teardown happens between repeat subscriptions

spec-dtslint/operators/mergeAll-spec.ts
This PR adds a dtslint test for `mergeAll` in which the observables within the higher-order observable have different types. It also changes the tests to use the predefined helper sources.
Added because I noticed a type issue in v6 and when I checked the v7 types, they were fine, but the test was missing.
=> test(mergeAll): add test with multiple types

docs_app/content/guide/operators.md
=> docs(operators.md): fix grammar

package-lock.json, package.json, spec-dtslint/types-spec.ts
This PR bumps TypeScript to `4.0.1-rc`. Almost no changes were needed:
* `npm run lint` effects no failures.
* `npm run test` sees all tests pass with no compile errors.
* `npm run build:package` builds with no compile errors.
* `npm run dtslint` effected a single failure that was due to named tuple elements being a thing in TS4. (It seems the file with this change had CRLF line endings. They're now LF, hence the large diff. The change is on line 71.)
* And I guess we'll soon find out what happens in CI ... It seems CI is happy 🎉
IMO, we might as well bump this now. Given that it will allow us to remove so many overloads, I think we should be choosing TS4 as the minimum supported version for v7.
Note that this change will affect the Google merge, as [they're using …
=> chore: bump TypeScript to 4.0.1-rc

api_guard/dist/types/index.d.ts, spec-dtslint/observables/throwError-spec.ts, spec/observables/throwError-spec.ts, src/internal/observable/throwError.ts
- Adds feature to allow the error instance the consumer is notified with to be created at the moment of notification.
- Updates tests to use "run mode".
- Improves documentation, including recommendations on when `throwError` is not necessary.
BREAKING CHANGE: In an extreme corner case for usage, `throwError` is no longer able to emit a function as an error directly. If you need to push a function as an error, you will have to use the factory function to return the function like so: `throwError(() => functionToEmit)`, in other words `throwError(() => () => console.log('called later'))`.
resolves #5617
=> feat(throwError): now accepts a factory to create the error

api_guard/dist/types/index.d.ts, src/internal/scheduler/VirtualTimeScheduler.ts
BREAKING CHANGE: The static `sortActions` method on `VirtualTimeScheduler` is no longer publicly exposed by our TS types.
=> refactor(VirtualTimeScheduler): remove sortActions from public API

spec/operators/catchError-spec.ts, src/internal/operators/catchError.ts
=> fix(catchError): inner synchronous observables will properly terminate

package-lock.json, package.json
=> chore: bump to released version of TS4

api_guard/dist/types/index.d.ts, spec/Subscriber-spec.ts, src/internal/Subscriber.ts, src/internal/config.ts
In profiling sessions, the `SafeSubscriber` constructor was showing as hot
function for code that creates and tear downs Observables very frequently.
The usage of `Object.create` attributes to the slowness; avoiding using it
completely removes any overhead of `SafeSubscriber`.
The `Object.create` result was used to call anonymous subscribers in their
own context, i.e. the `this` pointer in `next`/`error`/`complete` is the
anonymous object itself. This commit implements an alternative to achieve
the same effect; binding the subscriber functions to the observer object.
The below timings are with NodeJS 14.8.0 in a full Angular CLI build of https://github.com/JoostK/ng9-aot-build-times/tree/extra.
**Before**:
**After**:
=> perf(SafeSubscriber): avoid using `Object.create`

api_guard/dist/types/index.d.ts, src/internal/Subscriber.ts, src/internal/Subscription.ts, src/internal/observable/ConnectableObservable.ts, src/internal/operators/bufferTime.ts, src/internal/operators/bufferWhen.ts, src/internal/operators/groupBy.ts, src/internal/operators/refCount.ts, src/internal/operators/switchMap.ts, src/internal/operators/window.ts, src/internal/operators/windowCount.ts, src/internal/operators/windowToggle.ts, src/internal/scheduler/AsyncAction.ts
This is just another step toward getting what we're doing with inheritance to be a little more sane, ultimately, this may be refactored further, as I am not happy with some of these subscribers adding their own teardowns, but this is a start. The goal was to get rid of the weirdness around `_unsubscribe` in our code base.
- Moves to calling `_unsubscribe` a new internal name in `Subscription`: `initialTeardown`, because it's slightly more descriptive
- Removes `_unsubscribe` usage from the entire code base.
- Formatted a few files just for my sanity.
=> refactor(Subscription): Get rid of _unsubscribe weirdness

spec/operators/exhaustMap-spec.ts, spec/operators/switchMap-spec.ts, src/internal/operators/exhaustMap.ts, src/internal/operators/switchMap.ts
Some operators create inner subscriptions on `next()`. But during subscribing to the inner sub, some side effects may trigger another `next()` on this operator synchronously, i.e. synchronous reentrant, leading to a new inner subscription to be created. However the previous inner subscription is not yet set on the operator, which would cause unexpected behavior for some operators. It's clear to us that `switchMap` and `exhaustMap` behaves unexpectedly under this setting, because their correct behaviors are defined by the order of messages being received.
This PR is trying to address these unexpected behaviors so that:
- `switchMap` should unsubscribe previous inner sub when getting synchronously reentrance during subscribing the inner sub
- `exhaustMap` should ignore …
=> fix: handle synchronous reentrant during subscribing the inner sub

spec/operators/buffer-spec.ts, src/internal/operators/buffer.ts
- Resolves an issue where a multicast observable could not adequately be used to notify a buffer on itself
- Corrects a regression that was introduced by a bad merge back in 6.0. This was originally corrected in PR #2195.
fixes #1754
=> fix(buffer): Ensure notifier is subscribed after source

api_guard/dist/types/index.d.ts, integration/side-effects/snapshots/esm5/ajax.js, spec/helpers/test-helper.ts, spec/operators/concatWith-spec.ts, spec/operators/single-spec.ts, spec/operators/takeLast-spec.ts, spec/util/ArgumentOutOfRangeError-spec.ts, spec/util/EmptyError-spec.ts, spec/util/ObjectUnsubscribedError-spec.ts, spec/util/TimeoutError-spec.ts, spec/util/UnsubscriptionError-spec.ts, spec/util/createErrorClass-spec.ts, src/internal/observable/dom/AjaxObservable.ts, src/internal/operators/timeout.ts, src/internal/util/ArgumentOutOfRangeError.ts, src/internal/util/EmptyError.ts, src/internal/util/NotFoundError.ts, src/internal/util/ObjectUnsubscribedError.ts, src/internal/util/SequenceError.ts, src/internal/util/UnsubscriptionError.ts, src/internal/util/createErrorClass.ts
NOTE: Because we have to workaround compilation-to-ES5 inadequacies until call stack locations will show as being inside of the constructor implementation at the top level. This will go away as we are able to move the community to ES2015+
BREAKING CHANGE: Tests that are written with naive expectations against errors may fail now that errors have a proper `stack` property. In some testing frameworks, a deep equality check on two error instances will check the values in `stack`, which could be different.
fixes #4250
=> fix(errors): Custom RxJS errors now all have a call stack

spec/operators/throttleTime-spec.ts, src/internal/operators/throttleTime.ts
Works to align the behavior with expectations set by lodash's throttle
- Updates tests
- Ensures trailing throttle will wait to notify and then complete
- Ensures that every time we emit a value a new throttle period starts
fixes #3712
related #4864
fixes #2727
closes #4727
related #4429
=> fix(throttleTime): ensure the spacing between throttles is always at least the throttled amount

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/observables/onErrorResumeNext-spec.ts, spec-dtslint/operators/onErrorResumeNext-spec.ts, spec/observables/onErrorResumeNext-spec.ts, spec/operators/finalize-spec.ts, spec/operators/onErrorResumeNext-spec.ts, src/internal/observable/onErrorResumeNext.ts, src/internal/operators/onErrorResumeNext.ts
- Fixes an issue where finalize would be called after all sources were complete
- Removes superfluous onErrorResumeNext implementation
- Ensures that invalid sources handed to onErrorResumeNext do not cause an error, and instead resume to the next source
- Updates types to infer N arguments
- Removes invalid type signature that allowed a function for no reason
- Adds dtslint tests for static creation function
- Adds finalize test to ensure order of finalize calls (as a sanity check)
=> fix(onErrorResumeNext): observables always finalized before moving to next source

spec/observables/dom/webSocket-spec.ts, src/internal/observable/dom/WebSocketSubject.ts
Fix closing the underlying WebSocket when a WebSocketSubject is unsubscribed while the WebSocket is in the `CONNECTING` state.
Initial support for closing a WebSocket before it was opened was added in #4446.
However, that pull-request still waits for the connection to eventually become open before attempting to close it.
This pull-request takes it a step further by closing the WebSocket as soon as the subject is unsubscribed.
**Related issue (if exists):** #4446 #4447
=> fix(WebSocketSubject): close websocket connection attempt on unsubscribe

spec/subjects/ReplaySubject-spec.ts, src/internal/ReplaySubject.ts
This PR fixes a bug in `ReplaySubject` - demonstrated in failing tests - in which nexted values were buffered **after** the subject was stopped (by a `complete` or `error` call).
=> fix(ReplaySubject): don't buffer next if stopped

api_guard/dist/types/index.d.ts, spec/Observable-spec.ts, src/internal/Observable.ts, src/internal/Subscriber.ts
- Gets rid of weirdness with syncErrorThrowable, et al
- General code golf in a few spots.
=> refactor(Observable): simplify subscription and subscriber code

api_guard/dist/types/index.d.ts, src/internal/observable/bindCallback.ts, src/internal/observable/bindNodeCallback.ts, src/internal/observable/combineLatest.ts, src/internal/observable/forkJoin.ts, src/internal/observable/fromEvent.ts, src/internal/observable/fromEventPattern.ts, src/internal/observable/onErrorResumeNext.ts, src/internal/observable/race.ts, src/internal/operators/combineAll.ts, src/internal/operators/combineLatestWith.ts, src/internal/operators/onErrorResumeNext.ts, src/internal/operators/raceWith.ts, src/internal/util/argsArgArrayOrObject.ts, src/internal/util/argsOrArgArray.ts, src/internal/util/isArray.ts, src/internal/util/isNumeric.ts, src/internal/util/mapOneOrManyArgs.ts
- Gets rid of legacy `isArray` implementation.
- Centralizes the common tasks involving arrays of arguments that `isArray` was being used for into a few useful utilities.
- Additional LOC caused by formatting with prettier, not actual code addition. Should be less code when bundled.
=> Refactor isArray usage

api_guard/dist/types/index.d.ts, src/internal/Subscription.ts, src/internal/types.ts
- Reduces the size of subscription a little
- Moves back to a single property for single/many parents scenarios
- Updates the type of `Teardown` to not be so loose.  does not may any sense there.
=> refactor(Subscription): minor size reduction

package.json, spec/tslint.json, src/internal/operators/tap.ts, tslint.json
- Also ensures that unsubscribe is called in error and complete callbacks by calling `super._error` etc.
- Rewrites docs and adds more examples (LOC will look like more, probably)
Before: 913B
After: 549B (60% of original size)
=> refactor(tap): slight size reduction

spec/observables/combineLatest-spec.ts, src/internal/observable/combineLatest.ts, src/internal/operators/combineAll.ts, src/internal/operators/combineLatestWith.ts
- Refactors one test to make it easier to debug
- Removes the use of `stankyLift` for `combineLatestWith`.
- Builds `combineAll` from `toArray` and `combineLatest`. I think this has the added benefit if making it more obvious what the operator does for those that read the source.
- Refactors implementation of static `combineLatest` to be smaller.
I'm hopeful that this refactor will serve as the basis for refactoring other operators with similar issues.
combineLatest static judged by including a build of this PR into a new angular app, built in prod mode and looked at in `source-map-explorer`:
Before: 1.21KB
After: 698B
=> refactor(combineLatest): remove stankyLift, make smaller

spec/operators/bufferTime-spec.ts, src/internal/operators/bufferTime.ts
- Complete rewrite of `bufferTime`
- Adds some comments
- Formats a couple of tests for readability during debugging.
Before: 2.24KB
After: 823B
=> refactor(bufferTime): reduce the size of the implementation

src/internal/operators/sequenceEqual.ts
- Refactor and comments.
- If two sequences are compared in the forest, and no one subscribes, does it make a sound?
Before: 1.18KB
After: 565B (47% of the original size)
=> refactor(sequenceEqual): reduce the size of the implementation

spec-dtslint/observables/fromEvent-spec.ts
Adds dtslint tests for `fromEvent` to make things a little easier for contributors - see #5584.
**Related issue (if exists):** #5584
=> chore(fromEvent): add dtslint tests

src/internal/operators/throttleTime.ts
- Just a rewrite of the implementation and some comments.
Before: 1.11KB
After: 472B
=> refactor(throttleTime): reduce the size of the implementation

spec-dtslint/observables/fromEvent-spec.ts
This PR tweaks the types used for the jQuery source in the dtslint tests to better represent what's in `@types/jquery`. When the changes in #5584 are made, the jQuery dtslint test - which fail with the more accurate types - can be uncommented.
**Related issue (if exists):** #5584
=> chore(fromEvent): use more accurate jQuery types in dtslint test

docs_app/content/guide/overview.md
Corrected a grammatical error in the overview page document. **"the"** should not be used here.
=> docs(overview): corrected grammatical error

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec/Observable-spec.ts, spec/Subscriber-spec.ts, src/internal/config.ts
- Removes fancy code that would emit console warnings and other log messages
- Removes configuration that would disable the console warnings
- Size impact down to < 100 KB (from > 700 KB). I was unable to even get a measurement on it from source-map-explorer.
NOTE: Now that deprecations show up so prominently in IDEs like VS Code, I don't think we really need to be emitting anything to console, if we even should have to begin with.
=> refactor(config): just a POJO

spec/operators/scan-spec.ts, src/internal/operators/reduce.ts, src/internal/operators/scan.ts
- Smaller implementation
- Improved docs
- Adds comments
- Adds a test
- Fixes weird adjustment in `reduce`.
Size differences...
Before: 676 B
After: 248 B (36% of original size)
Documentation updates close a couple of issues:
Closes #4348
Closes #3879
=> fix(scan): proper indexes when seed is not supplied

spec/operators/catchError-spec.ts, spec/operators/exhaust-spec.ts, spec/operators/exhaustMap-spec.ts, spec/operators/raceWith-spec.ts, spec/operators/retryWhen-spec.ts, spec/operators/single-spec.ts
This PR enables/unskips the synchronous-firehose tests for operators that now pass - thanks to the smallify refactor in #5729. Some tests still fail and are left skipped - to be fixed/addressed in another PR.
**Related issue (if exists):** #5658
=> test: enable now-passing firehose tests

src/internal/AsyncSubject.ts, src/internal/observable/combineLatest.ts, src/internal/observable/concat.ts, src/internal/observable/throwError.ts, src/internal/operators/concatWith.ts, src/internal/operators/multicast.ts, src/internal/operators/retryWhen.ts, src/internal/operators/sampleTime.ts, src/internal/operators/takeLast.ts, src/internal/operators/tap.ts, src/internal/operators/throwIfEmpty.ts, src/internal/operators/windowCount.ts, src/internal/testing/TestScheduler.ts, tslint.json
This PR adds the `tslint-etc` `no-unused-declaration` rule and configures it to effect failures only for unused imports - not for variable declarations, etc.
The PR also removes a bunch of unused imports.
=> chore: add no-unused-declaration lint rule (for imports)

spec/observables/dom/webSocket-spec.ts, spec/operators/timeout-spec.ts, src/internal/operators/timeout.ts, wallaby.js
- closes #5746
let synchronous subscription do not try to unsubscribe from not yet assigned timer subscription.
=> fix(timeout): allow synchronous observable as source

docs_app/content/deprecations/scheduler-argument.md, docs_app/content/deprecations/tuple-argument.md, docs_app/content/guide/higher-order-observables.md, docs_app/content/navigation.json, docs_app/tools/transforms/angular-content-package/index.js, src/internal/observable/combineLatest.ts, src/internal/observable/concat.ts, src/internal/observable/from.ts, src/internal/observable/merge.ts, src/internal/observable/of.ts, src/internal/operators/endWith.ts, src/internal/operators/startWith.ts
This is a rough POC to see if it works for our purpose to improve the deprecation messages.
Text might need some improvement/additional information
@benlesh @cartant
=> [docs]: Create Deprecation page per deprecation group

src/internal/operators/mergeInternals.ts, src/internal/operators/mergeMap.ts, src/internal/operators/mergeScan.ts
Creates a new `mergeInternals` function that can be used to create a merge-strategy operator, with extensiblity points for accommodating the nuances of each operator.
In theory, we could use this in `concatMap`, etc, directly.
=> refactor(mergeMap/mergeScan): unify logic

api_guard/dist/types/operators/index.d.ts, src/internal/observable/zip.ts, src/internal/operators/combineAll.ts, src/internal/operators/count.ts, src/internal/operators/joinAllInternals.ts, src/internal/operators/reduce.ts, src/internal/operators/scan.ts, src/internal/operators/scanInternals.ts, src/internal/operators/toArray.ts, src/internal/operators/zipAll.ts
- refactor: `combineAll` and `zipAll` use shared logic
- fix(zip): zip now accepts an array of arguments like its counterparts
- `forkJoin` and `combineLatest` both allow an array of arguments to be passed to it like so: `forkJoin([a$, b$, c$])`. Now `zip` does the same: `zip([a$, b$, c$])`
BREAKING CHANGE: Zipping a single array will now have a different result. This is an extreme corner-case, because it is very unlikely that anyone would want to zip an array with nothing at all.
- refactor(toArray): reduce complexity a little.
There was a situation where the `toArray` implementation was relying on a quirk of `reduce` and a trick with the `index` in order to ensure that two subscriptions to the same `toArray`-ed observable would not mutate the same underlying array.
This change gets …
=> Unify approaches to reduce, scan, combineAll and zipAll

src/internal/observable/interval.ts
This PR removes the returning of the `subscriber` within the `interval` observable. Any returned teardown would be added to the sink - which is the subscriber itself.
=> chore(interval): remove pointless teardown return

src/internal/observable/defer.ts, src/internal/observable/dom/fetch.ts, src/internal/observable/forkJoin.ts, src/internal/observable/merge.ts, src/internal/observable/partition.ts, src/internal/observable/race.ts, src/internal/observable/using.ts, src/internal/observable/zip.ts, src/internal/operators/audit.ts, src/internal/operators/bufferToggle.ts, src/internal/operators/bufferWhen.ts, src/internal/operators/catchError.ts, src/internal/operators/debounce.ts, src/internal/operators/exhaust.ts, src/internal/operators/exhaustMap.ts, src/internal/operators/expand.ts, src/internal/operators/mergeInternals.ts, src/internal/operators/mergeMap.ts, src/internal/operators/onErrorResumeNext.ts, src/internal/operators/sequenceEqual.ts, src/internal/operators/skipUntil.ts, src/internal/operators/switchMap.ts, src/internal/operators/takeUntil.ts, src/internal/operators/throttle.ts, src/internal/operators/timeout.ts, src/internal/operators/windowToggle.ts, src/internal/operators/windowWhen.ts, src/internal/operators/withLatestFrom.ts
Uses `innerFrom` throughout the library where we know we don't need to pass a scheduler.
This is done to reduce bundle size. If we used `from` internally, but didn't need scheduling for that call, we were just using it to convert to an observable (the 95% case), we would end up including `scheduled` in the bundle when we didn't need to, because the deprecated path of `from` calls `scheduled`.
Perhaps it should be called `internalFrom` since  "inner" often has other connotations in our library? Happy to change that in this PR.
=> refactor: use `innerFrom` for internal calls

spec/operators/delay-spec.ts, src/internal/operators/delay.ts
- Resolves an issue where passing a Date would cause every value to be scheduled incorrectly, instead of delaying all values until the absolute date -- as documented.
- Resolves an issue where negative numbers were treated as though they were positive numbers
- Reduces operator sizes
- Adds comments and formatting
- Updates tests to reflect better behavior
- Adds test for Dates in the past.
- `delay` now based on `delayWhen` and `timer`.
=> fix(delay): Now properly handles Date and negative numbers

spec/operators/multicast-spec.ts, spec/operators/repeat-spec.ts, spec/operators/repeatWhen-spec.ts, spec/operators/retry-spec.ts, spec/operators/skipLast-spec.ts, spec/operators/throttle-spec.ts, spec/operators/timeoutWith-spec.ts, src/internal/operators/multicast.ts, src/internal/operators/throttle.ts
This PR enables the remaining synchronous firehose tests and fixes operators to ensure they pass. Several operators have tests that now pass due to changes made in other refactoring PRs.
**Related issue (if exists):** #5658
=> test: enable remaining synchronous firehose tests

src/internal/observable/generate.ts, src/internal/operators/timeout.ts, src/internal/scheduled/scheduleArray.ts, src/internal/scheduled/scheduleIterable.ts, src/internal/scheduled/schedulePromise.ts, src/internal/util/caughtSchedule.ts
Unifies a few areas where we are scheduling work that requires a try/catch that sends to `subscriber`.
Some other minor clean up of schedule-related calls.
=> Refactor some scheduled jobs with try/catch

api_guard/dist/types/index.d.ts, spec-dtslint/observables/timer-spec.ts, src/internal/observable/interval.ts, src/internal/observable/timer.ts
- `timer` now a smaller implementation.
- Improved types for `timer`.
- Improved docs for `timer`.
-`interval` now based off of timer, as the implementations were barely different, and no real efficiency was gained by `interval` having its own impl.
=> Refactor `timer` and `interval`

docs_app/src/app/app.component.ts
This pr should help fixing the SEO problem, that always the rxjs-dev-firebase... whatever url is shown in google etc.
This should be merged into 6.x and master
=> docs(canonical-link): add a canonical url for rxjs.dev

src/internal/observable/pairs.ts
BREAKING CHANGE: `pairs` will no longer function in IE without a polyfill for `Object.entries`. `pairs` itself is also deprecated in favor of users just using `from(Object.entries(obj))`.
=> refactor(pairs): Based off of `from` and `Object.entries`

src/internal/observable/generate.ts
- This seems obvious.
NOTE: There's some weirdness with the types here, and it seems like we need to figure out how to resolve it in either `defer` or `ObservableInput`? @kolodny @cartant
=> refactor(generate): Use an actual generator

src/internal/operators/skip.ts
- Add description, example, and See Also section for the `skip` operator
- Closes #4868
=> docs(skip): add description and example for the operator

api_guard/dist/types/operators/index.d.ts, src/internal/operators/expand.ts, src/internal/operators/mergeInternals.ts
- Adds a small amount of complexity to `mergeInternals` to support `expand`.
- `expand` now based off of the same internals as `mergeMap` and `mergeScan`.
- `deprecates` the scheduler argument to `expand` with an explanation.
NOTE: While I'm not fond of the number of arguments to `mergeInternals`, it's an _internal_ API, and given that it's not public, I'd like to refrain from creating named parameters via a configuration object just to make our internal code more readable, especially when this is relatively hot code. Instead, I've opted to make sure everything is well commented.
=> refactor(expand): use mergeInternals

src/internal/observable/dom/fetch.ts
Just what it says. A little smaller. Removes an unnecessary subscription reference. Adds comments, etc.
=> refactor(fromFetch): some clean up on the implementation

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/delayWhen-spec.ts, src/internal/operators/delayWhen.ts
Noticed this after **vscode** starts [showing][vsc] the deprecation from jsdoc, not sure how to test this change tho.
[vsc]: https://code.visualstudio.com/updates/v1_49#_deprecated-tag-support-for-javascript-and-typescript
=> fix(delayWhen): only deprecates when subscriptionDelay presents

spec/operators/auditTime-spec.ts
Fix one of the imperfect `auditTime` tests, which could mislead about the `auditTime` actual behavior.
#5730
=> test(auditTime): fix imperfect test

spec/operators/mergeScan-spec.ts, src/internal/operators/expand.ts, src/internal/operators/mergeInternals.ts, src/internal/operators/mergeMap.ts, src/internal/operators/mergeScan.ts
Fixes an issue were accumulated state would be emitted a second time upon completion.
- Also ensures `state` is cleared on teardown for `mergeScan`.
- Minor refactoring to `mergeInternals` related to this change
- Refactors `mergeMap` to be less verbose in the deprecated path.
BREAKING CHANGE: `mergeScan` will no longer emit its inner state again upon completion.
related #5372
=> fix(mergeScan): No longer emits state again upon completion.

src/internal/operators/skip.ts
basically `filter((_, index) => count <= index)`
=> refactor(skip): skip is just filtering by index

src/internal/operators/skipWhile.ts
- Add description, example, and See Also section for the `skipWhile` operator
- Closes #4869
=> docs(skipWhile): add description and example for the operator

spec/operators/skip-spec.ts, spec/operators/skipLast-spec.ts
~`take`, `takeLast` and `skipLast` are not throwing errors anymore when provided with negative values, so I updated docs and added tests for such cases. Also, I changed `skip` and `skipLast` tests to use `TestScheduler` in run mode.~
[Updated](https://github.com/ReactiveX/rxjs/pull/5796#issuecomment-705690602).
=> Update skip and skipLast tests to run mode

spec/operators/skip-spec.ts, spec/operators/skipLast-spec.ts, spec/operators/take-spec.ts, spec/operators/takeLast-spec.ts
Adding tests for `skip`, `skipLast`, `take` and `takeLast` when provided with negative `count` values.
=> Negative tests for skip, skipLast, take and takeLast

src/internal/types.ts
This PR adds a triple-slash `lib` reference to `esnext.asynciterable` as per the TypeScript recommendation/suggestion linked to in the accompanying comment.
I've tested this locally and it resolves the issue with `unknown` being inferred in situations in which the `tsconfig.json` does not specify a sufficiently-up-to-date `lib`.
We could add `lib` references for any other types we depend upon - like `Promise` - but I figured we ought to keep this minimal and address only the problems that we've seen so far to minimize and unintended consequences.
**Related issue (if exists):** #5708
=> chore: add triple-slash ref to asynciterable

spec/firstValueFrom-spec.ts, src/internal/firstValueFrom.ts
This PR adds a failing firehose test for `firstValueFrom` and fixes the problem by using a subscriber instead of a subscription - so that the `closed` 'signal' is chained to the source observable.
**Related issue (if exists):** #5811
=> fix(firstValueFrom): stop listening after first

spec/operators/defaultIfEmpty-spec.ts
Updated `defaultIfEmpty` tests to use run mode.
=> Update defaultIfEmpty tests to run mode

spec/operators/find-spec.ts, spec/operators/findIndex-spec.ts, spec/operators/first-spec.ts, src/internal/testing/TestScheduler.ts
Hi everyone,
I found about `TestScheduler`'s `time` helper function couple of [days ago](5819) and I wanted to know when it was added and how to use it. And I think I have found a bug.
Since `time` is an alias for  `TestScheduler`'s `createTime`, I don't know what implications will this fix have, since I'm not sure how much people were using `createTime` function. It was added many years ago and I think this bug was introduced with [this PR](5060).
What's the problem? `createTime` trims marbles passed to it and I think that this trimming should happen only if the scheduler is in run mode because when in run mode, we're also ignoring spaces. For example, much like
```ts
const subs = '^   !';
```
advances time the same way this does (when not in run mode)
```ts
const subs = '^---!';
``` …
=> TestScheduler's createTime bug fix

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/observables/forkJoin-spec.ts, spec-dtslint/operators/bufferToggle-spec.ts, spec/operators/expand-spec.ts, src/internal/observable/forkJoin.ts, src/internal/observable/from.ts, src/internal/observable/iif.ts, src/internal/operators/audit.ts, src/internal/operators/bufferToggle.ts, src/internal/operators/concatAll.ts, src/internal/operators/debounce.ts, src/internal/operators/mergeAll.ts, src/internal/operators/switchAll.ts, src/internal/operators/throttle.ts, src/internal/types.ts, src/internal/util/argsArgArrayOrObject.ts
Refactors to remove bad usage of `Subscribable` and updates the `InputObservable` type.
In the process I ended up needing to fix `mergeAll`, `concatAll` and `forkJoin`.
`bufferToggle` also had one bad dtslint test.
Related, I filed this in TS trying to figure this out: https://github.com/microsoft/TypeScript/issues/41091
=> Fix Issue 4532 subscribe no longer takes subscribable, forkJoin has N-arguments typings.

src/internal/observable/fromEvent.ts
- Adds a lot of comments.
- Adds one `TODO` that notes we may not want to be throwing the `TypeError` so late, it might be better for everyone if we throw that error as soon as we know about it, as it would provide a better call stack.
=> refactor(fromEvent): smaller implementation

spec/operators/audit-spec.ts, spec/operators/auditTime-spec.ts, src/internal/operators/audit.ts
Adjust audit operator to emit the last value when source completes
#5730
=> fix(audit, auditTime): audit and auditTime emit last value after source completes

spec/operators/withLatestFrom-spec.ts, src/internal/operators/withLatestFrom.ts
Attempt to fix #5827 by adjusting subscription order, let source does not complete even before subscribe into other sources.
=> fix(withlatestfrom): allow synchronous source

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/filter-spec.ts, src/internal/operators/filter.ts
I think that the changes on this PR improve the types of the `BooleanConstructor` overload of `filter`
EDIT: I force-pushed after @cartant approved the PR because I realized that I forgot to add `-0` to the list of falsy types. Sorry about that! :grimacing:
=> feat(filter): improve type inference for filter(Boolean)

api_guard/dist/types/index.d.ts, spec-dtslint/observables/iif-spec.ts, spec/observables/if-spec.ts, src/internal/observable/iif.ts
- Updates types
- Ensures that result arguments must be passed
- Ensures narrower type when conditional result is known to be `true`, or known to be `false`.
BREAKING CHANGE: `iif` will no longer allow result arguments that are `undefined`. This was a bad call pattern that was likely an error in most cases. If for some reason you are relying on this behavior, simply substitute `EMPTY` in place of the `undefined` argument. This ensures that the behavior was intentional and desired, rather than the result of an accidental `undefined` argument.
=> fix(iif): No longer allow accidental undefined arguments

api_guard/dist/types/index.d.ts, spec-dtslint/observables/combineLatest-spec.ts, spec-dtslint/observables/forkJoin-spec.ts, src/internal/observable/combineLatest.ts, src/internal/observable/forkJoin.ts
- Resolves an issue where `forkJoin([a, b, c] as const)` didn't infer properly.
- Updates `combineLatest` with new approach for n-args.
=> Refactor: combineLatest and forkJoin types for n-args

spec/operators/delayWhen-spec.ts, src/internal/operators/delayWhen.ts
- Resolves an issue where a duration selector that never emitted a value would cause the value to be emitted, even though there wasn't a "notification".
- `delayWhen` is now based on `mergeMap`. I started off with trying to use `mergeInternals`, but quickly realized it was doing the same thing as `mergeMap`, and I could just use that directly.
I'm not sure if this size optimization is "taking it too far", but I feel that `delayWhen` isn't exactly "hot path" code, so this optimization is fine, IMO, given the bundle savings it should yield.
=> fix(delayWhen): no longer emits if duration selector is empty

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/mergeMapTo-spec.ts, src/internal/operators/mergeMapTo.ts
I recently shipped a bug to production which TS should have caught. It looked something like this: https://stackblitz.com/edit/rxjs-jlgx8q?devtoolsheight=60
```ts
import { of } from "rxjs";
import { mergeMapTo } from "rxjs/operators";
const source = of(10);
const fn = () => {};
// Expected type error, but got none.
source.pipe(mergeMapTo(fn)).subscribe();
```
The reason TS doesn't catch this is because:
- `mergeMapTo` uses `ObservableInput<any>`
- `ObservableInput<any>` uses `ArrayLike<any>`
- TS has a "bug" whereby `ArrayLike<any>` is assignable to a function https://github.com/microsoft/TypeScript/issues/18757
We can workaround this by replacing `ObservableInput<any>` with `ObservableInput<unknown>`, as @cartant suggested on Twitter: …
=> Use `unknown` instead of `any` to catch more mistakes

tools/generate-alias.js
This aligns `types` prop usage in main `package.json` and generated ones via `generate-alias.js`.
=> build(package): use `types` instead of `typings` in generated alias

api_guard/dist/types/index.d.ts, spec-dtslint/observables/combineLatest-spec.ts, spec-dtslint/observables/forkJoin-spec.ts, src/internal/observable/combineLatest.ts, src/internal/observable/forkJoin.ts
This PR adds failing tests to show that the current signatures for `combineLatest` and `forkJoin` depend upon the excess-properties behaviour that TypeScript applies to object literals and fixes the problem by using a proper empty-object type in the function signatures.
See [this comment](https://github.com/ReactiveX/rxjs/pull/5830#discussion_r505902405).
=> fix: use empty object type in combineLatest/forkJoin sigs

spec/operators/endWith-spec.ts
Updated `endWith` tests to use run mode.
=> chore: update endWith tests to run mode

api_guard/dist/types/index.d.ts, spec-dtslint/observables/concat-spec.ts, src/internal/observable/concat.ts
This PR refactors the static `concat` to use N-args in the signature that accepts a trailing scheduler. And adds a bunch of this-usage-should-fail dtslint tests.
For whatever reason, the problems that occurred in the PRs that were opened for the static `merge` and `combineLastest` functions do not seem to occur here. A lot was going on in those PRs - and the conversations that took place in those PRs aren't especially easy to follow - but I would not be surprised if there is some small difference that effects different behaviour. For example, temporarily adding a signature that included a concurrency (for the purposes of experimentation) seemed to break things, so ... 🤷‍♂️ this seems fine here, but we might still have problems elsewhere. 🤞 …
=> refactor(concat): support N-args with scheduler

spec/operators/every-spec.ts
Updated `every` tests to use run mode.
=> chore: update every tests to run mode

spec/operators/concatMapTo-spec.ts, spec/operators/count-spec.ts, spec/operators/debounceTime-spec.ts, spec/operators/distinct-spec.ts, spec/operators/distinctUntilChanged-spec.ts, spec/operators/distinctUntilKeyChanged-spec.ts, spec/operators/skip-spec.ts, spec/operators/skipLast-spec.ts
- Reverted use of `of` from couple of test where I replaced them earlier (I could only find 3 such tests). See #5860.
- Improved imports, see #5820.
- Stopped passing scheduler to `debounceTime` now that it's been moved to run mode.
=> Test fixes

api_guard/dist/types/operators/index.d.ts, src/internal/operators/mergeWith.ts
This PR refactors the signatures of the `merge` and `mergeWith` _operators_ to use the variadic tuple technique that was employed in the `concat` PR - see #5857.
Hopefully, it should serve as a template for what needs to be done elsewhere whenever there are trailing arguments. It seems that when there are, the correct behaviour of the inference is extremely sensitive to the ordering of the signatures.
IMO, we should also be moving to using `unknown[]` as the type parameter constraint - along with `ObservableInputTuple` - instead of using `ObservableInput` in the constraint and `ObservedValueOf` in the return type. The former is, IMO, idiomatic TypeScript and the latter is not.
**Initial description (when it was still broken):**
This PR …
=> refactor(merge): support N-args with scheduler

src/internal/operators/first.ts, src/internal/operators/last.ts, src/internal/operators/mergeMapTo.ts
This PR replaces a few uses of `../../internal/types` with `../types`.
=> chore: simplify already-internal import locations

spec/operators/exhaust-spec.ts
Updated `exhaust` tests to use run mode.
@cartant, I've got two issues/questions here:
- The first test `should handle a hot observable of hot observables` is exactly the same as test `should handle a hot observable of observables` with the exception of `expectSubscriptions` calls. I was usually adding `expectSubscriptions` calls for those tests that didn't have them and wanted to do the same for this test, but then later I found out that they're the same. What I'd suggest is to transform this test to the one which would really satisfy what it says in the title (now, it doesn't handle observable of _hot_ observables, but rather _cold_ ones). I'd add `expectSubscriptions` where possible. Would you agree? If yes, is it OK to do it with this PR?
- I'd inline empty arrays. E.g. instead of: …
=> chore: update exhaust tests to run mode

api_guard/dist/types/index.d.ts, package-lock.json, package.json, src/internal/symbol/observable.ts, src/internal/types.ts
Resolves #5861
Resolves #4415
This is also related to issues here: https://github.com/benlesh/symbol-observable/issues/41
I don't think we can publish this in 6.x, as it will break people using older versions of `@types/node`, however, we do need to set an upper bounds for `@types/node` and version 6.x.
=> fix(Symbol.observable): properly defined as a `unique symbol`.

spec/operators/audit-spec.ts, spec/operators/bufferToggle-spec.ts, spec/operators/bufferWhen-spec.ts, spec/operators/debounce-spec.ts, spec/operators/sample-spec.ts, spec/operators/throttle-spec.ts, spec/operators/windowToggle-spec.ts, src/internal/operators/audit.ts, src/internal/operators/bufferToggle.ts, src/internal/operators/bufferWhen.ts, src/internal/operators/debounce.ts, src/internal/operators/sample.ts, src/internal/operators/throttle.ts, src/internal/operators/windowToggle.ts
This PR changes the behaviour of `audit`, `bufferToggle`, `bufferWhen`, `debounce`, `sample`, `throttle` and `windowToggle` so the that the `complete` notifications received from notifier/duration-selector observables are no longer treated as signals.
BREAKING CHANGES: the behaviour of the above-mentioned operators has changed for empty notifiers/selectors.
**Related issue (if exists):** #5838
=> fix: don't treat notifier completion as a signal

spec/operators/delay-spec.ts
- Enabled Prettier.
- Stopped passing scheduler to `delay` since run mode is already used.
- Used `time` helper to convert time units where possible (only negative time units were left out).
- Ordered variables so that they, where possible, have this order: `e1`, `e1subs` (where needed, renamed from `subs`), `t` and then `expected` since this is the most common ordering in many other tests.
None
=> chore: update delay tests

spec/operators/exhaust-spec.ts
As mentioned in #5866, the test edited in this PR is exactly the same as the test with this description `should handle a hot observable of observables` with the exception of `expectSubscriptions` calls, so I changed it a bit. Since it handles `observable of hot observables`, I changed `cold` with `hot` and added missing `expectSubscriptions` calls. I don't know if this change is necessary, but I thought that it could be included since having two same tests doesn't bring much value.
None
=> chore(exhaust-spec): replace cold with hot observable

docs_app/content/guide/testing/marble-testing.md
Adding documentation for `TestScheduler`'s `time` helper function.
#5822
=> docs(marble-testing): Document time helper function

spec/operators/auditTime-spec.ts
Updated `auditTime` tests:
- Enabled Prettier.
- Removed unused imports.
- Stoped passing scheduler to `auditTime`.
- Converted time with `time` helper.
- Renamed `subs` to `e1subs` to be consistent with other tests.
None
=> chore: update auditTime tests

src/internal/operators/shareReplay.ts
This PR removes a dead link from the comments/docs. It's a link to one of my blog posts, but the domain - which was once used for a Medium publication - seems to have been allowed to die, so lets just rid of the link altogether.
=> docs: remove dead link

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, src/internal/observable/onErrorResumeNext.ts, src/internal/operators/onErrorResumeNext.ts
This PR refactors the `onErrorResumeNext` creator and operator to use `ObservableInputTuple`, etc.
=> refactor: use ObservableInputTuple with onErrorResumeNext

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/withLatestFrom-spec.ts, src/internal/operators/withLatestFrom.ts
This PR refactors the signatures of the `withLatestFrom` operator to use N-args in the signature.
I also added a few more dtslint tests and altered the current ones to better reflect the intent of the typings.
There is one issue with the typings I could not get to work correctly.
```typescript
const a = of(1, 2, 3);
const b = [a, a, a];
const res = a.pipe(withLatestFrom(...b, (a, b, c, d) => d); // Should be Observable<number> but is infered as Observable<unknown>
```
#5066
=> refactor(withLatestFrom): support N-args with project function

package-lock.json, package.json, src/internal/util/deferred.ts
The TypeScript 4.1 RC was released on 5 November and - according the the [official release schedule/process](https://github.com/microsoft/TypeScript/wiki/TypeScript's-Release-Process) - actual releases occur two weeks after the RC. That means we can expect the 4.1 release in a week or so. IMO, we should aim at establishing 4.1 as our minimum version for version 7 - so that its features (recursive conditional types, in particular) are available to us (even if we don't rely upon them in the initial version 7 types).
=> chore: bump TypeScript version to 4.1 RC

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec/operators/combineLatest-spec.ts, spec/operators/combineLatestWith-spec.ts, spec/operators/zip-spec.ts, spec/operators/zipWith-spec.ts, src/internal/operators/combineLatestWith.ts, src/internal/operators/concatWith.ts, src/internal/operators/mergeWith.ts, src/internal/operators/raceWith.ts, src/internal/operators/zipWith.ts, src/internal/types.ts
This PR refactors the `xWith` operators - `concatWith`, et al. - to use `ObservableInputTuple` with a type-parameter constraint of `readonly unknown[]` - instead of `ObservableInput<any>[]`. The former is simpler, more idiomatic and doesn't rely on the `ObservedValueOf` type.
Interestingly, this change uncovered two tests that use result selectors. I have no idea how those tests compiled without effecting TypeScript compilation errors. I've split the tests out into separate files `combineLatest-spec.ts` and `zip-spec.ts`, as the non-`With` operators are deprecated, but still exported. I guess this shows that the `ObservableInputTuple` approach has some advantages.
The refactor also removed some unnecessary overload signatures.
This PR deliberately does not refactor the …
=> refactor: use ObservableInputTuple in xWith operators

package.json
This is a minimal PR that makes sure that the types are built whenever `api_guardian:update` is run. Once again, I wasted time running it with stale types. This small change will, at least, avoid that annoyance. Really, though, we should give these scripts some more serious tweaks to perhaps run `api_guardian:update` as part of running the dtslint tests - as discussed with Ben, on Slack.
=> chore: build types on api_guardian update

api_guard/dist/types/index.d.ts, src/internal/observable/merge.ts
#5844 was closed in favour of #5859, but that PR refactored only the operators - not the static `merge`.
This PR refactors the static `merge` to use `ObservableInputTuple`, etc.
FWIW, I'm aware that there is an `argsOrArgArray` call in the implementation, but IMO we should not be introducing signatures that allow arrays of sources to be passed to `merge`. AFAICT, there were no such signatures prior to the refactor and there are no such signatures in version 6. Furthermore, there are behavioural differences between `concat` and `merge` because of this. Basically, I've spent a chunk of time compiling a table of the signature and implementation differences (for v6 and v7) relating to arrays of sources and varargs. I'd like to keep this PR as simple as possible and address …
=> refactor(merge): support N-args with concurrency and scheduler

src/internal/operators/onErrorResumeNext.ts
After upgrading to TS 4.1 RC, there's an incorrect inference in the implementation of `onErrorResumeNext`. The problem didn't occur in the refactor of that operator - which was done under TS 4.0 - and the inference is clearly incorrect. This PR adds an explicit assertion - and a comment - as a workaround.
=> chore(onErrorResumeNext): work around TS 4.1 RC bug

package-lock.json, package.json
**Description:** What it says in the title.
=> chore: bump to TypeScript 4.1.2

spec/operators/finalize-spec.ts
Updated `finalize` tests to use run mode.
One note: I didn't want to add `testScheduler` and `beforeEach` to the `describe` callback (as it's usually done in other tests) because many of the tests in this suite don't use `testScheduler` instance, so I was creating them where they were needed.
None
=> chore: update finalize tests to run mode

api_guard/dist/types/index.d.ts, spec-dtslint/operators/pairs-spec.ts, src/internal/observable/pairs.ts
Types now match runtime behavior more closely.
=> refactor(pairs): Fix TS types to be more accurate

spec/schedulers/TestScheduler-spec.ts, spec/tsconfig.json, src/internal/testing/TestScheduler.ts, src/tsconfig.cjs.json, src/tsconfig.esm5.json
This PR adds support for emoji characters in marble diagrams by leveraging ES2015's built-in emoji support for string iteration.
An attempt to add this feature was made before - in #3857 - but that attempt sought to use `toArray` from `lodash`. This PR relies upon the built-in behaviour (and downleveled iteration for the ES5 builds):
```ts
const string = '🙈🙉🙊';
const { length } = string; // 6
const characters = [...string]; // ['🙈', '🙉', '🙊']
```
And, let's face it, this is something that everyone <s>wants</s> needs, right?
=> feat: support emoji in marble diagrams

api_guard/dist/types/index.d.ts, spec-dtslint/observables/zip-spec.ts, src/internal/observable/zip.ts
Updates the static `zip` to use `ObservableInputTuple`, etc.
=> refactor(zip): support N-args with result selector

api_guard/dist/types/index.d.ts, spec-dtslint/observables/forkJoin-spec.ts, src/internal/observable/forkJoin.ts
This PR tweaks the overload signatures for `forkJoin` to remove an `any`-based signature, replacing it with an N-args versions that accept (deprecated) result selectors.
<s>The PR also adds `readonly` qualifiers for the `[...ObservableInputTuple<A>]` types. I swear I tested `readonly` qualifiers with mapped tuple types for a blog post and found that they weren't necessary. However, without them, tests fail. IDK whether or not this is a TypeScript-version issue. I will look into it later and separately.</s>
=> refactor(forkJoin): remove any-based signature

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, api_guard/dist/types/testing/index.d.ts, spec/deprecation-equivalents/multicasting-deprecations-spec.ts, spec/operators/connect-spec.ts, spec/operators/publishReplay-spec.ts, spec/operators/share-spec.ts, spec/schedulers/TestScheduler-spec.ts, src/index.ts, src/internal/Observable.ts, src/internal/Subscriber.ts, src/internal/observable/ConnectableObservable.ts, src/internal/observable/connectable.ts, src/internal/observable/fromSubscribable.ts, src/internal/operators/connect.ts, src/internal/operators/multicast.ts, src/internal/operators/publish.ts, src/internal/operators/publishBehavior.ts, src/internal/operators/publishLast.ts, src/internal/operators/publishReplay.ts, src/internal/operators/refCount.ts, src/internal/operators/share.ts, src/internal/operators/shareReplay.ts, src/internal/testing/TestScheduler.ts, src/internal/types.ts, src/operators/index.ts
I'd like to do this instead of what I was doing over at #5432 ..
1. Make `share` configurable, such that it can be used to create things like `shareReplay` or people can configure the behavior however they like. If they want a `shareBehavior` or `shareLast`, they can easily make it work however they like.
2. Add a new`connect` operator that does the "selector" version of `multicast`, `publish`, et al. (this also fixes a broken error behavior in `publishReplay`). 
3. Add a new `makeConnectable` function that creates a `ConnectableObservableLike` (instead of `ConnectableObservable`).
- `share` (NOTE: I'll leave `shareReplay` as just a wrapper around this, as seen in this PR)
- `connect`
- `connectable`
- `share`
- `multicast`
- `publish`
- `publishLast`
- `publishReplay`
- `publishBehavior` …
=> Reworking Multicasting: share, connect, and makeConnectable

package-lock.json, src/internal/observable/dom/fetch.ts
`init` object is created using rest operator
this means that `init` always will be an object which is a truthy value
this commit removes redundant `init` check
Related: https://github.com/ReactiveX/rxjs/pull/5306/files#r542228847
=> refactor(fromFetch): remove redundant if wrap of init

spec-dtslint/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
Makes it possible to use `fromEvent()` with a simple `EventTarget`.
Closes #5944
=> fix(fromEvent): fixed HasEventTargetAddRemove to support EventTarget types

src/internal/operators/OperatorSubscriber.ts
See the comments within the change. This PR should help realise one of the advantages of replacing operator-specific subscribers with a general-purpose subscriber - reducing/eliminating megamorphic property accesses within `Subscriber`.
I've not done any micro optimization/analysis, yet. I'll look at doing that after the version 7 release. However, I think that what's in this PR makes sense and shouldn't be controversial. 🤞
=> perf: ensure same hidden class for OperatorSubscriber

spec/operators/ignoreElements-spec.ts
Updated `ignoreElements` tests to use run mode.
None
=> chore: update ignoreElements tests to run mode

spec/operators/isEmpty-spec.ts
Updated `isEmpty` tests to use run mode.
None
=> chore: update isEmpty tests to run mode

spec/Observable-spec.ts, src/internal/Observable.ts, src/internal/Subscriber.ts, src/internal/config.ts
Adds some logic to handle the deprecated case. This is unfortunate, but it's necessary to properly support people who are still using this feature until we can remove it. Note that there is potentially a severe performance penalty for people using this feature. But they're being warned at every turn, and the migration path to get away from this is easy: Stop relying on synchronously thrown errors.
fixes #5979
=> fix: Resolve issues with deprecated synchronous error handling and chained operators

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/observables/iif-spec.ts, spec-dtslint/operators/first-spec.ts, spec-dtslint/operators/last-spec.ts, spec-dtslint/operators/single-spec.ts, spec-dtslint/operators/takeWhile-spec.ts, src/internal/observable/iif.ts, src/internal/operators/first.ts, src/internal/operators/last.ts, src/internal/operators/single.ts, src/internal/operators/takeWhile.ts
=> fix: predicates that return `any` will now behave property in TS

spec/Observable-spec.ts, src/internal/Subscriber.ts
=> fix: useDeprecatedSynchronousErrorThrowing honored for flattened sync sources

docs_app/content/guide/testing/marble-testing.md
In the Time Progression Syntax section under Marble Testing, one of the examples's description is incorrect. Please see the example and the updated description below:
**Current**: `'a 9ms b 9s c|'`: on frame 0 emit a, on frame 10 emit b, on frame 10,012 emit c, then on on frame 10,013 complete.
**Updated**: `'a 9ms b 9s c|'`: on frame 0 emit a, on frame 10 emit b, on frame **9,011** emit c, then on on frame **9,012** complete.
https://github.com/ReactiveX/rxjs/issues/5977
=> Correct Progression Syntax example in the Marble Testing section

docs_app/content/navigation.json, docs_app/tools/transforms/links-package/index.js, docs_app/tools/transforms/links-package/services/disambiguators/disambiguateByNonMember.js, docs_app/tools/transforms/links-package/services/disambiguators/disambiguateByNonMember.spec.js, src/internal/ReplaySubject.ts, src/internal/Subscription.ts, src/internal/ajax/errors.ts, src/internal/operators/endWith.ts, src/internal/operators/publishReplay.ts, src/internal/operators/startWith.ts, src/internal/operators/windowTime.ts, src/internal/operators/zipAll.ts, src/internal/types.ts
By commits:
- Removed URL from navigation pointing to an already removed page that was mistakenly reverted back to `navigation.json` in #5814. The error when building `docs`:
is now gone.
- Fixed links on `Subscription` docs.
- Fixed link to `asObservable` in `publishReply`.
- Fixed `@return` statement in `windowTime` what had bad formatting producing warning when building docs.
- Adding new disambiguator that fixed links to `EMPTY` and `timestamp` because there were multiple documents pointing to them. New disambiguator does not prefer members. Taken from [Angular](https://github.com/angular/angular/pull/24000). Examples:
- `operators/timeout` vs `ajax/AjaxRequest.timeout`,
- `EMPTY` vs `Subscription.EMPTY`.
None
=> Fix errors and warnings when building docs + fix links

spec/observables/forkJoin-spec.ts, spec/observables/zip-spec.ts
This PR adds a test for `zip` that's similar to the one that was added for `combineLatest` in #5963.
**Related <s>issue</s> PR:** #5963
=> test: add empty-sources-array test for zip

spec/observables/dom/ajax-spec.ts
Moved the spec updates to a different PR than #6001 so they can be reviewed separately. That way it's perhaps easier to tell they're doing the same thing.
=> test: Fix/update the ajax tests to be a little more correct

spec/Observable-spec.ts, src/internal/observable/ConnectableObservable.ts, src/internal/operators/multicast.ts
- Adds tests to show fixed issues
- Adds tests to show issues that simply can't be fixed, and support a case against removing operators that return ConnectableObservable, as well as possibly a case against lifting Subject.
- Moves logic that patched lift for ConnectableObservable to the constructor so it is used by all multicast operators
=> fix: publish variants returning ConnectableObservable not properly utilizing lift

api_guard/dist/types/ajax/index.d.ts, spec/observables/dom/ajax-spec.ts, src/internal/ajax/AjaxResponse.ts, src/internal/ajax/ajax.ts, src/internal/ajax/types.ts
- Fixes a bunch of tests that were slightly off or had bad assumptions
- Adds two new features: `includeUploadProgress` and `includeDownloadProgress` that will add additional events to the output stream before the event that is usually emitted.
Resolves #2833
NOTE: We still need to add an example of usage.
=> feat(ajax): Add option for streaming progress

spec/operators/concatAll-spec.ts, spec/operators/concatMap-spec.ts, src/internal/operators/OperatorSubscriber.ts, src/internal/operators/mergeInternals.ts
Resolves an issue where inner observables would not finalize before the next inner observable got subscribed to. This happened in concat variants, and merge variants with concurrency limits, and could be surprising behavior to some users.
fixes #3338
=> fix: concat/merge operators will finalize inners before moving to the next

src/internal/operators/windowTime.ts
=> docs(windowTime): add units to windowTimeSpan documentation

spec/operators/distinctUntilChanged-spec.ts, src/internal/operators/distinctUntilChanged.ts
distinctUntilChanged should set `prev` value with `keySelector` even at the first time
https://github.com/ReactiveX/rxjs/issues/6012
=> distinctUntilChanged should set `prev` value with `keySelector` even at the first time

api_guard/dist/types/operators/index.d.ts, spec/operators/distinctUntilChanged-spec.ts, src/internal/operators/distinctUntilChanged.ts
- Fixes an issue where reentrant code would not be compared properly against previous emissions
- Adds better code comments
- Updates documentation with better text and examples
Related to #6013
=> fix(distinctUntilChanged): Ensure reentrant code is compared properly

src/internal/observable/combineLatest.ts, src/internal/observable/forkJoin.ts, src/internal/util/createObject.ts
- cleans up unnecessary helper function
- creates `createObject` helper function to use in both
- uses `mapOneOrManyArgs` helper.
- switches to decrement instead of increment for internal counters for lighter weight conditionals
=> refactor(forkJoin): clean up logic - unify approach with combineLatest

.github/workflows/ci_ts_latest.yml
This PR installs `tslib@latest` and `@types/node@latest` in the `ts@latest` CI check. Doing so will avoid problems like those that occurred in #5932.
**Related PR:** #5932
=> chore: install other @latest packages for ts@latest CI test

.github/workflows/ci_ts_latest.yml, spec/operators/shareReplay-spec.ts, spec/support/default.opts, src/internal/operators/shareReplay.ts
Fixes possible memory leaks caused by the `shareReplay` operator
#5931
=> fix(shareReplay): handle possible memory leaks

spec/operators/shareReplay-spec.ts, spec/support/.mocharc.js, src/internal/operators/share.ts
This PR brings in the test from #5932 and fixes a leak that it exposed in the `share` implementation.
Maybe we should add the test to the specs for `share`, too, but this is all I have time for, ATM.
**Related PR:** #5932
=> fix: add test from #5932 and plug leak in share

spec/observables/bindCallback-spec.ts, spec/observables/bindNodeCallback-spec.ts
The `ts@latest` CI task installs the latest Node types, too. This effects some breakages in tests - where `setTimeout` is assumed to return `number`. This PR uses `ReturnType` instead.
Also, as there are two signatures for `setTimeout` - in the Node types and in TypeScipt's DOM types - the duration has to be specified - otherwise, the call will match the second signature (the TypeScript one) which returns `number`. 🙈
**Related PR:** #6038
=> chore: account for Node.js setTimeout return type

spec/operators/materialize-spec.ts
Updated `materialize` tests to use run mode.
I have removed one of the tests (named `should materialize stream never completes`) because it was completely the same as the test before, it only used `cold` instead of `hot`, but emissions and the subscriptions points were the same.
None
=> chore: update materialize tests to run mode

spec/observables/dom/ajax-spec.ts, src/internal/ajax/ajax.ts
In the event of a network disconnection or other abort event, the returned observable will now error with an `AjaxError` and the message `"aborted"`.
Resolves #4251
=> fix(ajax): now errors on forced abort

spec/operators/max-spec.ts
Updated `max` tests to use run mode.
_Please note_: in test `should max the values of an ongoing hot observable`, I changed one of the values to be less then the value emitted by the hot observable _before_ the subscription (changed from `666` to just `6` as it is less than `42`), so it is clear that the value emitted before subscription is not taken into consideration.
None
=> chore: update max tests to run mode

src/internal/operators/debounceTime.ts
Addresses #6045 
This turned out to be similar to `debounce`, but with the optimisation on the scheduling bit. Tests unchanged are green, I'm not sure how can I add a test for performance.
This optimization can't be used in the `debounce` operator, as that one takes in a stream, where only way of getting the "time window" is by unsubscribing from the previous stream and subscribing on the current one. With `debounceTime`, as the dueTime is always the same we can optimise.
In case this PR moves forward, would it be worth also having the same optimisation on RxJS@^6' debounceTime?
=> fix(debounceTime): improves performance on quick succession of emits

package-lock.json, package.json, spec-dtslint/operators/materialize-spec.ts, spec-dtslint/operators/skipWhile-spec.ts, spec-dtslint/operators/takeWhile-spec.ts, src/internal/observable/bindCallback.ts, src/internal/observable/bindNodeCallback.ts
Does what it says on the tin.
As usual, there are some changed necessary in the dtslint tests.
And there seems to be a TS bug - with the `bindCallback` and `bindNodeCallback` signature matching - that needs a workaround. See https://github.com/ReactiveX/rxjs/pull/6048/commits/c71a9dcdd4211d67dc02879b16ca8f5841075fe3
=> chore: bump to TypeScript 4.2.2

src/internal/observable/bindCallback.ts, src/internal/observable/bindNodeCallback.ts, src/internal/util/workarounds.ts
This PR replaces the workaround - for what seems to be a TS 4.2 problem - with an explicit type instead of an `any`.
**Related PR:** #6048
=> chore: use workaround type instead of any

spec/observables/dom/ajax-spec.ts, src/internal/ajax/ajax.ts
fix(ajax): Ensure that `responseType` defaults to `"json"`
- Updates tests to be more accurate
Resolves #6052
chore: Fix XHR mock to not change responseType on its own
=> Fix/6052 ajax responseType should default to "json"

spec/operators/throttle-spec.ts, src/internal/operators/throttle.ts
Resolves an edge case where if a user provided a synchronous source and a synchronous notifier, using a trailing behavior, the returned observable would get caught in a loop emitting the final value over and over again.
fixes: #6058
=> fix(throttle): no longer emits more than necessary in sync/sync trailing case

package-lock.json, spec/observables/from-spec.ts, src/internal/Subscriber.ts, src/internal/observable/from.ts, src/internal/operators/OperatorSubscriber.ts
- Resolves an issue where AsyncGenerators were not properly finalized when an observable result was unsubscribed.
- Resolves another nearly impossible to test scenario that this happens to cover: In the event of an operator like `take()` completing the resulting observable, if an error is thrown in the terminal completion handler, teardown is not invoked, as it would not continue to the next line to call the unsubscribe method of the Subscriber instance. This was resolved by ensuring synchronous calls before the unsubscribe call are called in a try/finally block.
Fixes #5998
=> fix: finalization/teardown fixes for AsyncGenerators and take

src/internal/observable/bindCallback.ts, src/internal/observable/bindNodeCallback.ts, src/internal/util/workarounds.ts
This PR removes the workaround type that was added for `bindCallback` in #6050. TypeScript is correct that the signatures aren't compatible because callback arguments are contravariant.
**Related PR:** #6050
=> chore: remove bindCallback workaround

src/internal/operators/elementAt.ts, src/internal/operators/skipLast.ts
docs(skipLast): Fix a typo
docs(elementAt): Fix a typo
=> Fix two typos in docs

api_guard/dist/types/index.d.ts, src/internal/util/isObservable.ts
This PR removes a misused type parameter from `isObservable`. The type parameter `T` is misused because there's no way it  can be inferred; it's nothing more than a type assertion. There is no way `isObservable` can know the element type of any value that it deems to be an `Observable`, so it should return `Observable<unknown>`. IMO, we should not be encouraging devs to write unsafe code.
**BREAKING CHANGE:** `isObservable` returns `is Observable<unknown>` and no longer accepts a type parameter.
=> fix: remove misused type parameter from isObservable

api_guard/dist/types/index.d.ts, spec-dtslint/observables/using-spec.ts, src/internal/observable/using.ts
This PR uses `ObservedValueOf` in `using` to extract the observable element type from factories that return union types - as is done [elsewhere in the library](https://github.com/ReactiveX/rxjs/blob/65de22958f1b4cbf2b7a0de44be89a5bbf36ff90/src/internal/operators/mergeMap.ts#L9-L12).
=> fix/refactor: use ObservedValueOf in using

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/expand-spec.ts, src/internal/operators/expand.ts
This PR changes `expand` to use `ObservedValueOf` for its `project` function - as is done [elsewhere in the library](https://github.com/ReactiveX/rxjs/blob/65de22958f1b4cbf2b7a0de44be89a5bbf36ff90/src/internal/operators/mergeMap.ts#L9-L12).
=> fix/refactor: use ObservedValueOf in expand

api_guard/dist/types/index.d.ts, src/internal/observable/of.ts
This PR:
- refactors the `Scheduler`-related `of` signatures to use the n-args approach; and
- adds explicit `null` and `undefined` signatures to avoid incorrect types and confusing deprecation warnings for devs using `strictNullChecks: false` (even though they are naughty).
_I realize that these sigs are deprecated, but [we already have deprecated sigs in operators](https://github.com/ReactiveX/rxjs/blob/a7a04d1110666606a1f2ca6fd38642e6ca74f287/src/internal/operators/mergeWith.ts#L8-L17) that use n-args, so, IMO, things are less confusing if n-args is useds wherever possible. See also the reasons listed in https://github.com/ReactiveX/rxjs/pull/6092#issue-585989828_
=> refactor: use n-args for of scheduler signatures

api_guard/dist/types/operators/index.d.ts, src/internal/operators/elementAt.ts
This PR removes the overload signatures for `elementAt` and uses a default type parameter so that it's possible for (naughty) devs to explicitly specify a single type parameter. (This was the approach used with the related signatures in `first` and `last`.)
=> refactor: remove elementAt overload signatures

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/findIndex-spec.ts, src/internal/operators/findIndex.ts
The changes in #5987 missed a `findIndex` signature that matched predicates that always returned `false` and was not compatible with predicates typed as returning `any`.
**Related issue (if exists):** #5986 and #5987
=> fix: predicates that return `any` will now behave property with findIndex

api_guard/dist/types/operators/index.d.ts, src/internal/operators/endWith.ts
This PR refactors the `Scheduler`-related `endWith` signatures to use the n-args approach.
_I realize that these sigs are deprecated, but [we already have deprecated sigs in other operators](https://github.com/ReactiveX/rxjs/blob/a7a04d1110666606a1f2ca6fd38642e6ca74f287/src/internal/operators/mergeWith.ts#L8-L17) that use n-args, so, IMO, things are less confusing if n-args is useds wherever possible. See also the reasons listed in https://github.com/ReactiveX/rxjs/pull/6092#issue-585989828_
=> refactor: use n-args for endWith scheduler signatures

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/connect-spec.ts, src/internal/operators/connect.ts
This PR changes `connect` to use `ObservedValueOf` for its `selector` function - as is done [elsewhere in the library](https://github.com/ReactiveX/rxjs/blob/65de22958f1b4cbf2b7a0de44be89a5bbf36ff90/src/internal/operators/mergeMap.ts#L9-L12).
=> fix/refactor: use ObservedValueOf in connect

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/combineLatest-spec.ts, src/internal/operators/combineLatest.ts
This PR refactors the `combineLatest` operator's signatures to use the n-args approach.
=> refactor: use n-args for combineLatest operator

api_guard/dist/types/index.d.ts, spec-dtslint/observables/combineLatest-spec.ts, src/internal/observable/combineLatest.ts
This PR tightens the `combineLatest` POJO signature so that only POJOs with `ObservableInput` values are matched. The implementation throws if the received POJO contains a value that is not an `ObservableInput`, so the types should reflect that.
=> fix: combineLatest POJO signature should match only ObservableInput values

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/timeout-spec.ts, src/internal/operators/timeout.ts, src/internal/operators/timeoutWith.ts
This PR changes `timeout` to use `ObservedValueOf` for its `with` option - as is done [elsewhere in the library](https://github.com/ReactiveX/rxjs/blob/65de22958f1b4cbf2b7a0de44be89a5bbf36ff90/src/internal/operators/mergeMap.ts#L9-L12).
=> fix/refactor: use ObservedValueOf in timeout

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/every-spec.ts, src/internal/operators/every.ts
This PR adds an overload signature with a type parameter for the `thisArg` parameter in `every` so that if `this` is used in the predicate, it it correctly typed. If an arrow function is used, it behaves as before - regardless of whether a `thisArg` is specified or not.
=> fix/refactor: add type parameter for thisArg in every

api_guard/dist/types/index.d.ts, spec-dtslint/observables/partition-spec.ts, src/internal/observable/partition.ts
This PR adds an overload signature with a type parameter for the `thisArg` parameter in `partition` so that if `this` is used in the predicate, it it correctly typed. If an arrow function is used, it behaves as before - regardless of whether a `thisArg` is specified or not.
=> fix/refactor: add type parameter for thisArg in partition

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/map-spec.ts, src/internal/operators/map.ts
This PR adds an overload signature with a type parameter for the `thisArg` parameter in `map` so that if `this` is used in the predicate, it it correctly typed. If an arrow function is used, it behaves as before - regardless of whether a `thisArg` is specified or not.
=> fix/refactor: add type parameter for thisArg in map

spec/Subject-spec.ts, spec/operators/throttle-spec.ts, src/internal/Observable.ts, src/internal/Subscriber.ts
- Resolves an issue where errors thrown in a handler provided as a plain function, or as part of a POJO observer, to a `subscribe` call were not being handled appropriately. They will no longer synchronously throw unless `useDeprecatedSynchronousErrorHandling` is configured to `true`.
- Removes two tests that were poorly written, and were not passing (and should never have been passing). The ground they covered is covered adequately by other tests.
=> fix: unhandled errors in observers correctly scheduled

spec/operators/zipAll-spec.ts
This PR adds prettier formatting to the `zipAll` operator tests and replaces deprecated API calls.
None
=> refactor(zipAll): replace deprecated apis

spec/operators/zipWith-spec.ts
Use Prettier to format the `zipWith` tests. They are already written using the `TestScheduler`. Also refactored one of the tests that was using some deprecated APIs.
I made two commits to separate the refactoring from the formatting.
=> refactor(zipWith): remove deprecated api calls

spec/operators/zip-legacy-spec.ts
This PR introduces prettier formatting in `zip` Legacy tests. One use of the deprecated subscribe signature is replaced and anonymous functions are converted to arrow functions.
None
=> Zip legacy formatting

spec/operators/windowWhen-spec.ts
This PR converts `windowWhen` tests to run mode.
None
=> chore(windowWhen): convert windowWhen tests to run mode

api_guard/dist/types/operators/index.d.ts, src/internal/operators/concat.ts
This PR refactors the `concat` operator's signatures to use the n-args approach.
=> refactor: use n-args for concat operator

api_guard/dist/types/operators/index.d.ts, src/internal/operators/merge.ts
This PR refactors the `merge` operator's signatures to use the n-args approach.
=> refactor: use n-args for merge operator

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/race-spec.ts, src/internal/operators/race.ts
This PR refactors the `race` operator's signatures to use the n-args approach and deletes tests that are no-longer-relevant with the n-args implementation.
=> refactor: use n-args for race operator

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/zip-spec.ts, src/internal/operators/zip.ts
This PR refactors the `zip` operator's signatures to use the n-args approach and deletes tests that are no-longer-relevant with the n-args implementation.
=> refactor: use n-args for zip operator

api_guard/dist/types/operators/index.d.ts, src/internal/operators/startWith.ts
This PR refactors the `startWith` operator's signatures to use the n-args approach.
And ... AFAICT this is the last n-args refactor! They should all be done now. I have a few more things to do, but a v7 release is now imminent. 🎉
=> refactor: use n-args for startWith

spec/Subscriber-spec.ts, spec/operators/shareReplay-spec.ts, src/internal/Subscriber.ts, src/internal/operators/OperatorSubscriber.ts
This PR adds a failing test that shows that subscriptions - i.e. subscribers - returned from `subscribe` leak their destinations - i.e. their observers or callbacks.
The PR changes `Subscriber#unsubscribe` to null the `destination` after `super.unsubscribe` is called.
This change broke three operators - `bufferWhen` was one of them - because if unsubscription was effected within `onNext` and if an error was thrown from within `onNext` (after the unsubscription) it'd be caught in the `OperatorSubscriber` and an attempt would be made to call `this.destination.error`, but `this.destination` would be `null`.
Rather than capture `this.destination` before the `try/catch` around `onNext`, `onComplete`, and `onError`, I just used the `destination` that was passed in to the …
=> fix(Subscriber): don't leak destination

api_guard/dist/types/index.d.ts, spec-dtslint/util/pipe-spec.ts, src/internal/util/pipe.ts
The static `pipe` utility has a signature that accepts no argument yet has a type parameter - type parameters aren't really supposed to be used like this. This PR changes the return type for that signature to be `typeof identity` - which is what's returned. This means that the returned function can be used without losing the type of the argument passed to it:
```
const func = pipe();
const value = func(42); // type of value will be 42, not unknown
```
Calling `pipe` without passing arguments is something of an edge case, but I suppose it's more likely with spread tuples or something. Anyway, it's a misused type parameter, so we should remove it.
**Related issue (if exists):** #5557
=> fix: remove misused type parameter from static pipe

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/concatMapTo-spec.ts, src/internal/operators/concatMapTo.ts
This PR makes a similar change to what was made in #5839 so that functions are not matched - because of https://github.com/microsoft/TypeScript/issues/18757
**Related issue (if exists):** #5839
=> refactor: use unknown in concatMapTo type parameter constraint

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/switchMapTo-spec.ts, src/internal/operators/switchMapTo.ts
This PR makes a similar change to what was made in #5839 so that functions are not matched - because of https://github.com/microsoft/TypeScript/issues/18757
Also:
- The signatures prior to this change weren't using `ObservedValueOf`.
- The PR also uses `isFunction` to check the result selector, as that's what's done in both `concatMapTo` and `mergeMapTo` in `master`.
**Related issue (if exists):** #5839
=> refactor: use unknown in switchMapTo type parameter constraint

api_guard/dist/types/index.d.ts, spec-dtslint/observables/combineLatest-spec.ts, src/internal/observable/combineLatest.ts
This PR removes union-array signatures - i.e. signatures that contain `Array<O | SchedulerLike>`, etc. - from `combineLatest`. The n-args signatures are after - as they prevent arbitrarily-place schedulers, etc. - and the union-array signatures have already been removed from some other functions/operators.
=> chore: remove union-array signatures from combineLatest

spec-dtslint/operators/combineLatestAll-spec.ts, spec-dtslint/operators/zipAll-spec.ts
This PR adds dtslint tests - with comments - that better represent why `combineLatestAll` and `zipAll` need signatures that accept project functions that take values of type `any`.
=> test: add dtslint tests for combineLatestAll and zipAll

api_guard/dist/types/operators/index.d.ts, src/internal/operators/concatAll.ts
Does what it says in the title. The overloads aren't needed; `mergeAll` does not have them - they've already been removed from that operator, so they should be removed here.
=> chore: remove concatAll overloads

api_guard/dist/types/operators/index.d.ts, spec/operators/exhaustAll-spec.ts, src/internal/operators/exhaustAll.ts
Does what it says in the title. The overloads aren't needed; `mergeAll` does not have them - they've already been removed from that operator, so they should be removed here. The PR also changes the implementation signature to use `ObservedValueOf` - as in `concatAll` and `mergeAll`.
=> chore: remove exhaustAll overloads

src/internal/operators/switchAll.ts
This PR removes the `switchAll` overload - there was only one, so it might as well be the implementation signature.
=> chore: remove switchAll overload

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/find-spec.ts, spec-dtslint/operators/findIndex-spec.ts, src/internal/operators/find.ts, src/internal/operators/findIndex.ts
This PR adds an overload signature with a type parameter for the `thisArg` parameter in `find` and `findIndex` so that if `this` is used in the predicate, it it correctly typed. If an arrow function is used, it behaves as before - regardless of whether a `thisArg` is specified or not.
=> fix/refactor: add type parameter for thisArg in find/findIndex

api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/filter-spec.ts, src/internal/operators/filter.ts
This PR adds an overload signature with a type parameter for the `thisArg` parameter in `filter` so that if `this` is used in the predicate, it it correctly typed. If an arrow function is used, it behaves as before - regardless of whether a `thisArg` is specified or not.
=> fix/refactor: add type parameter for thisArg in filter

spec/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
This PR changes the implementation of `fromEvent` so that it throws when called - rather than when subscribed - if the passed event target is invalid.
**BREAKING CHANGE:** if passed an invalid event targed `fromEvent` will throw an error when called. Previously, it would emit an error notification when a subscription was made.
**Related issue (if exists):** #5823
=> fix(fromEvent): throw if passed invalid target

src/internal/operators/skipLast.ts
- Fixes names to be a little more relevant.
- Adds additional comments to the code about why it is doing what it is doing
- Updates documentation
- Remove incorrect documentation about thrown values
Inspired by @jakovljevic-mladen's PR: #5784
=> refactor(skipLast): fix names, update docs and comments

docs_app/content/guide/operators.md
The **distinctKey** operator does not exists anymore, but is listed in the /guide/operators page of the docs, with a link to a 404 page.
This PR just removes the reference.
https://github.com/ReactiveX/rxjs/issues/4980
=> fix(docs): remove distinctKey from operators list

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/Observable-spec.ts, spec-dtslint/operators/tap-spec.ts, src/internal/Observable.ts, src/internal/operators/tap.ts
Does what it says in the title.
=> refactor: align tap sigs with subscribe

docs_app/content/guide/operators.md
Hello! While learning about RxJS I came across a broken image link in the documentation. Not the biggest problem but I wanted to help fix it. Looks like it was a simple path issue.
With this fix, the image should now be properly displayed. You can see it in action on my [working branch](https://github.com/seanforyou23/rxjs/blob/docs-img-fix/docs_app/content/guide/operators.md#marble-diagrams). Hope it helps!
https://github.com/ReactiveX/rxjs/issues/5923
=> fix(doc): fix broken image link

api_guard/dist/types/index.d.ts, spec-dtslint/observables/partition-spec.ts, src/internal/observable/partition.ts
Just adds a new overload to `partition` to give more useful types, similar to the one for `filter`. I found myself wanting this feature, and It seemed easy enough to implement.
=> docs(partition): add an overload for better typing

src/internal/Observable.ts
* docs(subscribe): add comma after "In particular"
* docs(subscribe): add notice about asynchronously thrown errors
* docs(subscribe): add notice about deprecated usages of `subscribe` method (relates to #4159)
* docs(subscribe): add notice about using `subscribe` with no params
* docs(subscribe): fix example not to use deprecated `subscribe`
* docs(subscribe): add example with deprecated `subscribe` with notice that it's deprecated
* docs(subscribe): fix unsubscribe example replacing deprecated `subscribe` usage with Observer
* docs(subscribe): add notice that unprovided error handlers will cause throwing errors asynchronously
* docs(subscribe): fix return type
I'm certainly not a native English speaker, but there's a `span` tag in `Observable.subscribe` documentation that says this:
> …
=> docs(subscribe): update `subscribe` documentation

spec/operators/windowToggle-spec.ts
This PR converts `windowToggle` tests to run mode.
None
=> chore(windowToggle): convert windowToggle tests to run mode

spec/operators/windowWhen-spec.ts
This PR fixes the remaining test description typos that were effected by a search-replace of `var` with `const`.
=> chore: constying

spec/operators/window-spec.ts
This PR converts `window` tests to run mode.
None
=> chore(window): convert window tests to run mode

spec/operators/toPromise-spec.ts
This PR converts`toPromise` operator tests to run mode. I did a few intermediate commits formatting the code before introducing `TestScheduler` as I was not sure if these tests should really be converted to run mode.
Also `toPromise` is not an operator, so the tests should not be located with the other operators. I am not sure where the tests should be moved to instead. Maybe it is just fine to leave them where they are since `toPromise` is deprecated and will be removed sometime in the future.
None
=> chore(toPromise): replace deprecated types and use prettier

spec/operators/windowCount-spec.ts
This PR converts `windowCount` tests to run mode.
None
=> chore(windowCount): convert windowCount tests to run mode

spec/operators/windowTime-spec.ts
This PR formates `windowTime` tests with prettier. Also fixes indentation of some of the frame helper comments.
None
=> chore(windowTime): format windowTime test code with prettier

spec/operators/toArray-spec.ts
This PR converts the `toArray` operator tests to run mode.
None
=> chore(toArray): convert toArray tests to run mode

spec/operators/timestamp-spec.ts
This PR converts `timestamp` operator tests to run mode.
None
=> chore(timestamp): convert timestamp tests to run mode

spec/operators/share-spec.ts, src/internal/operators/share.ts
This PR replaces the observer-based subscription that's made within the `share` implementation with a `Subcriber`-based subscription - so that the `connection` variable is assigned _before_ the `subscribe` call is made - to support reentrant calls to `subscribe`.
**Related issue (if exists):** #6144
=> fix(share): handle reentrant subscribes

api_guard/dist/types/index.d.ts, spec-dtslint/observables/partition-spec.ts, src/internal/observable/partition.ts
Add exclusion to partition when using a type guard.
[Previously support for a user defined type guard was added to partition](https://github.com/ReactiveX/rxjs/pull/5756). This meant that Typescript could understand the first item in the resulting tuple to match a certain type. What was missing was Typescript understanding the second item in the tuple to _not_ be of that type. As an example:
```typescript
type AMessage = { a: number };
type BMessage = { b: number };
type Message = AMessage | BMessage;
const aMessage: AMessage = { a: 1 };
const bMessage: BMessage = { b: 2 };
const message$: Observable<Message> = from([aMessage, bMessage]);
function isAMessage(msg: Message): is AMessage { 
return msg.a;
}
const [aMessage$, bMessage$] = partition(message$, isAMessage); …
```
=> fix(partition): add exclusion when using type guard

api_guard/dist/types/index.d.ts, package-lock.json, package.json, spec-dtslint/observables/from-spec.ts, spec/observables/from-spec.ts, src/internal/observable/from.ts, src/internal/scheduled/scheduleReadableStreamLike.ts, src/internal/scheduled/scheduled.ts, src/internal/types.ts, src/internal/util/isReadableStreamLike.ts, src/internal/util/throwUnobservableError.ts
Support ReadableStream and other similar objects by checking for `getReader()` existence. In theory this isn't foolproof, but in practice I can't see this ever actually causing issues in practice. `instanceof` checks don't work with cross-Realm instances and neither ReadableStream nor ReadableStreamDefaultReader implement Symbol.asyncIterator yet (which is why this custom support is needed)
Closes #6006
=> feat(ReadableStreams): Support for ReadableStreams e.g. `from(readableStream)`

spec/operators/mergeScan-spec.ts
Updated `mergeScan` tests to use run mode.
None
=> chore: update mergeScan tests to run mode

spec/operators/timeInterval-spec.ts
This PR converts the `timeInterval` operator tests to run mode.
None
=> chore(timeInterval): convert timeInterval tests to run mode

spec/operators/throwIfEmpty-spec.ts
This PR converts `throwIfEmpty` operator tests to run mode.
None
=> chore(throwIfEmpty): convert throwIfEmpty tests to run mode

spec/operators/takeWhile-spec.ts
This PR converts `takeWhile` operator tests to run mode.
None
=> chore(takeWhile): convert takeWhile tests to run mode

spec/operators/tap-spec.ts
This PR converts `tap` operator tests to run mode. There are also a few small refactorings:
1. Replace deprecated `MochaDone` type with `Mocha.Done`
2. Replace deprecated singnatures of `subscribe` and `throwError`. Note that the deprecated signature usages of `tap` have not been touched.
3. Removed unused parameters in callbacks.
The refactorings have been placed in separate commits to ease reviewing and the possibility to drop some of the refactorings.
None
=> chore(tap): convert tap tests to run mode 

package.json
This PR moves the husky `commitmsg` script to the `husky.hooks` section within the `package.json` file. Husky complains about the use of hooks in the `scripts` section on every commit.
None
=> chore: move husky commit-msg script to husky.hooks

spec/operators/concatMap-spec.ts, spec/operators/exhaustMap-spec.ts, spec/operators/mergeMap-spec.ts, spec/operators/switchMap-spec.ts, src/internal/innerSubscribe.ts
**Note that this PR targets the `6.x` branch.**
AFAICT, `innerSubscribe` is pretty much always called outside of a `try`/`catch` and that means that the error that `subscribeTo` throws if it receives an invalid `ObservableInput` won't be reported via the chained subscribers. Given that `innerSubscribe` is an internal v6 implementation detail and that's its always passed a known-to-be-safe `Subscriber`, it seems that any error effected could be reported directly to said `Subscriber`.
With this change, the bug reported in #5344 - which occurs only in v6 - is fixed.
**Related issue (if exists):** #5344
=> fix: catch within innerSubscribe

src/internal/symbol/observable.ts, src/internal/types.ts
**Note that this PR targets the `6.x` branch.**
This PR moves the declaration merging associated with `Symbol.observable` from `internal/symbol/observable.ts` to `internal/types.ts` - which is where it's located in the v7 codebase. This fixes the problem raised in #6175.
**Related issue (if exists):** #6175
=> fix(types): move Symbol.observable into types.ts

api_guard/dist/types/ajax/index.d.ts, integration/side-effects/snapshots/esm/ajax.js, spec/observables/dom/ajax-spec.ts, src/internal/ajax/ajax.ts, src/internal/ajax/types.ts
Adds a feature that will accept a wide variety of possible inputs for `params` to set the query string parameters for ajax.
Note that this feature will require a polyfill for `URLSearchParams` in IE, but this is not a breaking change for IE, as if they do not use this feature `URLSearchParams` is never accessed. Adds documentation and relatively thorough tests.
Related to #5384
=> feat(ajax): add `params` query string parameter configuration

src/internal/operators/mergeScan.ts
While working on converting `mergeScan` tests to run mode, I struggled with finding out how `acc` parameter of the `accumulator` function is being set, so I had to read the code to figure it out. Now, I'm adding some documentation about `mergeScan` parameters and `mergeScan` internals.
None
=> docs(mergeScan): add parameter docs

.github/workflows/ci_main.yml, package.json, spec/module-test-spec.mjs
In order for module resolution to work with .mjs or package: module code
we need to utilize the conditional export feature of node.
> The current specifier resolution does not support all default behavior of the CommonJS loader. One of the behavior differences is automatic resolution of file extensions and the ability to import directories that have an index file.
https://nodejs.org/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm
https://nodejs.org/api/packages.html#packages_conditional_exports
This directly enables rxjs to work with mjs code and commonjs code since
mjs does not support loading bare folder paths.
This is a fix to:
https://github.com/sveltejs/kit/issues/612
and is directly related to the conversation in this issue within node
core …
=> Add exports within package.json to enable scoped package loading.

package.json
Fixes default export path
I was rebasing 33a9f06f2c59c8aef3bb583bdb7d61d08ab597a0 and this was uncovered with the import integration tests I added in #6043 I'll see if I can update CI with those.
cc @samccone
=> fix(esm): duplicate directory in export path

spec/operators/takeUntil-spec.ts
This PR converts `takeUntil` tests to run mode.
None
=> chore(takeUntil): convert takeUntil tests to run mode

spec/operators/take-spec.ts
This PR formats `take` tests with prettier.
None
=> chore(take): format take tests with prettier

spec/operators/switchMapTo-spec.ts
This PR converts `switchMapTo` tests to run mode.
None
=> chore(switchMapTo): convert switchMapTo tests to run mode

spec/operators/switchScan-spec.ts
This PR converts `switchScan` tests to run mode.
None
=> chore(switchScan): convert switchScan tests to run mode

spec/operators/switchMap-spec.ts
This PR converts `switchMap` tests to run mode.
None
=> chore(switchMap): convert switchMap tests to run mode

spec/operators/switchAll-spec.ts
This PR converts `switchAll` tests to run mode. It also replaces deprecated `subscribe` and `of` signatures within the tests. The deprecation removal has been done in its own commit to ease the review process.
None
=> chore(switchAll): convert switchAll tests to run mode

spec/operators/subscribeOn-spec.ts
This PR converts `subscribeOn` tests to run mode.
None
=> chore(observeOn): convert observeOn tests to run mode

api_guard/dist/types/ajax/index.d.ts, spec/observables/dom/ajax-spec.ts, src/internal/ajax/ajax.ts, src/internal/ajax/types.ts
As @jayphelps  suggested in [this comment](https://github.com/ReactiveX/rxjs/pull/6174#issuecomment-811036029) `queryParams` is a better name.
=> chore(ajax): rename `params` query string to `queryParams`

api_guard/dist/types/index.d.ts, spec-dtslint/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
This PR fixes some problems with `fromEvent`:
- The interfaces used to match targets need to use methods instead of props. Otherwise, [`extends` behaves in an unintended manner](https://www.typescriptlang.org/play?ts=4.2.0-beta#code/JYOwLgpgTgZghgYwgAgPIgIIGcAKUD2ADsgN4BQyy+IAXMgBQhwC2EdWYUoA5sgD7IsAT2YAjfABsAlMgC8APmQA3fMAAmAbjIBfMmVCRYiFOmwBZCGAAW+NaQpUQjFm0Gce-QSPHS6K9Vq6+uDQ8EjIePhIWFj2lNTOrHQARBAAHsBgyVJ+qpo6emBChCgAommQIGq4BMSyEQTRsemV1WiYNUTIAPzIyQCaEITJyCkAckQQyVpFJcjlrVgW1rZyDVEQMcgtEFWxpkuWNna9A0Mj45PTQA) and the types won't match.
- There is a signature that takes only the target and the event name, so the optional qualifiers on the other signatures are redundant.
- If the `resultSelector` returns `T`, the target's type should not be `FromEventTarget<T>`.
The …
=> fix(fromEvent): match targets properly; fix result selector type

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, src/internal/observable/combineLatest.ts, src/internal/observable/merge.ts, src/internal/observable/of.ts, src/internal/operators/endWith.ts
This PR changes the parameter names of some tuple-based signatures to use descriptive names - e.g. `sourcesAndScheduler` instead of `args`.
=> chore: use descriptive parameter names

spec/observables/bindCallback-spec.ts, spec/observables/bindNodeCallback-spec.ts, spec/observables/forkJoin-spec.ts, src/internal/observable/bindCallback.ts, src/internal/observable/bindCallbackInternals.ts, src/internal/observable/bindNodeCallback.ts, src/internal/observable/combineLatest.ts, src/internal/observable/forkJoin.ts, src/internal/observable/fromEvent.ts, src/internal/observable/fromEventPattern.ts, src/internal/observable/zip.ts
As outlined in #5824, this PR undeprecates the result selectors for:
- bindCallback
- bindNodeCallback
- combineLatest
- forkJoin
- fromEvent
- fromEventPattern
- zip
In addition to the reasons given in that issue for the undeprecation, there is another [in this comment](https://github.com/ReactiveX/rxjs/issues/4736#issuecomment-811065078) that applies to `bindCallback`, `bindNodeCallback`, `fromEvent` and `fromEventPattern`.
AFAICT, the docs that related to these deprecations have already been removed/updated to reflect said undeprecation. Anyway, the docs, etc. is what I'm looking at right now.
**Related issue (if exists):** #5824
=> chore: undeprecate some result selectors

spec/operators/startWith-spec.ts
This PR converts `startWith` tests to run mode.
None
=> chore(startWith): convert startWith tests to run mode

src/internal/operators/tap.ts
there are several errors in the origin documentation, and i fixed them, already tested.
=> docs: fix instruction demos in tap operator

spec/operators/skipWhile-spec.ts
This PR converts `skipWhile` tests to run mode. It also refactors a deprecated `tap` signature.
None
=> chore(skipWhile): convert skipWhile tests to run mode

api_guard/dist/types/index.d.ts, spec-dtslint/util/pipe-spec.ts, src/internal/util/pipe.ts
=> fix(pipe): Ensure that `unknown` is infered for 9+ arguments.

api_guard/dist/types/index.d.ts, spec-dtslint/observables/combineLatest-spec.ts, spec-dtslint/observables/forkJoin-spec.ts, spec-dtslint/observables/of-spec.ts, src/internal/AnyCatcher.ts, src/internal/observable/combineLatest.ts, src/internal/observable/forkJoin.ts
=> fix: forkJoin/combineLatest return Observable<unknown> if passed any

api_guard/dist/types/index.d.ts, src/internal/symbol/observable.ts, src/internal/types.ts
- closes #5919
This is manual revert to #5874. 
Core team have discussed around #5919 for a while, and at this moment pretty much agreed
- there is no good suggestion to resolve all of problems we are facing
- current changes (#5784) is too much breaking especially we don't have good workaround to suggest.
At least, providing as-is experience between v6 to v7 is something we'd like to have instead of making huge breaking changes. This doesn't mean we'll stay with this forever, it's just hard enough find right solution (and doesn't break whole world).
I'm making this PR to v7 not slip this accidentally when we publish official release.
=> fix(symbol): revert unique symbol in #5874

api_guard/dist/types/index.d.ts, spec-dtslint/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
This PR removes the `FromEventTarget` union and separates the `fromEvent` signatures so that each target type - DOM, Node, etc. - has its own group of overload signatures. This makes the typing of the result selectors and options (AFAICT, only `addEventListener` targets support an options argument) more accurate.
I left the type-parameters-as-type-assertions for the Node signatures, but deprecated them in favour of signatures that return `Observable<unknown>`. Elsewhere, IIRC, we've just removed/replaced such signatures 'cause this is type parameter misuse, but I think doing that here might be a little too breaking? The result selectors for the Node signatures are more relaxed than they could be - `...args: any[]` instead of `...args: unknown[]`. I suppose we could use …
=> refactor: separate fromEvent signatures by target type

api_guard/dist/types/index.d.ts, spec-dtslint/firstValueFrom-spec.ts, spec-dtslint/lastValueFrom-spec.ts, spec/firstValueFrom-spec.ts, spec/lastValueFrom-spec.ts, src/internal/firstValueFrom.ts, src/internal/lastValueFrom.ts
This PR adds an optional `defaultValue` parameter to `firstValueFrom` and `lastValueFrom`. The parameters are added using an overload to [avoid this issue](https://github.com/ReactiveX/rxjs/issues/4866) (for some usage, at least).
The `first` and `last` operators both support defaults and I see no reason why `firstValueFrom` and `lastValueFrom` should not do the same. Sure, you could apply `defaultIfEmpty` to the source, but you say the same for `first` and `last`. And, IMO, including `defaultValue` in the signatures serves as a reminder that the functions expect a value and that not having an available value is an unexpected/error situation.
Also, supporting default values would make implementing [a user-land equivalent that resolves with an …
=> feat: add (optional) defaultValue parameters to firstValueFrom and lastValueFrom

api_guard/dist/types/ajax/index.d.ts, src/ajax/index.ts, src/internal/ajax/AjaxResponse.ts, src/internal/ajax/ajax.ts, src/internal/ajax/errors.ts, src/internal/ajax/types.ts
This PR improves `ajax` docs, introduces `AjaxDirection` type and fixes multiple typos.
Also, some `npm run docs` failures are fixed with this PR, like:
- `No handler provided for inline tag "{@see {@link AjaxConfig}"` or
- `Error in {@link AjaxProgressEvents} - Invalid link (does not match any doc)`.
None
=> types(ajax): improve Ajax types and docs

package.json
This is an attempt to fix issues with VS Code auto-import, as described here in this issue: https://github.com/microsoft/TypeScript/issues/43034\#issuecomment-820621280
Related #6067
=> chore: Add typesVersions to package.json

docs_app/tools/transforms/templates/api/var.template.html
Fix `const` docs that were showing `any` for any constant. The docs now show/infer the constant type correctly. `dgeni-packages` version is high enough for this to work.
None related to RxJS, a fix taken from angular/angular#23850. Please read that PR for more info and visual description.
=> chore: display types of API const docs correctly

api_guard/dist/types/webSocket/index.d.ts, src/internal/observable/dom/WebSocketSubject.ts
**Description:** update the type result for multiplex method on WebSocketSubjectConfig
=> chore: update type for multiplex operator

src/internal/operators/timeInterval.ts
This PR fixes a broken image source to the `timeInterval` marble diagram in the documentation. 
See documentation of [timeInterval V6](https://rxjs.dev/api/operators/timeInterval) and [timeInterval V7](https://next.rxjs.dev/api/operators/timeInterval)
#5207
=> docs(timeInterval): fix broken link to timeInterval marble diagram

spec/Observable-spec.ts, src/internal/Observable.ts, src/internal/operators/finalize.ts
Adds tests and ensures a few more scenarios that were hit in Google because they use the deprecated synchronous error handling.
fixes #6250
cc @leggechr
=> fix: finalize behaves well with useDeprecatedSynchronousErrorHandling

spec/Observable-spec.ts, spec/operators/finalize-spec.ts
Related to the [comment here](https://github.com/ReactiveX/rxjs/pull/6251#issuecomment-825263480) on #6251. I didn't see anything that matched this scenario. So better safe than sorry.
=> test: Add tests to ensure finalize and teardown on sync init throw

docs_app/content/6-to-7-change-summary.md
Adds a document outlining all discovered differences between version 6 and version 7 as they can be found while diffing the api_guardian snapshots. This document should be an exhaustive list of changes and we should modify it ongoing if we think of anything else that has changed that cannot be found here yet.
@cartant @kwonoj @kolodny please review.
@niklas-wortmann We're going to need some place to link this in the site, ideally to something on the home page.
ALL: I recommend we get this merged and out in the public as soon as possible, and simply iterate on it, adding anything we missed or changing verbiage. I don't want to get stuck reviewing this PR for eternity, I think it's better to get the information out and iterate, as the RC is already live.
=> docs: Document differences between 6.x and 7.x golden files

spec/Observable-spec.ts, src/internal/Observable.ts
Fixes a should-be-obvious issue where we were making sure `dest` was `undefined`, then trying to set a property on it.
fixes #6271
=> fix: resolve run-time errors when using deprecated sync error handling

docs_app/content/6-to-7-change-summary.md
This PR adds the `buffer` breaking change mentioned in #6255 and a `ReplaySubject` breaking change that stems from a v7 bug fix - from an issue opened in this repo (#6260) it's clear that some people are relying upon the buggy behaviour.
=> docs: buffer and ReplaySubject breaking changes

api_guard/dist/types/index.d.ts, spec/observables/connectable-spec.ts, src/internal/observable/connectable.ts, src/internal/operators/connect.ts
This PR changes the API of the new-to-version-7 `connectable` function. The changes introduce a config object (much like the one used in the `connect` and `share` operators) that:
- allows a `connector` subject factory to be passed;
- allows a `resetOnDisconnect` option to be specified.
Without these changes, it wasn't possible to refactor all use cases of `ConnectableObservable` to use `connectable` because `ConnectableObservable` would reset its subject upon disconnection - that is, on calling `unsubscribe` on the `Subscription` returned from the `connect` method.
This PR adds a few tests (there were none) for `connectable`.
=> feat: add config object to connectable

spec-dtslint/observables/throwError-spec.ts, spec/Observable-spec.ts, spec/firstValueFrom-spec.ts, spec/lastValueFrom-spec.ts, spec/observables/throwError-spec.ts, spec/operators/buffer-spec.ts, spec/operators/bufferTime-spec.ts, spec/operators/catchError-spec.ts, spec/operators/concatAll-spec.ts, spec/operators/finalize-spec.ts, spec/operators/mergeAll-spec.ts, spec/operators/mergeScan-spec.ts, spec/operators/onErrorResumeNext-spec.ts, spec/operators/publishReplay-spec.ts, spec/operators/race-legacy-spec.ts, spec/operators/raceWith-spec.ts, spec/operators/retry-spec.ts, spec/operators/retryWhen-spec.ts, spec/operators/throwIfEmpty-spec.ts, spec/operators/toPromise-spec.ts, src/internal/Notification.ts
…
- As per docs, throwError accepts factory functions to emit an error and no longer able to accept an error directly. That's why i went ahead and made changes in all unit tests wherever throwError is getting used to accept factory function.
Noop
=> refactor: refactor throwError operator to use factory function in unit tests and .ts file

src/internal/ajax/errors.ts
Because the constructor signature of `AjaxErrorCtor` and `AjaxTimeoutErrorCtor` are marked as @internal, and #6215 added `stripInternals: true`, the interface of these two constructors was exported as an empty interface.
Typescript would then complain on projects that use `error instanceof AjaxError`, as it doesn't identify AjaxError as callable.
**Related issue (if exists):** #6269 
I've found this solution, which I _think_ works nicely: The type is still exported, the constructor signature is still stripped (because it's internal) and typescript now allows to check instanceof AjaxError, while preventing the consumer from trying to call the constructor:
=> fix: unable to evaluate `instanceof AjaxError`

docs_app/content/blackLivesMatter.md, docs_app/content/marketing/index.html, docs_app/content/navigation.json, docs_app/src/app/app.component.html, docs_app/src/app/layout/footer/footer.component.html, docs_app/src/styles/1-layouts/_footer.scss, docs_app/src/styles/1-layouts/_marketing-layout.scss, docs_app/src/styles/1-layouts/_top-menu.scss
This pr creates a link to the change list in the side nav. It also reinitializes the former homepage and promote v7, while having a BLM banner and a standalone page with the content we used to have on the homepage
=> Preparation v7 Docs

spec-dtslint/errors-spec.ts, spec-dtslint/index.d.ts, src/internal/ajax/errors.ts, src/internal/operators/timeout.ts, src/internal/util/ArgumentOutOfRangeError.ts, src/internal/util/EmptyError.ts, src/internal/util/NotFoundError.ts, src/internal/util/ObjectUnsubscribedError.ts, src/internal/util/SequenceError.ts, src/internal/util/UnsubscriptionError.ts
This PR adds __@deprecated__ tags to the error constructors so that devs attempting to create instances of this package's errors will be told they're being naughty. We can't tag them as __@internal__ because TypeScript gets too upset about it - see linked issue and PR.
This PR also adds some dtslint tests to make sure the deprecations work properly and don't interfere with `instanceof` usage.
**Related issue (if exists):** #6269 and #6275
=> chore: deprecate error ctors

package.json, src/index.ts
- Adds typesVersions, enforcing TypeScript >= 4.2.
- Adds some superfluous imports required for TS and VS Code to find proper import locations for our strange deep import sites.
- Independantly tested by building the package and installing it locally in another project, then testing in VS code.
Fixes #6067
Related https://github.com/microsoft/TypeScript/issues/43034
NOTE: I'm worried about the `check-side-effects` run here, because it can't seem to figure out what to make of it. However, tested against an Angular build locally, this branch didn't have any problems tree-shaking or removing dead code. Given the importance of people getting their imports right, and the DX around this, we might want to disable `check-side-effects` if it causes us issues.
=> fix: VS code will now properly import operators, et al

api_guard/dist/types/ajax/index.d.ts, src/internal/ajax/AjaxResponse.ts, src/internal/ajax/ajax.ts, src/internal/ajax/types.ts
**Description:** currently `AjaxResponse['type']` is typed as `string`, but we can use a stricter type for this since we know which strings will be used. This will help users `switch` over the various types.
=> feat(AjaxResponse): add stricter `type` (`AjaxResponseType`)

api_guard/dist/types/index.d.ts, src/index.ts, src/internal/config.ts, src/internal/types.ts
The reason why I wanted to add an interface for `config` object is so that we can have a proper documentation page for it. Constant documentation pages don't have a list of properties like interface documentation pages do.
Also, by introducing this interface, we will fix an error while building the docs (`npm run docs`) from this line:
https://github.com/ReactiveX/rxjs/blob/23bc7fdc16acd76dd71a4faf57b8b949684c3249/src/internal/Observable.ts#L101
because a link to `onUnhandledError` will now be available.
I was thinking about naming this interface with just as `Config`, but I chose `GlobalConfig` in the end. If needed, I can change to `Config` if it feels more appropriate.
None
=> types(config): add GlobalConfig interface

README.md
A simple change in the readme to remove the (beta) tag since v7 is now official
nope
=> docs: remove beta tag since v7 is now official

docs_app/content/guide/operators.md
=> docs: highlight the delay operator

src/internal/operators/delay.ts
A minor doc change proposed by @BioPhoton in #4921
Created a new PR to remove unnecessary formatting changes
Related issue: #4921
=> docs(delay): add relevant operator links to delay docs

docs_app/content/6-to-7-change-summary.md
This PR adds the breaking changes that relate to notifiers having to emit a value to: `docs_app/content/6-to-7-change-summary.md`
**Related issue (if exists):** #6298
=> docs: add notifier breaking changes

src/internal/operators/endWith.ts
=> Fix typo in endWith summary

spec/operators/shareReplay-spec.ts
This PR converts `shareReplay` tests to run mode and updates a deprecated `subscribe` signature.
None
=> chore(shareReplay): convert shareReplay tests to run mode 

spec/operators/share-spec.ts
This PR updates the remaining part of `share` tests to run mode.
None
=> chore(share): convert share tests to run mode

.github/PULL_REQUEST_TEMPLATE.md
This PR updates the repo's PR template to include the breaking-change notice along with instructions on how it should be used. It has been missed numerous times, so a reminder is warranted, IMO.
=> chore: add breaking change notice to PR template

spec/operators/scan-spec.ts
This PR converts `scan` tests to run mode.
None
=> chore(scan): convert scan tests to run mode

spec/operators/sequenceEqual-spec.ts
This PR converts `sequenceEqual` tests to run mode. There are two more things that i believe where not correct which are also adressed in this PR.
* Two of the tests are using `values` instead of the default string values. They where defined however not used with the correct marble source.
* The same tests where modifying the `booleans` constant by using `_.assign`. This side effect was removed.
I also had to modify the last test in the test file from a subscription within `scheduler.schedule` to subscription marbles. While I believe that this change is semantically equal I am not totally sure if that is the case.
None
=> chore(sequenceEqual): convert sequenceEqual tests to run mode

docs_app/content/6-to-7-change-summary.md
This PR adds more breaking changes that are missing from the v6/v7 changes doc:
- There were breaking changes made to `audit` and, therefore, `auditTime` in https://github.com/ReactiveX/rxjs/pull/5799
That PR description did not include 'BREAKING CHANGE', so, AFAICT, the changes weren't mentioned in the CHANGELOG.
- Prior to separating the `fromEvent` signatures by target type - in https://github.com/ReactiveX/rxjs/pull/6214 - it was possible to pass options to APIs that didn't support them. (The options are ignored in the `fromEvent` implementation for targets that don't support them.) Attempting to do this in v7 will effect a TypeScript compilation error.
- In https://github.com/ReactiveX/rxjs/pull/5433, `finalize` was changed so that it unsubscribes from its source …
=> docs: more breaking changes

spec/operators/throttle-spec.ts
There are a bunch of `throttle` tests that are in a `describe` section that's devoted to testing with `leading: false`. However, some of those tests seem to have been copied from the section devoted to testing with `leading: true`. This PR changes the copied tests so that they do in fact test with the `leading` option set to `false`.
Basically, the tests weren't testing what they were said to be testing and they were testing scenarios that are tested elsewhere in the file.
**Related issue (if exists):** #5360
=> test(throttle): test leading: false

src/index.ts
This PR removes all DOM-related imports from the references that were added to help VS Code choose the correct import locations for its automatic imports feature.
I've confirmed - using https://github.com/OliverJAsh/rxjs-v7-no-dom-lib-test - that this resolves the problem.
**Related issue (if exists):** #6297
=> fix: do not reference DOM-related imports

spec/operators/sampleTime-spec.ts
This PR converts `sampleTime` tests to run mode.
I did encounter an issue with the `never` test. It seems that in run mode there is no maximum frame count, so I had to add an explicit unsubscription to the expectation.
None
=> chore(sampleTime): convert sampleTime tests to run mode

spec/Subscription-spec.ts, src/internal/Subscription.ts
This PR fixed the bug reported in #6351 by nulling `this._parentage` before the array is iterated. This was an oversight. It should have been nulled as is `this._teardowns`, immediately after it is destructured:
https://github.com/ReactiveX/rxjs/blob/7b30546717ab8bb271217064318ef9e0c0c40ecc/src/internal/Subscription.ts#L76-L78
If `this._parentage` is not nulled, it's mutated as it's iterated and parents can be left holding onto child subscriptions that have been closed.
The PR also adds - in a separate commit - an `if` statement around the handling of `_parentage`, so that the implementation is more like what's done with `_teardowns`. If there's some reason for not using the `if` statement, we can just revert that commit.
**Related issue (if exists):** #6351
=> fix(Subscription): null _parentage on unsubscribe

src/internal/observable/dom/WebSocketSubject.ts
Fix several grammatical errors in `WebSocketSubject` documentation.
=> docs(WebSocketSubject): fix grammar

spec/operators/retry-spec.ts, src/internal/operators/retry.ts
=> fix(retry): when # of retries is smaller than one

spec/Observable-spec.ts, src/internal/Observable.ts
Resolves an issue where teardowns returned by the Observable initializer were not being registered with the subscriber.
Fixes #6364
cc @leggechr
=> fix: Observable teardowns now properly called if `useDeprecatedSynchronousErrorHandling` is `true`.

spec/operators/sample-spec.ts
This PR converts `sample` tests to run mode.
None
=> chore(sample): convert sample tests to run mode

spec/observables/bindCallback-spec.ts, spec/observables/bindNodeCallback-spec.ts, src/internal/observable/bindCallbackInternals.ts
This PR fixes `bindCallback` and `bindNodeCallback`. In v6 the internal subject was created in the factory that returns the bound observable:
https://github.com/ReactiveX/rxjs/blob/881cacdc99a7ebae219b595004c632f7358f730d/src/internal/observable/bindCallback.ts#L196-L198
However, in v7, the subject creation was inadvertently moved outside of the factory:
https://github.com/ReactiveX/rxjs/blob/f9d29f7e75ff9394e3f4f79cfd4688593eb757c9/src/internal/observable/bindCallbackInternals.ts#L38-L42
With it outside of the factory, calls subsequent to the first were ineffectual: the arguments passed were ignored and the previous result was returned.
This PR add some failing tests and moves the subject creation back into the factory.
=> fix(bindCallback): create subject within factory

spec/operators/multicast-spec.ts, spec/operators/refCount-spec.ts, spec/operators/share-spec.ts, spec/operators/shareReplay-spec.ts, src/internal/operators/share.ts
This PR fixes `share` so that it wires up the teardown _before_ subscribing to the source - ensuring the assignment to the subscriber's `closed` property is propagated to the firehose source.
The skipped firehose test has been enabled and the firehose tests that related to now-deprecated operators have been removed.
**Related issue (if exists):** #5834 (I've closed this because it related to the now-deprecated APIs)
=> fix(share): propagate closed to firehose sources

.eslintrc, .gitignore, integration/import/fixtures/commonjs/index.js, package.json
This PR re-enables subpath import under `internal` in v7. 
Previously subpath import was not restricted in v6. With change of import maps node.js only allows explicitly exposed subpath import, ends up any subpath import to `internal` is prohibited. This is not a breaking change techinically - we never officially supported internal subpath and never will. But for some cases, user have usecases with `at your own risk` and this PR will allow it again.
=> build(package): support internal subpath import

docs_app/src/styles/2-modules/_api-pages.scss, docs_app/tools/transforms/templates/api/lib/memberHelpers.html
This PR adds deprecation notes to the documentation for single method and function overrides. Additionally a strikethrough is also added to the method signature. The source of the changes was the angular.io project, although only the pieces necessary for the deprecations where included.
There are still some places that are a little odd:
* if all function overloads are deprecated, the deprecation note is shown for the function and all of its overloads
* if all function overloads are marked as deprecated the function is *not* marked with a deprecated badge
* the deprecation notes contain literal links to http://rxjs.dev/... Their purpose is probalby to accomodate IDEs to show the correct link
I am planing on working on some of the issues above in follow up PRs to keep this …
=> docs: add deprecation notes to documentation pages

.github/workflows/ci_main.yml
This PR removes Node v11 from the CI configuration. Node v12 is no longer active LTS - it's now maintenance - so IMO a version that's older than that and wasn't an LTS version isn't something we need to continue to support. And it doesn't support `globalThis`, so it's annoying.
=> chore: remove Node v11 from CI

docs_app/content/6-to-7-change-summary.md
This PR adds mention of `jasmine.clock().mockDate()` to the v6/v7 changes doc. Mostly 'cause Jasmine is so widely used in the Angular community, 'cause it does not mock `Date.now()` by default and 'cause `debounceTime` is a frequently-used operator.
It's not really a breaking change, but if people's tests suddenly fail - 'cause Jasmine is ... Jasmine - it might as well be.
🤬
**Related issue (if exists):** #6382
=> docs: mention jasmine.clock().mockDate() re: debounceTime

spec/operators/shareReplay-spec.ts
Restores and unskips the `shareReplay` firehose-source test.
**Related issue (if exists):** #6370
=> test: add shareReplay firehose-source test

spec-dtslint/observables/partition-spec.ts, spec-dtslint/operators/every-spec.ts, spec-dtslint/operators/filter-spec.ts, spec-dtslint/operators/find-spec.ts, spec-dtslint/operators/findIndex-spec.ts, spec-dtslint/operators/map-spec.ts
This PR adds dtslint tests for the `thisArg` deprecations that were added in #6361.
**Related issue (if exists):** #6361
=> test: add thisArg deprecation tests

spec/schedulers/animationFrameProvider-spec.ts, spec/schedulers/dateTimestampProvider-spec.ts, spec/schedulers/intervalProvider-spec.ts, spec/schedulers/timeoutProvider-spec.ts
This PR adds tests to ensure that `animationFrameProvider` and it's friends are affected by any monkey patches that might be made in user-land tests, etc.
**Related issue (if exists):** Somewhat related to #6382
=> test: add tests for animationFrameProvider, et al.

spec/operators/take-spec.ts
provides a failing test case for an edge case of take and dependent operators as presented in https://github.com/ReactiveX/rxjs/issues/5487
Will add a fix, if a change in behavior is agreed upon.
**Related issue (if exists):** fixes https://github.com/ReactiveX/rxjs/issues/5487
=> fix(take): notifies errors after limit is reached

src/internal/operators/mapTo.ts
Smaller `mapTo` implementation.
None
=> refactor(mapTo): smaller implementation

src/internal/operators/multicast.ts, src/internal/operators/publish.ts, src/internal/operators/publishReplay.ts
This adds deprecated tags to the primary signatures of deprecated multicast, publish & publishReplay, so they are properly marked as such in the [API reference](https://rxjs.dev/api).
=> Docs: multicast deprecation

docs_app/src/index.html
The docs site has a meta tag that stops `googlebot` from indexing the site and this causes the site not to show up in google search results. I think was a bug as the `index.html` layout adds a `noindex` tag for both `googlebot` and `robots`, but the code that removes the `noindex` when the page is determined to be good only removes the `robots` tag but not the `googlebot` one: https://github.com/ReactiveX/rxjs/blob/6fa819beb91ba99dadd6262d6c13f7ddfd9470c5/docs_app/src/app/layout/doc-viewer/doc-viewer.component.ts#L163
/cc: @niklas-wortmann @benlesh
=> docs: remove googlebot noindex from index.html

api_guard/dist/types/operators/index.d.ts, spec/operators/groupBy-spec.ts, src/internal/operators/groupBy.ts
- Adds support for named arguments.
- Adds support for returning promises, et al, from the duration selector.
NOTES:
* There's a problem with type inferrence from the options `duration` selector that is noted in a `TODO` in the code here.
* The tests for `groupBy` appear to be EXTREMELY old and outdated, and I was unable to updated them easily to use run mode. We may have to rewrite them all at some point to use better techniques. The issue seems to be a rudementary means of testing the inner observables that is incompatible with run mode.
* Docs still need updated
* Older paths still need to be deprecated
* dtslint tests need to be added
=> feat(groupBy): Support named arguments, support ObservableInputs for duration selector

spec/operators/share-spec.ts, src/internal/operators/share.ts
This is a PoC. I will add tests, if the approach is agreed up on.
Extends the share operator to allow passing an observable factory to control the reset behavior and enable reset delays.
```ts
declare function createObservableWithExpensiveInitialization(): Observable<number>;
const number$ = createObservableWithExpensiveInitialization().pipe(share({ resetOnRefCountZero: () => timer(5000) }));
concat(number$.take(1), number$.take(1)).subscribe(); // this wont unsubscribe (unless your process is REALLY busy, one could say "stuck")
```
closes https://github.com/ReactiveX/rxjs/issues/4033
=> feat(share): use another observable to control resets

spec/operators/single-spec.ts
This PR corrects a misleading test description. `undefined` is not returned/emitted; an error is emitted.
=> test(single): correct misleading test description

spec/operators/publish-spec.ts, spec/operators/publishBehavior-spec.ts, spec/operators/publishLast-spec.ts, spec/operators/publishReplay-spec.ts, spec/operators/share-spec.ts, spec/operators/shareReplay-spec.ts, src/internal/operators/publish.ts, src/internal/operators/publishBehavior.ts, src/internal/operators/publishLast.ts, src/internal/operators/publishReplay.ts, src/internal/operators/share.ts
This PR incorporates the fixes and tests in #5585 and also fixes and tests the `share`, `shareReplay`, `publishBehavior` and `publishLast` operators.
The problem that is fixed can be described as follows:
- Calls to **operators** - like `share` - _must be referentially transparent_. Otherwise, those operators cannot be used in calls to the static `pipe` function (to create partial pipelines).
- It's the calls to the **operator functions** - the functions that are returned from **operator** calls - that _do not have to be referentially transparent_ (and can therefore implement the publishing and sharing). Those calls are made when the complete pipeline is composed via a call to a source observable's `pipe` method.
IMO, the changes are a bug fix, rather than a breaking …
=> fix: make share, publish, et al. operator calls referentially transparent

src/internal/Notification.ts, src/internal/config.ts, src/internal/observable/ConnectableObservable.ts
This PR fixes broken links within the documentation that are reported by the build of the documentation.
Two examples of the broken links can be found on the [Global Config](https://rxjs.dev/api/index/interface/GlobalConfig) documentation page.
None
=> docs: fix broken links in documentation

api_guard/dist/types/index.d.ts, spec/Subject-spec.ts, src/internal/Subject.ts
This PR adds an api `subject.isObserved()` to handle the common use case of the deprecated `subject.observers` member 
* https://stackoverflow.com/questions/44555615/rxjs-detect-when-observable-has-been-subscribed-to
* https://stackoverflow.com/questions/33441393/is-there-a-way-to-check-for-output-wire-up-from-within-a-component-in-angular-2
Relates to: #5967
=> feat(Subject): add isObserved() api

src/internal/operators/sequenceEqual.ts
probably a mistake, because not 'rxjs' nor 'rxjs/operators' has `innerFrom` exported
=> docs(operators): sequenceEqual

src/internal/observable/timer.ts
**Description:** A minor mistake in the JSDoc description of the parameter threw me off when I was using a quick lookup of the parameter meaning in my IDE. The example and earlier explanation correctly stated milliseconds, but the parameter description was wrong.
**Related issue (if exists):** Didn't really look, just created a quick edit from the GitHub editor.
=> docs: "timer" accepts milliseconds, not seconds

spec-dtslint/errors-spec.ts, spec-dtslint/observables/bindCallback-spec.ts, spec-dtslint/observables/empty-spec.ts, spec-dtslint/observables/race-spec.ts, spec-dtslint/observables/zip-spec.ts, spec-dtslint/operators/count-spec.ts, spec-dtslint/operators/dematerialize-spec.ts, spec-dtslint/operators/reduce-spec.ts, spec-dtslint/operators/scan-spec.ts, spec-dtslint/operators/zip-spec.ts, spec/helpers/test-helper.ts
Raising this PR to clean files by removing unused imports from several files.
Noop
=> refactor: clean unuse imports in several files

docs_app/content/deprecations/multicasting.md
The `share` operator should be imported from 'rxjs/operators'
none
=> chore(docs): update multicasting in deprecations

src/internal/operators/switchMap.ts
**Description:** -
**Related issue (if exists):** -
=> docs(operators): Rerun is changed to Return

src/internal/operators/OperatorSubscriber.ts
No breaking change, no nothing, just getting rid of a small typo ;)
=> docs: remove typo in OperatorSubscriber.ts

spec/Subject-spec.ts, src/internal/Observable.ts, src/internal/Subject.ts, src/internal/Subscriber.ts, src/internal/util/errorContext.ts
As an alternative to #6472 ... which is SHENANIGANS
this adds a cleaner solution for handling super-gross mode. It shouldn't have much impact on regular use.
=> refactor: More elegantly handle super gross mode

.github/workflows/ci_ts_latest.yml, package-lock.json, package.json
Bumps the `tslint-etc` version to the latest, updating its dependencies and, hopefully, fixing the issue that relates to the TypeScript peer range in `@phenomnomnominal/tsquery`.
Bumping solved the problem for `@phenomnomnominal/tsquery`, but just kicked the can further down the road, as there's a similar peer-dependency issue for `api-guardian`. Rather than chase all of these down, I've added the `--legacy-peer-deps` flag to the `install` command.
**Related issue (if exists):** #6485
=> chore: use latest version of tslint-etc and legacy-peer-deps

api_guard/dist/types/index.d.ts, spec-dtslint/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
This PR simply fixes the return type of one overloaded form of `fromEvent()` that accepts a `resultSelector`.
With a `resultSelector: (event: T) => R`, `fromEvent<T, R>` should return a `Observable<R>`, instead of `Observable<T>`.
**Related issue (if exists):** N/A
=> fix: fromEvent() type with resultSelector

docs_app/content/guide/operators.md
Please check https://rxjs.dev/guide/operators#marble-diagrams.
https://github.com/ReactiveX/rxjs/pull/5924 has repaired this image link, but it only works when we read markdown directly, doesn't work on our website.
https://github.com/ReactiveX/rxjs/issues/5923
=> fix(doc): correct broken image link

spec/observables/from-spec.ts
Just realized we didn't really have a test for this, and I wanted to make sure it was working properly.
=> test: add test for from(asynciterable) unsubscribe

CONTRIBUTING.md, docs_app/content/guide/core-semantics.md
This is a starting place to put together a document that outlines the semantics of functionality provided by the core library. This will be used as a reference for the "correct" behaviors of the library starting in version 8. We probably can't do that in version 7 without breaking _someone_, but it's definitely something we want to get defined, as it keeps coming.
=> Core semantics

spec/operators/debounceTime-spec.ts, src/internal/operators/debounceTime.ts
Since `debounceTime` is not based on `debounce` anymore (https://github.com/ReactiveX/rxjs/pull/6049), the "notifier subscription" is not managed within the parent subscription anymore, but scheduled "raw". We need to make sure we dont leave dangling tasks behind.
I am not sure how to test this.
edit: this also prevents stopped notifications, if the source errors, because that could also leave dangling tasks behind
=> fix(debounceTime): unschedule dangling task on unsubscribe before complete

spec/Subscriber-spec.ts, spec/operators/shareReplay-spec.ts, spec/schedulers/intervalProvider-spec.ts
CI seems to be failing with the latest TypeScript and Node types. This PR should fix the failures.
=> chore: fix TypeScript latest breakage in CI

spec/operators/retryWhen-spec.ts
This PR converts `retryWhen` tests to run mode. It also updates the deprecated subscribe signatures within the spec file.
=> chore(retryWhen): convert retryWhen tests to run mode 

spec/operators/retry-spec.ts
This PR converts `retry` tests to run mode. It also replaces deprecated `subscribe` and `Observable.create` signatures in the test file and removes some unused parameters.
None
=> chore(retry): convert retry tests to run mode

spec/operators/pairwise-spec.ts
Updated `pairwise` tests to use run mode.
None
=> chore: update pairwise tests to run mode

src/internal/operators/share.ts
A bit hard to see the that there are two subscriptions if they have the same name.
=> fix(share): Minor fix of subscription name in example

spec/subjects/AsyncSubject-spec.ts, src/internal/AsyncSubject.ts
=> fix(AsyncSubject): properly emits values during reentrant subscriptions

spec/operators/pluck-spec.ts
Updated `pluck` tests to use run mode.
There are two commits that I can exclude if needed (and possibly move to another PR), please let me know if I should.
The first one removes unused constant (its never been altered anywhere, it can be safely removed).
The second one adds firehose test for `pluck`, can this go with this PR or should I move it to another one?
None
=> chore: update pluck tests to run mode

spec/Observable-spec.ts, spec/Subject-spec.ts, spec/operators/repeatWhen-spec.ts, spec/operators/take-spec.ts, spec/subjects/BehaviorSubject-spec.ts, spec/support/.mocharc.js
- Adds a commented out bit to the .mocharc so it's a little easier to figure out how to find skipped tests when we need to.
- Stops skipping tests that no longer need to be skipped
- Adds an additional test to simplify the assertion of one of the skipped tests
- Adds a comment above a skipped section of tests explaining that we can probably remove them in v8 after we've moved completely to newer multicasting paradigms and removed deprecated operators.
- Some of the skipped tests in `repeatWhen-spec` were clearly copied from `retryWhen-spec` but never updated appropriately.
- One of the skipped tests showed a buggy behavior that is now reported in an issue and a comment with a link to that issue is now above it.
- Adds comments about why some tests are skipped.
Resolves #5370
Resolves …
=> Fix as many skipped tests as possible.

api_guard/dist/types/index.d.ts, src/internal/observable/connectable.ts, src/internal/types.ts
Renames previously unexposed return type of `connectable` from `ConnectableObservableLike` to `Connectable`. Moves it to `types.ts`, from which we export everything.
Resolves #6529
=> fix: Expose `Connectable`, return type of `connectable`

spec/operators/retry-spec.ts, src/internal/operators/retry.ts
- Adds a `delay` configuration that allows the user to create simpler exponential backoff, simple retry delays, and/or other functionality.
Basically, this will allow a user to write an exponential backoff or simple delay more easily and intuitively than `retryWhen` could. In fact, we might want to deprecate `retryWhen` in favor of this, and also add this pattern to `repeat` (if we decide it's a good idea).
**Retry every 5 seconds, a maximum of 100 times:**
```ts
source.pipe(
retry({
// max retries (count is an unfortunate existing name)
count: 100, 
// retry 5 seconds after any error
delay: 5000, // retry after 5 seconds
})
)
```
**Exponential backoff example**:
```ts
source.pipe(
retry({
// max 100 retries
count: 100,
// backoff starting at 2 seconds, exponentially up to 1 minute.
// …
```
=> feat(retry): Add configurable delay

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec/operators/tap-spec.ts, src/internal/operators/tap.ts
This adds a common request/task for RxJS users, which are three new handlers:
- `subscribe`: fires on subscription to the source
- `unsubscribe`: fires when the subscription to the result is unsubscribed from, but NOT if the source completes or errors
- `finalize`: always fires on finalization, (basically equivalent to `finalize`)
This is useful for situations where you'd like to know that your consumer has decided to unsubscribe (and you're not terminating because of a complete or an error).
```ts
let subject = new Subject();
const sub1 = subject.pipe(
tap({ 
subscribe: () => console.log('subscribed'),
complete: () => console.log('complete'),
unsubscribe: () => console.log('unsubbed'),
finalize: () => console.log('finalize')
})
).subscribe();
// logs "subscribed"
sub1.unsubscribe();
// …
```
=> feat(tap): Adds subscribe, unsubscribe, finalize handlers

src/internal/operators/find.ts
**Description:** Was bitten by this; I expected no emission to happen if nothing is found. Thought it would be good to explicitly state the edge case in the docs, since just “it won't throw” don't really say anything about what _will_ happen instead (nothing vs emits undefined).
=> docs(operators): clarify that `find` can emit `undefined`

src/internal/operators/concatWith.ts
Add used operators to the `import` statement.
=> docs(operators): fix code example of concatWith

docs_app/content/guide/operators.md
Change exhaust to exhaustAll as first one is deprecated.
[https://rxjs.dev/guide/operators](url)
=> Change exhaust to exhaustAll

spec/schedulers/QueueScheduler-spec.ts, spec/util/UnsubscriptionError-spec.ts, src/internal/scheduler/AsyncAction.ts
Because TS 4.4 now infers `unknown` for `catch` blocks, we had to make some adjustments.
This also helped us catch a type problem where we were maybe creating `new Error(false)` or `new Error('')`, etc, in some cases.
=> fix(Schedulers): Throwing a falsy error in a scheduled function no longer results in strange error objects.

src/internal/operators/combineLatestWith.ts, src/internal/operators/connect.ts, src/internal/operators/endWith.ts, src/internal/operators/filter.ts, src/internal/operators/finalize.ts, src/internal/operators/find.ts, src/internal/operators/findIndex.ts, src/internal/operators/first.ts, src/internal/operators/groupBy.ts, src/internal/operators/ignoreElements.ts, src/internal/operators/observeOn.ts, src/internal/operators/repeat.ts, src/internal/operators/switchAll.ts, src/internal/operators/timeInterval.ts
Going to fix code examples so that can run in stackblitz.
=> docs(operators): fix code example

api_guard/dist/types/index.d.ts, spec/Observable-spec.ts, spec/config-spec.ts, spec/operators/toPromise-spec.ts, src/internal/Observable.ts, src/internal/config.ts
BREAKING CHANGE: `config.Promise` no longer exists. As a workaround, you will need to set a global Promise if one does not already exist in your environment.
=> feat: removed `config.Promise` injection point.

api_guard/dist/types/index.d.ts, spec/Subscriber-spec.ts, src/internal/Subscriber.ts, src/internal/config.ts
BREAKING CHANGE: `useDeprecatedNextContext` is no longer available. No workaround.
=> feat: `useDeprecatedNextContext` no longer available

spec/operators/delay-spec.ts, spec/operators/switchAll-spec.ts, src/internal/Subscription.ts
- Adding the same instance of a teardown more than once is the same as adding it once
- Removing a teardown with `Subscription.prototype.remove` will remove it much faster
BREAKING CHANGE: Adding the same function instance to a subscription as a teardown multiple times will now result in that function being executed only once on teardown. This brings us inline with the behavior of EventTarget, and also makes removing teardowns faster. The workaround is to make sure you are adding a new function instance to the Subscription each time if you need the same effect.
Resolves #6400
=> feat(Subscription): idempotent add and remove of teardowns

docs_app/content/guide/glossary-and-semantics.md
As I was reading the docs, I found out that the anchor links in the [Glossary and Semantics page](https://rxjs.dev/guide/glossary-and-semantics) were not working.
After a bit of research, I realized that the anchor links were not in the correct way. So I have opened this PR to fix this problem 😁
=> docs: fix glossary anchor links

spec/Observable-spec.ts
This test works sometimes and not other times. I stopped skipping it a while back and it seemed to be fixed. I think what's really happening is that it's _not_ fixed, rather the test scheduler is saving us sometimes by bailing out at a max time limit just before the call stack is exceeded... but that's a wild guess. Basically it's a bad test and we need to make a better test, then fix the issue seperately.
=> chore: Skip test that sporadically fails

docs_app/src/styles/2-modules/_label.scss, docs_app/tools/transforms/angular-base-package/index.js, docs_app/tools/transforms/angular-base-package/processors/checkOperator.js, docs_app/tools/transforms/templates/api/base.template.html
This PR adds a label to all functions that are considered as operator functions. That is, any function that is exported from `src/internal/operators` will have this label.
The processor that was created to determine if a document `isOperator` determines this by checking if a document has `originalModule` and if `originalModule` starts with `'internal/operators'`. This means that any exported function that is not operator that may in future come from `'internal/operators'` will be marked as an operator - for now, there are no such functions. But if some util (non-operator) function gets exported in future from `'internal/operators'`, it should be moved to another place so that it doesn't get marked as operator.
This is a handy addition, especially after RxJS v7.2.0 since …
=> docs: add operator flag to operator functions

docs_app/content/guide/observable.md
Just fix promise link in the related doc.
=> fix promise link

docs_app/content/guide/installation.md
Documentation to describe how to leverage the ES2015 export condition feature in 7.4.0 and introduced via https://github.com/ReactiveX/rxjs/commit/268777bc3a4fd0cf76882683b51809771741ddc3 has been added to the installation guide.
Related PR: https://github.com/ReactiveX/rxjs/pull/6614
=> docs: add es2015 code usage notes in installation guide

spec/schedulers/AnimationFrameScheduler-spec.ts, spec/schedulers/AsapScheduler-spec.ts, src/internal/scheduler/AnimationFrameAction.ts, src/internal/scheduler/AnimationFrameScheduler.ts, src/internal/scheduler/AsapAction.ts, src/internal/scheduler/AsapScheduler.ts
This PR adds failing tests and fixes for the following scenarios:
- In the `AnimationFrameScheduler` and the `AsapScheduler`, it was possible for actions scheduled within a `flush` call - i.e. scheduled by actions executed with said `flush` call - to be themselves executed within the _same_ `flush` call. This would only occur if actions were unsubscribed, as that would 'move' the newly-scheduled actions to a lower index in the `actions` queue - rendering the `count`-based mechanism unreliable for determining which actions should be executed.
- In the `AnimationFrameAction` and the `AsapAction`, the cancellation of the animation frame and the clearing of the microtask depended upon whether or not the `actions` queue was empty. However, that's insufficient, as the `actions` …
=> fix: scheduler unsubscription scenarios

spec/operators/refCount-spec.ts
Updated `refCount` tests to use run mode.
None
=> chore: update refCount tests to run mode

spec/observables/dom/webSocket-spec.ts, src/internal/observable/dom/WebSocketSubject.ts
The close event on WebSocket does not always occur immediately after running the close function. If the close event is occurs after a new WebSocket is opened, then the reset needs to be skipped. This checks to make sure the socket being reset is the one that matches the event.
The MockWebSocket class skipped the state between CLOSING and CLOSED. I removed the automatic closing so that the CLOSED state must be trigger manually. This caused many of the existing tests to expect CLOSING instead - I changed the codes instead of triggering close because it did not affect the tests.
I also changed the readyState codes to use an enum for clarity. If that is an unwanted change I can revert back to comments.
**Related issues:**
Closes #4650, #3935
=> fix(WebSocketSubject): handle slow WebSocket close

spec/Observable-spec.ts, src/internal/Observable.ts
=> fix(forEach): properly unsubs after error in next handler

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/takeWhile-spec.ts, src/internal/operators/takeWhile.ts
I think that the typings for the Boolean constructor of `takeWhile` are off... For instance, I think that the following dtslint test:
```ts
const c = of(
false as const,
0 as const,
"hi" as const,
-0 as const,
0n as const,
"" as const,
null,
undefined
).pipe(takeWhile(Boolean)); // $ExpectType Observable<false | "" | 0 | 0n | "hi" | null | undefined>
```
should expect this, instead:
```ts
const c = of(
false as const,
0 as const,
"hi" as const,
-0 as const,
0n as const,
"" as const,
null,
undefined
).pipe(takeWhile(Boolean)); // $ExpectType Observable<"hi">
```
The goal of this PR is to make the Boolean constructor typings of `takeWhile` (when the `inclusive` flag is set to `false`) consistent with the typings of `filter`.
=> fix: takeWhile Boolean constructor types

docs_app/content/guide/importing.md, docs_app/content/guide/installation.md, docs_app/content/navigation.json, docs_app/src/app/custom-elements/api/api-list.component.html
As of RxJS version 7.2.0, a new way of importing operators is introduced. This PR adds a document that covers this addition.
None
=> docs: introduce importing document

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec/operators/repeat-spec.ts, src/internal/operators/repeat.ts
Adds a feature to `repeat` to match the configurable API of `retry`.
`repeat` can now be used in a similar manner to `repeatWhen`, only
perhaps in a more developer-friendly way.
- Also updates `repeat` tests to use run mode.
=> feat(repeat): now has configurable delay

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec/Observable-spec.ts, src/internal/Observable.ts
BREAKING CHANGE: `Observable.create` has been removed. Use `new Observable` instead.
=> feat(Observable.create): removed

docs_app/content/deprecations/multicasting.md, docs_app/content/deprecations/resultSelector.md, docs_app/content/deprecations/scheduler-argument.md, docs_app/content/deprecations/to-promise.md, docs_app/content/guide/operators.md, docs_app/content/guide/overview.md, docs_app/content/guide/scheduler.md, docs_app/content/guide/subject.md, docs_app/content/guide/testing/marble-testing.md
Fix remaining examples from `.md` files from `docs_app/content/` folder.
#6650 and #6678
=> docs: update operator imports in remaining examples

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, src/internal/operators/concatMapTo.ts, src/internal/operators/ignoreElements.ts, src/internal/operators/mapTo.ts, src/internal/operators/mergeMapTo.ts, src/internal/operators/switchMapTo.ts
After upgrading an application's typescript-eslint dependency from 4.30 to 5.9, I found that the "@typescript-eslint/no-unsafe-argument" rule was flagging my use of the RxJS `mapTo` and `ignoreElements` operators, because they return functions that operate on observables of `any`.  Since the operator functions ignore the values from the source observable, they don't need the dynamic typing that `any` provides for *accessing* the values.  Using `unknown` instead makes it clear (to both eslint and humans) that the operator function doesn't have any expectations about the type of observable it's given.
This PR changes `OperatorFunction<any, ...>` to `OperatorFunction<unknown, ...>` in the return type of `ignoreElements` and the `mapTo` family of operators.  No implementation …
=> fix: use "unknown" type for operators that ignore input values

docs_app/tools/transforms/templates/api/lib/memberHelpers.html
This PR fixes the issue with the docs rendering. Please see more details in this issue: #6427
One note: I took `{% if clause.doc.path %}` section from Angular docs to check if the doc has the `path` - if it has it, then render the `<a>` tag; otherwise, render only `text`.
Closes #6427
Related angular/angular#43956
Related  ngrx/platform#3262
=> chore: fix heritage links

src/internal/operators/shareReplay.ts
The default value of refCount is not documented currently, so I added some info on it, so that people are not caught unaware.
This is well described here:
https://ncjamieson.com/whats-changed-with-sharereplay/
=> docs(operators): shareReplay refCount is false by default

src/internal/observable/empty.ts
This PR aligns `EMPTY` docs with `NEVER` docs. It removes all documentation from [`empty()`](https://rxjs.dev/api/index/function/empty) page and moves it to [`EMPTY`](https://rxjs.dev/api/index/const/EMPTY) page. Just like it's done with `NEVER` docs.
None
=> docs: move duplicate docs from empty() to EMPTY

api_guard/dist/types/index.d.ts, spec-dtslint/observables/empty-spec.ts, spec-dtslint/observables/never-spec.ts, spec/Observable-spec.ts, spec/index-spec.ts, spec/observables/empty-spec.ts, src/index.ts, src/internal/observable/empty.ts, src/internal/observable/never.ts
Just removing `empty()` and `never()` finally. (version 8 only)
=> Removing deprecated empty and never functions

src/internal/observable/dom/WebSocketSubject.ts, src/internal/testing/TestScheduler.ts
Simply put, I'm replacing `subscribe(fn, fn, fn)` calls with `subscribe(observer)` calls. The process here was to comment out the deprecated signature and fix what was broken.
=> chore: remove deprecated subscribe use in library code

src/internal/operators/sample.ts
It did not really improve readability, and I could not see the benefit of keeping it.
=> refactor(sample): remove unnecessary variable declaration

spec/operators/onErrorResumeNext-spec.ts, src/internal/operators/onErrorResumeNext.ts
Removes the `subscriber.add` call because an RxJS native `OperatorSubscriber` will automatically do that upon subscribing.
Also adds an additional test to sanity check that the previous finalization occurs before the next subscription.
=> refactor: Remove unnecessary addition of subscription to subscriber

src/internal/util/identity.ts
Now that #6734 is merged, accessing to `identity` page is much more likely since `<code>` tags contain references to it. It's time to document it.
None
=> docs(identity): add identity docs

api_guard/dist/types/index.d.ts, spec-dtslint/Observable-spec.ts, spec/Subject-spec.ts, spec/operators/min-spec.ts, src/internal/Observable.ts, src/internal/Subscriber.ts
BREAKING CHANGE: `subscribe(fn, fn, fn)` is no longer a valid call for `subscribe`. Instead, use an observer: `subscribe({ next: fn, error: fn, complete: fn })`.
(finally)
=> feat(subscribe): Removed deprecated fn, fn, fn call pattern.

src/internal/observable/iif.ts
Classical typo: 'excepts' instead of 'expects' ;-)
=> docs: fix typo in 'iif' comments

docs_app/tools/transforms/templates/api/lib/memberHelpers.html, docs_app/tools/transforms/templates/api/lib/paramList.html
This PR fixes issue mentioned by [this comment](https://github.com/ReactiveX/rxjs/pull/6756#discussion_r783055893) so that it looks like this now:
It also turns on an option to render parameter types:
None.
=> docs: fix rendering parameters

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/tap-spec.ts, src/internal/operators/tap.ts
BREAKING CHANGE: `tap(fn, fn, fn)` call pattern is no longer available. Use named arguments (observers) instead: `tap({ complete: fn, error: fn, next: fn })`.
=> feat(tap): Removed deprecated `tap(fn, fn, fn)` call pattern.

src/internal/operators/OperatorSubscriber.ts, src/internal/operators/groupBy.ts
Adds a special case to `OperatorSubscriber` to support `groupBy`.
Related: #6805 #6803 #6804
=> refactor: remove GroupBySubscriber

src/internal/Subscriber.ts
No longer require function binding if we aren't using the deprecated next context. This should improve performance in the common path of consumers subscribing with an object or even with a function.
Adds a simple class `ConsumerObserver` which is mostly meant to optimize the number of function refrences created. We should never expose this externally.
Related #6783
=> refactor(SafeSubscriber): optimize perf for ordinary observers

src/internal/Subject.ts
Previously we were cloning the observers array every time `next` was called on a `Subject`. This change attempts to reuse the same clone over and over until a new one is required because a new observer joined, or because an observer left.
I attempted to performance test this, and in terms of ops/sec it didn't show any real difference, but I didn't check memory pressure. Adding as a placeholder. I'm wondering what @cartant and @kwonoj think.
=> perf(Subject): Don't clone observers array unless we have to

spec/operators/raceWith-spec.ts
This PR converts `raceWith` tests to run mode.
None
=> chore(raceWith): convert raceWith specs to run mode

spec/operators/publishReplay-spec.ts
This PR converts `publishReplay` operator tests to run mode.
None
=> chore(publishReplay): convert publishReplay specs to run mode

spec/operators/publishLast-spec.ts
This PR converts `publishLast` operator tests to run mode.
None
=> chore(publishLast): convert publishLast specs to run mode

spec/operators/publishBehavior-spec.ts
This PR converts `publishBehavior` tests to run mode.
None
=> chore(publishBehavior): convert publishBehavior specs to run mode

spec/operators/publish-spec.ts
This PR converts `publish` operator tests to run mode.
None
=> chore(publish): convert publish specs to run mode

spec/operators/repeatWhen-spec.ts
This PR converts `repeatWhen` operator tests to run mode.
None
=> chore(repeatWhen): convert repeatWhen specs to run mode

package.json
=> fix(esm): add types to exports

package.json
If using the upcoming `jest@28` with support for `exports` and running tests in JSDOM, this module will fail to load unless the user also uses ESM. The JSDOM env supplies `browser` condition, and either `import` or `require` (plus `default`). But since this module only has the `node` condition, it goes all the way to `default`, which is ESM, resulting in a syntax error.
Can probably just replace `node` with `require`, but that's possibly a breaking change for node users who use native ESM and the code is different in browsers vs a node env?
(I've never used rxjs, so I don't have the answer to the last question. I just noticed Jest's integration test with Angular failing after adding `exports` support 🙂)
N/A
=> fix(pkg): add `require` export condition

docs_app/tools/transforms/angular-base-package/index.js, docs_app/tools/transforms/angular-base-package/post-processors/auto-link-code.js, docs_app/tools/transforms/angular-base-package/services/filterFromInImports.spec.js, docs_app/tools/transforms/angular-base-package/services/filterFromInImports.ts
This PR adds a filter to [`autoLinkCode`](https://github.com/ReactiveX/rxjs/blob/4ba8f9a5845bfa76154f7dcebc73d688b3416afb/docs_app/tools/transforms/angular-base-package/post-processors/auto-link-code.js#L23) which is responsible for auto-detection of words inside code examples that have valid links. This filter can be used for multiple reasons. The first reason is to filter adding a link where not needed. For example, for this piece of code:
```
import { interval, from } from 'rxjs';
```
`autoLinkCode` will add links to both occurrences of the word "from". But, the second occurrence is not valid and should be skipped as this is the keyword. The newly added `filterFromInImports` filters such occurrences.
This is how it looked like before this fix:
This is how this looks …
=> docs: remove a link from keyword 'from' in code examples

spec/operators/groupBy-spec.ts, src/internal/testing/TestScheduler.ts
This PR converts `groupBy` operator tests to run mode. This should be the last operator test that was using run mode.
*Note*: The defaults for `runMode` for the static marble parsing utilities in `TestScheduler` was changed to `true` because the corresponding methods are only used for the `groupBy` tests.
None
=> chore(groupBy): convert groupBy specs to run mode

spec-dtslint/operators/concatMapTo-spec.ts, spec-dtslint/operators/mapTo-spec.ts, spec-dtslint/operators/mergeMapTo-spec.ts, spec-dtslint/operators/switchMapTo-spec.ts, src/internal/operators/concatMapTo.ts, src/internal/operators/mapTo.ts, src/internal/operators/mergeMapTo.ts, src/internal/operators/switchMapTo.ts
Deprecating MapTo variants, as they were only wrappers around the Map variants, and added unnecessary API surface area.
related #6367
=> chore: deprecate MapTo variants

spec/operators/timeout-spec.ts, src/internal/operators/timeout.ts
The `timeout` operator should not timeout if the source emits synchronously when subscribed.
**Related issue:** #6862
=> fix(timeout): do not timeout if source emits synchronously when subscribed

docs_app/tools/transforms/templates/api/lib/paramList.html
This PR fixes issues with rendering generics in the parameter list. In the following example:
Generic type `O` doesn't get rendered in the _Parameters_ table, but instead gets converted to tag `<o>`.
This PR fixes these issues so that it looks like this:
None. Similar to #6655
=> docs: fix parameter generics rendering

docs_app/tools/transforms/templates/api/lib/memberHelpers.html
This PR removes links from the docs that render heritage. This step will be replaced with [`autoLinkCode`](https://github.com/ReactiveX/rxjs/blob/8e0f8cc532accddd8333d78f89377fe6ca8bd7ae/docs_app/tools/transforms/angular-base-package/post-processors/auto-link-code.js#L23) processor that inserts links automatically while [it can't work](https://github.com/ReactiveX/rxjs/blob/8e0f8cc532accddd8333d78f89377fe6ca8bd7ae/docs_app/tools/transforms/angular-base-package/post-processors/auto-link-code.js#L41-L44) if the document is already a link. Adding links through `autoLinkCode` processor will fix multiple issues with links mostly related to rendering generic parameters.
For example, in this image the link tag also included generic parameters (which could've been links …
=> docs: remove links from heritage docs

src/internal/operators/timeoutWith.ts
Please check the related issue for more info. This is how the page looks like with this fix (sorry for the large image):
#6660
=> docs(timeoutWith): fix rendering docs

src/internal/operators/retry.ts
Please check the related issue for more info. This is how the page looks like with this fix (sorry for the large image):
#6660
=> docs(retry): fix rendering docs

src/internal/scheduler/intervalProvider.ts, src/internal/scheduler/timeoutProvider.ts
As discussed this makes these two changes that allow the providers to conform with Google's stricter conformance rules. Just typing changes.
=> Add stricter argument types to timeout and interval providers

docs_app/tools/transforms/angular-base-package/index.js, docs_app/tools/transforms/angular-base-package/services/filterFromInImports.spec.js, docs_app/tools/transforms/angular-base-package/services/filterNeverAsGeneric.spec.js, docs_app/tools/transforms/angular-base-package/services/filterNeverAsGeneric.ts
This PR adds a new filter that removes link from generic type `<never>`.
This is how this looks like before this fix:
And this is how this looks like after:
None
=> docs: remove a link from keyword 'never' in code examples

spec/helpers/testScheduler-ui.ts, spec/observables/from-spec.ts
This PR converts `from` unit tests to run mode. Additionally the testing assertion helpers are removed from the test context because they are not used anymore.
None
=> From run mode

spec/observables/fromEvent-spec.ts
This PR converts `fromEvent` unit tests to run mode.
None
=> chore(fromEvent): convert fromEvent specs to run mode

spec/observables/generate-spec.ts
This PR migrates `generate` unit tests to run mode.
None
=> chore(generate): convert generate specs to run mode

docs_app/src/styles/2-modules/_api-list.scss
Fix styling of the deprecated items. With this fix, it looks like this:
vs previously:
None
=> docs: ensure deprecated styling is not overridden

spec/observables/interval-spec.ts
This PR converts `interval` unit tests to run mode.
None
=> chore(interval): convert interval specs to run mode

src/internal/operators/switchMapTo.ts
Fixes a copy/paste error in the `switchMapTo` TSDoc - the replacement should be `switchMap` and not `mergeMap` - that was mentioned [here](https://github.com/ReactiveX/rxjs/pull/6860#pullrequestreview-914312284) and [here](https://github.com/ReactiveX/rxjs/pull/6860#pullrequestreview-919493278).
=> docs: fix mergeMap/switchMap copy/paste error

spec/observables/if-spec.ts
This PR converts `iif` unit tests to run mode.
None
=> chore(iif): convert iif specs to run mode

spec/observables/of-spec.ts
This PR converts `of` unit tests to run mode. The PR also removes the scheduler argument from the parameters of `of` in a second commit. If that is not desired just drop the commit before merging. 
None
=> chore(of): convert of specs to run mode

spec/observables/onErrorResumeNext-spec.ts
This PR converts `onErrorResumeNext` unit tests to run mode. 
None
=> chore(onErrorResumeNext): convert onErrorResumeNext specs to run mode

spec/observables/pairs-spec.ts
This PR converts `pairs` unit tests to run mode.
None
=> chore(pairs): convert pairs specs to run mode

spec/observables/partition-spec.ts
This PR converts `partition` unit tests to run mode.
None
=> chore(partition): convert partition specs to run mode

src/internal/operators/pluck.ts
Adds `@deprecated` to all overload signatures of `pluck` operator.
The implementation was already marked as deprecated, but that wasn't picked up by tooling, e.g. TypeScript, eslint-plugin-deprecation, IntelliJ, ...
=> fix: add missing deprecated JSDoc tag to pluck overload signatures

spec/Subject-spec.ts, spec/operators/min-spec.ts
Looks like a few were missed because of `any`. Ugh.
(This change is also already in #6757)
=> Remove more deprecated subscribes in tests

src/internal/observable/innerFrom.ts, src/internal/operators/connect.ts, src/internal/operators/onErrorResumeNext.ts, src/internal/operators/share.ts
=> fix: `share` and `connect` no longer bundle scheduling code by default

src/internal/Observable.ts
Fix docs table of contents issue where headings inside of a method's description are included. In the example below, it looks like `Observable` only has two methods.
Before:
After:
=> docs: Fix table of contents extra headings

src/internal/operators/distinctUntilChanged.ts
Please check the related issue for more info. This is how the page looks like with this fix (sorry for the large image):
One note: I'm not an expert, but it looks like that having multiple JSDocs comments on the same function overload (for two or more overloads) don't really work with the docs rendering scripts. Maybe there is an option to turn it on, but for now, all documentation should be contained in one JSDocs comment (`/** here */`) instead of having it in multiple comments (for example, one for each overload).
Closes #6660
=> docs(distinctUntilChanged): fix docs rendering

docs_app/content/6-to-7-change-summary.md, docs_app/content/deprecations/to-promise.md, docs_app/content/guide/importing.md, docs_app/tools/transforms/angular-base-package/index.js
This PR re-enables H1 checker post processor disabled in #6734 and fixes all issues with H1 headers by increasing every but first H1 to H2; every H2 to H3 and so on.
None.
=> docs: fix issues with H1 headers

docs_app/content/deprecations/scheduler-argument.md
The arguments to 'of' should not be an array. When running the stackblitz, the output is:
[1, 2, 3]
1
2
3
That is the 'of' emitting the array, and the scheduled emitting each item in the array separately; not the same thing.
=> Update inaccurate example to 'of' replacement.

docs_app/content/6-to-7-change-summary.md
From: This a correction...
To: This is a correction...
=> missing word 'is' in Observable change description

spec/operators/shareReplay-spec.ts, src/internal/operators/share.ts
**Description:** Fixes the bug described in #6760, which seems to be a race condition.
The conditions are as such:
- Have an observable that emits immediately, but does not complete (eg. a `BehaviorSubject`, or something with `startWith`)
- Share it with `shareReplay` (or any `share` with `refCount: true`)
- Subscribe multiple times simultaneously, then unsubscribe immediately (can happen with `firstValueFrom`)
- The shared observable then gets into a bad state where it stays subscribed to the source observable but doesn't emit new values when next subscribed to.
The reason this happens is because `share` adds the reset subscription before subscribing to the source. As a result, if we subscribe and unsubscribe simultaneously, the reset block can actually run before subscribing to the …
=> fix(share): Prevent setup/reset race condition in share with refCount

src/internal/operators/share.ts
+ removes reliance on `take` operator.
+ cleans up some unnecessary `null`s (code golf, really)
=> refactor(share): Remove reliance on take

src/internal/operators/delayWhen.ts
Improve `delayWhen` docs related to the inner notification Observable.
Closes #6977
=> docs(delayWhen): improve docs related to the notification Observable

docs_app/content/guide/observable.md
Adds missing import in one of the examples in the `Disposing Observable Executions` section. Prettier did many "fixes" in the file, I'm sorry for that.
Closes #6904
=> docs(observable.md): add missing import

docs_app/content/guide/operators.md
fix typo word 'occurrance' in operators doc. the correct spelling should be `occurrence`.
=> docs: fix typo word 'occurrance' in operators doc

src/internal/observable/dom/animationFrames.ts
Leverages a single id variable instead of creating a new child Subscription for each scheduled animation frame. This is important because animation frames are scheduled very rapidly and this helps prevent CPU and GC thrashing.
Related #7018
=> perf(animationFrames): uses fewer Subscription instances

api_guard/dist/types/index.d.ts, src/internal/scheduler/AnimationFrameAction.ts, src/internal/scheduler/AsapAction.ts, src/internal/scheduler/AsyncAction.ts, src/internal/scheduler/AsyncScheduler.ts, src/internal/scheduler/QueueAction.ts, src/internal/scheduler/VirtualTimeScheduler.ts
+ Changes the check for existing action ids to simply check the last action in the queue to see if its id matches. Previously we were doing an O(n) loop on each execution of an action to check to see if the scheduling id needed to be recycled. This is problematic in AsapScheduler and AnimationFrameScheduler, where we're not reusing an interval. Since AsapScheduler and AnimationFrameScheduler reuse the most recent action id until their scheduled microtask or animation frame fires, the last action in the actions queue array is all we really need to check (rather than checking them all with `some`). O(1) vs O(n).
+ Refactors a weird conditional gaff from `if ((X && A) || (!X && B))` to just be `if (X ? A : B)`
+ Appropriately types action ids
resolves #7017
related #7018
related #6674
=> fix(schedulers): improve performance of animationFrameScheduler and asapScheduler

spec/observables/bindCallback-spec.ts
This PR converts `bindCallback` unit tests to run mode.
None
=> chore(bindCallback): convert bindCallback specs to run mode

spec/observables/bindNodeCallback-spec.ts
This PR converts `bindNodeCallback` unit tests to run mode.
None
=> chore(bindNodeCallback): convert bindNodeCallback specs to run mode

spec/observables/fromEventPattern-spec.ts
This PR converts `fromEventPattern` unit tests to run mode.
None
=> chore(fromEventPattern): convert fromEventPattern specs to run mode

spec/observables/race-spec.ts
This PR converts `race` unit tests to run mode.
None
=> chore(race): convert race specs to run mode

spec/observables/range-spec.ts
This PR converts `range` unit tests to run mode.
None
=> chore(range): convert range specs to run mode

spec/observables/zip-spec.ts
This PR converts `zip` unit tests to run mode.
None
=> chore(zip): convert zip specs to run mode

spec/observables/never-spec.ts
This PR converts `never` unit tests to run mode.
None
=> chore(never): convert never specs to run mode

docs_app/content/guide/installation.md
Adding rollup guide alongside with webpack.
Rollup enables this via its plugin `@rollup/node-resolve` which has no dedicated Doc site, thus pointing it to the git URL (blob/tags) with version embedded in.
additions to #6637
=> docs: add export condition guide for Rollup

docs_app/README.md, docs_app/src/app/custom-elements/elements-loader.spec.ts, docs_app/src/app/shared/select/select.component.spec.ts, spec/operators/timeout-spec.ts, src/internal/scheduler/VirtualTimeScheduler.ts
Replace typos "the the" with "the".
=> docs: fix "the the" -> "the"

.github/workflows/rebase.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/internal/operators/shareReplay.ts
Since we never had marble diagram image for `shareReplay`, it can be removed from the docs.
Closes #6989
=> docs(shareReplay): remove marble diagram

docs_app/content/guide/glossary-and-semantics.md
`the scenario is a unlikely`
should be:
`the scenario is an unlikely one`
This comment applies to the first commit.
=> docs(glossary): fix typo

src/internal/operators/scan.ts
There seems to be a typo in this doc,
... received so ~var~ -> ... received so _far_
_My PR is only fixing a typo, not adding or changing behavior of existing or new operators._
=> docs(operators): fixing a typo

src/internal/ReplaySubject.ts
This PR fixes a minor typo in the constructor annotation for the _windowTime_ parameter.
"[...] will ~~say~~ buffered" --> "[...] will __stay__ buffered"
=> docs(ReplaySubject): fix typo in constructor jsdoc

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, src/internal/Observable.ts, src/internal/operators/tap.ts
close #6717
fix type error caused by observable subscribe function overloads
**Related issue (if exists):** #6717
=> fix: subscribe and tap type overloads

src/internal/symbol/observable.ts
=> chore: deprecate observable symbol export

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, docs_app/content/guide/importing.md, src/index.ts, src/internal/observable/onErrorResumeNext.ts, src/internal/operators/onErrorResumeNextWith.ts, src/operators/index.ts
The `onErrorResumeNext` operator is deprecated due to a rename. The rename was done so we can move all operator exports to the top level `rxjs` export site. We were not currently exporting that operator.
This commit also refactors to logic to be based on the creation function, which is more widely used
=> feat(onErrorResumeNextWith): renamed `onErrorResumeNext` and exported from the top level

.github/workflows/ci_main.yml, .github/workflows/ci_ts_latest.yml
We had an issue where older, unsupported node versions were choking on the npm install script for latest npm. We needed to update our node versions
=> chore: Update to valid, active Node versions

src/internal/scheduler/timerHandle.ts
The `TimerHandle` type references a type from `@types/node` but that package might not be available, using the return type of `setTimeout` achieves the same result but doesn't require `@types/node` to be installed.
https://github.com/angular/angular-cli/issues/16980#issuecomment-1321839101
=> fix(schedulers): use return type of `setTimeout`

api_guard/dist/types/index.d.ts, api_guard/dist/types/operators/index.d.ts, spec-dtslint/operators/distinct-spec.ts, src/internal/operators/distinct.ts
This PR adds support for distinct's flush argument to accept ObservableInput.
https://github.com/ReactiveX/rxjs/issues/6367
=> feat(distinct): `flush` supports `ObservableInput`

spec-dtslint/operators/window-spec.ts, spec/operators/window-spec.ts, src/internal/operators/window.ts
Description:
This PR adds support for `window`'s `windowBoundaries` to accept `ObservableInput`.
Related issue (if exists):
#6972
=> feat(window): windowBoundaries should support ObservableInput

spec-dtslint/operators/skipUntil-spec.ts, spec/operators/skipUntil-spec.ts, src/internal/operators/skipUntil.ts
This PR adds support for `skipUntil`'s `notifier` to accept `ObservableInput`.
#6972
=> feat(skipUntil): notifier should support ObservableInput

spec-dtslint/operators/sequenceEqual-spec.ts, src/internal/operators/sequenceEqual.ts
Description:
This PR adds support for `sequenceEqual`'s `compareTo` to accept `ObservableInput`.
Related issue (if exists):
#6972
=> feat(sequenceEqual): compareTo should support ObservableInput

spec-dtslint/operators/buffer-spec.ts, spec/operators/buffer-spec.ts, src/internal/operators/buffer.ts
This PR adds support for `buffer`'s `closingNotifier` to accept `ObservableInput`.
#6972
=> feat(buffer): closingNotifier should support ObservableInput

spec-dtslint/operators/delayWhen-spec.ts, spec/operators/audit-spec.ts, spec/operators/delayWhen-spec.ts, src/internal/operators/delayWhen.ts
This PR adds support for `delayWhen`'s `delayDurationSelector` to accept `ObservableInput` as a return type.
Since `subscriptionDelay` is deprecated, I didn't add support for `ObservableInput` for that parameter.
Closes #7046
=> feat(delayWhen): `delayWhen`'s `delayDurationSelector` should support `ObservableInput`

spec-dtslint/operators/share-spec.ts, src/internal/operators/share.ts
This PR adds support for `ShareConfig`'s `resetOnError`, `resetOnComplete` and `resetOnRefCountZero` properties to accept `ObservableInput` when used as factory functions.
Please note: it's bound to happen that this PR will create conflicts with #7050 if that one gets merged before.
#6972
=> feat(share): ShareConfig factory properties should support ObservableInput

docs_app/tools/transforms/angular-base-package/processors/checkOperator.js
Interfaces exported from the `internal/operators` module get marked as operators. Fix this issue by checking the doc type - only docs that originate as functions are operators.
None, but please take a look at the image from #6944
=> docs: fix checkOperator processor not to mark interfaces as operators

docs_app/src/styles/1-layouts/_api-page.scss, docs_app/tools/transforms/templates/api/module.template.html
This PR improves modules template by marking deprecated items with a strikethrough.
For example, this is how [`/api/index`](https://rxjs.dev/api/index) page looks like now:
With this PR, deprecated items are now marked with a strikethrough:
None
=> docs: mark deprecated items in module template

src/internal/observable/timer.ts
**Description:** 
- Fix `timer` documentation typo
> "...after words" -> "afterwards"
=> (docs) - Fix typo

spec-dtslint/operators/find-spec.ts, spec-dtslint/operators/findIndex-spec.ts, spec/operators/find-spec.ts, spec/operators/findIndex-spec.ts, src/internal/operators/find.ts, src/internal/operators/findIndex.ts
**BREAKING CHANGE:** `find(predicate, thisArg)` call pattern is no longer available. Use `find(predicate.bind(thisArg))`
**BREAKING CHANGE:** `findIndex(predicate, thisArg)` call pattern is no longer available. Use `findIndex(predicate.bind(thisArg))`
**Related issue (if exists):** #6367
=> feat: removed deprecated call pattern in `find` & `findIndex`

spec-dtslint/observables/throwError-spec.ts, spec/observables/throwError-spec.ts, src/internal/observable/throwError.ts
**BREAKING CHANGE:** `throwError(error)` call pattern is no longer available. Use `throwError(() => error)`.  
**BREAKING CHANGE:** `throwError(errorFactory, scheduler)` call pattern is no longer available. [Read more](https://rxjs.dev/deprecations/scheduler-argument).
**Related issue (if exists):** #6367
=> feat(throwError): removed deprecated call patterns

spec-dtslint/operators/endWith-spec.ts, spec/operators/endWith-spec.ts, src/internal/operators/endWith.ts
**BREAKING CHANGE:** `endWith(value, scheduler)` call pattern is no longer available. [Read more](https://rxjs.dev/deprecations/scheduler-argument).
**Related issue (if exists):** #6367
=> feat(endWith): removed deprecated `endWith(value, scheduler)` call pattern

spec-dtslint/operators/map-spec.ts, spec/operators/map-spec.ts, src/internal/operators/map.ts
BREAKING CHANGE: `map(project, thisArg)` call pattern is no longer available. Use Function#bind method: `map(project.bind(thisArg))`
**Related issue (if exists):** #6367
=> feat(map): removed deprecated `map(project, thisArg)` call pattern

src/internal/observable/defer.ts
Since #5449 factory function of defer can't return a falsy value anymore, but comment/doc was not updated.
=> docs(defer) fix facory function return

src/internal/observable/innerFrom.ts, src/internal/operators/endWith.ts, src/internal/util/subscribeToArray.ts
I would like to propose a simplification and optimization of the `endWith` operator.
Some operators may spend significantly more CPU and RAM than you expect from them. When trying to use the debugging tools, you can notice that often the problem lies in the fact that operators can consist of other operators. For example, in dealing with [`count`](https://github.com/ReactiveX/rxjs/blob/71a26ac155cb0f48c8054843282e7bbb5ed4e6fe/src/internal/operators/count.ts#L59-L61) you can see that the `reduce` operator is used in the implementation, but the code is quite simple and can hardly affect performance in any way. But if you take the operator from this PR ([`endWith`](https://github.com/ReactiveX/rxjs/blob/71a26ac155cb0f48c8054843282e7bbb5ed4e6fe/src/internal/operators/endWith.ts#L54-L58)), you …
=> perf(operator): simplify the implementation of the `endWith` operator

src/internal/observable/bindCallback.ts
docs: Fix the example for bindCallback.
The example, as it was, crashes with `Error: cb is not a function` on line 5. The new example demonstrates how arguments are forwarded or added.
=> docs: Fix example for bindCallback

docs_app/content/6-to-7-change-summary.md
Fixed typo in the 6 to 7 upgrade docs
=> docs: fix typo in 6 to 7 summary

spec/observables/fromEvent-spec.ts, src/internal/observable/fromEvent.ts
+ `fromEvent` no longer relies on `mergeMap` or `from` to handle the case of an `ArrayLike` of event targets (for example a `NodeList`).
+ Overall code size reduction, should also be a lot faster on subscribe.
+ Added an error message for invalid input when an `ArrayLike` comes with non-event-like items in it.
=> refactor(fromEvent): Make fromEvent a lot smaller

spec/schedulers/AsapScheduler-spec.ts, src/internal/scheduler/AsapAction.ts
Fixes an issue where trying to share a microtask cause the scheduler to trip over itself.
resolves ReactiveX#7196
A non-breaking alternative fix to PR https://github.com/ReactiveX/rxjs/pull/7197
=> fix(asapScheduler): No longer stops after scheduling twice during flush

spec/observables/dom/webSocket-spec.ts, spec/operators/delay-spec.ts, spec/operators/elementAt-spec.ts, spec/operators/first-spec.ts, spec/operators/take-spec.ts, spec/operators/takeUntil-spec.ts, spec/operators/takeWhile-spec.ts, src/internal/operators/take.ts, src/internal/operators/takeWhile.ts
- fix(first/take): behave properly with reentrant errors and completions
- Resolves an issue with both `first` and `take` where an error emitted by a reentrant source at the moment the last value it taken would result in superceding the expected emitted value and completion.
- Resolves a similar issue where a reentrant completion would supercede the expected last value and completion
Fixes #5487
- fix(takeWhile): reentrant errors and completions behave properly
- Resolves an issue where a reentrant error notification would short circuit the completion.
- Adds additional tests.
Related #5487
- chore: Add reentrant error test for takeUntil
=> Fix/5487 reentrancy in take, takeWhile, and first

spec/operators/buffer-spec.ts, src/internal/operators/buffer.ts
Per [RxJS Core Semantics guide](https://rxjs.dev/guide/core-semantics):
> "Notifiers" provided directly to the operator MUST be subscribed to before the source is subscribed to.
This PR fixes this issue in `buffer` operator. Since there was a test related to this, I adjusted it so that it works with the new setup.
Also, one note: since we waited with similar bug for v8 in #7152, I think this should not be cherry picked to v7 branch.
None, only [this comment](https://github.com/ReactiveX/rxjs/pull/7073#discussion_r1000298398).
=> fix(buffer): subscribe to the closing notifier before the source

src/internal/types.ts
Since I proposed a `TapObserver` documentation page PR (#6944), I thought that we should document the Observer interface [page](https://rxjs.dev/api/index/interface/Observer) as well. Although there are [a guide](https://rxjs.dev/guide/observer) and [a glossary](https://rxjs.dev/guide/glossary-and-semantics) pages that explain most of what I wrote in this PR (which I also mentioned in this PR), I wanted to still add the basic documentation to the [Observer interface page](https://rxjs.dev/api/index/interface/Observer) which users can encounter while roaming the docs app (which is empty for now).
This is how these changes look like:
None
=> docs(Observer): add documentation to Observer interface

docs_app/content/6-to-7-change-summary.md
**Summary of fixes:**
```diff
-and the the return type
+and the return type
-a little used feature
+a little-used feature
-convert any `Observable` in to a `Promise`
+convert any `Observable` into a `Promise`
-Calling takeLast without
+Calling `takeLast` without
-This puts us in-line with
+This puts us in line with
-handling is use
+handling is used
-information was send
+information was sent
-the equality of to observables
+the equality of two observables
```
=> Proofread 6-to-7 change summary

docs_app/content/deprecations/scheduler-argument.md
This PR is to fix a couple of typos found in "Scheduler Argument" page within "Deprecations & breaking changes" section.
=> docs(deprecations): fix some typos in Scheduler Argument

docs_app/content/guide/operators.md
Introduce the concept that what we normally call "operators", such as `map`
or `filter`, are Pipeable Operator Factory functions which, when called,
return a "real" Pipeable Operator.
=> docs: update Operators overview

src/internal/operators/takeLast.ts
This change moves the code back to using a ring buffer for the value collection of takeLast. This should be much more efficient when writing to, and reading from, the buffer.
NOTE: I tried to use github.dev for this, we'll see if it passes CI or not. (lol).
=> refactor(takeLast): Move back to using a ring buffer

spec-dtslint/observables/combineLatest-spec.ts, spec/observables/combineLatest-spec.ts, src/internal/observable/combineLatest.ts, src/internal/util/argsArgArrayOrObject.ts
+ Removes the `combineLatest(a$, b$, c$)` signature, so we can standardize on `combineLatest([a$, b$, c$])` and `combineLatest({ a: a$, b: b$ })`.
NOTE: It appears we forgot to deprecate the `resultSelector` signature. Which isn't even supported for the newer object argument syntax (and never was).
=> feat(combineLatest): remove spread params deprecated signature.

spec/operators/throttle-spec.ts, spec/operators/throttleTime-spec.ts, src/internal/operators/throttle.ts, src/internal/operators/throttleTime.ts
This PR is split into two commits. The first one fixes an issue described in #7146, while the second one adds `ThrottleConfig` docs.
This issue should be probably cherry picked to the `7.x` branch.
Fixes #7146
=> fix(throttle): properly handle default ThrottleConfig values

src/internal/observable/fromEvent.ts
Updates the example according to the API.
Closes #7245
=> docs(fromEvent): update the example to match the actual API

spec/Observable-spec.ts, src/internal/Observable.ts
Adds async iterator support to `Observable`!
#6779 
#6857
=> feat(Observable): now implements `Symbol.asyncIterator`

spec/Subject-spec.ts, spec/operators/groupBy-spec.ts, src/internal/observable/onErrorResumeNext.ts, src/internal/operators/OperatorSubscriber.ts, src/internal/operators/groupBy.ts
fix(groupBy): will no longer leak inner subscriptions
`groupBy` no longer supports the behavior where inner subscriptions will cause the outer subscription to stay connected after consumer unsubscribes from result.
Resolves #6805
BREAKING CHANGE: `groupBy` no longer allows grouped observable subscriptions to stay connected after parent subscription unsubscribed. If you need this behavior, don't unsubscribe from the parent.
refactor: Remove direct instantiation of `OperatorSubscriber`
+ Stopped exporting `OperatorSubscriber` class from module
+ Updated `onErrorResumeNext` and a `Subject` test to use `createOperatorSubscriber`
Actual stream of the work is here, if that helps: https://youtu.be/rHgED1U6XDY
=> Fix 6805: remove strange groupBy behavior

spec/schedulers/AnimationFrameScheduler-spec.ts, spec/schedulers/AsapScheduler-spec.ts, spec/schedulers/QueueScheduler-spec.ts, spec/schedulers/VirtualTimeScheduler-spec.ts
This PR formats the scheduler spec files using prettier, with the exception of the test file for the `TestScheduler` for which a separate PR #7258 was opened.
None
=> chore: format scheduler test files using prettier

spec-dtslint/operators/ignoreElements-spec.ts
The old signature of the function forced the previous types to unknown.
Taking into account @cartant `s comment https://github.com/ReactiveX/rxjs/issues/5236#issuecomment-575399386, losing the typing for the previous operators forces to duplicate the typing information when it is not necessary.
Losing the explicit typing and as a side effect duplicating the type information is also a bad practice.
```typescript
of('a string').pipe(
tap((value) => {
/** string **/
}),
tap((value) => {
/** unknow **/
}),
ignoreElements(),
tap((value) => {
/** never **/
})
);
```
```typescript
of('a string').pipe(
tap((value) => {
/** string **/
}),
tap((value) => {
/** string **/
}),
ignoreElements(),
tap((value) => {
/** never **/
})
);
```
**Related issue :** …
=> fix(ignoreElements): change the return type from unknown to Generic Type

spec/observables/forkJoin-spec.ts, src/internal/observable/forkJoin.ts
BREAKING CHANGE: `forkJoin` will no longer just complete if a source completes without a value. Instead you will get an error of `EmptyError`. If you want to complete in this case, add `catchError(() => EMPTY)` to the forkJoin... however, if you just want to default the sources of your `forkJoin` to some other value if they're empty, apply the `defaultIfEmpty` operator. for example, `forkJoin(sources.map(defaultIfEmpty(null)))`.
resolves #5561
=> fix(forkJoin): the first empty source will now cause an EmptyError

spec-dtslint/operators/startWith-spec.ts, spec/operators/startWith-spec.ts, src/internal/observable/from.ts, src/internal/operators/endWith.ts, src/internal/operators/startWith.ts
+ Removes deprecated scheduler signature
+ Improves performance slightly
+ Moves `subscribeToArray` closer to usage.
=> feat(startWith): remove deprecated scheduler signature.

docs_app/content/guide/glossary-and-semantics.md
fix hyperlink, grammatical errors, and improve clarity on the glossary and semantics page of the docs.
=> docs: improve glossary and semantics page

package-lock.json, spec/Subscriber-spec.ts, src/internal/Subscriber.ts
This PR fixes type signature of `Subscriber.prototype.next` method that was previously taking optional argument which was violating generic constraint `T`.
**BREAKING CHANGE:** `Subscriber.prototype.next` now takes strict argument.
```typescript
new Observable(subscriber => {
subscriber.next() // throws in compile time (expected, caused by this PR)
})
new Observable<string>(subscriber => {
subscriber.next() // throws in compile time (expected, caused by this PR)
})
new Observable<void>(subscriber => {
subscriber.next() // ok
})
```
**Related issue (if exists):** https://github.com/ReactiveX/rxjs/issues/2852
**Additional changes:**
- update package version in lockfile to `7.8.0` (running `npm i`)
=> fix(subscriber): strict type signature for next method

src/internal/types.ts
This PR adds [MonoTypeOperatorFunction](https://rxjs.dev/api/index/interface/MonoTypeOperatorFunction) docs.
None
=> docs: add MonoTypeOperatorFunction documentation

docs_app/content/navigation.json
Now that V8 is actively being developed and published, we need to provide URL for the V8 docs app ([next.rxjs.dev](https://next.rxjs.dev)).
None
=> docs: provide URL for the V8 docs app

spec/operators/mergeWith-spec.ts, src/internal/operators/merge.ts
Fixes #7278 
I've also ran into this issue in the past.
#7278
=> fix(mergeWith): works correctly with an Array

src/tsconfig.cjs.json
Makes sure we're publishing newer JavaScript for CJS files as well.
=> feat(cjs): output ES2022

spec/Subscription-spec.ts, spec/helpers/interop-helper.ts, spec/helpers/setup.ts, src/internal/Subscription.ts
Just an initial pass at implementing `Symbol.dispose`. Theoretical usage would be something like:
```ts
async function someLongRunningThing() {
let valueFromObservable;
// This is the usage.
using someObservable$.subscribe(value => {
valueFromObservable = value;
})
let n = 0;
while (n++ < 10) {
const userInput = await userInput();
console.log(userInput + valueFromObservable);
}
// when this exits, the subscription will be "disposed".
}
```
cc @rbuckton
Related #7299
=> feat(Subscription): Subscription now implements `Symbol.dispose`

packages/rxjs/spec/operators/share-spec.ts, packages/rxjs/src/internal/Subscriber.ts, packages/rxjs/src/internal/util/reportUnhandledError.ts
This is removing dependency on `timeoutProvider` in `Observable` because observable depends on `Subscriber`, and `Subscriber` users `timeoutProvider` for both `onUnhandledError` and `onStoppedNotification`, when it doesn't really need to. That's not particularly what `timeoutProvider` is for.
This also preps us to publish `@rxjs/observable` by limiting the dependencies that `Observable` has.
Resolves #7343
=> Async dispatched config handlers

packages/rxjs/src/internal/Subscriber.ts
fix typo, 'subcription' to 'subscription'
=> docs(operate): fix typo

apps/rxjs.dev/tools/transforms/templates/api/function.template.html
This PR fixes an issue in the docs app, that does not display the overlays if the number of overloads is 2. The overload is printed at the top of the document.
**Related issue (if exists):** #5281
See also AIO Commit: https://github.com/angular/angular/commit/e0c736066cfd3fb4d784c2a335e6214ed6d6ec21
=> fix(docs): fix missing overloads in docs when overload count is less than 3

apps/rxjs.dev/content/deprecations/resultSelector.md
In the current version, the link does not resolve, but with this change, it navigates users properly.
=> Fixes a broken link to /api/operators/switchMapTo

packages/rxjs/spec/helpers/interop-helper-spec.ts, packages/rxjs/spec/helpers/test-helper.ts, packages/rxjs/spec/observables/from-spec.ts, packages/rxjs/src/index.ts, packages/rxjs/src/internal/Observable.ts, packages/rxjs/src/internal/observable/from.ts, packages/rxjs/src/internal/symbol/observable.ts, packages/rxjs/src/internal/util/isInteropObservable.ts
BREAKING CHANGE: `observable` (the `Symbol.observable` symbol instance) is no longer exported. Use a polyfill like `symbol-observable`, or use `Symbol.observable ?? '@@observable'` as a workaround.
=> feat: remove deprecated observable symbol export (#4466)

apps/rxjs.dev/package.json, yarn.lock
This gets rid of strange errors when running the tests for rxjs.dev, apparently there was some use of core-js without actually having a dependency for it, so when some other dependency was updated and no longer pulling it in, we didn't have it for some code that was using it.
=> chore: fix broken rxjs.dev test execution

.github/workflows/ci_main.yml, package.json
In getting started with the repo, my global yarn installation of latest v4 tried to upgrade the repo.
This PR adds a volta config so that those that use it to manager their node toolchain can benefit from automatic resolution of node and yarn, and also adds a `packageManager` definition for corepack users.
This should make it easier for first time contributors to get up and running faster.
=> chore: set primary node version and yarn v1 package manager

.github/actions/install-dependencies/action.yml, .github/workflows/ci_main.yml, .github/workflows/ci_ts_latest.yml, .github/workflows/publish.yml, .github/workflows/rebase.yml, .gitignore, lerna.json, nx.json, package.json, packages/rxjs/package.json, scripts/copy-common-package-files.js, scripts/release.js, yarn.lock
Demoed to Ben today. This PR adds release utilities for the rxjs repo. Ben will run `yarn release` locally which will version all the packages (currently just `rxjs`) and create a `CHANGELOG.md` entry, as well as create a GitHub release.
The release will act as a trigger for the publish GitHub workflow (which can also be triggered manually via the GitHub UI). It has also been configured to generate provenance data for npm (something which is only possible when publishing from GitHub actions like this)
--- 
Additionally, creating the publish workflow involved adding a setup-node and install step again so I took the opportunity to create a shared composite action for this, and fix the node_modules caching to work for yarn across the board
=> chore: add release utilities

.github/workflows/ci_main.yml, .github/workflows/ci_ts_latest.yml
All current issues on the 7.x branch relate to the same problem - the code has stayed the same, but it is trying to be run with tooling which has since evolved. Therefore this PR:
- Removes the `@latest` usage of npm
- Disables TS latest workflow
=> chore: 7.x remove global npm install and ignore latest TS

packages/rxjs/spec/schedulers/TestScheduler-spec.ts, packages/rxjs/src/internal/testing/TestScheduler.ts
=> fix(TestScheduler): explicit unsubscribe works properly with toEqual

packages/rxjs/spec-dtslint/observables/fromEvent-spec.ts, packages/rxjs/spec/observables/fromEvent-spec.ts, packages/rxjs/src/internal/observable/fromEvent.ts
Allow passing a value of type `symbol` to `eventName` if a `NodeStyleEventEmitter` is passed to `source`, according to [the documentation](https://nodejs.org/api/events.html#emitteraddlistenereventname-listener).
Closes #7338
=> fix(fromEvent): allow `fromEvent` to handle symbols as event names

packages/rxjs/src/internal/observable/bindCallbackInternals.ts, packages/rxjs/src/internal/observable/dom/fetch.ts, packages/rxjs/src/internal/observable/forkJoin.ts, packages/rxjs/src/internal/observable/fromEvent.ts, packages/rxjs/src/internal/observable/fromEventPattern.ts, packages/rxjs/src/internal/operators/delayWhen.ts, packages/rxjs/src/internal/operators/elementAt.ts, packages/rxjs/src/internal/operators/first.ts, packages/rxjs/src/internal/operators/groupBy.ts, packages/rxjs/src/internal/operators/last.ts
Removes internal usage of the `pipe` method, so that in the future, other observables that do not implement `pipe` will work with our operators.
This PR doesn't have the explicit goal of ensuring operators work with "observable shaped things", but it's a step in that direction.
=> Refactor: no internal pipe method use

packages/rxjs/spec/scheduled/scheduled-spec.ts, packages/rxjs/src/internal/observable/range.ts, packages/rxjs/src/internal/observable/timer.ts, packages/rxjs/src/internal/operators/debounceTime.ts, packages/rxjs/src/internal/operators/timeout.ts, packages/rxjs/src/internal/scheduled/scheduleArray.ts, packages/rxjs/src/internal/util/executeSchedule.ts
This goes through and moves all of the reliance on the `this` context for scheduling to a single point, `executeSchedule`. It also moves common complexities to that helper function. All of this is done in preparation for creating newer, simplified schedulers
=> refactor: isolate reliance on SchedulerAction `this` context

packages/rxjs/src/internal/observable/fromEvent.ts
This should never have been deprecated. There's not really a great way to infer these types because it's for both DOM and Node APIs. So `fromEvent<MouseEvent>(button, 'click')` is totally a thing.
=> fix(fromEvent): passing a generic parameter is no longer deprecated

packages/rxjs/spec/operators/expand-spec.ts, packages/rxjs/src/internal/operators/expand.ts, packages/rxjs/src/internal/operators/mergeInternals.ts, packages/rxjs/src/internal/operators/mergeScan.ts
BREAKING CHANGE: `expand` no longer supports a scheduler parameter. Use `scheduled` or `subscribeOn` or `observeOn` instead.
=> feat(rxjs): `expand` no longer supports a scheduler parameter

packages/rxjs/spec/operators/every-spec.ts, packages/rxjs/src/internal/operators/every.ts
- Removes `thisArg`.
- Removes `source` parameter in predicate (for consistency reasons)
- Fixes re-entrancy issue from #7425
=> Fix `every` re-entrancy and signature.

packages/rxjs/src/internal/operators/connect.ts
Fix a small typo in the docstring: `and Observable` -> `an Observable`.
=> Fix typo in docstring in connect.ts

apps/rxjs.dev/src/app/custom-elements/operator-decision-tree/README.md
Updating the docs to match the new pathof the decision tree.
=> docs(rxjs.dev): fix decision tree file url in README

packages/rxjs/src/internal/operators/retryWhen.ts
When I'm reading the documentation of [retryWhen](https://rxjs.dev/api/operators/retryWhen), I saw that the deprecation notice has two identical sentences.
> Will be removed in v9 or v10, use [retry](https://rxjs.dev/api/operators/retry)'s [delay](https://rxjs.dev/api/index/function/delay) option instead. Will be removed in v9 or v10. Use [retry](https://rxjs.dev/api/operators/retry)'s [delay](https://rxjs.dev/api/operators/RetryConfig#delay) option instead.
So, I merge them together, wdyt?
=> docs: remove duplicate deprecated note on retryWhen

apps/rxjs.dev/src/index.html
This PR replaces the `polyfill.io` with a Cloudflare equivalent because `polyfill.io` can no longer be trusted.
> polyfill.io, a popular JavaScript library service, can no longer be trusted and should be removed from websites.
Source: [https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet](https://blog.cloudflare.com/automatically-replacing-polyfill-io-links-with-cloudflares-mirror-for-a-safer-internet)
=> Replace polyfill.io with a Cloudflare equivalent
